### ISSUE TITLE
Changing timezone sets milliseconds to 0

### ISSUE THREAD

**Issue by fgblomqvist** [iamkun/dayjs#1002]
**Describe the bug**
```js
let d = dayjs(1596735327399);
console.log(d.millisecond()); // Will print 399
d = d.tz('America/New_York');
console.log(d.millisecond()); // Will print 0
```

**Expected behavior**
Milliseconds should be preserved.

**Information**
 - Day.js Version: v1.8.33
 - OS: macOS
 - Browser: Chrome 84
 - Time zone: GMT-04:00 DST

**Comment by iamkun** [comment]
Thanks, Fixed.

**Comment by fgblomqvist** [comment]
Wow that was fast, thanks a lot!
