### ISSUE TITLE
Gives Invalid Date on Safari browser

### ISSUE THREAD

**Issue by hiravesonali** [iamkun/dayjs#1011]
**Describe the bug**

I have this date string **2020-07-16 11:27:38.000000** from server.

When I parse it to dayjs, it works fine in Chrome and Firefox but giving **Invalid Date** error in Safari.

I have tried out with different formats(see below) but none of them works in safari.

```
var serverDate = '2020-07-16 11:27:38.000000'

console.log(dayjs(serverDate, 'YYYY-MM-DD hh:mm:ss.SS').format('MMM Do, YYYY')) // => "Invalid Date"

console.log(dayjs(serverDate, 'YYYY-MM-DD hh:mm:ss.SSS').format('MMM Do, YYYY')) // => "Invalid Date"

console.log(dayjs(serverDate, 'YYYY-MM-DD hh:mm:ss.SSSSSS').format('MMM Do, YYYY')) // => "Invalid Date"
```

The codepen link for my case is [here](https://codepen.io/sonali-hirave/pen/PoNzxWa?editors=0112).

**Expected behavior**
Should parse the given string in Safari as well.

**Information**
 - Day.js Version ^1.8.28
 - OS: MacOs Mojave(10.14 )
 - Browser - Safari Version 12.0

**Comment by iamkun** [comment]
This fix https://github.com/iamkun/dayjs/pull/1010 might also fix this bug I think.

**Comment by hiravesonali** [comment]
@iamkun Thanks for the update. I think the fix you mentioned will solve my problem. When are you planning to make a next release?

**Comment by iamkun** [comment]
released @hiravesonali

**Comment by hiravesonali** [comment]
Yes, it is working perfect. Thank you 🙌
