### ISSUE TITLE
DayJS Timezone Typescript issue: Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by vupham84** [iamkun/dayjs#1014]
We follow the sample in https://day.js.org/docs/en/plugin/timezone like this 

`dayjs("2014-06-01 12:00").tz("America/New_York")`

It's working fine but Typescript is throwing an error below.

```
TS2554: Expected 0 arguments, but got 1.
Version: typescript 3.8.3
```

**Comment by iamkun** [comment]
Hi, this bug has been fixed in the latest version.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
