### ISSUE TITLE
Dayjs.diff not working for specific time format in safari

### ISSUE THREAD

**Issue by patelab1** [iamkun/dayjs#1016]
**Describe the bug**

Converting `2020-11-17 16:52:09.046090+00:00` to dayjs object and then calling `diff` on that object does not work in safari and returns `NaN`. Please open the sandbox below in safari and chrome. It works as expected in chrome but not in safari

https://codesandbox.io/s/async-surf-286sn

**Expected behavior**

day.js object and its diff works identically on both safari and chrome

**Information**
 - Day.js Version [v1.8.34]
 - OS: [MacOS,iOS]
 - Browser [Safari Version 13.1.2]
 - Time zone: [`2020-11-17 16:52:09.046090+00:00`]

**Comment by iamkun** [comment]
Hi, For consistent results parsing anything other than ISO 8601 strings, you should use String + Format. https://day.js.org/docs/en/parse/string-format

**Comment by patelab1** [comment]
That worked! Thanks for the quick reply :D 

sorry about that should have RTFM first :<
