### ISSUE TITLE
Can't parse ISO 8601 string with timezone (when not UTC)

### ISSUE THREAD

**Issue by jin60641** [iamkun/dayjs#1020]
**Describe the bug**

[parseDate](https://github.com/iamkun/dayjs/blob/e1890c969122c677350af2f457b7066d1fcf787a/src/index.js#L54) does not support ISO 8061 with timezone. (ex. 2020-08-05T05:27:00+0900)
On Chrome, last line's `new Date` will parse well, but not work on safari.

**Expected behavior**

Can parse on both Chrome and Safari.

**Information**
 - Day.js Version: 1.8.31
 - OS: macOS Catalina (10.15.3)
 - Browser: Safari 13.0.5,  Chrome 84.0.4147.135
 - Time zone: GMT 09:00

**Comment by iamkun** [comment]
afaik, `+0900` is not timezone string in ISO 8061 format. 

thus, parseDate could parse `2020-08-05T05:27:00+09:00` well, but for `2020-08-05T05:27:00+0900`, for consistent results parsing anything other than ISO 8601 strings, you should use String + Format. https://day.js.org/docs/en/parse/string-format

**Comment by jin60641** [comment]
Thanks. It's not a bug.
