### ISSUE TITLE
Using dayjs with Sapper

### ISSUE THREAD

**Issue by vcheeze** [iamkun/dayjs#1024]
**Describe the bug**
I am using [Sapper](https://sapper.svelte.dev/) as my framework, and was using `moment.js` along with it. I noticed that `moment.js` is taking way too much space when I build my project, and found `dayjs` to be an awesome alternative. However, when I switch from `moment.js` to `dayjs`, my page always crashes. Sapper throws me no errors, and I am at a loss for what is causing the error.

Steps to reproduce:
- get the [Sapper project template](https://sapper.svelte.dev/docs#Getting_started)
- `npm install dayjs`
- use it in any page, and observe the behavior

**Expected behavior**
Simply for everything to work exactly as they did when I was using `moment.js`.

**Information**
 - Day.js Version: 1.8.34
 - OS: Linux Mint 19.3 (Cinnamon 4.4.8)
 - Browser: Chrome 80.0
 - Time zone: GMT +4

**Comment by iamkun** [comment]
Seems not a `Day.js` issue? Maybe you can test dayjs on a pure js page to see if it worked or not.

**Comment by vcheeze** [comment]
@iamkun you are right. I found out that it's actually because of a certain difference between `moment.js` and `Day.js`. In `moment.js`, when you do something like this
```js
let today = moment();
today.add(1, 'days');
console.log(today); // value will be tomorrow
```

However, in `Day.js`, `add` will simply return the new value and not modify the original value (`today` in the case above). This difference was causing an infinite loop in my code. I had assumed that all functions behaved the same, so I didn't do a thorough check when I switched over.

Appreciate your work and your help!

**Comment by iamkun** [comment]
The Day.js object is immutable, that is, all API operations that change the Day.js object in some way will return a new instance of it.

However, there is a plugin to make it mutable, but not recommended.

https://day.js.org/docs/en/plugin/bad-mutable
