### ISSUE TITLE
Date validity check does not work correctly

### ISSUE THREAD

**Issue by kasongoyo** [iamkun/dayjs#1025]
**Describe the bug**
I tried to parse `2020-13-13` with this library and its `isValid()` check returned true while I expected it to return false

**Expected behavior**
I expected the date is valid check to return false

**Information**
 - Day.js Version [1.8.34]
 - OS: [iOS]
 - Browser [Node]
 - Time zone: [e.g. GMT+03:00 EAT (East African Time)]

**Comment by iamkun** [comment]
You may specify a boolean for the last argument to use strict parsing. Strict parsing requires that the format and input match exactly, including delimiters.
```
dayjs('1970-00-00', 'YYYY-MM-DD').isValid() // true
dayjs('1970-00-00', 'YYYY-MM-DD', true).isValid() // false
dayjs('1970-00-00', 'YYYY-MM-DD', 'es', true).isValid() // false
```
https://day.js.org/docs/en/parse/string-format

**Comment by WesCossick** [comment]
I'm experiencing this issue with `2020-01-32`, even when the strict argument is set to `true`:

```js
dayjs('2020-01-32', 'YYYY-MM-DD', true).isValid(); // Returns true instead of false
```

Corresponding JSFiddle: https://jsfiddle.net/1jobm0wz/

**Comment by iamkun** [comment]
@WesCossick Hi, this feature dependent on [`CustomParseFormat`](https://day.js.org/docs/en/parse/string-format) plugin to work, check the link in this comment above for more information. https://github.com/iamkun/dayjs/issues/1025#issuecomment-679748048.

**Comment by WesCossick** [comment]
Thanks, @iamkun. For those who are interested, here's an updated JSFiddle that works correctly: https://jsfiddle.net/p946hw3o/2/

**Comment by iamkun** [comment]
Cool!
I'll close this issue since it's been solved. Feel free to reopen if you have updates on this
