### ISSUE TITLE
weekOfYear 'week' method doesn't seems to handle week number 53 for 'nl' locale

### ISSUE THREAD

**Issue by gavinlight** [iamkun/dayjs#1030]
**Describe the bug**
Similar to the issue mentioned in https://github.com/iamkun/dayjs/issues/956, with a dutch locale (`nl`), the week number on the end of the year is incorrect.

**Expected behavior**
When selecting the 'nl' locale and trying to return the weeknumber via `days('2020-12-31').week()`, the number returned is `1`, while dutch calenders are supposed to return `53`. See https://www.kalender-365.nl/kalender-2020.html

**Information**
 - Day.js Version: [v1.8.34[
 - OS: [MacOS]
 - Browser [Chrome 84]
 - Time zone: [CEST]

**Comment by iamkun** [comment]
Thanks, Update  Dutch (nl) locale to set correct yearStart config. https://github.com/iamkun/dayjs/commit/1533a2cc1475270032da2d87b19fc3d62327e6e3

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
