### ISSUE TITLE
antd中日期组件使用dayjs后，通过form.setFildsValue改变日期组件的值，然后点击会报错

### ISSUE THREAD

**Issue by victorWuxz** [iamkun/dayjs#1037]
antd中日期组件使用dayjs后，通过form.setFildsValue改变日期组件的值，然后点击会报错
clone.weekday is not a function

![image](https://user-images.githubusercontent.com/36194121/92580295-c9b5d100-f2c0-11ea-9253-bd1190613602.png)

**Information**
 - Day.js Version [1.6.4]
 - OS: [mac]
 - Browser [chrome 85]

**Comment by iamkun** [comment]
请提供一个 复现的 demo 或 repo

**Comment by harshithmullapudi** [comment]
似乎可以在4.4.0下使用

**Comment by harshithmullapudi** [comment]
4.5.0版本更新打破了dayjs的实现。这似乎适用于4.4.3

**Comment by iamkun** [comment]
@harshithmullapudi  4.5.0 更新了什么吗

**Comment by harshithmullapudi** [comment]
我可以看到这些
日期选择器

    新的DatePicker支持date-fns。 ＃25822 @fireairforce
    改进了DatePicker悬停的新体验，当悬停日期单元格时，占位符将更改为target-date的格式值。 （＃25050）。 ＃25784 @柯密轩
    新的RangePicker onCalendarChange添加范围参数以指示当前激活的窗格。 ＃25568 @金永丰
    新的DatePicker支持panelRender以自定义面板。 ＃25488
    甲虫修复QuarterPicker无法正常工作，请删除DatePicker.XxxPicker并建议使用picker ='xxx'。 ＃25768

**Comment by iamkun** [comment]
还是希望能提供一个测试 repo

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by willwan92** [comment]
我在用ant-design-vue@3.1.1的时候遇到了同样的问题，在更新到3.2.0之后没有这个问题了。

**Comment by wzyQD** [comment]
![image](https://user-images.githubusercontent.com/41660068/210349430-aead5966-9def-4fe2-9951-620c0afee6f3.png)

**Comment by Ahspagh** [comment]
import weekday from 'dayjs/plugin/weekday';
  import localeData from 'dayjs/plugin/localeData';
  dayjs.extend(localeData);
  dayjs.extend(weekday);
