### ISSUE TITLE
UTC timezone .utc() is not behaving as expected

### ISSUE THREAD

**Issue by Mateusz-Kopec** [iamkun/dayjs#1038]
**Describe the bug**
```
  const timeZone = 'UTC';
  console.log(dayjs().tz(timeZone));
  console.log(dayjs().tz(timeZone).format());
  console.log(dayjs().tz(timeZone).utc());
  console.log(dayjs().tz(timeZone).utc().format());
```
Result:
```
d {$L: "en", $u: true, $d: Wed Sep 09 2020 16:11:04 GMT+0200 (Central European Summer Time), $y: 2020, $M: 8, …}
$D: 9
$H: 14
$L: "en"
$M: 8
$W: 3
$d: Wed Sep 09 2020 16:11:04 GMT+0200 (Central European Summer Time) {}
$m: 11
$ms: 167
$offset: 0
$s: 4
$u: true
$y: 2020
__proto__: Object
2020-09-09T14:11:04Z

d {$L: "en", $u: true, $d: Wed Sep 09 2020 18:11:04 GMT+0200 (Central European Summer Time), $y: 2020, $M: 8, …}
$D: 9
$H: 16
$L: "en"
$M: 8
$W: 3
$d: Wed Sep 09 2020 18:11:04 GMT+0200 (Central European Summer Time) {}
$m: 11
$ms: 170
$s: 4
$u: true
$y: 2020
2020-09-09T16:11:04Z
```

**Expected behavior**
Dayjs in UTC timezone shouldn't change after calling `utc()`

**Information**
 - Day.js Version v1.8.35
 - OS: MacOS
 - Browser Chrome 84
 - Time zone: GMT+0200 as seen in logs

**Comment by iamkun** [comment]
Seems there's no timezone named `UTC`, maybe you can try `Europe/London` instead?

**Comment by Mateusz-Kopec** [comment]
Geez, I spent so much time trying to figure it out and it was not-existing timezone. Thanks for the help! :) 

When I changed it to `Etc/UTC` it works.

Do you think that maybe throwing an exception when timezone is not found would be useful?

**Comment by iamkun** [comment]
If the timezone is invalid (you can try it with some random string), there will of course be an exception 'Invalid time zone specified'. However, I don't know why `Intl` API think `UTC` is ok but does not perform as expected.

**Comment by Mateusz-Kopec** [comment]
I see, thanks!
