### ISSUE TITLE
updateLocale plugin should optionally require a locale (right now it is required, and does not match momentjs behavior)

### ISSUE THREAD

**Issue by niftylettuce** [iamkun/dayjs#1039]

**Comment by iamkun** [comment]
Any detail or demo code, please?

**Comment by niftylettuce** [comment]
Sure, it should be something like this:

Before (you have to specify every locale):

```js
var updateLocale = require('dayjs/plugin/updateLocale')
dayjs.extend(updateLocale)

dayjs.updateLocale('en', {
  months : String[]
})
```

After (if you don't specify a locale, it should do it for every one):

```js
var updateLocale = require('dayjs/plugin/updateLocale')
dayjs.extend(updateLocale)

dayjs.updateLocale({
  months : String[]
})
```

**Comment by niftylettuce** [comment]
This is especially helpful (for my use case) which is updating the relativeTime:

```js
dayjs.extend(updateLocale)

dayjs.updateLocale({
  relativeTime: {
    future: "in %s",
    past: "%s ago",
    s: 'a few seconds',
    m: "a minute",
    mm: "%d minutes",
    h: "an hour",
    hh: "%d hours",
    d: "a day",
    dd: "%d days",
    M: "a month",
    MM: "%d months",
    y: "a year",
    yy: "%d years"
  }
})
```

**Comment by iamkun** [comment]
Since Day.js's locale files are loaded on demand. There's no way that we can update them in a global scope.

Also, seems `moment.updateLocale({})` can not be called without a locale?

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
