### ISSUE TITLE
Format `MMMM D, YYYY, h:mm a` is invalid?

### ISSUE THREAD

**Issue by SHxKM** [iamkun/dayjs#1040]
**Describe the bug**
When parsing a string like so:

```js
dayjs.extend(dayjs_plugin_relativeTime);
dayjs.extend(dayjs_plugin_customParseFormat);
relative_time = dayjs("May 21, 2020, 4:50 a.m.", 'MMMM D, YYYY, h:mm a'); // even when false is specified
```

I get an invalid date object. [My string matches the documentation](https://day.js.org/docs/en/parse/string-format).

If I remove the time portion `h:mm a`, it works. But it wouldn't be useful to me.

**Expected behavior**
I expect to get a valid date object which I can then manipulate.

**Information**
 - Day.js Version 1.8.35
 - OS: MacOS
 - Browser: Safari
 - Time zone: GMT+3

Note: I'm importing the plugins in my HTML file, hence no `require()`.

**Comment by iamkun** [comment]
According to https://day.js.org/docs/en/parse/string-format#list-of-all-available-parsing-tokens, Day.js supports `am / AM` instead of `a.m.`.

One possible solution is 
```
const dateStr = 'May 21, 2020, 4:50 a.m.'
const parseStr = dateStr.replace('a.m.', 'am')
dayjs(parseStr, 'MMMM D, YYYY, h:mm a')
```
