### ISSUE TITLE
[RelativeTime] Support for custom precision

### ISSUE THREAD

**Issue by cloydlau** [iamkun/dayjs#1049]
May I ask how to make a count down with relativeTime or diff correcting to custom unit? RelativeTime only displays the nearest unit, is there a way to integrate it?

```js
dayjs.updateLocale('en', {
  relativeTime: {
    mm: function (number, withoutSuffix, key, isFuture) {

      // there's no ss here

      return string
    }
  }
})
```

I tried diff but it seems the minimal precision of which is 4 seconds.

I found a solution here [preciseDiff](https://github.com/huangjinlin/dayjs-precise-range), but it do not support localization, and it's under ISC license rather than MIT.

**Comment by iamkun** [comment]
Maybe `thresholds` and `rounding` is what you are looking for.

https://day.js.org/docs/en/customization/relative-time#relative-time-thresholds-and-rounding

**Comment by cloydlau** [comment]
Thresholds and rounding control the precision **respectively**, however, what I need is the whole thing. I checked the momentjs document, it seems the 'precise-range' plugin has been brought in as an official plugin. [momentjs-preciserange](http://momentjs.cn/docs/#/plugins/preciserange/)

**Comment by iamkun** [comment]
AFAIK, this is not an official plugin, just some listed on the website.

However, maybe https://day.js.org/docs/en/durations/diffing just suit your needs.

**Comment by cloydlau** [comment]
Duration+diffing will do the work, thanks for the reply.
