### ISSUE TITLE
Add notice in the Docs

### ISSUE THREAD

**Issue by cupcakearmy** [iamkun/dayjs#1058]
**Describe the bug**
User should be notified to install also the duration pluging when using `humanize`

When reading the docs (https://day.js.org/docs/en/durations/humanize) the user is told to install the `RelativeTime` plugin in order to make the humanize function work. However the `Duration` plugin is required to. Just a hint, took me 5-10 min to figure that out, unfortunatly it's nowhere in the docs.

Thanks for the great work!

**Comment by iamkun** [comment]
This is an interesting suggestion. However, the whole section is all about Duration and introduced here https://day.js.org/docs/en/durations/durations.

Should we also add this to each sub sections like https://day.js.org/docs/en/durations/milliseconds?

**Comment by cupcakearmy** [comment]
Fair point, seems a bit redundant.
I guess what threw me off was that that the sidebar was going ..., `i18n`, `Plugins`, ..., `Durations` so my mind probably was like: Oh ok it's outside of the docs for Plugins, nothing to be done for me.
Altough I appreciate giving it more visibility and not "hiding" it in the plugins docs.
On the other side adding a little banner like you already have in the humanitze docs is not much real estate and could help some people. 
I'll just leave it to you to decide :)
Feel free to close it

**Comment by iamkun** [comment]
Why not, added. 😬
