### ISSUE TITLE
weekdaysShort only return the first day

### ISSUE THREAD

**Issue by bahung1221** [iamkun/dayjs#1059]
Hi there, I facing a strange bug of `dayjs locale` that I can't reproduce on fiddle 😢
It only occur on my projects, this isn't the first time I used `dayjs`, but this is the first time I facing this problem. 
I know I should create reproduce steps but I can't because my projects is too large and I trying to replace `moment` by `dayjs` so it have a lot of changes 😢  

https://github.com/iamkun/dayjs/blob/8cf4d2d608b3cf99863b3ae77467dc8b9d83e729/src/index.js#L284
Sometime, the `locale.weekdaysShort` (line above) return only the first item of the full list, so it will result in a error on line below because `arr[index]` will be `undefined`:
https://github.com/iamkun/dayjs/blob/8cf4d2d608b3cf99863b3ae77467dc8b9d83e729/src/index.js#L262

I debugging a half of day but I can't find out why it occur, below is image that I captured when debugging directly on `dayjs.min.js` built file, please see it for more information because It really hard to describe by comment 😢 

A strange point is the error doesn't occur on default locale (en), It only occur when I use other locales (tested zh and vi locale).

Please see debug images below for more information because it really hard to be describe by comment.

<img width="940" alt="Screen Shot 2020-09-19 at 16 33 00" src="https://user-images.githubusercontent.com/27690861/93664066-55d0b100-fa96-11ea-8590-26113723e6a6.png">
<img width="792" alt="Screen Shot 2020-09-19 at 16 24 03" src="https://user-images.githubusercontent.com/27690861/93664188-430aac00-fa97-11ea-96ea-f2b7cfd4a860.png">

Thank you so much for a great library ever.

**Expected behavior**
The error `t is not a function` shouldn't fired

**Information**
 - Day.js Version 1.8.36
 - OS: MacOs
 - Browser: chrome 85
 - Time zone: GMT+07:00
 - Locale used for test: zh and vi

**Comment by bahung1221** [comment]
A quick work around for this issue is add check `function type` of weekdays `arr` parameter in `getShort` method:

```js
 format(formatStr) {
    if (!this.isValid()) return C.INVALID_DATE_STRING

    const str = formatStr || C.FORMAT_DEFAULT
    const zoneStr = Utils.z(this)
    const locale = this.$locale()
    const { $H, $m, $M } = this
    const {
      weekdays, months, meridiem
    } = locale
    const getShort = (arr, index, full, length) => (
      (arr && (arr[index] || typeof arr === 'function' && arr(this, str))) || full[index].substr(0, length)
    )
   ...
}
```

**Comment by iamkun** [comment]
I'm afraid I can not reproduce this on my computer. A demo repo provided will be better.

**Comment by bahung1221** [comment]
Thanks, I will try to reproduce it soon 😄

**Comment by bahung1221** [comment]
Figured it out, 
That is my mistake when migrating `moment` to `dayjs`, I call `splice` on array that returned from `dayjs.weekdaysShort()`, so it mutated *dayjs* locale data 😢 
Truly sorry 😄

**Comment by iamkun** [comment]
Cheers~
