### ISSUE TITLE
An unexpected type returned from dayjs.minMax when called with empty array

### ISSUE THREAD

**Issue by Firfi** [iamkun/dayjs#1061]
**Describe the bug**

An empty array is very unexpected here:

typeof dayjs.max([]) === 'array'; // true

there's an example: 

https://jsfiddle.net/7y5f6r3g/1/

**Expected behavior**

I expect to see either falsy value or a thrown exception when dayjs.max is called with an empty array.

**Information**
 - Day.js Version 1.8.36
 - OS: OSX
 - Browser Chrome

**Comment by iamkun** [comment]
Thanks, we will fix it to 'Return current time if passing empty array' the same as 'Return current time if no argument'

**Comment by Firfi** [comment]
@iamkun thank you for checking it so quickly! Appreciated. 

However, I humbly ask you to reconsider returning the current date. Had the library returned the current date I wouldn't have never caught this bug, leaving it to users instead to be puzzled by weird component behaviour. With an array, I at least had a chance to get an exception during development.

In that sense, there's no difference between returning the current date, 1 January 1970 or Donald Trump's birthday - all lead to hard to catch bug, with no help from static typing (if ts is used) or from dynamic type system (i.e. this array I've encountered giving some 'is not a function' error).

**Comment by iamkun** [comment]
Thanks, that makes sense.

Maybe Return `null` will be better to "passing empty array" and "passing no argument"?

**Comment by Firfi** [comment]
Whatever fits better the library general error handling approach. Assuming your API is similar to moment.js, they return null for this case. Also, a lot of other JS libraries would do so in similar cases. I think returning null is a safe bet.

**Comment by iamkun** [comment]
https://runkit.com/embed/c65l73q16y8p

![image](https://user-images.githubusercontent.com/17680888/94354367-e289f900-00ac-11eb-8792-c275ede99e17.png)

An interesting result from moment.js

**Comment by iamkun** [comment]
Finally, decide to return null while "passing empty array" and "passing no argument"?
