### ISSUE TITLE
withSuffix should be optional in the type for humanize

### ISSUE THREAD

**Issue by Axnyff** [iamkun/dayjs#1064]
**Describe the bug**
In this function
https://github.com/iamkun/dayjs/blob/dev/src/plugin/duration/index.js#L151
and in the website: https://day.js.org/docs/en/durations/humanize
we can see that humanize does not require an argument.

However, in the type declaration, it is mandatory:
https://github.com/iamkun/dayjs/blob/dev/types/plugin/duration.d.ts#L14

**Expected behavior**
The withSuffix parameters should be declared optional

I can do the fix if needed,
Thanks for your time

**Comment by iamkun** [comment]
Thanks.

**Comment by iamkun** [comment]
fixed in #1065
