### ISSUE TITLE
UTC conversion gives same timestamp as non-UTC object

### ISSUE THREAD

**Issue by ghostjester** [iamkun/dayjs#1066]
**Describe the bug**
When converting a dayjs object to UTC (using the https://github.com/guisturdy/dayjs-plugin-utc plugin), the unix() function returns the same timestamp as the non UTC object.

Result: 

        const nonUTC_dayjs= dayjs().startOf('month');
        const UTC_dayjs = dayjs.utc().startOf('month');
        const nonUTC_moment= moment().startOf('month');
        const UTC_moment = moment().utc().startOf('month');
        
        console.log(nonUTC_dayjs.unix());
        console.log(UTC_dayjs.unix());
        console.log(nonUTC_moment.unix());
        console.log(UTC_moment.unix());

outputs:
Dayjs:
        1598932800
        1598932800
Momentjs:
        1598932800
        1598918400

![image](https://user-images.githubusercontent.com/71670411/93820189-c8729580-fc2a-11ea-9aac-4b90aadd85c1.png)

**Expected behavior**
Converting a date object from EST timezone to UTC would (if I'm not mistaken) result in an epoch timestamp of 4 * (60 * 60) seconds in difference.

Note that the object themselves are of correct date ( with the UTC offset).

**Information**
 - Day.js Version [1.8.36]
- Moment.js Version [2.27.0]
 - Browser chrome/Microsoft Edge
 - Time zone: [Eastern Daylight Time]

**Comment by iamkun** [comment]
Please use our official UTC plugin  https://day.js.org/docs/en/parse/utc

**Comment by ghostjester** [comment]
I'm confused I thought this was the official one.
It's imported that way? 
import utc from 'dayjs/plugin/utc';

npm install dayjs-plugin-utc

**Comment by iamkun** [comment]
No extra installation is needed.

All you have to do is
```
var utc = require('dayjs/plugin/utc')
dayjs.extend(utc)
dayjs.utc().format()
```

**Comment by ghostjester** [comment]
Thank you for the clarification, although I am now using the official one, I am experiencing the same behavior when logging two separate objects (one local timezone and the other UTC)
        console.log(dayjs());
        console.log(dayjs.utc());
OR
       console.log(dayjs().unix());
        console.log(dayjs.utc().unix());

It returns the same date.
outputs:
![image](https://user-images.githubusercontent.com/71670411/93839541-4189e100-fc5b-11ea-8664-0b1a69a74c97.png)

**Comment by iamkun** [comment]
Please do not compare the Dayjs object directly. There's a lot inner logic before outputing.

Use `format` `toDate` `valueOf` to get the expected result.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by StasKovalov** [comment]
> Please do not compare the Dayjs object directly. There's a lot inner logic before outputing.
> 
> Use `format` `toDate` `valueOf` to get the expected result.

With these three methods, only format works fine, the rest do not check the date in utc or not, they return the local time.

**Comment by Dazaer** [comment]
@iamkun I'm having the same problem. Only `.format` works, everything else has utc returning the same value as local.

 I feel like if this is a feature it should be documented on https://day.js.org/docs/en/parse/utc that you will only truly get the utc value once you use `.format`.

**Comment by a-yerzhyk** [comment]
Issu opened in 2020 and still not fixed. Same for me only format() works well. Other methods like valueOf() doesnt.
