### ISSUE TITLE
Do you have any plans to support weeks to fromNow()

### ISSUE THREAD

**Issue by bumhyunkim** [iamkun/dayjs#1070]
Why does the fromNow function not support weeks?

It jumps from days ago -> months ago. Wouldn't the natural order be go from days to weeks?

ex 1 week ago, 2 weeks ago, 3 weeks ago, etc.

**Comment by iamkun** [comment]
No.

But it is easy to customize it by your self.

https://day.js.org/docs/en/customization/relative-time
