### ISSUE TITLE
Missing setDefault() method in DayjsTimezone interface plugin

### ISSUE THREAD

**Issue by antoninmorvan** [iamkun/dayjs#1071]
**Describe the bug**

In typescript, when i try to define setDefault() method from DayjsTimezone interface, it trigger a typescript error : 

`dayjs.tz.setDefault('Europe/Paris'); //Property 'setDefault' does not exist on type 'DayjsTimezone'.ts(2339)`

**Expected behavior**

The method has to be added in DayjsTimezone interface to make typescript happy.

**Information**
 - Day.js Version [e.g. v1.8.36]
 - OS: [MacOs Catalina]
 - Browser [chrome 85.0.4183.102]
 - Time zone: [e.g. UTC+2 CEST (Central European Summer Time)]

**Comment by iamkun** [comment]
This is already added here https://github.com/iamkun/dayjs/blob/dev/types/plugin/timezone.d.ts#L14

**Comment by antoninmorvan** [comment]
Ok thanks you, so it'll be available in next version
