### ISSUE TITLE
dayjs("Aug 2020") not working on Firefox and Safari

### ISSUE THREAD

**Issue by Omar-kh** [iamkun/dayjs#1075]
**Describe the bug**
When I try to create a dayjs object from a string with this format (ex.) "Aug 2020", it returns an object with an "Invalid date":

![image](https://user-images.githubusercontent.com/45049663/94168075-8d23d100-fe8d-11ea-819f-babd4f68412f.png)

In chrome, it works well

![image](https://user-images.githubusercontent.com/45049663/94168309-c8be9b00-fe8d-11ea-817a-1a09740e7405.png)

**To reproduce**
Go to the [dayjs](https://day.js.org/) website, open the console and try: `dayjs("Aug 2020")`
**Expected behavior**
It should be working the same as in chrome

**Information**
 - Day.js 1.18.36
 - OS: Linux 20.04
 - Browser Firefox 80.0.1 (64-bit)
 - Time zone: GMT +2 (France)

**Comment by iamkun** [comment]
For consistent results parsing anything other than ISO 8601 strings, you should use String + Format.
https://day.js.org/docs/en/parse/string-format

**Comment by Omar-kh** [comment]
That solved my issue, thanks
