### ISSUE TITLE
How can I include relativeTime in the browser without using import?

### ISSUE THREAD

**Issue by simplenotezy** [iamkun/dayjs#1076]
I'd like to simply include relativeTime in the browser without webpack/importing. Just a simple script tag.

I tried just adding the script tag for dayjs and then relativeTime, but that does not work.

Getting error: dayjs.unix(...).fromNow is not a function

**Comment by iamkun** [comment]
We have a demo code here https://day.js.org/docs/en/plugin/loading-into-browser

**Comment by simplenotezy** [comment]
Thanks. Figured that out quickly afterwards when looking at globals in the `window` object; guess I was a bit too fast there, and missed the "loading-into-browser" plugin page. Anyhow, thanks for a very fast response.
