### ISSUE TITLE
MomentJS UTC(true) Equivalent in DayJS

### ISSUE THREAD

**Issue by ChildishDanbino** [iamkun/dayjs#1078]
We are currently in the process of migrating our legacy momentJS code over to dayJS and so far it is going well. However, we are running into issues finding the equivalent function for utc(true) from MomentJS. 

Docs: https://momentjs.com/docs/#/manipulating/utc/

Per the Moment Docs: ```Passing true will change the time zone without changing the current time.```

For Reference This is the Failing Test:
```
  it('startOf year with local timezone', () => {
    const result = dayjs().startOf('year').utc().toISOString();

    const momentResult = moment().startOf('year').utc(true).toISOString()

    expect(result).toEqual('2020-01-01T00:00:00.000Z'); // fails
    expect(momentResult).toEqual('2020-01-01T00:00:00.000Z'); // passes
  });
```
 
In DayJS is there an equivalent function or how we can accomplish the same goal?

**Comment by iamkun** [comment]
We do support `.utcOffset(true)` only at present.

And `.utc(true)` shares a lot the same logic.  I'll implement it later soon.

**Comment by iamkun** [comment]
Added, and docs updated accordingly.  https://day.js.org/docs/en/manipulate/utc

**Comment by ChildishDanbino** [comment]
Awesome! Thanks so much. Cant wait for this to be merged.
