### ISSUE TITLE
.format('L') unexpected return

### ISSUE THREAD

**Issue by Firfi** [iamkun/dayjs#1082]
**Describe the bug**

`.format('L') === 'L' // true`

https://jsfiddle.net/t8k92h1f/

**Expected behavior**

MM/DD/YYYY as documented https://day.js.org/docs/en/display/format

**Information**
 - Day.js Version 1.8.36
 - OS: OSX
 - Browser Chrome
 - Time zone: GMT+8 (US system locale)

**Comment by iamkun** [comment]
As mentioned in https://day.js.org/docs/en/display/format#localized-formats

Localized formats dependent on LocalizedFormat plugin to work
