### ISSUE TITLE
Ignoring given format

### ISSUE THREAD

**Issue by dextermb** [iamkun/dayjs#1083]
**Describe the bug**
I've providing a format when passing in a date and it just seems to be ignored.

**Expected behavior**
When initially parsing the date given it should also check for the given format as suggested by the typings.

**Information**
 - Day.js Version `^1.8.36`
 - OS: `MacOS`
 - Ran in: `Node`

```js
const d1 = dayjs('31-03-2020', 'DD-MM-YYYY')

// d {
//   '$L': 'en',
//   '$d': Invalid Date,
//   '$y': NaN,
//   '$M': NaN,
//   '$D': NaN,
//   '$W': NaN,
//   '$H': NaN,
//   '$m': NaN,
//   '$s': NaN,
//   '$ms': NaN
// }

const d2 = dayjs('03-31-2020', 'DD-MM-YYYY')

// d {
//   '$L': 'en',
//   '$d': 2020-03-30T23:00:00.000Z,
//   '$y': 2020,
//   '$M': 2,
//   '$D': 31,
//   '$W': 2,
//   '$H': 0,
//   '$m': 0,
//   '$s': 0,
//   '$ms': 0
// }
```

Any ideas on why this is not working as expected or the last release that it was working?

**Comment by iamkun** [comment]
For consistent results parsing anything other than ISO 8601 strings, you should use [String + Format](https://day.js.org/docs/en/parse/string-format).

https://day.js.org/docs/en/parse/string
