### ISSUE TITLE
用antd-dayjs-webpack-plugin将moment替换成dayjs后，timeGrid模式下不能正常显示时间列表

### ISSUE THREAD

**Issue by semdy** [iamkun/dayjs#1087]
![微信截图_20200928122148](https://user-images.githubusercontent.com/9401913/94393362-5b608200-018d-11eb-92ca-46c40fd067b3.png)
fullcalendar: https://github.com/fullcalendar/fullcalendar
项目技术栈：react+antd+fullcalender+fullcalender-react

以下是引入的插件：
![微信截图_20200928132251](https://user-images.githubusercontent.com/9401913/94393512-c742ea80-018d-11eb-83c7-6219057bf53f.png)

**Comment by iamkun** [comment]
请先自行 debug 一下有什么报错，issue 反馈的信息里没有任何有价值的信息

**Comment by semdy** [comment]
经验证，不支持参数为数组的情况，例如：dayjs([2020, 9, 11, 20, 0, 0, 0]).format('HH:mm')

**Comment by iamkun** [comment]
a reproduction demo will be helpful.

**Comment by semdy** [comment]
运行dayjs([2020, 9, 11, 20, 0, 0, 0]).format('HH:mm')输出的结果是Invalid Date

**Comment by iamkun** [comment]
You can use arraySupport plugin in dayjs@1.9.2 like this
```js
var arraySupport = require("dayjs/plugin/arraySupport");
dayjs.extend(arraySupport);

dayjs([2020, 9, 11, 20, 0, 0, 0]);
```

Ref: https://day.js.org/docs/en/parse/array
