### ISSUE TITLE
format only can show am/pm?

### ISSUE THREAD

**Issue by lgy1159** [iamkun/dayjs#1088]
**Describe the bug**

**Expected behavior**

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

dayjs().format('YYYY-MM-DD hh:mm:ss') 
"2020-09-28 05:23:37"
i want to show "2020-09-28 17:23:37"

**Comment by lgy1159** [comment]
@iamkun

**Comment by iamkun** [comment]
You can check format tokens here https://day.js.org/docs/en/display/format#list-of-all-available-formats

**Comment by lgy1159** [comment]
> You can check format tokens here https://day.js.org/docs/en/display/format#list-of-all-available-formats

you are right thx  :)
