### ISSUE TITLE
Parse with array, month is off by 1.

### ISSUE THREAD

**Issue by greginns** [iamkun/dayjs#1091]
dayjs([2020, 8, 28]);
--> August 28, 2020

Should be September 28, 2020.

Dayjs 1.8.21
Firefox/Win7

**Comment by iamkun** [comment]
This is the expected behavior. 
Like the native `Date` object, the month is zero-based.

**Comment by greginns** [comment]
But August is month 8.  If zero based it should be the ninth month, September.

**Comment by iamkun** [comment]
Yes, I did not check this issue clearly.

Day.js does not officially support array like [2020, 8, 28] in the document.

And will pass it to native `Date` object.

So, the result should be exactly the same as `new Date([2020, 8, 28])`

**Comment by greginns** [comment]
OK, fair enough.
