### ISSUE TITLE
正则写法错误

### ISSUE THREAD

**Issue by Hareis** [iamkun/dayjs#1092]
![image](https://user-images.githubusercontent.com/11290701/94507168-b94ea180-0241-11eb-9d38-f6d59aa3d670.png)

**Comment by iamkun** [comment]
Any detail, please?

**Comment by Hareis** [comment]
> Any detail, please?

![image](https://user-images.githubusercontent.com/11290701/94507370-2eba7200-0242-11eb-9cb1-263558cc46ec.png)

**Comment by Hareis** [comment]
可能是我的编辑器提示错误了吧 实际我控制台中执行是可以的
