### ISSUE TITLE
Wrong difference calculation after converting date to UTC

### ISSUE THREAD

**Issue by criticalserenity** [iamkun/dayjs#1095]
**Describe the bug**
Method `diff` makes wrong calculation of time difference using UTC plugin.
There are test cases indicating the issue:

```js
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import utc from "dayjs/plugin/utc";

dayjs.extend(utc);
dayjs.extend(relativeTime);

const date = "09/29/2020 12:00"; // Initial date
const targetDate = "09/29/2020 17:00"; // Date for calculation date difference
const simulatedUTCDate = "09/29/2020 09:00"; // Simulated UTC date from my timezone (GMT+3)
const TIME_FORMAT = "HH:mm";

it("should calculate difference between dates in local timezone", () => {
  expect(dayjs(date).format(TIME_FORMAT)).toStrictEqual("12:00"); // Correct
  expect(dayjs(date).diff(targetDate, "hour")).toStrictEqual(-5); // Correct
});

it("should calculated difference between simulated UTC date and local date", () => {
  expect(dayjs(simulatedUTCDate).format(TIME_FORMAT)).toStrictEqual("09:00"); // Correct (works as 1st case)
  expect(dayjs(simulatedUTCDate).diff(targetDate, "hour")).toStrictEqual(-8); // Correct (works as 1st case)
});

it("should calculate difference between UTC date and local date", () => {
  expect(dayjs(date).utc().format(TIME_FORMAT)).toStrictEqual("09:00"); // Converted to UTC - correct for my timezone
  expect(dayjs(date).utc().diff(targetDate, "hour")).toStrictEqual(-8); // [!] Converted to UTC - incorrect for my timezone (result is -5)
});
```

[Codesandbox](https://codesandbox.io/s/sharp-austin-iej0q?file=/src/index.js) ("Tests" tab)

As a result method `fromNow` also works incorrect.

**Expected behavior**
2nd and 3rd cases should produce the same results, but `diff` method calculates difference wrong after conversion date to UTC.

**Information**
 - Day.js Version: `1.9.1`
 - OS: `Mac OS 10.15.5`
 - Browser: `Google Chrome 85.0.4183.121`, `Opera 71.0.3770.198`, `Firefox 81.0`
 - Time zone: `GMT+3 Europe/Minsk`

**Comment by iamkun** [comment]
`-5` is the expected result.

`.utc()` is only a flag to display the date in UTC mode, but it does not change the real date.

That is to say, 

`dayjs()` and `dayjs().utc()` represent the same time with no difference.

What you really need is [`.utcOffset`](https://day.js.org/docs/en/manipulate/utc-offset) or [`.tz`](https://day.js.org/docs/en/timezone/converting-to-zone) to change the timezone to get what you want.

**Comment by criticalserenity** [comment]
@iamkun not so obvious. I assumed `.utc()` is the alias of `.tz('UTC')`.
But anyway `dayjs(date).tz('UTC').diff(targetDate, 'hour')` is still `-5` while `dayjs` object contains correct time (09:00) under `$d` property. Am I doing something wrong?

**Comment by iamkun** [comment]
I think this is what you are looking for:
```
dayjs.tz('2020-09-29 12:00:00', 'UTC').diff(targetDate, 'hour')
```

**Comment by criticalserenity** [comment]
Main confusion is `dayjs.tz(date, 'UTC')` parses date in passed timezone, but `dayjs(date).tz('UTC')` converts date to passed timezone ([moment-timezone documentation](https://momentjs.com/timezone/docs/#/using-timezones/)).
Thank you for the answers.

**Comment by Brokray** [comment]
Hello there,

I am not sure to fully understand timezone with dayjs. 
With a practical example, I have the following snippet :
```javascript
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import customParseFormat from "dayjs/plugin/customParseFormat";
import utc from "dayjs/plugin/utc";
import timezone from "dayjs/plugin/timezone";
import "dayjs/locale/fr";

dayjs.locale("fr");
dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.extend(relativeTime);
dayjs.extend(customParseFormat);

dayjs.tz.setDefault("Europe/Paris");


dayjs().to(dayjs.tz("19:00:00", "HH:mm:ss", "Europe/Paris"));
```

The real server local timezone is unknown and I just want to output the time to a certain hours.
At 17:00:00 (Europe/Paris) upon calling the server I expect the answer to be : "In 2 hours". 
However the function returns "In 3 hours".

What am I missing here ? 🤔

**Comment by iamkun** [comment]
@Brokray  

dayjs.tz().to(dayjs.tz("19:00:00", "HH:mm:ss", "Europe/Paris"))
