### ISSUE TITLE
Wrong diff for DST in UTC mode 

### ISSUE THREAD

**Issue by jkondela** [iamkun/dayjs#1097]
**Describe the bug**
When using `utc` and one date is in DST while another is in non-DST, `diff` returns wrong value.
Diff for hours is correct, only days diff is affected.

For comparison, moment works as expected.

I noticed that `diff` is using timezone delta, but when dayjs is in UTC mode, the delta is 0 which is probably causing this bug.
https://github.com/iamkun/dayjs/blob/dev/src/index.js#L314

Maybe the same problem as here #1021 

```javascript
const dayjsD1 = dayjs.utc("2020-10-31"); // non DST date
const dayjsD2 = dayjs.utc("2020-10-31").add(-100, "days"); // DST
console.log(dayjsD1.diff(dayjsD2, "days"))
// prints 99


const momentD1 = moment.utc("2020-10-31");
const momentD2 = moment.utc("2020-10-31").add(-100, "days");
console.log(momentD1.diff(momentD2, "days"))
// prints 100
```

**Expected behavior**
Subtract 100 days from the original date should return diff 100 days.

**Information**
 - Day.js Version `v1.9.1`
 - OS: `Windows 10`
 - Browser `Chrome 85, Firefox 81`
 - Time zone: `GMT+2 DST Bratislava (Central European Summer Time)`

Thanks for the excellent date library.

**Comment by LiPinghai** [comment]
+1

**Comment by pavel-klavik** [comment]
+1, noticed this problem due to recent DST change in Central Europe. The number of hours is computed correctly by diff, so I can use it as a workaround.

```js
const day1 = dayjs.utc("20201023");
const day2 = dayjs.utc("20201026");
day1.diff(day2, "d"); // incorrect 2
day1.hour(day2, "h"); // correct 72
```

**Comment by iamkun** [comment]
fixed, thanks.

**Comment by robozb** [comment]
I experienced substract error when I use timezones, an example:

```
import dayjs from 'dayjs'; // Importáljuk a dayjs könyvtárat
import utc from 'dayjs/plugin/utc.js'
import timezone from 'dayjs/plugin/timezone.js'

dayjs.extend(utc); 
dayjs.extend(timezone);

const dt1=dayjs().tz("Atlantic/Reykjavik")
console.log(dt1.format("YYYY-MM-DD HH:mm"))

const dt2=dt1.subtract(1,"day")
console.log(dt2.format("YYYY-MM-DD HH:mm"))
```

Result:

```
2023-08-24 00:38
2023-08-22 22:38
```
