### ISSUE TITLE
wrong day in my timezone (UTC+3)

### ISSUE THREAD

**Issue by xvaara** [iamkun/dayjs#1105]
**Describe the bug**
I noticed a utc test failing after midnight at my timezone.

**Expected behavior**
Run tests.

**Information**
 - Day.js dev branch
 - OS: macos
 - Node v14.11.0
 - Time zone:(UTC+3)

![Screenshot 2020-10-02 at 1 55 43](https://user-images.githubusercontent.com/130606/94871507-d0b0a900-0452-11eb-8cbf-2d72c9ea184f.png)

```
 FAIL  test/plugin/objectSupport.test.js
  ● Constructor from Object UTC

    expect(received).toBe(expected) // Object.is equality
    
    Expected value to be:
      "2020-10-02 15:25:50.125"
    Received:
      "2020-10-01 15:25:50.125"

      121 |   for (let i = 0; i < tests.length; i += 1) {
      122 |     expect(dayjs.utc(tests[i][0]).format(fmt)).toBe(tests[i][1])
    > 123 |     expect(moment.utc(tests[i][0]).format(fmt)).toBe(tests[i][1])
      124 |   }
      125 | })
      126 | it('Set from Object', () => {
      
      at Object.<anonymous> (test/plugin/objectSupport.test.js:123:49)


Test Suites: 1 failed, 58 passed, 59 total
Tests:       1 failed, 569 passed, 570 total
Snapshots:   0 total
Time:        3.982s
Ran all test suites.
```

**Comment by xvaara** [comment]
It's about 2 am here at(or in) the moment. (pun intended)

**Comment by xvaara** [comment]
I'm thinking since it was the second date locally, and first ion UTC, dayjs initializes days differently. moment initialises on local time, then changes hours, dayjs initialized at utc?

**Comment by iamkun** [comment]
Thanks, fixed.
