### ISSUE TITLE
With localeData plugin extended, dayjs misses typescript types on listing name functions, dayjs.weekdays() e.g.

### ISSUE THREAD

**Issue by Mocha--** [iamkun/dayjs#1113]
**Describe the bug**
dayjs does not have function types in Typescript.

**Expected behavior**
With localeData plugin included, dayjs should have the declaration of functions below.

dayjs.weekdays()
dayjs.weekdaysShort()
dayjs.weekdaysMin()
dayjs.monthsShort()
dayjs.months() 

**Information**
 - Day.js Version 1.8.33
 - OS: Mac
 - Browser Chrome 85
 - Time zone: GMT+11:00

**Comment by iamkun** [comment]
True, would you like pulling request for this?

**Comment by Mocha--** [comment]
cool, happy to do that.

**Comment by zarghamkhandev** [comment]
@Mocha--  are you done with this ?

**Comment by iamkun** [comment]
Fixed in #1116
