### ISSUE TITLE
Parse Date from Object { date: 18 hour: 4 minute: 0 month: 6 year: 2020 }

### ISSUE THREAD

**Issue by RailgunWinjoy** [iamkun/dayjs#1114]
How to get the date from a object  ?
` 
 let obj = {date: 18
hour: 4
minute: 0
month: 6
year: 2020}`

I was using moment it could just `moment(obj)`

**Comment by iamkun** [comment]
https://day.js.org/docs/en/plugin/object-support

You can use ObjectSupport Plugin
ObjectSupport extends dayjs(), dayjs().set, dayjs().add, dayjs().subtract APIs to support object argument.
```
var objectSupport = require("dayjs/plugin/objectSupport");
dayjs.extend(objectSupport);

dayjs({
  year: 2010,
  month: 1,
  day: 12
});
dayjs().set({ year: 2010, month: 1, day: 12 })
dayjs().add({ M: 1 })
dayjs().subtract({ month: 1 })
```

**Comment by RailgunWinjoy** [comment]
Thank you
I also came up with a manual way:
` 
     let tmpParing = tmpDate = new Date(
                dateObj.year,
                dateObj.month, dateObj.date, dateObj.hour || 0, dateObj.minute || 0, dateObj.second || 0);
            tmpDate = dayjs.utc(tmpParing)
`

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
