### ISSUE TITLE
incorrect week of 2021

### ISSUE THREAD

**Issue by duxiaofeng-github** [iamkun/dayjs#1115]
**Describe the bug**
first week of 2021 should be 1, but it's 53 now.

**Expected behavior**
dayjs("2021-01-01T00:00:00").week() should equal 1.

**Information**
 - Day.js Version: 1.8.36
 - OS: Mac OS
 - Nodejs: v14.8.0
 - Time zone: +08:00

**Comment by duxiaofeng-github** [comment]
also, when i run `dayjs("2021-01-01T00:00:00").week(1)`, the expected result is "2021-01-01T00:00:00", because "2021-01-01" is the first week of 2021. but now it's "2021-01-03T00:00:00".

**Comment by iamkun** [comment]
Have you tried setting the correct locale?  https://day.js.org/docs/en/i18n/i18n

**Comment by duxiaofeng-github** [comment]
@iamkun yes, i set the locale to "zh-cn" already, but i don't think locales have anything to do with this issue.

code example here: https://codepen.io/anon/pen/xakpq

**Comment by iamkun** [comment]
Seems not a valid code demo link.

You can check this as a reference of week number https://www.epochconverter.com/weeks/2021

**Comment by duxiaofeng-github** [comment]
@iamkun ok, my bad, that code demo link is wrong.

according to that doc, the output result **week 53** was expected.

**Comment by iamkun** [comment]
Besides, If you want to get the first day of that year, you can use startOf('year')
