### ISSUE TITLE
[Question] How can I run unit tests after installing all the dependencies?

### ISSUE THREAD

**Issue by wadecoding** [iamkun/dayjs#1125]
I want to know how test cases are written so I cloned this repo to my machine and run `cnpm install`. Then I opened this repo in VS Code and typed `npm run test` in its console but got an error saying `'TZ' is not an internal or external command, nor is it a running program or batch file.`. Is there anything I miss or did wrong? I will appreciate it if you can help me at your convience.

我想学一下测试用例是怎么写的所以我把这个库克隆下来用VS Code打开并安装好了依赖，在VS Code的控制台输入`npm run test`之后报错，显示`'TZ' 不是内部或外部命令，也不是可运行的程序或批处理文件。`是不是我漏掉了什么东西或者什么步骤操作得不对呢，如果你能点拨我几句的话就非常谢谢了。

**Comment by iamkun** [comment]
We are running tests on a Linux machine. Not test it but I guess, TZ may not be supported on other OS.

**Comment by wadecoding** [comment]
Got it, thank you very much!
