### ISSUE TITLE
[Question] Is passing an array of formats to format input string the best option?

### ISSUE THREAD

**Issue by vicelu** [iamkun/dayjs#1127]
Hello, we have recently made the move to Dayjs from Moment in our projects and are very happy about it, but I have one question which is partially discussed in [#902](https://github.com/iamkun/dayjs/issues/902)

The question is if this is the right way of testing if the input format of a date (in the input field) does make a valid Dayjs object (for form validation)? And if it is, how big is the performance hit when Dayjs has so many format options to validate?

Our implementation includes following (called at every `onchange` of the input field):
```
dayjs(event.target.value, this.dateTimeFormat, true).isValid();
```
where dateTimeFormat is the array of all possible valid combinations of the datetime a user can write into the input field (other than these will show the input is not valid):
```
dateTimeFormat: [
            'DD.MM.YYYY HH:mm', 'D.MM.YYYY HH:mm', 'DD.M.YYYY HH:mm', 'D.M.YYYY HH:mm',
            'DD.MM.YYYY H:mm', 'D.MM.YYYY H:mm', 'DD.M.YYYY H:mm', 'D.M.YYYY H:mm',
            'DD.MM.YYYY HH:m', 'D.MM.YYYY HH:m', 'DD.M.YYYY HH:m', 'D.M.YYYY HH:m',
            'DD.MM.YYYY H:m', 'D.MM.YYYY H:m', 'DD.M.YYYY H:m', 'D.M.YYYY H:m'
        ]
```

**Comment by iamkun** [comment]
Dayjs treats this as a simple for loop, that is to say, to test each given format until a valid one.

**Comment by vicelu** [comment]
Thanks for the answer.
I suppose that means we have to stick with this method, even though it is not so elegant.

**Comment by iamkun** [comment]
What do you mean by 'stick with this method', pls?

**Comment by vicelu** [comment]
Well, we use Angular so we put Dayjs in a service, and because of that we don't need to define dateTimeFormat mulitple times (for every component that uses it), and makes it acceptable to define such an "error prone" and repetitive array of strings only once.

The idea was maybe to get some quirky way of defining those formats, which we possibly didn't see in the documentation or similar. I was hoping you would answer something like formats can be defined also in a bit different way, lets say `"D||DD.M||MM..."` which would mean that the format could be either with non leading zero or leading zero numbers and still be valid.
