### ISSUE TITLE
Property 'tz' does not exist on type 'Dayjs'

### ISSUE THREAD

**Issue by nishtacular** [iamkun/dayjs#1128]
**Describe the bug**
When trying to set timezone on `dayjs` TS throws the following error: `Property 'tz' does not exist on type 'Dayjs'`

```
// Example code
import * as dayjs from 'dayjs'

const testFunction = (date: Date) => {
  console.log(dayjs(date).tz('Australia/Sydney').format())
}
```

**Expected behavior**
`tz` function call should work as per example listed in the docs here https://day.js.org/docs/en/timezone/timezone

**Information**
 - Day.js Version 1.9.1
 - OS: MacOS
 - Browser - N/A 
 - Time zone: AEST

**Comment by nishtacular** [comment]
My bad didn't read the complete documentation. Fixed.

**Comment by bhaveshdaswani93** [comment]
can you provide the guide
how you solve this issue
I am facing the same problem

**Comment by iamkun** [comment]
@bhaveshdaswani93 

This dependent on Timezone plugin to work

https://day.js.org/docs/en/timezone/timezone

**Comment by bhaveshdaswani93** [comment]
Thanks brother for your reply.
I got your point and now it is working
