### ISSUE TITLE
Incorrect parsing of ISO 8601 duration

### ISSUE THREAD

**Issue by JasonHK** [iamkun/dayjs#1136]
**Describe the bug**

Durations with omitted units, like `"P4Y"`, will cause undefined behaviours, since the omitted units were `undefined`, not `0`. Also, decimals in second was not converted to integer. Lastly, `PnW` was not parsed.

**Expected behavior**

**Information**
 - Day.js Version v1.9.3
 - OS: Kubuntu
 - Browser Firefox 81.0
 - Time zone: GMT+08:00

**Comment by iamkun** [comment]
Can you provide a demo code, please?

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
