### ISSUE TITLE
[Feature request] [Website] Support trying plugins

### ISSUE THREAD

**Issue by KaKi87** [iamkun/dayjs#1138]
Hello,

Code snippets containing `dayjs.extend(somePlugin)` cannot be tested from the DevTools JavaScript console at [day.js.org](https://day.js.org).

Would it be possible to add support for this ?

Thanks !

**Comment by iamkun** [comment]
Sure, would you like to make a pull request on this? 

All we have to do is to add those plugins to this array

https://github.com/dayjs/dayjs-website/blob/master/website/core/Footer.js#L105

**Comment by KaKi87** [comment]
Okay, how about dynamically getting the plugins list ?

**Comment by KaKi87** [comment]
Also, what's that at L124 ?
I was surprised to see this request on uBlock.

**Comment by iamkun** [comment]
Maybe we don't need a dynamic list cause the plugin name won't change too often.

**Comment by iamkun** [comment]
> Also, what's that at L124 ?
> I was surprised to see this request on uBlock.

This is just a web static same as google analytics.

**Comment by KaKi87** [comment]
> Maybe we don't need a dynamic list cause the plugin name won't change too often.

You know, the efficient developers are the lazy ones. So the plugins list should be dynamically fetched so that they will never have to be updated :wink: 

> This is just a web static service same as google analytics.

Chinese analytics, seriously ?

**Comment by iamkun** [comment]
> > Maybe we don't need a dynamic list cause the plugin name won't change too often.
> 
> You know, the efficient developers are the lazy ones. So the plugins list should be dynamically fetched so that they will never have to be updated 😉

You can have a try 😬 

> > This is just a web static service same as google analytics.
> 
> Chinese analytics, seriously?

Any problem with this?

**Comment by KaKi87** [comment]
> You can have a try

Okay, however there is no tutorial on how the website works ?

> Any problem with this?

Definitely yes, major privacy concerns.

**Comment by iamkun** [comment]
> Okay, however there is no tutorial on how the website works ?

npm start 🤣 

> Definitely yes, major privacy concerns.

uBlock at your service 😁

**Comment by KaKi87** [comment]
I never used React, for example, how do I make an HTTPS GET request to an API returning a JSON body ?
Also, why isn't `iamkun/dayjs` located at `dayjs/dayjs` like the website at `dayjs/dayjs-website` ?
uBlock works for me, but what about other people who doesn't know ?

**Comment by iamkun** [comment]
this is not react.js and if you need any assistance related, you'd better visit https://github.com/facebook/react/

**Comment by KaKi87** [comment]
Nevermind, [it's done](https://github.com/dayjs/dayjs-website/pull/26).

**Comment by iamkun** [comment]
cool thanks

**Comment by KaKi87** [comment]
But, I still have two unanswered questions xD

> Also, why isn't iamkun/dayjs located at dayjs/dayjs like the website at dayjs/dayjs-website ?

> uBlock works for me, but what about other people who doesn't know ?
