### ISSUE TITLE
Warn/error if a format is given when customParseFormat plugin is not enabled?

### ISSUE THREAD

**Issue by andreynering** [iamkun/dayjs#1139]
It confused me on why the format was totally ignored when parsing dates, until I noticed you need to plugin to do it.

I think the lib should print a warning in the console (or even print or throw an error) when a format argument is given but the plugin wasn't enabled. Otherwise, it's having a totally different behavior which can cause confusion to users.

### Plugin disabled

```js
dayjs('2020-12-31T06:44:08.194Z', 'MM/DD/YYYY').format('MM/DD/YYYY')
"12/31/2020"
```

### Plugin enabled

```js
dayjs('2020-12-31T06:44:08.194Z', 'MM/DD/YYYY').format('MM/DD/YYYY')
"Invalid Date"
```

**Comment by iamkun** [comment]
True, maybe we should leave more notice either in the lib or the docs.

**Comment by iamkun** [comment]
We can add this as a special dev plugin

**Comment by iamkun** [comment]
Added in #1163.

**Comment by andreynering** [comment]
@iamkun Thanks!
