### ISSUE TITLE
Option to display time zone in .format() not working

### ISSUE THREAD

**Issue by JorgeSivil** [iamkun/dayjs#1141]
**Describe the bug**

```
import dayjs from 'dayjs';
import dayjsUtc from 'dayjs/plugin/utc';
import dayjsTimezone from 'dayjs/plugin/timezone';
import dayjsAdvancedFormat from 'dayjs/plugin/advancedFormat';
dayjs.extend(dayjsUtc);
dayjs.extend(dayjsTimezone);
dayjs.extend(dayjsAdvancedFormat);

dayjs(unixTimestamp).tz('America/Los_Angeles').format(`z`) // results in z being outputted instead of the short timezone name.
```

The other advanced format options do work (at least the ones not requiring a plugin)

**Expected behavior**
Should be able to display timezone short name / long name

**Information**
 - Day.js Version "dayjs": "^1.9.3", plugin-utc": "^0.1.2",
 - OS: Linux
 - Browser Firefox 82
 - Time zone: [e.g. GMT-07:00 PDT (Pacific Daylight Time)]

**Comment by JorgeSivil** [comment]
Never mind it was in the advanced format section, depending on a plugin

**Comment by JorgeSivil** [comment]
Fuck I'm so tired of being wrong

**Comment by mrkrlli** [comment]
Newest version of dayjs will have the `z` formatting option (added in 1.9.0): https://github.com/iamkun/dayjs/pull/1069
