### ISSUE TITLE
[Bug] format() with H or HH returns 1 or 01 instead of 0

### ISSUE THREAD

**Issue by KaKi87** [iamkun/dayjs#1142]
Hello,

**Describe the bug**

Example :

`dayjs(1000 * 60 * 2).format('HH:mm:ss')`

Real use case :
```js
const
    t2 = dayjs(),
    t1 = t2.subtract(2, 'minute');
return dayjs(t2 - t1).format('HH:mm:ss');
```

**Expected behavior**

`00:02:00`

**Actual behavior**

`01:02:00`

**Information**

 - Day.js Version : the one in devtools at day.js.org
 - OS : `Linux`
 - Browser : `Brave 1.15.75`
 - Time zone : `GMT+0200 (Central European Summer Time)`

**Thanks !**

**Comment by iamkun** [comment]
It makes none sense to use `dayjs(t2 - t1)`, cause dayjs will treat this passed in number as a Unix timestamp.

**Comment by KaKi87** [comment]
Then how can I output the diff between two dates in `HH:MM:SS` format ?

**Comment by KaKi87** [comment]
Plus, if my code isn't supposed to work, shouldn't it output an error ?

**Comment by iamkun** [comment]
The argument you passed in is absolutely valid to Day.js. Just not the behavior you expected. So no output error is needed.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by KaKi87** [comment]
> Then how can I output the diff between two dates in HH:MM:SS format ?

Still unanswered.
