### ISSUE TITLE
Advanced formater not showing PDT for 2019.

### ISSUE THREAD

**Issue by JorgeSivil** [iamkun/dayjs#1145]
**Describe the bug**
Advanced formatter not showing PDT for 2019.
I have a date formatted with z to show PDT, which in fact works correctly for this year dates.
However, for the previous year, it is not showing PDT, even if the date is in PDT.

![image](https://user-images.githubusercontent.com/12187148/96279444-0b672500-0fad-11eb-9598-51ee2a53c522.png)

**Expected behavior**
It should show PDT for all previous years, not only for current.

**Information**
 - Day.js "dayjs": "1.9.3",   "dayjs-plugin-utc": "0.1.2",
 - OS: Linux
 - Browser [Firefox 82]
 - Time zone: [GMT-07:00 PST / PDT]

**Comment by iamkun** [comment]
"dayjs-plugin-utc" this is not our official plugin, please use UTC mode with the timezone plugin instead. https://day.js.org/docs/en/timezone/timezone

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by JorgeSivil** [comment]
@iamkun this is the code we are using. I don't think we are using the plugin, right?

```
import ListDataMapper from 'domain/Services/DataMappers/ListDataMapper';
import dayjs from 'dayjs';
import dayjsUtc from 'dayjs/plugin/utc';
import dayjsTimezone from 'dayjs/plugin/timezone';
import dayjsAdvancedFormat from 'dayjs/plugin/advancedFormat';
dayjs.extend(dayjsUtc);
dayjs.extend(dayjsTimezone);
dayjs.extend(dayjsAdvancedFormat);

export default class ListDataMapperServerSide extends ListDataMapper {
  map(data) {
    const mappedData = super.map(data);

    mappedData.list.editorialModifiedOnFormatted = data.editorialModifiedOn
      ? dayjs(data.editorialModifiedOn)
          .tz('America/Los_Angeles')
          .format(`MMMM D, YYYY ${mappedData.options.includeTimestamp ? '[&#x2022;] h:mma z' : ''}`)
      : '';

    mappedData.list.publishDateFormatted = data.list.publishDate
      ? dayjs(data.list.publishDate)
          .tz('America/Los_Angeles')
          .format(`MMMM D, YYYY ${mappedData.options.includeTimestamp ? '[&#x2022;] h:mma z' : ''}`)
      : '';

    return mappedData;
  }
}
```

**Comment by iamkun** [comment]
This is because, in the main issue, we could see a "dayjs-plugin-utc": "0.1.2", which is not an official plugin we provide.
