### ISSUE TITLE
Add short descriptions to TypeScript types

### ISSUE THREAD

**Issue by usernamehw** [iamkun/dayjs#1147]
This library has built-in types for TypeScript https://github.com/iamkun/dayjs/blob/b342bd3d84987d6c7587a0c4590d614fb0e670d7/types/index.d.ts and that's great.

Would it be possible to create a short description for every function, perhaps with examples like input->output and links to documentation.

Example:

```ts
class Dayjs {
    /**
     * Returns a cloned Day.js object with a specified amount of time added.
     * @example
     * ```
     * dayjs().add(7, 'day')
     * ```
     * Docs: https://day.js.org/docs/en/manipulate/add
     */
    add(value: number, unit: OpUnitType): Dayjs
}
```

**Comment by iamkun** [comment]
That sounds cool. Would you like to give it a try?
