### ISSUE TITLE
String Type Unix timestamp support   

### ISSUE THREAD

**Issue by lqzhgood** [iamkun/dayjs#1150]
**Describe the bug**
```
dayjs("1564482923186").format('YYYY-MM-DD') ==> "1567-12-29" ❌
dayjs(1564482923186).format('YYYY-MM-DD') ==> "2019-07-30"  ✔️
```

**Expected behavior**
```
dayjs("1564482923186").format('YYYY-MM-DD') ==>  "2019-07-30"  ✔️
```

**Information**
 - Day.js Version 1.9.3
 - OS: Windows
 - Browser Chrome 86
 - Time zone: UTC+08:00

**Comment by iamkun** [comment]
a unit timestamp is always a `Number` not a `String`

**Comment by lqzhgood** [comment]
I know that timestamps are numeric, and supporting this will be stronger.

Or for this kind of obvious error, error should be reported directly instead of giving an error value.

like  `new Date("1564482923186") ==> Invalid Date `

**Comment by iamkun** [comment]
Ture, we can add this as a special plugin

**Comment by iamkun** [comment]
Added in #1163
