### ISSUE TITLE
Should add polyfill option in timezone

### ISSUE THREAD

**Issue by chuanxie** [iamkun/dayjs#1152]
Using dayjs for react native but got an issue on android due to `Intl` is not support.
would nice to have polyfilll option if `Intl` is undefined
https://github.com/formatjs/date-time-format-timezone

**Comment by iamkun** [comment]
Yes, you can check the introduction here https://day.js.org/docs/en/timezone/timezone

**Comment by devinjameson** [comment]
> Using dayjs for react native but got an issue on android due to `Intl` is not support.
> would nice to have polyfilll option if `Intl` is undefined
> https://github.com/formatjs/date-time-format-timezone

@chuanxie If you're seeing this issue on Android you may need to update your app build.gradle:

```
/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc-intl:+'
```
