### ISSUE TITLE
antd3  umi2.9   dayjs 1.9.3   DatePicker.RangePicker  月份和星期显示为 英文

### ISSUE THREAD

**Issue by ado5** [iamkun/dayjs#1155]
umirc : 

```
    config.plugin('moment2dayjs').use('antd-dayjs-webpack-plugin', [
      {
        preset: 'antdv3',
      },
    ])


    config.plugin('ignore').use(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)) //忽略/moment/locale下的所有文件
```

```
import 'dayjs/locale/zh-cn'
 dayjs.locale('zh-cn')
```

设置后，日期选择器还是 月份和星期是 英文， 其他是中文

![base64str](https://raw.githubusercontent.com/ado5/Spa/master/picker.png)

**Comment by iamkun** [comment]
Please set the Day.js locale correctly/. 
https://ant.design/components/date-picker/#Localization

**Comment by ado5** [comment]
> Please set the Day.js locale correctly/.
> https://ant.design/components/date-picker/#Localization

Thanks. Done.
