### ISSUE TITLE
Links on the docs website always go to a cdn.jsdelivr.net page

### ISSUE THREAD

**Issue by scottsandersdev** [iamkun/dayjs#1158]
Currently any link on the docs website (https://day.js.org/docs/en/parse/parse) link to a https://cdn.jsdelivr.net/gh/dayjs/dayjs-website url. If I click on the link on the redirected page it gives me unformatted html. This makes looking things up in documentation complicated

**Comment by jhartman86** [comment]
seconded - seeing only a CDN page

**Comment by nuflowx** [comment]
cool, it's not just me. Thought maybe one of my extensions was messing things up, but seems to be on the site itself :/

**Comment by iamkun** [comment]
Fixed, thanks.
