### ISSUE TITLE
No ordinal number spelling after the day automatically when using format()

### ISSUE THREAD

**Issue by ljmerza** [iamkun/dayjs#116]
Using D or DD for the day format string doesn't add the ordinal number spelling such as 1st, 2nd, 3rd, 4th, etc. 

```
dayjs('2016-01-24 01:23:45').format('MMMM D YYYY, h:mm:ss a')
```

outputs:

```
"January 24 2016, 1:23:45 am"
```

We need a way to automatically detect which ordinal number spelling goes after the day

**Comment by iamkun** [comment]
Currently we support. 

Unit| - | -
-- | -- | --
D | 1-31 | The day of the month
DD | 01-31 | The day of the month, 2-digits

Please check our docs.

**Comment by iamkun** [comment]
@ljmerza
We have this now.
ordinal number support added in release 1.6 🎊 🎉 through AdvancedFormat Plugin

check [AdvancedFormat Plugin](https://github.com/iamkun/dayjs/blob/master/docs/en/Plugin.md#advancedformat)

**Comment by hutber** [comment]
It might be worth making this clearer? Sorry as I didn't understand this :)
