### ISSUE TITLE
Cannot find module 'dayjs/plugin/timezone' in sub-module

### ISSUE THREAD

**Issue by spsaucier-bakkt** [iamkun/dayjs#1167]
**Describe the bug**
Similar to #1135, getting `Cannot find module 'dayjs/plugin/timezone' from 'node_modules/my-module'` when importing my module from elsewhere and trying to run tests.

The plugin works properly within the code where it's used, but this issue appears when importing it as  node_module.

**Expected behavior**
Able to import dayjs plugins and use them in code used as a sub-module.

Usage in sub-module:
```
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';
import dayjsIsBetween from 'dayjs/plugin/isBetween';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone';
dayjs.extend(customParseFormat);
dayjs.extend(dayjsIsBetween);
dayjs.extend(utc);
dayjs.extend(timezone);
```

**Information**
 - Day.js Version: v1.9.4
 - OS: Mac
 - Browser Terminal

**Comment by iamkun** [comment]
A reproduction repo, please?

**Comment by spsaucier-bakkt** [comment]
This was resolved when I added `dayjs` to the app that consumes the library which uses `dayjs`. Not sure why that would be required.

**Comment by BroJenuel** [comment]
I dont know if its in codesanbox that's making the error,, but here is the example of an error,,, cant find module.
https://codesandbox.io/s/dayjs-playground-forked-mqd4u?file=/src/index.js
![image](https://user-images.githubusercontent.com/31676163/142381116-92f669c5-f751-486f-b17f-892b6472e99b.png)

**Comment by bartosjiri** [comment]
I had a similar problem when compiling a production build of a SvelteKit app. The solution, as console error has suggested, was to add the `.js` extension to the import path:

Example:
`import timezone from 'dayjs/plugin/timezone';` -> `import timezone from 'dayjs/plugin/timezone.js';`

**Comment by mohas** [comment]
but why?

**Comment by vhscom** [comment]
Using PNPM a related error appeared as:

```term
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/src/svelte-headlessui-starter/node_modules/dayjs/plugin/weekOfYear' imported from /src/svelte-headlessui-starter/.svelte-kit/output/server/entries/pages/calendar.svelte.js
Did you mean to import dayjs@1.11.0/node_modules/dayjs/plugin/weekOfYear.js?
```

Adding `.js` to the `dayjs/plugin` imports [as suggested](https://github.com/iamkun/dayjs/issues/1167#issuecomment-972880586) by @bartosjiri and mentioned in https://github.com/sveltejs/kit/issues/699 cleared up the issue.

**Comment by vhscom** [comment]
Using PNPM a related error appeared as:

```term
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/src/svelte-headlessui-starter/node_modules/dayjs/plugin/weekOfYear' imported from /src/svelte-headlessui-starter/.svelte-kit/output/server/entries/pages/calendar.svelte.js
Did you mean to import dayjs@1.11.0/node_modules/dayjs/plugin/weekOfYear.js?
```

Adding `.js` to the `dayjs/plugin` imports [as suggested](https://github.com/iamkun/dayjs/issues/1167#issuecomment-972880586) by @bartosjiri and mentioned in https://github.com/sveltejs/kit/issues/699 cleared things up.

**Comment by vhscom** [comment]
Likely root cause of this error: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions

**Comment by vhscom** [comment]
More about what's causing this error with bare imports: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions

**Comment by vhscom** [comment]
More about what's causing this error with bare imports: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions
Learned about it here: https://github.com/tailwindlabs/tailwindcss/issues/5089#issuecomment-900228952

**Comment by nahumzs** [comment]
> but why?

If you are using playwright, It has to do with module resolution, typescript and js, don't remember where I read it but I know is close enough to that situation. I someone can add a more extensive description would be great.
