### ISSUE TITLE
Typings for arraySupport missed

### ISSUE THREAD

**Issue by Lonli-Lokli** [iamkun/dayjs#1170]
**Describe the bug**
arraySupport (https://github.com/iamkun/dayjs/issues/1129) lacks Typescript typings

**Expected behavior**
It should be possible to use arrays with typescript

**Information**
 - Day.js Version 1.9.4
 - OS: Win10
 - Browser Chrome
 - Time zone: GMT+3

**Comment by iamkun** [comment]
Thanks, will support it.

A problem here seems we can not update the dayjs function typing via another .d.ts file in plugin.

**Comment by Lonli-Lokli** [comment]
@iamkun why?
I believe it's pretty common, see https://www.damirscorner.com/blog/posts/20200911-ExtendingTypescriptTypeDefinitions.html as an example.

**Comment by iamkun** [comment]
I've tried but seems not working. 
Would you like to draft a pull request to fix this? It is expected to update this file https://github.com/iamkun/dayjs/blob/dev/types/plugin/arraySupport.d.ts to make it work.
