### ISSUE TITLE
What is the equivalent of this moment code momentDateObj.localeData().meridiem?

### ISSUE THREAD

**Issue by suaha** [iamkun/dayjs#1172]
**Describe the bug**
What is the equivalent of this moment code momentDateObj.localeData().meridiem?

In moment I did this:

```
momentDateObj.localeData().meridiem = function (hours) {
                return hours > 11 ? I18NService.getMessage('default:time.picker.pm') : I18NService.getMessage('default:time.picker.am');
            };
```

**Expected behavior**
I want to change a dayjs object's meridiem function

**Information**
 - Day.js 1.8.36
 - OS: windows 10
 - Browser Chrome 86
 - Time zone: +8

**Comment by iamkun** [comment]
If you want to update `meridiem`  config, you could use 
```
dayjs.updateLocale('en', {
    meridiem: function() {}
})
```
https://day.js.org/docs/en/customization/customization

**Comment by suaha** [comment]
> If you want to update `meridiem` config, you could use
> 
> ```
> dayjs.updateLocale('en', {
>     meridiem: function() {}
> })
> ```
> 
> https://day.js.org/docs/en/customization/customization

Thanks @iamkun for the quick response, I just want to update one dayjs object's meridiem not the dayjs config of the locale, is it possible?

**Comment by iamkun** [comment]
There no function to update the locale config in one Day.js instance ATM. You can use a new custom locale config in that instance.

We will add `localeData().meridiem` in the next release.

**Comment by suaha** [comment]
> There no function to update the locale config in one Day.js instance ATM. You can use a new custom locale config in that instance.
> 
> We will add `localeData().meridiem` in the next release.

Got it, will try. Thanks for the information.
