### ISSUE TITLE
Parse date in ISO 8601 format with strict mode

### ISSUE THREAD

**Issue by pustovalov** [iamkun/dayjs#1173]
**Describe the bug**

```
dayjs('2017-07-08T07:25:17.000-07:00').format('YYYY-MM-DDTHH:mm:ss.SSSZ')
"2017-07-08T17:25:17.000+03:00"

dayjs('2017-07-08T07:25:17.000-07:00', 'YYYY-MM-DDTHH:mm:ss.SSSZ', true)
d {$L: "en", $u: undefined, $d: Invalid Date, $y: 2017, $M: 6, …}
```

is this expected behavior?

**Information**
 - Day.js Version 1.9.3
 - OS: macOS 10.15.17
 - Browser chrome 85.0.4183.121
 - Time zone: GMT+3

**Comment by iamkun** [comment]
if you want to specify the format, you have to enable customParseFormat plugin first. https://day.js.org/docs/en/parse/string-format

**Comment by pustovalov** [comment]
this is already with enabled `CustomParseFormat` plugin

**Comment by iamkun** [comment]
Thanks. I see. This is a known bug. re #929
