### ISSUE TITLE
Leap year is not added to dayjs().week()

### ISSUE THREAD

**Issue by helenabarmer** [iamkun/dayjs#1176]
**Describe the bug**

When I use `dayjs('2020-12-30').week()`, is should return 53 since this year is a **leap year** but the output is 1.

If you then do `dayjs('2021-01-04').week()` it returns 2 but should return 1 as this is the first week of year 2021.

**Expected behavior**
`dayjs('2020-12-30').week(`) should return 53 this year (2020).
`dayjs('2021-01-04').week()` should return 1 next year (2021)

**Information**
 - Day.js Version 1.9.4
 - OS: Windows
 - Time zone: GMT +1

**Comment by iamkun** [comment]
Hi, if you want to get the ISO week of the year, you should check https://day.js.org/docs/en/get-set/iso-week
```
dayjs('2020-12-30').isoWeek()
```

**Comment by helenabarmer** [comment]
@iamkun I totally missed this, thank you ever so much!

**Comment by iamkun** [comment]
Cheers
