### ISSUE TITLE
Compute a human-readable difference between two date-times?

### ISSUE THREAD

**Issue by njlr** [iamkun/dayjs#118]
(I did a quick Google for this and found nothing)

I would like to format the difference between two dates so that it is easily human-readable. 

For example: 

 - `Just now`
 - `1 hour ago`
 - `3 days ago`
 - etc... 

Does `daysjs` provide this functionality?

**Comment by iamkun** [comment]
No for now, I'm afraid.

But we may could add such function through a plugin later.

**Comment by iamkun** [comment]
@njlr added in release 1.6.4.🎊 🎉

check [RelativeTime Plugin](https://github.com/iamkun/dayjs/blob/master/docs/en/Plugin.md#relativetime)
