### ISSUE TITLE
How to use dayjs in a simple HTML /JS (non node) project

### ISSUE THREAD

**Issue by MinesService** [iamkun/dayjs#1181]
I do not understand how to use this library in a simple project without the need to install the node module.
If I download the latest release and unzip the archive, I cannot find the `dayjs.min.js` file in it.

Thanks in advance.

**Comment by iamkun** [comment]
https://day.js.org/docs/en/installation/browser

**Comment by iamkun** [comment]
This should be the link you are looking for https://www.jsdelivr.com/package/npm/dayjs

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by davidkonrad** [comment]
So, we are forced to use a CDN if we want to use dayjs? Or where is this famous, mysterious day.min.js?
