### ISSUE TITLE
isValid() function is broken

### ISSUE THREAD

**Issue by rkazakov** [iamkun/dayjs#1182]
**Describe the bug**
isValid() function is broken.

![image](https://user-images.githubusercontent.com/168863/98067095-e62f4d80-1eac-11eb-8cd4-ad3d577d5f5a.png)

**Expected behavior**
isValid() should work correctly.

**Information**
 - Day.js Version: v1.9.4
 - Runtime: Node 10

**Comment by iamkun** [comment]
Please pass 'true' as the third argument to enable strict parsing https://day.js.org/docs/en/parse/string-format

**Comment by rkazakov** [comment]
@iamkun Got it, thanks.
