### ISSUE TITLE
t is not a function

### ISSUE THREAD

**Issue by mingxin-yang** [iamkun/dayjs#1185]
**Describe the bug**
My code is 
`import dayjs from 'dayjs';     
import {isSameOrBefore} from 'dayjs/plugin/isSameOrBefore'     
import {isSameOrAfter} from 'dayjs/plugin/isSameOrAfter'     
dayjs.extend(isSameOrBefore)   
dayjs.extend(isSameOrAfter) `

**Expected behavior**

**Information**
 - Day.js Version v1.9.5
 - OS: android
 - Browser react native
 - Time zone:UTC/GMT +8 hours CST

**Comment by iamkun** [comment]
can you try `import isSameOrBefore from 'dayjs/plugin/isSameOrBefore'` instead

**Comment by mingxin-yang** [comment]
ok, it work
