### ISSUE TITLE
Incorrect date on dayjs creation via string format on Firefox, ok on Chrome

### ISSUE THREAD

**Issue by CodeMantle** [iamkun/dayjs#1191]
Describe the bug:
    var cdate = dayjs('12-Jan-2020', 'DD-MMM-YYYY');
    console.log(cdate);
    // displays a datejs object with $d date value of Sat Jan 12 -2020 00:00:00 GMT-0001 (Greenwich Mean Time)

Expected behavior:
As on Chrome, where this displays a corresponding date of Sun Jan 12 2020 00:00:00 GMT+0000 (Greenwich Mean Time)

Information:
 - Day.js Version: 1.9.4
 - OS: Windows 10
 - Browsers FF 82.0.2, Chrome 86.0.4240.183
 - Time zone: GMT-01:00 (Daylight Savings Time)

**Comment by iamkun** [comment]
For consistent results parsing anything other than ISO 8601 strings, you should use String + Format. https://day.js.org/docs/en/parse/string-format

Plus, you could enable DevHelper plugin to get this warning in your development https://day.js.org/docs/en/plugin/dev-helper

**Comment by CodeMantle** [comment]
Thanks for reply. I have the customParseFormat.js file. How can I use this in a plain JS DOM environment?
The usage advice is based only on node - dayjs.extend(customParseFormat)?

**Comment by iamkun** [comment]
https://day.js.org/docs/en/plugin/loading-into-browser Loading plugin in the browser

**Comment by CodeMantle** [comment]
Thanks for the speedy reply, and instructions on how to deploy the customParseFormat extension.
Issue is now solved.
