### ISSUE TITLE
customParseFormat plugin make some mistakes

### ISSUE THREAD

**Issue by lyz810** [iamkun/dayjs#1194]
**Describe the bug**
```
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';
// this is right
console.log(dayjs('2020-01-01', 'YYYY-MM-DD', true).isValid());// true

// using customParseFormat plugin
dayjs.extend(customParseFormat);

// this is wrong, after customParseFormat plugin loaded
console.log(dayjs('2020-01-01', 'YYYY-MM-DD', true).isValid());// false
```

**Expected behavior**
The second console.log should print true as the first one.

**Information**
 - Day.js Version 1.9.5
 - OS: Mac OS X 10.15.7
 - Browser : Chrome/86.0.4240.80
 - Time zone: GMT +08:00

**Comment by alex-w0** [comment]
I've the same problem when I'm trying to use strict format:

This example should return true:
```
dayjs.extend(customParseFormat);
dayjs(
    '2020-11-08 19:34:39',
    'YYYY-MM-DD HH:mm:ss',
    true
  ).isValid() // false
```
https://repl.it/@alexw0/dayjs-test#index.js

Is this a bug or are we doing anything wrong?

**Comment by SomethingSexy** [comment]
I am actually noticing this is an issue between 1.9.4 and 1.9.5.

**Comment by iamkun** [comment]
Will fix soon in the next release.
