### ISSUE TITLE
From where to download isBetween plugin

### ISSUE THREAD

**Issue by kunalahirrao** [iamkun/dayjs#1204]
**Describe the bug**
NPM package to download isBetween plugin is missing.

**Expected behavior**
NPM package to download isBetween plugin is missing. Share link from NPM/Github 

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
```
var isBetween = require('dayjs/plugin/isBetween')
dayjs.extend(isBetween)
```
https://day.js.org/docs/en/plugin/is-between

**Comment by kunalahirrao** [comment]
Is it a NPM package or it comes preshipped with dayjs itself.

**Comment by kunalahirrao** [comment]
It returns false for this dayjs('2020-11-11').isBetween('2020-10-19', dayjs('2010-11-25')).It should return true as 11-11 is between 19-10 and 25-11

**Comment by iamkun** [comment]
> Is it a NPM package or it comes preshipped with dayjs itself.

you can see the demo code above, it comes pre-shipped with dayjs itself

**Comment by kunalahirrao** [comment]
It returns false for demo code as well , it must return true for this --- dayjs('2010-10-20').isBetween('2010-10-19', dayjs('2010-10-25'), 'year')

**Comment by iamkun** [comment]
Looks ok
https://runkit.com/embed/zsy62fiq7o5d
![Uploading Screen Shot 2020-11-11 at 3.31.09 PM.png…]()
