### ISSUE TITLE
希望能够增加公历和农历的转换。

### ISSUE THREAD

**Issue by jingyuexing** [iamkun/dayjs#1215]
I hope to support the transformation of the Chinese calendar and the Gregorian calendar

**Comment by iamkun** [comment]
Sorry, we have no plan to support this feature.

**Comment by SalahAdDin** [comment]
> Sorry, we have no plan to support this feature.

so, you have no plans to support non-gregorian calendars as well, right?

**Comment by Chen-913** [comment]
It's a pity.
🤧

**Comment by Bricks-moving** [comment]
有阳历转农历的插件么

**Comment by SalahAdDin** [comment]
Have to move to `date-fn` then.

**Comment by SalahAdDin** [comment]
> > 有阳历转农历的插件么
> 
> [dayjs-plugin-lunar](https://github.com/baranwang/dayjs-plugin-lunar)

@baranwang It is the Chinese calendar. right?

**Comment by baranwang** [comment]
> > > 有阳历转农历的插件么
> > 
> > 
> > [dayjs-plugin-lunar](https://github.com/baranwang/dayjs-plugin-lunar)
> 
> @baranwang It is the Chinese calendar. right?

yeah

**Comment by SalahAdDin** [comment]
> > > > 有阳历转农历的插件么
> > > 
> > > 
> > > [dayjs-plugin-lunar](https://github.com/baranwang/dayjs-plugin-lunar)
> > 
> > 
> > @baranwang It is the Chinese calendar. right?
> 
> yeah

we need to do our plugin for Hijri calendar.
