### ISSUE TITLE
Convert js date object to dayjs date object? 

### ISSUE THREAD

**Issue by TMHDesign** [iamkun/dayjs#1218]
I am using the Google Time Zone api to give me the current date and time using latitude & longitude. My code is below. I want to now take the returned date object (localdate) and make it a dayjs date object. I can use the js date get methods to get the year, month, hour, minute, etc., but how do I then make this a dayjs date with the time, etc.  Right now I am getting this returned - 11/13/2020, 11:56:48 PM  but I want that to be a dayjs date object

var targetDate = new Date() // Current date/time of user computer
var timestamp = targetDate.getTime()/1000 + targetDate.getTimezoneOffset() * 60 // Current UTC date/time expressed as seconds since midnight, January 1, 1970 UTC
var apikey = 'myApiKey'' 
var apicall = 'https://maps.googleapis.com/maps/api/timezone/json?location=' + loc + '&timestamp=' + timestamp + '&key=' + apikey
var xhr = new XMLHttpRequest() // create new XMLHttpRequest2 object
xhr.open('GET', apicall) // open GET request
xhr.onload = function(){
    if (xhr.status === 200){ // if Ajax request successful
        var output = JSON.parse(xhr.responseText) // convert returned JSON string to JSON object
        console.log(output.status) // log API return status for debugging purposes
        if (output.status == 'OK'){ // if API reports everything was returned successfully
            var offsets = output.dstOffset * 1000 + output.rawOffset * 1000 // get DST and time zone offsets in milliseconds
            var localdate = new Date(timestamp * 1000 + offsets) // Date object containing current local time
            console.log(localdate.toLocaleString()) // Display current local date and time
            pDateTime = localdate.getFullYear() + '-' + localdate.getMonth() + '-' + localdate.getDate() ;
            console.log(pDateTime);
        }
    }
    else{
        alert('Request failed.  Returned status of ' + xhr.status)
    }
}
xhr.send() // send request

**Comment by TMHDesign** [comment]
Maybe this:



var ld = new Date(timestamp * 1000 + offsets)

var xyz = dayjs(ld.getFullYear()+'-'+ld.getMonth()+'-'+ld.getDate()+'T'+msToTime(ld.getTime)+'+10:00')

**Comment by iamkun** [comment]
You can pass the Date object to dayjs directly.

`dayjs(new Date(timestamp * 1000 + offsets))`

**Comment by TMHDesign** [comment]
Thank you so much.,
