### ISSUE TITLE
Considering add duration?

### ISSUE THREAD

**Issue by kangkang07** [iamkun/dayjs#122]
In moment I use duration a lot.

**Comment by iamkun** [comment]
Will support as a plugin later.

**Comment by xx45** [comment]
@kangkang07 Are you mean `moment.duration(Number, String);`? 

Could your please tell us what's this API used for in moment.js? I'm not familiar with this.

**Comment by kangkang07** [comment]
@xx45 Yes

**Comment by iamkun** [comment]
@kangkang07 

check [RelativeTime Plugin](https://github.com/iamkun/dayjs/blob/master/docs/en/Plugin.md#relativetime)

This should suits you.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by probablyup** [comment]
Any chance this could be reopened? Specifically looking for a plugin that can handle ISO duration format. https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by iamkun** [comment]
@probablyup 

will do 😁

**Comment by devanp92** [comment]
@iamkun Is there an ETA/release timeline for this? This would be an amazing feature to have!

**Comment by iamkun** [comment]
#564 Duration Plugin
