### ISSUE TITLE
Day.js should support also other JavaScript engine

### ISSUE THREAD

**Issue by Wernfried** [iamkun/dayjs#1222]
In the documentation you state: "Day.js was designed to work both in the browser and in Node.js."

Of course, these are the major environments for JavaScript, however I would like to see downloads and installation guideline also for other ones, see [JavaScript Engine](https://en.wikipedia.org/wiki/JavaScript_engine) 

I search the repository for example for "dayjs.min.js" but it does not exist. 
You may also provide an instruction guideline to build the library.

I like to test Day.js in the [MongoDB Shell](https://docs.mongodb.com/mongodb-shell/), however I don't find any instructions for download and installation.

Kind Regards

**Comment by iamkun** [comment]
Hi you can download yourself here https://day.js.org/docs/en/installation/download

**Comment by Wernfried** [comment]
Do you like me to download 69 Plugins and 141 locale files manually? I don't see a way to download them as one package.

**Comment by iamkun** [comment]
If you've checked the link clearly, you can find a download as zip file button in the CDN side.

**Comment by Armanio** [comment]
@Wernfried [catch](https://registry.npmjs.org/dayjs/-/dayjs-1.9.6.tgz) ;)

**Comment by Wernfried** [comment]
Yes, the icon is a bit hidden. 
Anyway, it does not work with the new MongoDB Shell, perhaps this is still in "too much beta" status.
