### ISSUE TITLE
Typing issue with startOf("isoWeek")

### ISSUE THREAD

**Issue by tonysamperi** [iamkun/dayjs#1228]
**Describe the bug**
Typescript compile produces error when using `dayjs().startOf("isoWeek")`

![image](https://user-images.githubusercontent.com/5957244/99283851-d6f9b980-2835-11eb-8fec-24cd427c158c.png)

**Expected behavior**
Basically I should get no errors if all types are exposed correctly.

**Information**
 - Day.js Version [e.g. v1.0.0] 1.9.6
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome 62] Irrelevant, using **Typescript 3.6.5** though
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)] GMT +01:00

**Comment by iamkun** [comment]
You can check this as a reference https://day.js.org/docs/en/manipulate/start-of#list-of-all-available-units

isoWeek need an additional plugin to work

**Comment by tonysamperi** [comment]
Oops, my bad. Thanks a lot for your reply!
