### ISSUE TITLE
Diff incorrectly works in timezone

### ISSUE THREAD

**Issue by Lonli-Lokli** [iamkun/dayjs#1247]
**Describe the bug**
Assuming we have two dates in same locale, diff will be calculated wrong
https://stackblitz.com/edit/typescript-x1audr

let dayX = dayjs().set('year', 2020).set('month', 11).set('day', 17);
let dayY = dayjs().set('year', 2020).set('month', 11).set('day', 1);
console.log(`Dayjs: ${dayX.format()} - ${dayY.format()}:  we have ${diff} days`);

I see this
Dayjs: 2020-12-16T10:38:43-07:00 - 2020-11-30T10:38:43-07:00: we have 15 days

**Expected behavior**
Diff should work

**Information**
 - Day.js Version 1.9.4
 - OS: Win10
 - Browser Chrome
 - Time zone: GMT-07:00 DST (Pacific Daylight Time)

**Comment by MathieuCouette** [comment]
Hi!

According to [the documentation](https://day.js.org/docs/en/display/difference):

> By default, `dayjs#diff` will truncate the result to zero decimal places, returning an integer. If you want a floating point number, pass true as the third argument.

Using `let diff = dayX.diff(dayY, "day", true);`, you should get:

```
Dayjs: 2020-12-16T13:00:38-05:00 - 2020-11-30T13:00:38-05:00: we have 15.999999988425927 days
```

The slight time difference is caused by `dayX` being created just before `dayY`.

**Comment by Lonli-Lokli** [comment]
Got you.
Is there option for rounding instead of trancate?

**Comment by MathieuCouette** [comment]
[`Math.round`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) should do the trick:

```ts
let diff = Math.round(dayX.diff(dayY, "day", true));
```

**Comment by Lonli-Lokli** [comment]
Yep, same as 
dayX.startOf('day').diff(dayY.startOf('day'), 'day')

Does it make sense to create story for round option? I believe it's pretty common situation. I also believe that's not an issue with moment.

**Comment by MathieuCouette** [comment]
It seems to me that using `Math.round` is simple enough that it does not warrant a new feature.

Also, Moment.js has had the same behaviour since v2.0.0, according to [the documention](https://momentjs.com/docs/#/displaying/difference/):

> By default, `moment#diff` will truncate the result to zero decimal places, returning an integer. If you want a floating point number, pass true as the third argument. Before **2.0.0**, `moment#diff` returned a number rounded to the nearest integer, not a truncated number.
