### ISSUE TITLE
请问是否有计划支持对moment的替换的vite插件？

### ISSUE THREAD

**Issue by PineSongCN** [iamkun/dayjs#1252]
目前可以搜到的只有webpack版的，谢谢。

**Comment by iamkun** [comment]
Sorry, we have no plan yet.

**Comment by hzh1990** [comment]
**仅限Ant Design Vue**

> vite.config.ts
```javascript
resolve: {
    alias: {
        'moment': 'dayjs'
    }
}
```

> main.js
```javascript
import dayjs from 'dayjs'
import isSameOrBefore from 'dayjs/plugin/isSameOrBefore'
import isSameOrAfter from 'dayjs/plugin/isSameOrAfter'
import advancedFormat from 'dayjs/plugin/advancedFormat'
import customParseFormat from 'dayjs/plugin/customParseFormat'
import weekday from 'dayjs/plugin/weekday'
import weekYear from 'dayjs/plugin/weekYear'
import weekOfYear from 'dayjs/plugin/weekOfYear'
import isMoment from 'dayjs/plugin/isMoment'
import localeData from 'dayjs/plugin/localeData'
import localizedFormat from 'dayjs/plugin/localizedFormat'
import badMutable from 'dayjs/plugin/badMutable'
import 'dayjs/locale/en'
import 'dayjs/locale/zh-cn'


// ### extend
dayjs.extend(isSameOrBefore)
dayjs.extend(isSameOrAfter)
dayjs.extend(advancedFormat)
dayjs.extend(customParseFormat)
dayjs.extend(weekday)
dayjs.extend(weekYear)
dayjs.extend(weekOfYear)
dayjs.extend(isMoment)
dayjs.extend(localeData)
dayjs.extend(localizedFormat)
dayjs.extend(badMutable)

// ### locale
// dayjs.locale('en')
dayjs.locale('zh-cn')

```

**Comment by PineSongCN** [comment]
> **仅限Ant Design Vue**
> 
> > vite.config.ts
> 
> ```js
> resolve: {
>     alias: {
>         'moment': 'dayjs'
>     }
> }
> ```
> 
> > main.js
> 
> ```js
> import dayjs from 'dayjs'
> import isSameOrBefore from 'dayjs/plugin/isSameOrBefore'
> import isSameOrAfter from 'dayjs/plugin/isSameOrAfter'
> import advancedFormat from 'dayjs/plugin/advancedFormat'
> import customParseFormat from 'dayjs/plugin/customParseFormat'
> import weekday from 'dayjs/plugin/weekday'
> import weekYear from 'dayjs/plugin/weekYear'
> import weekOfYear from 'dayjs/plugin/weekOfYear'
> import isMoment from 'dayjs/plugin/isMoment'
> import localeData from 'dayjs/plugin/localeData'
> import localizedFormat from 'dayjs/plugin/localizedFormat'
> import badMutable from 'dayjs/plugin/badMutable'
> import 'dayjs/locale/en'
> import 'dayjs/locale/zh-cn'
> 
> 
> // ### extend
> dayjs.extend(isSameOrBefore)
> dayjs.extend(isSameOrAfter)
> dayjs.extend(advancedFormat)
> dayjs.extend(customParseFormat)
> dayjs.extend(weekday)
> dayjs.extend(weekYear)
> dayjs.extend(weekOfYear)
> dayjs.extend(isMoment)
> dayjs.extend(localeData)
> dayjs.extend(localizedFormat)
> dayjs.extend(badMutable)
> 
> // ### locale
> // dayjs.locale('en')
> dayjs.locale('zh-cn')
> ```

谢谢！好人一生平安！

**Comment by qq34347476** [comment]
> **仅限Ant Design Vue**
> 
> > vite.config.ts
> 
> ```js
> resolve: {
>     alias: {
>         'moment': 'dayjs'
>     }
> }
> ```
> 
> > main.js
> 
> ```js
> import dayjs from 'dayjs'
> import isSameOrBefore from 'dayjs/plugin/isSameOrBefore'
> import isSameOrAfter from 'dayjs/plugin/isSameOrAfter'
> import advancedFormat from 'dayjs/plugin/advancedFormat'
> import customParseFormat from 'dayjs/plugin/customParseFormat'
> import weekday from 'dayjs/plugin/weekday'
> import weekYear from 'dayjs/plugin/weekYear'
> import weekOfYear from 'dayjs/plugin/weekOfYear'
> import isMoment from 'dayjs/plugin/isMoment'
> import localeData from 'dayjs/plugin/localeData'
> import localizedFormat from 'dayjs/plugin/localizedFormat'
> import badMutable from 'dayjs/plugin/badMutable'
> import 'dayjs/locale/en'
> import 'dayjs/locale/zh-cn'
> 
> 
> // ### extend
> dayjs.extend(isSameOrBefore)
> dayjs.extend(isSameOrAfter)
> dayjs.extend(advancedFormat)
> dayjs.extend(customParseFormat)
> dayjs.extend(weekday)
> dayjs.extend(weekYear)
> dayjs.extend(weekOfYear)
> dayjs.extend(isMoment)
> dayjs.extend(localeData)
> dayjs.extend(localizedFormat)
> dayjs.extend(badMutable)
> 
> // ### locale
> // dayjs.locale('en')
> dayjs.locale('zh-cn')
> ```

这是哪个版本的，我引入报错
{
          find: 'moment',
          replacement: 'dayjs',
          // customResolver:
        },
error when starting dev server:
Error: ENOENT: no such file or directory, open 'dayjs/dist/locale/zh-cn'

**Comment by qq34347476** [comment]
我这个版本好像会强制带入个 dist
