### ISSUE TITLE
RelativeTime plugin's dayjs().from() returned string in terms of future 

### ISSUE THREAD

**Issue by HangCcZ** [iamkun/dayjs#1259]
**Describe the bug**
dayjs().from(dayjs('1990')) return string **"in 31 years"**

**Expected behavior**
Based on the documentation of dayjs().from() function, dayjs().from(dayjs('1990')) should return string **"31 years ago"**

**Information**
 - Day.js Version [1.9.7]
 - OS: [Windows 10]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
This is the expected result.

Why do you think it should return 31 years ago?

**Comment by HangCcZ** [comment]
Hah! Maybe I interpreted it other way around. 
But the [dayjs documentation](https://day.js.org/docs/en/display/from) shows `var a = dayjs()
a.from('1990-01-01') // 2 years ago` whereas it is "in some years" if I run it via the developer tool.

Sorry about that.

**Comment by iamkun** [comment]
Ah, there's doc error. I'll update it shortly. THX

**Comment by HangCcZ** [comment]
No problem!
