### ISSUE TITLE
server sync method

### ISSUE THREAD

**Issue by mhf-ir** [iamkun/dayjs#126]
Any method for server sync method date time if client datetime is not correct?

**Comment by Imperat** [comment]
This library don't have this feature. You can send to client the number in unix format and check it manually. For example:
const serverTime = // get it now you want
const client = dayjs();
// If difference between client and server time greater than 10 min
if (Math.abs(client.valueOf() - serverTime) < 1000 * 60 * 10) {
  // Big problem
}

**Comment by iamkun** [comment]
Thanks @Imperat , agreed.
