### ISSUE TITLE
Invalid parse with format "DD.MM.YYYY HH:mm"

### ISSUE THREAD

**Issue by vitage** [iamkun/dayjs#1263]
Alpine Linux 3.11
Node: v14.4.0
dayjs: 1.9.7

How to reproduce:

> dayjs("30.12.2020 12:39","DD.MM.YYYY HH:mm").isValid();
false

BUT:

> dayjs("12.30.2020 12:39","DD.MM.YYYY HH:mm").isValid();
true

DD <> MM, seens like format is not apply.

**Comment by razh** [comment]
Are you using the [`customParseFormat`](https://day.js.org/docs/en/parse/string-format) plugin?

If not, `dayjs` will assume the string is in ISO 8601 format.

```tsx
dayjs('30.12.2020 12:39').toString();
// Uncaught RangeError: Invalid time value

dayjs('12.30.2020 12:39').toISOString();
// '2020-12-30T17:39:00.000Z'
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
