### ISSUE TITLE
Default to current time for isBefore/isAfter

### ISSUE THREAD

**Issue by bcongdon** [iamkun/dayjs#127]
In the momentjs API, calling `momentObj.isBefore()` (without an argument) returns whether the `momentObj` is before the current time.

Calling `dayjsObj.isBefore()` results in `TypeError: Cannot read property 'valueOf' of undefined`.

It'd be nice to have the same behavior as moment in this case, or at least note that it's different in the README. 🙂

**Comment by iamkun** [comment]
Think we might better keeping the same behavior with moment.js~

**Comment by iamkun** [comment]
@bcongdon fixed and released, thanks
