### ISSUE TITLE
Convert month number to month name

### ISSUE THREAD

**Issue by VeeK727** [iamkun/dayjs#1277]
I'm migrating one of my software from moment.js and I can't seem to find a way to convert month numbers into month names. For example, in moment.js I could do the following

`let monthName = moment(3, 'M').format('MMM'); // returns Mar`

How to do the same thing in dayjs? Docs didn't make it clear.

**Comment by iamkun** [comment]
ref https://day.js.org/docs/en/parse/string-format

**Comment by VeeK727** [comment]
I tried that. It doesn't work. The dayjs object always refer to Jan 1, 1970. I don't have a full date, I just have the month num, its in a loop.

**Comment by VeeK727** [comment]
Figured it out

`let monthName = dayjs().month(2).format('MMM'); // 0 indexed so 2 returns Mar`
