### ISSUE TITLE
Unexpected Input Parse

### ISSUE THREAD

**Issue by arthurbrazil** [iamkun/dayjs#1286]
**Describe the bug**
I have an industry standard date type of August 11 2022 as 220811
console.log(dayjs("220811", "YYMMDD").format("YYYYMMDD"));

**Expected behavior**
Expected output should be 20220811 but instead is 22081101

**Comment by bornova** [comment]
You need to use [`customParseFormat`](https://day.js.org/docs/en/parse/string-format) plugin:

https://runkit.com/5fe3882258e5c600182f88d7/5fe3882bcf4431001a61fd63

**Comment by arthurbrazil** [comment]
Thank you!
