### ISSUE TITLE
deno support

### ISSUE THREAD

**Issue by transtone** [iamkun/dayjs#1288]
Is there a plan to support deno, as date-fns do?

https://deno.land/x/date_fns

**Comment by iamkun** [comment]
Sounds cool, I'll publish dayjs to deno.land/x soon

**Comment by iamkun** [comment]
Here we are https://deno.land/x/dayjs

**Comment by transtone** [comment]
> Here we are https://deno.land/x/dayjs

咋用呢，有示例没？

**Comment by michaeldesu** [comment]
@iamkun thanks, but publishing to deno land is like sharing a link to your github. Do you have some documentation about how to import it precisely? There's no deno-specific doc on the deno land page. Thanks.

**Comment by KaKi87** [comment]
Still no documentation in 2024 :sweat_smile:
