### ISSUE TITLE
IsSameOrBefore and IsSameOrAfter

### ISSUE THREAD

**Issue by Imperat** [iamkun/dayjs#129]
Hi, guys!
moment.js supports these two methods. Do we need to support it also?

**Comment by iamkun** [comment]
May be not.

`dayjs().isBefore && dayjs().isSame` could do the same thing

Or, maybe a plugin later.

**Comment by Imperat** [comment]
Agreed. Or `!dayjs().isAfter()` is better

**Comment by iamkun** [comment]
Nice 😁

**Comment by iamkun** [comment]
we have it already
