### ISSUE TITLE
.utc().format() returns wrongly formatted output

### ISSUE THREAD

**Issue by mkarajohn** [iamkun/dayjs#1290]
**Describe the bug**
Using `dayjs.utc().format()` after the `dayjs` has been extended as described [here](https://day.js.org/docs/en/plugin/utc) returns the output `"2020-12-26T21:08:04+00:00"`

**Expected behavior**
According to [the documentation](https://day.js.org/docs/en/plugin/utc) executing that code should return the string `"2020-12-26T21:08:04Z"`

**Information**
 - Day.js Version: 1.9.7
 - OS: Linux
 - Browser: Chromium 87.0.4280.88
 - Time zone: +2

**Comment by iamkun** [comment]
a reproduction demo, please?

**Comment by mkarajohn** [comment]
@iamkun 

Turns out it must be an issue with the `@date-io/dayjs`. Just loading it by `import`ing it, causes this issue. Try it with the import commented out and it works as expected (you need to refresh the "browser" view though in order to apply the changes).

**Comment by iamkun** [comment]
Yes, you can try pure dayjs first to see if it works as expected.

**Comment by mkarajohn** [comment]
I am closing this, I will open it in the `date-io` repo. Sorry for wasting your time. Cheers

**Comment by iamkun** [comment]
I'm happy I could help 😁
