### ISSUE TITLE
Subtracting weekdays returns the wrong date

### ISSUE THREAD

**Issue by aoloo** [iamkun/dayjs#1293]
**Describe the bug**
![image](https://user-images.githubusercontent.com/66189547/103239933-f7c92a80-491c-11eb-8820-71bd02ae1dd1.png)
As you can see in the image the incorrect date is `December 20th` instead of the `21st`. I am doing something wrong ` dayjs().weekday(-7)`? 

**Expected behavior**
The documentation clearly states `If the locale assigns Monday as the first day of the week, dayjs().weekday(0) will be Monday. If Sunday is the first day of the week, dayjs().weekday(0) will be Sunday.`  At the time of writing this issue the date was `December 28th on Monday` I am trying to get last `Monday December 21`. But I am getting the incorrect date. 

Plain vanilla JS  `new Date(new Date().setDate(new Date().getDate() - 7))`  returns the correct date. 
`Mon Dec 21 2020 15:41:20 GMT-0500 (Eastern Standard Time)
`

**Information**
 - Day.js Version [e.g. v1.9.8]
 - OS: [Windows]
 - Browser [chrome]
 - Time zone: [Eastern Standard Time]

**Comment by iamkun** [comment]
By default, Sunday is the first day of the week in the English-US locale.

So weekday(-7) results in last Sunday.

You can set the correct locale to get the result you want.

Also, I've updated the doc to make it more clear.

**Comment by iamkun** [comment]
doc updated here https://github.com/dayjs/dayjs-website/commit/3349230a4cd7887d114434a1a337d786aa0264ef

**Comment by aoloo** [comment]
@iamkun  is this what you mean by  `set correct locale to get the result you want`? 
```
var a = dayjs.utc()
a.format() 
a.local().weedays(-7).format() 
```

**Comment by iamkun** [comment]
You can check this as a reference https://day.js.org/docs/en/i18n/i18n
