### ISSUE TITLE
[just a Question] why 0-44s instead of 0-60s

### ISSUE THREAD

**Issue by soul-of-code** [iamkun/dayjs#1294]
Why is [plugin/relativeTime.js] in dayjs not distinguished by standard time in time range configuration? For example: why 0-44s instead of 0-60s?

**Comment by iamkun** [comment]
Feel free to customize it like this

https://day.js.org/docs/en/customization/relative-time

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by soul-of-code** [comment]
I know~ I just don’t know the reason for setting the default value like this, haha

**Comment by iamkun** [comment]
Well, mainly to keep the same with moment.js

**Comment by soul-of-code** [comment]
oh! thinks~ I thought it had any special meaning～～

**Comment by soul-of-code** [comment]
haha
