### ISSUE TITLE
Typescript Issue - Type expected issue on line 20

### ISSUE THREAD

**Issue by oswaldpope** [iamkun/dayjs#1300]
https://github.com/iamkun/dayjs/blob/bc53b53561f223b5efe7c4fbb76587f083ec8230/types/index.d.ts#L20.

node_modules/dayjs/index.d.ts:20:29 - error TS1110: Type expected.

tsc Version 3.9.5

issue from commit https://github.com/iamkun/dayjs/pull/1289/commits/676d09b46aed143e2780c45f58cb1443ef6e2e33#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceR20

**Comment by iamkun** [comment]
Can you please provide a reproduction repo? tsc Version 3.9.5 tested fine on my side.

**Comment by navneetkaurbatth** [comment]
Me also having the same issue and getting this error during run time: TypeError: dayjs.extend is not a function

**Comment by ptz0n** [comment]
Same issue as the initial report.

- node@14.13.0
- typescript@3.9.6
- dayjs@1.10.0

tsconfig.json:

```json
{
  "compilerOptions": {
    "sourceMap": false,
    "inlineSources": false,
    "inlineSourceMap": false,
    "noEmit": false,
    "declaration": true,
    "stripInternal": true,
    "outDir": "dist",
    "downlevelIteration": true,
    "esModuleInterop": true,
    "importHelpers": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "removeComments": true,
    "target": "es6"
  },
  "include": [
    "src",
    "test"
  ]
}
```

test.ts:

```typescript
import dayjs, { Dayjs } from "dayjs";
```

build:

```bash
$ tsc -p tsconfig.json 
node_modules/dayjs/index.d.ts:20:29 - error TS1110: Type expected.

20   type UnitTypeLongPlural = `${UnitTypeLong}s`
                               ~~~

Found 1 error.
```

**Comment by oswaldpope** [comment]
Updating typescript to "typescript": "^4.1.3" fixed the issue.

**Comment by iamkun** [comment]
wiill fix soon

**Comment by pushred** [comment]
I'm still experiencing an issue I think related to this where there is an `Uncaught TypeError: dayjs.extend is not a function` error at runtime:

- Direct dependency: chrono-node@1.4.3
- dayjs@1.10.1
- TypeScript is not in use

I will probably need to fork chrono-node and pin the dayjs version in use to something earlier to resolve this as I'm not using Yarn in this particular project to be able to control `resolutions`

**Comment by pushred** [comment]
I see the comment in https://github.com/iamkun/dayjs/issues/1281#issuecomment-754381268 indicating that version 1.10.0 unintentionally introduced an ESM-related breaking change and that 1.10.2 will reverse this. I'll fork chrono-node for the moment to pin to 1.9.8 and will see if 1.10.2 fixes the issue.
