### ISSUE TITLE
Typescript compile error with antd 4.9

### ISSUE THREAD

**Issue by TingzhouJia** [iamkun/dayjs#1308]
**Describe the bug**
![WechatIMG1923](https://user-images.githubusercontent.com/44245347/103551259-19279a80-4e78-11eb-83c9-e10f843b5289.png)

```js
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "es2017",
      "es7",
      "es6"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "**/*.test.ts"
  ]
}
```
<img width="454" alt="截屏2021-01-04 上午10 33 30" src="https://user-images.githubusercontent.com/44245347/103551483-6277ea00-4e78-11eb-8d31-7d3f333af335.png">
<img width="623" alt="截屏2021-01-04 上午10 33 49" src="https://user-images.githubusercontent.com/44245347/103551484-63108080-4e78-11eb-84ab-b0880f150951.png">

**Information**
 - Day.js Version [ v1.10.1]
 - Typescript Version [~3.7.2]
 - OS: [e.g. Mac]
 - Browser [ chrome 83+]
 - Time zone: [ GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
do #1281
