### ISSUE TITLE
TypeError: dayjs__WEBPACK_IMPORTED_MODULE_22__ is not a function

### ISSUE THREAD

**Issue by yangyuqing123** [iamkun/dayjs#1312]
Describe the bug
Hey, first I want to say thank you for an awesome lightweight package.

I've recently updated my  dayjs packages in my Typescript project and have started to get the following error in browser

TypeError: dayjs__WEBPACK_IMPORTED_MODULE_22__ is not a function
Here is what I have in my code base

import * as dayjs from 'dayjs'
const today = dayjs(); 

Not sure why this is happening, I've checked around and based on current findings I do have the appropriate configurations. Thanks ahead of time for your support.

"allowSyntheticDefaultImports": true,

Information

Day.js Version 1.10.1
Typescript Version 3.0.0

**Comment by iamkun** [comment]
maybe related to #1281
