### ISSUE TITLE
Time parse failed  => dayjs('2020-12-18 12:05:42 473').format('YYYY-MM-DD')

### ISSUE THREAD

**Issue by ugvgylkm** [iamkun/dayjs#1320]
**Describe the bug**
dayjs('2020-12-18 12:05:42 473').format('YYYY-MM-DD')
Invalid Date

**Expected behavior**
dayjs('2020-12-18 12:05:42 473').format('YYYY-MM-DD')
2020-12-18

**Information**
 - Day.js Version [e.g. v1.10.2]
 - OS: [e.g. nodejs]

**Comment by iamkun** [comment]
Please check String + Format parse here https://day.js.org/docs/en/parse/string-format

**Comment by ugvgylkm** [comment]
Can you give me an example ？

My writing：

dayjs.extend(customParseFormat);
dayjs('2021-1-7 12:05:42 473').format('YYYY-MM-DD')
Invalid Date

**Comment by iamkun** [comment]
According to the doc https://day.js.org/docs/en/parse/string-format

you should pass in the parsing format like

```
dayjs.extend(customParseFormat)
dayjs("12-25-1995", "MM-DD-YYYY").format('YYYY-MM-DD')
```

**Comment by ugvgylkm** [comment]
This will be wrong：
dayjs.extend(customParseFormat);
dayjs('2020/1/30 10:09:34 477', 'YYYY-MM-DD HH:mm:ss SSS').format('YYYY-MM-DD')
Invalid Date

2020/1/30
YYYY-MM-DD
=======================================
It was a success：
dayjs.extend(customParseFormat);
dayjs('2021/12/2 10:09:34 477', 'Y-M-D H:m:s SSS').format('YYYY-MM-DD HH:mm:ss SSS')
'2021-12-02 10:09:34 477'

2021/12/2
Y-M-D H:m:s SSS

**Comment by iamkun** [comment]
You should use
```
dayjs.extend(customParseFormat)
dayjs('2020/1/30 10:09:34 477', 'YYYY/M/DD HH:mm:ss SSS')
```

check the parsing token here https://day.js.org/docs/en/parse/string-format#list-of-all-available-parsing-tokens
