### ISSUE TITLE
milliseconds method isn't defined in typescript types

### ISSUE THREAD

**Issue by JemarJones** [iamkun/dayjs#1322]
**Describe the bug**
The `dayjs().milliseconds()` method is not defined in the typescript. Its alias `dayjs().millisecond()` however is. This is despite both methods existing at runtime:
![image](https://user-images.githubusercontent.com/6874590/103972247-971ac880-513a-11eb-8f2b-6653bd566bfa.png)

**Expected behavior**
This function should be defined with the same typing at the `millisecond` method.

**Information**
 - Day.js Version [e.g. v1.10.2]

**Comment by iamkun** [comment]
Yes, are you willing to make a PR to fix this?

**Comment by JemarJones** [comment]
For sure, no problem :)

**Comment by JemarJones** [comment]
Actually @iamkun maybe i am missing something, when i check in the console of https://day.js.org/ this function is included, but when i try to do the same via the npm package installed in my app it actually doesn't appear to be present at runtime. Is this pluralized method added via a plugin or something? 🤔

**Comment by iamkun** [comment]
Oh, correct. You just noticed to me that this is made via a plugin `pluralGetSet`. And the type should be ok if you have this plugin enabled.

**Comment by JemarJones** [comment]
Ah okay i see! Just a misunderstanding on my part then, thanks!
