### ISSUE TITLE
13. Oktober 2020 is an invalid date

### ISSUE THREAD

**Issue by alexander-fischer** [iamkun/dayjs#1324]
**Describe the bug**

Parsing 13. Oktober 2020 with the German locale gives me back an invalid date. 

```
import dayjs from 'dayjs';
import * as DAYJS_LOCALE_DE from 'dayjs/locale/de';
dayjs.locale(DAYJS_LOCALE_DE);

const dayjsDate = dayjs("13. Oktober 2020", 'LL');
```

Trying with more concrete parsing format also didn't work:
```
const dayjsDate = dayjs("13. Oktober 2020", 'DD MMMM YYYY');
```

**Expected behavior**

I expect a valid date as in Germany this is a complete valid string. If I write 13. November 2020 it works.

**Information**
 - Day.js Version v1.10.2
 - OS: MacOS
 - Browser: Node
 - Time zone: MEZ

**Comment by iamkun** [comment]
you can pass 'de' as the third arguments, ref https://day.js.org/docs/en/parse/string-format

**Comment by alexander-fischer** [comment]
@iamkun Yes I tried, but this also doesn't work.

**Comment by iamkun** [comment]
tested ok here
https://runkit.com/embed/xgmdzgah7tym
![Uploading image.png…]()

**Comment by alexander-fischer** [comment]
@iamkun adding `customParseFormat` fixed it. Thanks!
