### ISSUE TITLE
Dayjs makes understanding code difficult

### ISSUE THREAD

**Issue by navanshu** [iamkun/dayjs#1330]
I love dayjs but its a bit hard to understand how to make modules for it in typescript and I cannot compare for multiple things like year, month, day at once using the queries, I wish dayjs be able to handle multiple queries at once like

```javascript
dayjs().isSame('2019-01-30', 'ymd') // comparing if the dates have same year, months and day
// If I want to put a query like this it just return false
```
This is much simpler from my perspective than the existing methods

```javascript
const D = dayjs();
const E = dayjs();
D.format('L') === E.format('L')
// comparing two dates as strings feels dirty 
D.isSame(E,'y').isSame(E,'m').isSame(E,'d') // this is impossible
// most of the times one may not need an accurate comparison but partial comparisons
// one good solution in the library is

const O = D.startOf('d');
const P = E.startOf('d');
O.isSame(P);
```

Having more advanced query which would make codebase much simpler would be so better and please include a section in docs on making plugins in typescript.

**Comment by LilDevil** [comment]
@navanshu I think you are missing the point. If you compare days, you do not need to compare months or years.

`dayjs('2019-05-01').isSame('2019-05-01', 'day')`
`> true`

`dayjs('2020-05-01').isSame('2019-05-01', 'day')   // same day different years`
`> false`

From the [moment.js docs](https://momentjs.com/docs/#/query/is-same/):
> When including a second parameter, it will match all units equal or larger. Passing in `month` will check `month` and `year`. Passing in `day` will check `day`, `month`, and `year`.

(@iamkun  This phrase should probably also be included in the day.js doc.)

**Comment by navanshu** [comment]
Okay now I get it, I am new to using this library. It was unnecessary computation, it was kind of ambiguous to me thanks.

**Comment by iamkun** [comment]
added thantks https://github.com/dayjs/dayjs-website/commit/5115ef1bb67b08787e76dfa8254433483829cea1
