### ISSUE TITLE
format 格式化字符串错误，理解的不对吗？

### ISSUE THREAD

**Issue by steady-join** [iamkun/dayjs#1334]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29935583/104532537-69a6b100-564b-11eb-87d5-433b898610cc.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/29935583/104532582-82af6200-564b-11eb-91fc-a15855c33e9a.png)

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]
v1.10.3

**Comment by iamkun** [comment]
what's the bug is then?

**Comment by steady-join** [comment]
> what's the bug is then?

Will the string type here be implicitly converted to a number type?

**Comment by iamkun** [comment]
No, check here, https://day.js.org/docs/en/parse/unix-timestamp-milliseconds 

>The passing argument must be a number

**Comment by lqzhgood** [comment]
https://github.com/iamkun/dayjs/issues/1150

![image](https://user-images.githubusercontent.com/9134671/105276516-89eee680-5bdc-11eb-8761-1a657670a15e.png)

in  `development` has warn tips. is not bug.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
