### ISSUE TITLE
Strict input parsing does not work properly

### ISSUE THREAD

**Issue by alex-w0** [iamkun/dayjs#1337]
**Describe the bug**
According to the documentation strict input parsing should behave like the following: https://day.js.org/docs/en/parse/string-format

> Strict parsing requires that the format and input match exactly, including delimiters.

When i'm trying now  to parse an invalid string it returns the information that the date is valid.

`dayjs_1.default('14970-44-22', 'YYYY-MM-DD', true).isValid()`

Also the example from the documentation returns true instead of false

`dayjs('1970-00-00', 'YYYY-MM-DD', true).isValid()`

**Expected behavior**
Should also validate if the date is correct.

**Information**
 - Day.js Version 1.10.3
 - Time zone: America/New_York

**Comment by iamkun** [comment]
As mentioned in the doc, 
> This dependent on CustomParseFormat plugin to work

**Comment by alex-w0** [comment]
Oh sorry my fault, for some reasons I've thought that the plugin is only required when i'm using some special formats, because in most cases the date can be parsed correctly without even registering the plugin.
