### ISSUE TITLE
 Internet Explorer - Option value 'EUROPE/LUXEMBOURG' for 'timeZone' is outside of valid range. Expected: ['UTC']

### ISSUE THREAD

**Issue by vdg437** [iamkun/dayjs#1339]
**Describe the bug**
```
import * as dayjs from 'dayjs';
import * as utc from 'dayjs/plugin/utc';
import * as timezone from 'dayjs/plugin/timezone';
dayjs.extend(utc);
dayjs.extend(timezone);

dayjs.tz.setDefault('Europe/Luxembourg');
```

Works fine in Chrome / Firefox but in IE throws error:
** Option value 'EUROPE/LUXEMBOURG' for 'timeZone' is outside of valid range. Expected: ['UTC']**

_Please point out if I am doinng something wrong_

**Expected behavior**
Uses given timezone

**Information**
 - Day.js Version v^1.9.6"
 - OS: Windows 10
 - Browser: Internet Explorer 11

**Comment by iamkun** [comment]
As mentioned in doc https://day.js.org/docs/en/timezone/timezone

For legacy or unsupported environments, please use a proper polyfill.

**Comment by vdg437** [comment]
Thank you very much, I missed that. Sorry for the inconvenience
