### ISSUE TITLE
how to support jalili calender?

### ISSUE THREAD

**Issue by mehdiraized** [iamkun/dayjs#134]
i am use jalili calender
this package not support. please support jalili calender

**Comment by Imperat** [comment]
Hi, @mehdiraized. You mean this: https://en.wikipedia.org/wiki/Jalali_calendar, right?
I hope this calendar will be implemented as plugin, after working on plugin system will be finished here:
https://github.com/xx45/dayjs/pull/123
Do you know how many people are using this calendar? In Russian Wikipedia I see that this is not usable now

**Comment by iamkun** [comment]
Maybe related to #67 ?

**Comment by mehdiraized** [comment]
hi,
yes this is https://en.wikipedia.org/wiki/Jalali_calendar
tank you, I am waiting.
jalili calendar is iranian calendar and some countries that speaking persian

**Comment by iamkun** [comment]
pr welcome

**Comment by theMasix** [comment]
https://github.com/alibaba-aero/jalaliday
This plugin solves the problem.

**Comment by amirhmoradi** [comment]
Hi @mehdiraized ,

I have created a new dayjs plugin that allows managing multiple calendar systems.
I have already implemented the Persian, Hijri and Hebrew calendar systems and I am working on other calendar systems now.
It does correct conversions to and from persian calendar, and is compatible with .tz, .utc and other functions.
The current plugin is stable and tested (more tests/bug reports/feature requests are WELCOME).

My plugin uses a standard dayjs plugin development approach and I tried to avoid all hacks and patch work.
Please test it and open issues or PRs, everything is in the documentation file README.md.

https://github.com/calidy-com/dayjs-calendarsystems
