### ISSUE TITLE
Relative time

### ISSUE THREAD

**Issue by samullman** [iamkun/dayjs#1341]
```
import dayjs from "dayjs";

var relativeTime = require('dayjs/plugin/relativeTime')
dayjs.extend(relativeTime)

const timeFrom = dayjs().from(dayjs('2015-01-01'), true) 
// timeFrom = 6 years
```

Is there any way to customize the format of relative time? (XX years XX months XX days XX minutes XX seconds)

**Comment by iamkun** [comment]
https://day.js.org/docs/en/customization/customization

**Comment by samullman** [comment]
I'm here. 

```
var updateLocale = require('dayjs/plugin/updateLocale')
dayjs.extend(updateLocale)

dayjs.updateLocale('en', {
  relativeTime: {
    yy: "%d years"
  }
})
```

Almost everything I do results in NaN ... Sry noob here

**Comment by iamkun** [comment]
You should pass the whole `relativeTime` config object, not part of it.
