### ISSUE TITLE
weekOfYear shows wrong calender week at the turn of the year when using the "pt" locale

### ISSUE THREAD

**Issue by MarinaFernandes** [iamkun/dayjs#1344]
**Describe the bug**
The 2020-12-31 should be calender week 53 but it shows as calender week 1.
(similar issue: #1264)

**Expected behavior**
https://runkit.com/marferna/6006c2f0e5d69000136b7ad0
We expected the example to output: 
"With this date we are in week number: 53" and not 1;
"The current week is:  3" and not 4.

**Information**
 - Day.js Version 1.10.3
 - Browser Chrome 87.0.4280.141

**Comment by iamkun** [comment]
would you like to submit a PR to fix this? all we have to do is to add a 'yearStart: 4' to https://github.com/iamkun/dayjs/blob/dev/src/locale/pt.js

**Comment by MarinaFernandes** [comment]
All right @iamkun, 
I will submit the PR.
Thank you for the quick answer!

**Comment by iamkun** [comment]
fixed
