### ISSUE TITLE
diff函数两种不同写法的返回结果不一致

### ISSUE THREAD

**Issue by fuxichen** [iamkun/dayjs#1353]
**Describe the bug**
diff函数两种不同写法的返回结果不一致

**Expected behavior**
今天是2021/01/23,
在使用 dayjs().diff("2021/01/24", 'day') 返回结果是 0
而使用dayjs('2021/01/23').diff("2021/01/24", 'day') 返回结果是 -1
预期的输出结果应该是 -1
![image](https://user-images.githubusercontent.com/17411462/105569274-62825000-5d7b-11eb-8a09-5eb9063b0541.png)

**Information**
 - Day.js Version 1.10.4
 - OS: window 10
 - Browser chrome 87
 - Time zone: Sat Jan 23 2021 13:08:19 GMT+0800 (中国标准时间)

**Comment by iamkun** [comment]
This is the expected result. You can pass `true` as the third argument to see the exact diff result and you will see why.
```
dayjs().diff("2021/01/24", 'day', true)
```

**Comment by fuxichen** [comment]
了解了，谢谢
