### ISSUE TITLE
dayjs("2021-01-26T14:25:04.871Z", "YYYY-MM-DDTHH:mm:ss.SSSZ") doesn't work

### ISSUE THREAD

**Issue by beckyconning** [iamkun/dayjs#1358]
**Describe the bug**
`dayjs("2021-01-26T14:25:04.871Z", "YYYY-MM-DDTHH:mm:ss.SSSZ")` doesn't work
`moment("2021-01-26T14:25:04.871Z", "YYYY-MM-DDTHH:mm:ss.SSSZ")` works

**Expected behavior**
Should work as moment does treating Z as +00:00

**Information**
 - Day.js Version 1.10.3
 - OS: Node v10.16.3
 - Browser: Node v10.16.3
 - Time zone: London

**Comment by iamkun** [comment]
fixed in #1359

**Comment by ghiscoding** [comment]
@beckyconning 
Have you tried this code change in strict mode?

Since this is not released yet so I tried to manually modify the `customParseFormat.js` minified file with your code change and in strict mode it seems to fail the `isValid` check. 
```js
const format = 'YYYY-MM-DDTHH:mm:ss.SSSZ';
const inputDate = '1993-12-01T10:22:33.128Z';
const isDateValid = dayjs(inputDate, format, true).isValid(); // returns false
```

I use this Zulu format a lot in my open source lib and this is the only piece missing to migrate to DayJS

**Comment by tbastyns** [comment]
@ghiscoding 

When I escape the 'Z' as such `'YYYY-MM-DDTHH:mm:ss.SSS[Z]'`, I get the expected results when I use strict mode:

```
  expect(dayjs('2022-01-21T12:12:12.123Z', 'YYYY-MM-DDTHH:mm:ss.SSS[Z]').isValid()).toBeTruthy();
  expect(dayjs('2022-01-21T12:12:12.123Z', 'YYYY-MM-DDTHH:mm:ss.SSS[Z]', true).isValid()).toBeTruthy();
  // set month to 13; should not be accepted in strict mode
  expect(dayjs('2022-13-21T12:12:12.123Z', 'YYYY-MM-DDTHH:mm:ss.SSS[Z]').isValid()).toBeTruthy();
  expect(dayjs('2022-13-21T12:12:12.123Z', 'YYYY-MM-DDTHH:mm:ss.SSS[Z]', true).isValid()).toBeFalsy();
```

**Comment by tbastyns** [comment]
the last 2 lines illustrate one of the differences of strict VS non-strict: only when using strict, a 13th month is considered invalid
