### ISSUE TITLE
why now.diff('2021-01', 'M') === now.diff('2021-02', 'M') === 0?

### ISSUE THREAD

**Issue by davidxiao** [iamkun/dayjs#1369]
today is 2021-01-30,

`
const dayjs = require('dayjs')
const today = dayjs()
const jan = '2021-01'
const feb = '2021-02'

console.log(`diff of today - jan = ${today.diff(jan, 'M')}`)
console.log(`diff of today - feb = ${today.diff(feb, 'M')}`)

diff of today - jan = 0
diff of today - feb = 0
`

what's the logic behind?

How can I get natural month difference instead of based on days?

thanks

**Comment by iamkun** [comment]
just pass true as the third argument, and you will see why

**Comment by davidxiao** [comment]
hmm, 
thanks
