### ISSUE TITLE
weekOfYear `week` does not count the day of the week correctly for 'ru' locale 

### ISSUE THREAD

**Issue by ushakov-igor** [iamkun/dayjs#1371]
**Describe the bug**
I have an issue with the week(). Maybe similar problem was there https://github.com/iamkun/dayjs/issues/956 

**Expected behavior**
I tried with date '2010-12-30' and it's return 1 week. But I think it should be 52.

**Information**
 - Day.js Version [1.10.4]
 - OS: [macOS Big Sur 11.1  ]
 - Browser [Chrome 88]
 - Time zone: [GMT+3]

**Comment by iamkun** [comment]
Yes, we should set https://github.com/iamkun/dayjs/blob/dev/src/locale/ru.js to `yearStart: 4`

Would you like to submit a PR to fix it?

**Comment by KashyapPavra** [comment]
@iamkun if the bug is unassigned I would love to contribute

**Comment by iamkun** [comment]
go ahead please

**Comment by tlegen-k** [comment]
I am new to committing. And would like to follow up on the issue.
Just submitted request for merge. And is it had no conflicts was able to merge it with original branch.
Have i done everything correctly?

**Comment by ushakov-igor** [comment]
I think everything is good. Maybe @iamkun can merge and up version?🙏

**Comment by iamkun** [comment]
fixed in #1372
