### ISSUE TITLE
Jest snapshot test failed with TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by vikaspuri-goswami** [iamkun/dayjs#1374]
Below is the sample code.

```
Filename: TestComponent.svelte
<script>
  import * as dayjs from 'dayjs'
  import relativeTime from 'dayjs/plugin/relativeTime'
  dayjs.extend(relativeTime)

  dayjs('1999-01-01').fromNow()
</script>
<div>
Hello World !!!
</div>

Filename: TestComponent.test.js

import { render } from '@testing-library/svelte'
import TestComponent from './TestComponent.svelte'

describe('Render component', () => {
  it('should render component correctly', () => {
    const { component } = render(TestComponent)
    expect(component).toMatchSnapshot()
  })
})
```
**Information**
dayjs : 1.10.4

** Error ** 
![image](https://user-images.githubusercontent.com/48320416/107041910-13aad080-67e7-11eb-8853-cc622ebc2e79.png)

**Comment by jeserkin** [comment]
Having same issue. What was the solution @vikaspuri-goswami ? Asking since you closed issue.

**Comment by vikaspuri-goswami** [comment]
@jeserkin You can mock the dayjs like below. 

```
const dayjs = jest.fn().mockImplementation(() => ({
  fromNow: () => {
    return "2 days ago"
  },
  format: () => "2/15/2021 4:30 PM",
}))

dayjs.extend = jest.fn()

export default dayjs
```

**Comment by jeserkin** [comment]
Interesting. For some reason in my case, test still fails with `TypeError: Cannot read property 'extend' of undefined`.

**Comment by harvanchik** [comment]
> Interesting. For some reason in my case, test still fails with `TypeError: Cannot read property 'extend' of undefined`.

You ever figure it out?

**Comment by jeserkin** [comment]
Yes. Just had wrong import. For some reason it worked on application level both ways, but on test level it didn't. Once the import was changed and was same on both sides it was working as intended.
At the moment, I have following imports:

```ts
import { Dayjs } from 'dayjs';
import * as dayjs from 'dayjs';
import * as en from 'dayjs/locale/en';
import * as relativeTime from 'dayjs/plugin/relativeTime';
```

**Comment by harvanchik** [comment]
> > @rogerprz What version of Angular are you using? What version of dayjs?
> 
> Im using React with typescript. The latest `"dayjs": "^1.10.7",` The file is a javascript file.

Oh, hmm.  Well, I've done basically the same thing as you, but in Angular, and get no error.

**Comment by mashirozx** [comment]
> Yes. Just had wrong import. For some reason it worked on application level both ways, but on test level it didn't. Once the import was changed and was same on both sides it was working as intended. At the moment, I have following imports:
> 
> ```ts
> import { Dayjs } from 'dayjs';
> import * as dayjs from 'dayjs';
> import * as en from 'dayjs/locale/en';
> import * as relativeTime from 'dayjs/plugin/relativeTime';
> ```
> 
> Also I am calling now `dayjs.extend(...);` inside constructor. This is my case, other people requirements can be different.

Better solution: https://github.com/iamkun/dayjs/issues/1494#issuecomment-1571808942

**Comment by fogfire** [comment]
I also encountered the same problem，but i used TypeScript,  and i just added `{ compilerOptions: { esModuleInterop: true } }` to my tsconfig.json and it fixed it.
