### ISSUE TITLE
Deno support!

### ISSUE THREAD

**Issue by michailVestnik** [iamkun/dayjs#1382]
Deno does not support  ` require `!
Please add ES import, examples and documentation for Deno / #1288

**Comment by Hunam6** [comment]
Why did you close this issue?

**Comment by michailVestnik** [comment]
Sorry, my mistake, reopen

**Comment by Soremwar** [comment]
@michailVestnik DayJS is already supported through NPM compatibility

```js
import dayjs from "https://cdn.skypack.dev/dayjs@1.10.4";
// Import locale
import "https://cdn.skypack.dev/dayjs@1.10.4/locale/es";

const current_time = dayjs();

const current_time_pretty = current_time.locale('es').format('D de MMMM, YYYY h:mm A');

console.log(current_time);
console.log(current_time_pretty);
```

@iamkun Adding a note about Deno compatibility in the docs would be awesome

**Comment by stillalivx** [comment]
Hey, @Soremwar ! I tried import utc's plugin like this and is not working. :( Have you an idea of how I can import plugins?

```typescript
import dayjs from 'https://cdn.skypack.dev/dayjs'; 
import utc from 'https://cdn.skypack.dev/dayjs/plugins/utc'; 
```

**Comment by Soremwar** [comment]
@stillalivx Dammit, you made me look it up for you XD

**Comment by stillalivx** [comment]
@Soremwar Im so sorry. My mistake. 😪

**Comment by raviteja83** [comment]
@Soremwar it is not working with latest version. Getting this error - https://cdn.skypack.dev/error/build:dayjs@v1.11.1-hjNPZCmDt5LAsgqX8MmQ

**Comment by paudrow** [comment]
> @Soremwar it is not working with latest version. Getting this error - https://cdn.skypack.dev/error/build:dayjs@v1.11.1-hjNPZCmDt5LAsgqX8MmQ

I had better luck with [esm.sh](https://esm.sh/). This worked for me:

```typescript
import dayjs from 'https://esm.sh/dayjs';
import utc from 'https://esm.sh/dayjs/plugin/utc';
import timezone from 'https://esm.sh/dayjs/plugin/timezone';

dayjs.extend(utc)
dayjs.extend(timezone)

export { dayjs }
```

**Comment by rentzsch** [comment]
You can use Deno's built-in NPM support as well:

```typescript
import dayjs from "npm:dayjs@1.11.7";
import { assertStrictEquals } from "https://deno.land/std@0.168.0/testing/asserts.ts";

assertStrictEquals(dayjs("2022-02-31", "YYYY-MM-DD", true).isValid(), true);

import customParseFormat from "npm:dayjs@1.11.7/plugin/customParseFormat.js";
dayjs.extend(customParseFormat);

assertStrictEquals(dayjs("2022-02-31", "YYYY-MM-DD", true).isValid(), false);
```

Refs:
- <https://day.js.org/docs/en/plugin/custom-parse-format>
- <https://day.js.org/docs/en/parse/is-valid>

**Comment by bombillazo** [comment]
Thank you both @stillalivx @paudrow ! Was having trouble importing plugins as well.

**Comment by mo** [comment]
I also had problems import dayjs plugins in deno. It worked after I added ".js" to the import though:
```
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc.js'
dayjs.extend(utc)
```

**Comment by Ayfri** [comment]
Thank you for your solution @mo , this is the only single solution that has worked for me.

**Comment by riderx** [comment]
> I also had problems import dayjs plugins in deno. It worked after I added ".js" to the import though:
> 
> ```
> import dayjs from 'dayjs'
> import utc from 'dayjs/plugin/utc.js'
> dayjs.extend(utc)
> ```

this was the only good answer
