### ISSUE TITLE
moment.isDST() alternative in DayJS

### ISSUE THREAD

**Issue by tomvorel13** [iamkun/dayjs#1388]
Hi,

I'm trying to get rid of `moment.js` in our Gatsby site and replace it with DayJS. However, there is a method `moment().isDST() `that is currently being used and I haven't found an alternative in DayJS. I'm using the timezones plugin.

How can I implement this functionality with DayJS?

Thank you.

**Comment by iamkun** [comment]
I'm afraid Day.js do not have this method ATM

**Comment by tomvorel13** [comment]
I thought so. Anyways, I implemented a "manual" solution as I was only using 3 timezones.

**Comment by PavelJacobo** [comment]
Which solution tomvorel13? @tomvorel13 
Thanks :)

**Comment by tomvorel13** [comment]
I wish I remembered :-D I'll have a look tomorrow if I can remember.

**Comment by FrontDream** [comment]
> I thought so. Anyways, I implemented a "manual" solution as I was only using 3 timezones.

@tomvorel13  So Which solution?

**Comment by wscesar** [comment]
I found a workaround for my case tha uses only one scenario:

function isDST(timestamp: any) {
  dayjs.extend(utc)
  dayjs.extend(timezone)

  const osloTime = dayjs.tz(timestamp, "Europe/Oslo")
  const utcTime = osloTime.utc()
  const differenceInHours = osloTime.diff(utcTime, 'hour');
  return differenceInHours !== 1
}

to add other scenarios you just need to put the return inside an if/else or switch/case statement

so if you need to add eastern time zone (GMT -5) if is the difference in hours is other value than -5, so isDST will return true

if ( osloTime )
    return differenceInHors !== 1
else if (est)
    return differenceInHors  !== -5
...

I hope this help you guys
@FrontDream
