### ISSUE TITLE
Duration returns strings instead of numbers

### ISSUE THREAD

**Issue by Emroni** [iamkun/dayjs#1389]
**Describe the bug**
When parsing a duration string, eg `dayjs.duration('P1Y2M3W4DT12H34M56S')` and logging the result, it returns the values as strings instead of numbers:

![image](https://user-images.githubusercontent.com/788290/108583588-fe987a80-736c-11eb-9c35-417757af4b0c.png)

**Expected behavior**
It should return numbers, as given by the return type in `plugins/duration.d.ts`.

**Information**
 - Day.js Version 1.10.4
 - OS: OSX 11.2.1
 - Browser: Chrome 88.0.4324.182
 - Time zone: GMT+7

**Comment by iamkun** [comment]
Yes, it's a bug. Would you like to create a pull request to fix this?
