### ISSUE TITLE
[Compatibility] Default duration when no argument is provided

### ISSUE THREAD

**Issue by JesusTheHun** [iamkun/dayjs#1398]
Currently to create a duration object one must pass at least one argument.

```ts
dayjs.duration("PT0H") // ok
dayjs.duration() // error
```

`Moment.js` supports no argument, so in the spirit to ease the transition for the many, I would love to see that in `Day.js`.
Of course the default duration is 0.

**Comment by iamkun** [comment]
nice catch, pr is welcomed

**Comment by JesusTheHun** [comment]
I've pushed a PR. 
Please consider pushing a `package-lock.json` to the repository. I had to use `npm install --force` otherwise npm refused to proceed because of broken dependencies.
