### ISSUE TITLE
Can't Set Year

### ISSUE THREAD

**Issue by thecodeclimber** [iamkun/dayjs#1404]
I am trying to figure out setters in dayjs.  To that extent, I tested out the following code:

```
let orwell = dayjs();
orwell.year(1984);
console.log(orwell.format("YYYY"));
```

My expectation is that the year 1984 will show up in the console.  But that is not the case, instead 2021 shows up.

What am I doing wrong?

**Comment by iamkun** [comment]
dayjs is immutable.

var a = orwell.year(1984);

a.format()

**Comment by thecodeclimber** [comment]
so, just to be clear, this would work:

```
const a = dayjs()
const orwell = a.year(1984)
console.log(orwell.format('YYYY')
```
