### ISSUE TITLE
Parse format is ignored

### ISSUE THREAD

**Issue by MarijaStojanovic** [iamkun/dayjs#1419]
When I try to do the following:
```javascript
dayjs('12.09.1990', 'DD.MM.YYYY')
// or
dayjs('12.09.1990', 'DD.MM.YYYY', true)
```
I am getting the wrong date. Instead of September 12, 1990, the result is December 8, 1990.

This happens in the Node.js package installed from npm, but not in the browser when I try on the https://day.js.org.

I tried versions 1.8.22, 1.9.x and 1.10.4 (the latest version).

Here's the screenshot of the issue:

<img width="578" alt="Screenshot 2021-03-17 at 18 58 04" src="https://user-images.githubusercontent.com/17946107/111515452-15a37000-8753-11eb-8037-85a418f740a0.png">

**Expected behavior**
When I run the following code:
```javascript
dayjs('12.09.1990', 'DD.MM.YYYY').format('YYYY-MM-DD')
```
the result should be `1990-09-12`.

**Information**
 - Day.js Version: 1.8.22 and 1.10.4
 - OS: Mac OSX and Linux
 - Browser: Node.js
 - Time zone: CET

**Comment by bornova** [comment]
Hi @MarijaStojanovic,
Please make sure to use [CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format): 

[https://runkit.com/6052c5915dac89001a8e3602/6052c9bee9a79f001a5f7d5e](https://runkit.com/6052c5915dac89001a8e3602/6052c9bee9a79f001a5f7d5e)

**Comment by iamkun** [comment]
You can check @bornova 's comment

**Comment by MarijaStojanovic** [comment]
@bornova Thanks a lot

> Hi @MarijaStojanovic,
> Please make sure to use [CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format):
> 
> https://runkit.com/6052c5915dac89001a8e3602/6052c9bee9a79f001a5f7d5e

Thanks a lot
