### ISSUE TITLE
Plugin system documentation

### ISSUE THREAD

**Issue by Imperat** [iamkun/dayjs#142]
Hello, guys!
Can we have some docs in readme about how to write new plugins for dayjs?

**Comment by dmckenna24** [comment]
I agree, I've previously contributed to moment.js, and would love to add to the existing capabilities within day.js. Does anyone know the best way to go about adding unique plugins?

**Comment by iamkun** [comment]
I'll add a example code later in our readme. Besides, the whole project is just around 300 lines of code and easy to understand. 😬

**Comment by iamkun** [comment]
Just updated our documentation with locale and plugin! @Imperat @dmckenna24
