### ISSUE TITLE
Strict parsing does not work

### ISSUE THREAD

**Issue by dextreza** [iamkun/dayjs#1420]
command: dayjs('197-00-00', 'YYYY-MM-DD', true).isValid();

current value: **true**

expected value: **false**
reason: the year value does not match with format 'YYYY', one 'Y' is missing

**Comment by bornova** [comment]
Hi @dextreza,
Seems to be working as expected on my end.  Are you using the latest version of dayjs?

[https://runkit.com/6052c5915dac89001a8e3602/6052c5914124820013dd1902](https://runkit.com/6052c5915dac89001a8e3602/6052c5914124820013dd1902)

**Comment by dextreza** [comment]
i missed the custom parser... my fault! :(
you are right. It works fine now.
sorry
