### ISSUE TITLE
Issue parsing 'YYYY-MMM-DD' formatted dates

### ISSUE THREAD

**Issue by johnaschroeder** [iamkun/dayjs#1422]
**Describe the bug**
dayjs does not appear to parse the month and day for MMM dates.  For example, dayjs('2021-Mar-15', 'YYYY-MMM-DD') appears to parse to 1/1/2021.

**Expected behavior**
Parses dates with month formatted with "MMM" to the correct date.  FYI moment parses as expected.  I ran the codepen with both.

[Code Pen](https://codepen.io/jschroeder123/pen/VwmoYKa)

```
const mmDateString = "2021-03-15";
const mmmDateString = "2021-Mar-15";

const testMmParsing = dayjs(mmDateString, 'YYYY-MM-DD').format();
console.log('testMmParsing:', testMmParsing);

const testMmmParsing = dayjs(mmmDateString, 'YYYY-MMM-DD').format();
console.log('testMmmParsing:', testMmmParsing);
```
Console:
```
testMmParsing: 2021-03-15T00:00:00-04:00
testMmmParsing: 2021-01-01T15:00:00-05:00
```

**Information**
 - Day.js Version: 1.10.4
 - OS: Mac
 - Browser: Chrome/Node
 - Time zone: EST

**Comment by hakimio** [comment]
You have to use [CustomParseFormat extension](https://day.js.org/docs/en/plugin/custom-parse-format).

**Comment by johnaschroeder** [comment]
Yes, that worked perfectly. Thank you.
