### ISSUE TITLE
「timezone」Why I input similar data but get different output?

### ISSUE THREAD

**Issue by bbwlfx** [iamkun/dayjs#1440]
**Describe the bug**
input: console.log(dayjs(1616888607000).tz("Europe/London").format('HH:mm:ss YYYY-MM-DD z'))
output: "Europe/London" 23:43:27 2021-03-27 GMT

input: console.log(dayjs(1616988607000).tz("Europe/London").format('HH:mm:ss YYYY-MM-DD z'))
output: 1616487607000, "Europe/London" 04:30:07 2021-03-29 GMT+1

I'm puzzled why I get different results: GMT and GMT+1

**Expected behavior**
Both two outputs are GMT+1 or GMT.

**Information**
- I debug this problem on website https://day.js.org/
- Chrome:  89.0.4389.90
- OS: macOS

**Comment by ashconnell** [comment]
I'm seeing the same thing here. The issue also exists on the latest dev commit

**Comment by ashconnell** [comment]
I have a sneaky suspicion that the timezone plugin is only compatible with a few methods such as `startOf()` etc.

The timezone plugin code itself is only 150 LOC and contains wrappers for the base `day()` call and `.startOf()` methods. Nothing else.

My guess is that we would need to write custom overrides for all the base dayjs methods to calculate timezone offsets, eg `.hour()` and `.format()` etc

Seriously think the docs should explicitly say timezone support is not ready. I've invested way too much time on this and now have move to something else.

**Comment by bbwlfx** [comment]
And I found Date.prototype.toLocaleString and Intl.DateTimeFormat have same problem....
`new Date(1616888607000).toLocaleString('en-US', {timeZone: 'Europe/London', timeZoneName: 'short'})
"3/27/2021, 11:43:27 PM GMT"
new Date(1616988607000).toLocaleString('en-US', {timeZone: 'Europe/London', timeZoneName: 'short'})
"3/29/2021, 4:30:07 AM GMT+1"`

**Comment by bbwlfx** [comment]
ohhhh, sorry
I found that 3/28/2021 Britain switched from winter time to summer time, which means switching from GMT+0 to GMT+1, so this output maybe right?
