### ISSUE TITLE
Add ObjectSupport TypeScript definition(s)

### ISSUE THREAD

**Issue by AviBueno** [iamkun/dayjs#1441]
**Describe the bug**
Attempting to initialize a dayjs object based on ObjectSupport syntax under a TypeScript project yields the following error: `Type 'number' is not assignable to type '{ (): number; (value: number): Dayjs; }'.`

**Expected behavior**
The dayjs index.d.ts file should be updated such that object-based initialization would be possible.

**Information**
 - Day.js Version: v1.10.4
 - OS: MacOS
 - Browser: Irrelevant. Node.js project.
 - Time zone: UTC

**Comment by kuanyui** [comment]
Any news on this issue?

**Comment by manix84** [comment]
+1: Still occurring in v1.10.7

**Comment by adam-marshall** [comment]
affecting me in 1.11.3

**Comment by autopp** [comment]
I created PR #1990 for this issue.
