### ISSUE TITLE
Invalid date when parsing MMMM, YYYY format

### ISSUE THREAD

**Issue by MrPoketes** [iamkun/dayjs#1452]
**Describe the bug**
Parsing does not working for `MMMM, YYYY` format even after extending `customParseFormat`.

**Expected behavior**
Doing `dayjs("April, 2021", "MMMM, YYYY")` should return a normal date. However it returns `Invalid Date`

**Information**
 - v1.10.4
 - OS: unrelated
 - Browser: unrelated
 - Time zone: unrelated
 
EDIT:
Here is the sandbox example of this bug.
https://codesandbox.io/s/dayjs-bug-4djm6?file=/src/App.tsx

**Comment by nerijunior** [comment]
Having the same problem too:
```
console.log(dayjs("2021-06-09", "YYYY-MM-DD").format("DD/MM/YYYY"));
console.log(dayjs("14/06/1993", "DD/MM/YYYY").format("DD/MM/YYYY"));
```
will print:
```
09/06/2021 
Invalid Date 
```

It appears to be a problem with typescript only.

**Comment by iamkun** [comment]
Bug confirmed, error matching `April,` instead of `April`

**Comment by BePo65** [comment]
The problem is the comma in the date / format string; dayjs cannot handle this. PR #1913 should fix that.
