### ISSUE TITLE
Locale && Plugin released @1.6.0 🎊 🎉 🎊 🎉 

### ISSUE THREAD

**Issue by iamkun** [iamkun/dayjs#146]
Just released @1.6.0 with i18n and plugin system. 

Thanks @Frondor @schiem 's contribution.

ping @aalises @Imperat @kfirba @harrysarson

Discussion and test welcome.

**Comment by Frondor** [comment]
What do you mean? You can't understand the documentation? 
![https://github.com/xx45/dayjs#format](https://i.imgur.com/i0e3dPA.png)

**Comment by ronildo** [comment]
I'm sorry I thought that option wasn't available.
I remember looking at here before and it wasn't available, also there was a discussion here on the issues asking for this feature.

ps: yes I know how to read, thanks for your good manners.

**Comment by xx45** [comment]
@ronildo We added this list of all available formats table to our docs several days ago, sorry for the confusion.

**Comment by ronildo** [comment]
Hey @xx45 just notice it, last time I took a look it wasn't there.
Thank you so much, great work, so nice to have an alternative to momentJS
