### ISSUE TITLE
String + Format Parsing using customParseFormat plugin doesn't work

### ISSUE THREAD

**Issue by taribowo** [iamkun/dayjs#1466]
**Describe the bug**
dayjs seems unable to parse date in 'DD-MMM-YYYY' format in Mozilla Firefox. i've tried using the customParseFormat but the parsed date always returns 'Invalid Date'

```javascript
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';

dayjs.extend(customParseFormat);

const date = dayjs('27-Oct-20', 'DD-MMM-YYYY');

console.log(date.format('YYYY-MM-DD')); // Invalid Date
console.log(date);
/*
{
    $D: NaN,
    $H: NaN,
    $L: "en",
    $M: NaN,
    $W: NaN,
    $d: Invalid Date {},
    $m: NaN,
    $ms: NaN,
    $s: NaN,
    $u: undefined,
    $y: NaN
}
*/
```

This happens in both Firefox and Chrome. However, in Chrome, i succeeded in parsing the date if i didn't the format argument
```javascript
const date = dayjs('27-Oct-20');
console.log(date.format('YYYY-MM-DD')); // 2020-10-27 this somehow worked in Chrome
```
Any idea why this happened? Is my set up of the customParseFormat plugin correct?

**Expected Behaviour**
Using the first block of code should log the string '2020-10-27' to the console, regardless of browser

**Information**
Day.js Version: 1.10.4
Environment: NodeJS (ReactJS to be precise)
OS: Windows 10
Browsers: Chrome Version 89.0.4389.128, Firefox 88.0
Time Zone: GMT+7

**Comment by ivansieder** [comment]
@taribowo your above codes causes "Invalid Date" on Firefox and Chrome (in my case). It seems like you have an issue in your format, try to change it from this
`const date = dayjs("27-Oct-20", "DD-MMM-YYYY");`
to this
`const date = dayjs("27-Oct-20", "DD-MMM-YY");`

In your format, you're specifying a 4-digit year-number, but in the date-string, you only have a 2-digit year-number

**Comment by taribowo** [comment]
@ivansieder Oh God, you're right. I didn't notice i used the wrong format to parse the string. I've changed it to 
`const date = dayjs("27-Oct-20", "DD-MMM-YY");`
and now it worked perfectly in both browsers.

Thanks a lot for the help and apology for my oversight. Will close the issue now.
