### ISSUE TITLE
TypeError: dayjs__WEBPACK_IMPORTED_MODULE_0___default.a.duration is not a function

### ISSUE THREAD

**Issue by harvanchik** [iamkun/dayjs#1472]
**Describe the bug**

Brower log:
https://pastebin.com/Di0fD6Yu

tsconfig.json:
https://pastebin.com/3bNcWm5F

My code (hours.pipe.ts):
https://pastebin.com/AXHQnquQ

**Information**
 - Day.js Version: v1.10.4
 - Framework: Angular 11 w/ TypeScript
 - OS: Desktop Windows 10
 - Browser: Brave 1.23.73
 - Time zone: Pacific Daylight Time

**Comment by brujo-rojas** [comment]
You need to extend it with:
`dayjs.extend(duration)`

https://day.js.org/docs/en/plugin/duration

**Comment by harvanchik** [comment]
I will try that out when I get the chance.  Thanks!  Closing for now, but will re-open if needed.
