### ISSUE TITLE
[Feature Request] Let Dayjs object extend JS Date

### ISSUE THREAD

**Issue by bglgwyng** [iamkun/dayjs#1520]
I recently migrated my project from `date-fns` to `dayjs` to use its concise builder pattern.
Each of them has good parts and less good parts.
- `date-fns` manipulates `Date`, so `date-fns` can't provide such nice methods.
- `dayjs` has its own date object that allows us to write better code. However, it also requires to be cast to `Date` with `.toDate()`at the end of the building, which is not the case in `date-fns`.

Here is my idea. Let dayjs object extend JS Date and override mutation methods like `setDate` to broken methods that always throw a message like `Don't try to mutate me!`.

Then we can omit `.toDate()`.  `someDayjsObject instanceof Date === true` holds now, so we can pass new `Dayjs` object to functions of other external packages which use this condition to distinguish `Date` objects to other values.

Furthermore, we can use `dayjs` object across packages. `dayjs` is a very popular package, but none of the package writers wants to expose functions with `dayjs` object. Because it's not standard.

For instance, let's assume that you are writing a package named 'doomsday.js' which has a function called `getDoomsday`.
```typescript
function getDoomsday(): Date {
  const day = dayjs().blah().blah().
  return day.toDate();
}
```
You might not want to force users of 'doomsday.js' to use `dayjs` only just to use your package, though `dayjs`will be installed as a dependency, so you'd cast it to JS Date.

What if `Dayjs` is a subtype of `Date`?
```typescript
function getDoomsday(): Dayjs {
  const day = dayjs().blah().blah().
  return day;
}
```
The second version of `getDoomsday` has a stricter constraint than the first one.  It'll pass every type checks that the first one has passed.

I know that I missed one important fact. The new `Dayjs` is not mutable via methods like `setDate`. Thus, it's the extension in the sense of interface, but not in behavior. However, when a programmer tries to mutate an object which is not constructed by his code, then it's hard to avoid undesirable behavior in many cases. I mean it's evil to write such code. So, I think that prohibiting mutation via vanilla `Date` methods doesn't make a huge inconvenience. Besides, `toDate` is still there, you can use it to obtain mutable `Date`.

The packages like `momentjs`, `date-fns` and `dayjs` came up because of the weakness of vanilla `Date`. However, they all can't replace `Date` with something better. With this interface, `dayjs` can offer 'the better Date' that works with the codes use vanilla `Date`.

I only mentioned about benefits of this change. I expect there must be some problems. I tried to provide a reference implementation of this change, but it wasn't that trivial. What sort of problems would be there with this change? I like to hear your opinions.

**Comment by iamkun** [comment]
If you are looking for a better js Date object, you can check here proposal-temporal https://github.com/tc39/proposal-temporal
