### ISSUE TITLE
Incorrect date parsing in Firefox browser

### ISSUE THREAD

**Issue by ppiyush13** [iamkun/dayjs#1547]
**Describe the bug**
Parsing date using dayJs and then converting to native JavaScript Date is not working as expected in Firefox browser.

```javascript
const parsedDate = dayJs(
  "25-MAY-2021 12:00 +08:00",
  "DD-MMM-YYYY HH:mm Z"
).toDate().toString();
```

**Output**
Getting below output in Firefox browser
```
Fri May 25 -2021 09:53:28 GMT+0553 (India Standard Time) 
```

**Expected output**
In chrome and NodeJs, getting correct below output
```
Tue May 25 2021 09:30:00 GMT+0530 (India Standard Time)
```

**Issues:**
- Time is incorrect (09:53:28 instead of 09:30:00)
- Time zone is incorrect (GMT+0553 instead of GMT+0530)
- Year is negative (-2021 instead of 2021)
- Weekday is incorrect (Friday instead of Tuesday)

Could this be related to Firefox bug [Inconsistent date object - Negative year in result](https://bugzilla.mozilla.org/show_bug.cgi?id=1609401) ?

**Information**
 - **Day.js Version:** 1.10.5
 - **OS:** windows 10
 - **Browser:** Firefox 89.0.1 (64-bit)
 - Time zone: GMT+05:30 IST (India Standard Time)

**Issue reproduce**
I have created minimal repo to reproduce above issues https://codesandbox.io/s/determined-mayer-fsc4e?file=/src/index.js
 
Anyone aware of possible workarounds ?

**Comment by MirzaLeka** [comment]
I've noticed the same issue with Moment on Firefox. Scary
`moment(
    "25-MAY-2021 12:00"
  ).format("YYYY-MM-dddd HH:mm:ss")

// chrome: "2021-05-Tuesday 12:00:00"
// firefox: "-2021-05-Friday 12:00:00"
`

Anyway, there is a workaround with the customParseFormat plugin:
`
import * as customParseFormat from 'dayjs/plugin/customParseFormat'
import * as dayjs from 'dayjs'
dayjs.extend(customParseFormat)
const date = dayjs('2021-05-25 12:00 PM', 'YYYY-MM-DD HH:mm A').toDate().toString()
// "Tue May 25 2021 12:00:00 GMT+0200 (Central European Summer Time)"
`
and the output is the same across browsers. More on that [here](https://stackoverflow.com/questions/65839590/dayjs-telling-me-invalid-date-for-this-date-string/65840581#65840581).
Cheers!

**Comment by iamkun** [comment]
For consistent results parsing anything other than ISO 8601 strings, you should use String + Format. 

ref https://day.js.org/docs/en/parse/string
