### ISSUE TITLE
FEATURE REQUEST: Short format for dayjs().from()

### ISSUE THREAD

**Issue by ThePotato10** [iamkun/dayjs#1559]
As of now, dayjs().from() returns a string somewhere along the lines of `1 day ago` or `6 minutes ago`. Personally, I prefer a shorter format like `1d` or `6min`. It'd be wonderful if dayjs().from() took an optional parameter to output in the short format I described instead. 

I'd be happy to work on this feature myself

**Comment by iamkun** [comment]
Day.js is very easy to customize.

https://day.js.org/docs/en/customization/relative-time
