### ISSUE TITLE
Format date with month instead of day

### ISSUE THREAD

**Issue by RigottiG** [iamkun/dayjs#1564]
**Describe the bug**
I'm trying to format a date in the following format `DD/MM/YYYY` to `DD MMM YYYY` but it is taking the month instead of the day and getting wrong

```javascript
import dayjs from 'dayjs'

dayjs('12/03/2020', 'DD/MM/YYYY').format('DD MMM YYYY') // 03 Dec 2020

```

**Expected behavior**
`12/03/2020` -> `12 Mar 2020` instead of `03 Dec 2020`

**Information**
 - Day.js Version: 1.10.4
 - OS: macOS 11.4
 - React Native
 - Time zone: Brasilia Standard Time GMT-3

**Comment by Bibazavr** [comment]
https://codesandbox.io/s/magical-ramanujan-kotn1?file=/src/App.tsx
