### ISSUE TITLE
Invalid Date when parse time in node

### ISSUE THREAD

**Issue by liudonghua123** [iamkun/dayjs#1574]
**Describe the bug**
I tried to parse some time using dayjs in node. For example
```js
const  startTime = '23:00:00'
const startTimeDayjs = dayjs(startTime,'HH:mm:ss')
```
But the pared result is `Invalid Date`, if I using it in browser environment, then it is ok.

**Expected behavior**
startTime passed correct.

**Information**
 - Day.js Version ^1.10.6
 - OS: Microsoft Windows [Version 10.0.19042.1083]
 - Browser chrome 91
 - Time zone: GMT+08:00 DST (Pacific Daylight Time)

![image](https://user-images.githubusercontent.com/2276718/125384682-e08aef80-e3cb-11eb-8c85-572a7690f00b.png)
![image](https://user-images.githubusercontent.com/2276718/125385009-50997580-e3cc-11eb-86bc-b4f84cfa7707.png)

**Comment by tttocklll** [comment]
According to [this page, ](https://day.js.org/docs/en/parse/string-format) you have to use `customParseFormat` plugin to work.

```
var dayjs = require("dayjs");
var customParseFormat = require("dayjs/plugin/customParseFormat");
dayjs.extend(customParseFormat);

const startTime = '23:00:00';
const startTimeDayjs = dayjs(startTime,'HH:mm:ss');
```

It worked fine for me.

**Comment by liudonghua123** [comment]
@tttocklll Thanks, now I get it. 😄
