### ISSUE TITLE
Add documentation on how to globally setup dayjs with typescript and plugins

### ISSUE THREAD

**Issue by kjellski** [iamkun/dayjs#1577]
**Describe the bug**
After reading the current section about using dayjs with typescript I have to redo the steps from there on every file I want to use a plugin in: https://day.js.org/docs/en/installation/typescript 

**Expected behavior**
Setup instructions on how to setup dayjs once globally and have it recognize all used plugin types globally 

**Information**
 - Day.js Version latest

I would love to contribute, but from reading a ton of tickets I still can't figure out what the setup should be. If we can clear that up, I'll prepare a PR :+1:

**Comment by addisonElliott** [comment]
Here's how I use Day.js in my codebase. This is in a `dayjs.ts` file and it is imported once from my main file (`index.ts`). After that, I don't have to import the plugin files or even this file again in order to get Typescript definitions.

```typescript
/* eslint-disable func-names */
import dayjs from 'dayjs';
import 'dayjs/plugin/utc';
import 'dayjs/plugin/duration';

dayjs.extend(require('dayjs/plugin/utc'));
dayjs.extend(require('dayjs/plugin/duration'));
```

So, to be clear, I'm able to write code like this in **completely** different files and it works for me:

```typescript
import dayjs from 'dayjs';

dayjs.utc('2021-07-14T00:00:00Z');
```

**Comment by kjellski** [comment]
@addisonElliott that sounds fantastic, it's exactly what I would be looking for. Could you post something about your setup? For example your `tsconfig.json`?

**Comment by addisonElliott** [comment]
Here's my `tsconfig.json`, but there's nothing special about it I don't think.

```
{
  "compilerOptions": {
    "target": "es2019",
    "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
    "module": "commonjs",
    "incremental": true,
    "outDir": "./dist",
    "allowJs": true,
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

Are you having troubles with the setup I described?

**Comment by BePo65** [comment]
During my tests with dayjs I created a small demo project for using dayjs with typescript; it can be found on [github](https://github.com/BePo65/dayjs-typescript-demo).

Perhaps this will help answering some questions.

**Comment by kjellski** [comment]
> During my tests with dayjs I created a small demo project for using dayjs with typescript; it can be found on [github](https://github.com/BePo65/dayjs-typescript-demo).
> 
> Perhaps this will help answering some questions.

This is unfortunately not what I'm thinking about. I think it would be nice to have `dayjs` setup once and then make it project globally aware of having the types applied by certain extensions.

**Comment by kjellski** [comment]
> Here's my `tsconfig.json`, but there's nothing special about it I don't think.
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es2019",
>     "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
>     "module": "commonjs",
>     "incremental": true,
>     "outDir": "./dist",
>     "allowJs": true,
>     "strict": true,
>     "esModuleInterop": true,
>     "sourceMap": true,
>     "forceConsistentCasingInFileNames": true
>   }
> }
> ```
> 
> Are you having troubles with the setup I described?

Yes, if I'm setting this up in e.g. an index.ts at the root of the project with some plugins, then somewhere down the line using `import dayjs from 'dayjs'` will just not recognize the applied plugins signatures from their types. But that's what's working fine for you, right?

**Comment by addisonElliott** [comment]
Yes, and I use this concept daily with other packages besides Day.js.

This is a feature for how module augmentation. Module augmentation, which is extended existing packages, is used by Day.js to add functionality to the existing Day.js type definitions. From my understanding, once this file is imported, the module is augmented **everywhere**. The Typescript compiler doesn't conditionally augment modules or do it on a file-by-file basis.

For example, I've augmented the built-in `Array` class to add some helper functions. I placed the augmented files in `.d.ts` file and Typescript knows to import them and utilize them. I don't have to import them anywhere else to see the new functions in the `Array` class.

Can you create a sample project where you're having the issue so I can look it over?

**Comment by BePo65** [comment]
Hm, is it possible that we mix here 2 different concepts?

In the "old days" we used packages via global "variables" (i.e. they added properties to the window object that can be access by javascript as if they were global variables). This way you can augment a "module" once and use it everywhere.  
The disadvantage was clobbering of the global system (i.e. you have to carefully select your package name).

But then there are "module systems" (like commonjs or esm). The idea was to avoid this pitfalls and encapsulatee all modules. This way a module and its augmentations is only visible in the file that uses a module.

If I may quote from the [node documentation](https://nodejs.org/docs/latest/api/modules.html#modules_modules_commonjs_modules):

> In the Node.js module system, each file is treated as a separate module.

So IMHO its by design that commonjs modules are only visible inside of a file that uses these modules.

**Comment by iamkun** [comment]
The plugins will update the global dayjs instance.

That is to say, in a single page application, if you extend the plugins in your main entry file like index.js,

There's no need to do the same thing on other pages in your app, 

only `import dayjs from 'dayjs'` , and use the added methods by the plugins.

**Comment by afacode** [comment]
Official documents 
Import and use in your Typescript file
```
import * as dayjs from 'dayjs'
import * as isLeapYear from 'dayjs/plugin/isLeapYear' // import plugin
import 'dayjs/locale/zh-cn' // import locale

dayjs.extend(isLeapYear) // use plugin
dayjs.locale('zh-cn') // use locale
```
Replace with the following
```
import dayjs from 'dayjs'
import isLeapYear from 'dayjs/plugin/isLeapYear' // import plugin
import 'dayjs/locale/zh-cn' // import locale
dayjs.extend(isLeapYear) // use plugin
dayjs.locale('zh-cn') // 
```

**Comment by kjellski** [comment]
Thanks for the hints @addisonElliott - it must be due to our setup then.

@iamkun that I know, and it works nicely. But it isn't updating the types on the imported dayjs file afterwards. So when I try to use plugin methods, I'm getting compile errors from typescript.

I'm closing this due to the fact that I might be misconfiguring something on my end. Thanks for the help everyone!

A working example of this

**Comment by j-a-h-i-r** [comment]
One additional question. Does extending dayjs with plugin(s) affect imported modules too?

Let me explain, in my NextJs project, I am adding some plugins to dayjs in the `_app.tsx` file (the root file basically).

```js
import dayjs from 'dayjs'
import updateLocale from "dayjs/plugin/updateLocale";
import relativeTime from "dayjs/plugin/relativeTime";

// update locale
dayjs.extend(relativeTime);
dayjs.extend(updateLocale);
dayjs.updateLocale("en", {
  relativeTime: {
    future: "in %s",
    past: "%s ago",
    s: "a few modified seconds",
    m: "1 minute",
    mm: "%d modified minutes",
    h: "1 hour",
    hh: "%d modified hours",
    d: "1 day",
    dd: "%d days",
    M: "a month",
    MM: "%d months",
    y: "a year",
    yy: "%d years",
  },
});
```

Now, I have a component library where I have pure components. This lives outside of the NextJS application and is imported as an external dependency. As this is a component library, it does not have any "root" file per se. I use dayjs in this library. So will the added plugins also apply to the dayjs in this library too? For example,

```js
// @ComponentLibrary/Test.tsx
import dayjs from 'dayjs';

export function MyLib() {
    return dayjs(new Date()).fromNow()
}
```

Will this print `a few seconds ago` (the default) or `a few modified seconds` (the result of applying the plugins)?

**Comment by BePo65** [comment]
IMHO it will output `a few modified seconds` as the code of the external component runs in the scope of your `_app.tsx` file and module features are imported via `import` into the scope of a single script - in your case this is your tsx file (see [mdn on JavaScript modules).](module features are imported into the scope of a single script).

**Comment by ala-garbaa-pro** [comment]
This is the right way: 😊👌

```ts
import type { Dayjs } from "dayjs";
import dayjs from "dayjs";
...

const formatDate = (date: Date): string => {
  const dayObj: Dayjs = dayjs(date);
  return `${dayObj.format("MMM D, YYYY")}`;
};
```

**Comment by JonathanSTH** [comment]
> Here's how I use Day.js in my codebase. This is in a `dayjs.ts` file and it is imported once from my main file (`index.ts`). After that, I don't have to import the plugin files or even this file again in order to get Typescript definitions.
> 
> ```ts
> /* eslint-disable func-names */
> import dayjs from 'dayjs';
> import 'dayjs/plugin/utc';
> import 'dayjs/plugin/duration';
> 
> dayjs.extend(require('dayjs/plugin/utc'));
> dayjs.extend(require('dayjs/plugin/duration'));
> ```
> 
> So, to be clear, I'm able to write code like this in **completely** different files and it works for me:
> 
> ```ts
> import dayjs from 'dayjs';
> 
> dayjs.utc('2021-07-14T00:00:00Z');
> ```

so sorry to bother you. i'd love to actually see this. can't really seem to make it work like you've indicated. do you have a sample repo or even just the code on what needs to happen? using cypress v12

**Comment by yannxaver** [comment]
I'm using next.js 14 app router. Extending day.js globally does not work.

```typescript
// layout.tsx

import dayjs from 'dayjs';
import AdvancedFormat from 'dayjs/plugin/advancedFormat';
dayjs.extend(AdvancedFormat);
```

**Comment by ghostlexly** [comment]
> I'm using next.js 14 app router. Extending day.js globally does not work.
> 
> ```ts
> // layout.tsx
> import dayjs from 'dayjs';
> import AdvancedFormat from 'dayjs/plugin/advancedFormat';
> dayjs.extend(AdvancedFormat);
> ```

On NextJS, you have to create a new lib file and export it.

```ts
import dayjs from "dayjs";
import "dayjs/locale/fr";
import utc from "dayjs/plugin/utc";
import customParseFormat from "dayjs/plugin/customParseFormat";

const dayjsExt = dayjs;

dayjs.locale("fr");
dayjs.extend(utc);
dayjs.extend(customParseFormat);

export { dayjsExt };
```

**Comment by wherehows** [comment]
> > I'm using next.js 14 app router. Extending day.js globally does not work.
> > ```ts
> > // layout.tsx
> > import dayjs from 'dayjs';
> > import AdvancedFormat from 'dayjs/plugin/advancedFormat';
> > dayjs.extend(AdvancedFormat);
> > ```
> 
> On NextJS, you have to create a new lib file and export it.
> 
> ```ts
> import dayjs from "dayjs";
> import "dayjs/locale/fr";
> import utc from "dayjs/plugin/utc";
> import customParseFormat from "dayjs/plugin/customParseFormat";
> 
> const dayjsExt = dayjs;
> 
> dayjs.locale("fr");
> dayjs.extend(utc);
> dayjs.extend(customParseFormat);
> 
> export { dayjsExt };
> ```

What if have to support i18n?

do you know how to import only the necessary languages instead of importing all languages as shown below?

```javascript
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import "dayjs/locale/ko";
import "dayjs/locale/zh-cn";
import "dayjs/locale/ja";
import "dayjs/locale/en";

const dayjsExt = dayjs;
dayjs.extend(relativeTime);

export default dayjsExt;
```

**Comment by eseQ** [comment]
`use client` guys

**Comment by sikirumoshood** [comment]
Exporting the extended dayjs from a file in lib folder, worked for me.

```

const dayjs = require('dayjs')
const utc = require('dayjs/plugin/utc')

dayjs.extend(utc)

export const dayjsUtc = dayjs


```

**Comment by sebastienlabine** [comment]
It worth nothing that this will only work for Server components, and you will need to use the newly exported dayjs instance in the client component.

 
 app/layout.tsx
 ```ts
 import dayjs from "@/lib/dayjs.tsx";
 export default function Layout({children}) {
 return children;
 }
```


 app/page.tsx
 ```ts
 import dayjs from "dayjs";
 export default function Layout({children}) {
 return <div>{dayjs(new Date()).format("LLL")}</div>; // works!!
 }
```

Client side not working
app/error.tsx
```ts
"use client";
import dayjs from "dayjs";
export default function Error({ error }) {
  return (
    <div className="bg-white shadow-lg rounded-lg p-6 w-full max-w-lg">
     <div>{dayjs(new Date()).format("LLL")}</div>; // doesn't work...
    </div>
  );
}

Client side working
app/error.tsx
```ts
"use client";
import { Paragraph, Title, Text } from "@smartbills/react";
import customDayjs from "@/utilities/dayjs";
export default function Error({ error }) {
  return (
    <div className="bg-white shadow-lg rounded-lg p-6 w-full max-w-lg">
     <div>{customDayjs (new Date()).format("LLL")}</div>; // works!!
    </div>
  );
}
```
