### ISSUE TITLE
Time formatting

### ISSUE THREAD

**Issue by tigone** [iamkun/dayjs#1579]
**Describe the bug**
With moment we can use:
moment("00:00:00", "HH:mm:ss").format("HH:mm"); and we get "00:00"
if we do the same with dayjs we get: "Invalid Date".

**Expected behavior**
We should be able to get the same result with dayjs, i.e:  "00:00"

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by bornova** [comment]
Hi @tigone,
Please make sure to use [CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format):

https://runkit.com/60d2556ba6adc7001308f54d/60f07249453159001ea12f0c

**Comment by tigone** [comment]
Thank you @bornova! Really helped me out. Bests!
