### ISSUE TITLE
DayJS duration plugin appends undefined everywhere

### ISSUE THREAD

**Issue by Milo123459** [iamkun/dayjs#1588]
**Describe the bug**
Using this code:
```ts
dayjs.duration(sg.time_played, 'seconds').format('d[d] h[h] m[m]')
```
Gives this: `undefinedd undefinedh 13m` - It is because the value isn't great enough for days or hours.
**Expected behavior**

Should remove the fields that the value isn't great enough to touch

**Information**
 - Day.js Version v1.10.6
 - OS: Linux (Ubuntu)
 - Browser: A node project
 - Time zone: GMT+0

**Comment by Milo123459** [comment]
This code was just taken from the moment-duration-plugin and it worked using Moment.

**Comment by Milo123459** [comment]
@iamkun mind helping?

**Comment by bornova** [comment]
Hi @Milo123459,
Looks like dayjs only supports the following formats for the duration plugin:
https://day.js.org/docs/en/durations/format#list-of-all-available-formats

So you may want to try this instead:
```javascript
dayjs.duration(sg.time_played, 'seconds').format('D[d] H[h] m[m]')
```

**Comment by Milo123459** [comment]
Oh, Thanks.
