### ISSUE TITLE
dayjs not work in React Native Android

### ISSUE THREAD

**Issue by Bob-MYMC** [iamkun/dayjs#1591]
**Describe the bug**
dayjs parse the date string `Tue, 27 Jul 2021` in react native android returns `null` instead `Date`

**Expected behavior**
The expected result of `dayjs("Tue, 27 Jul 2021")` is `2021-07-26T14:00:00.000Z`, and it works well in react native iOS.
But on Android, the function returns `null`

**Information**
 - Day.js Version 1.10.6
 - OS: React Native Android

**Comment by iamkun** [comment]
For consistent results parsing anything other than ISO 8601 strings, you should use String + Format. https://day.js.org/docs/en/parse/string-format

**Comment by Bob-MYMC** [comment]
@iamkun `customParseFormat` approach has also been tried, but it does not work on either iOS or android

**Comment by WJimmyCook** [comment]
@Bob-MYMC Did you figure out a solution to this? I'm having the same problem with dayjs returning null on Android (iOS works fine). customParseFormat doesn't work either.
