### ISSUE TITLE
diff计算天数问题

### ISSUE THREAD

**Issue by ace0109** [iamkun/dayjs#1597]
dayjs('2018-08-01 00:00:00').diff(dayjs('2018-08-01 23:59:59'), 'day')

当前的0点到当天的23:59:59 ，计算出来是0，这个是不是应该是1天啊？

业务中，经常设置开始时间和结束时间，一般都是设置开始时间是0点   结束时间是23：59：59，这时候计算出来天数就少了一天。

**Comment by iamkun** [comment]
you can pass a third argument 'true'

dayjs.diff(dayjs(), 'day', true)
