### ISSUE TITLE
Can't parse date string with a day of the week

### ISSUE THREAD

**Issue by dudintv** [iamkun/dayjs#1616]
**Describe the bug**
Dayjs can't parse a string with extra words like days of the week.

```js
scheduledTime = "14:05 - Friday 3 Sep 2021"
dayjs(scheduledTime, "hh:mm D MMM YYYY")   // => Invalid date
dayjs(scheduledTime, "hh:mm - D MMM YYYY")   // => Invalid date
```

I've found that ```dayjs(scheduledTime, "hh:mm - ...... D MMM YYYY")``` works for "Friday", but days of the week have a different count of characters :)

_It worked two weeks ago. But now, after I've updated Dayjs, it's not working anymore._

**Expected behavior**
Two variants:
1. ignore all extra words (better)
2. add days of the week as a parameter of the string parsing (which should leads to ignoring this info)

**Information**
 - Day.js Version 1.10.6
 - OS: MacOS
 - Browser Version 92.0.4515.159 (Official Build) (x86_64)
 - Time zone: GMT+0200 (Central European Summer Time)

**Comment by BePo65** [comment]
There is a problem with parsing of some formats. I pushed a pr for this already.
