### ISSUE TITLE
Property 'tz' does not exist on type 'Dayjs'.ts(2339)

### ISSUE THREAD

**Issue by lucrus73** [iamkun/dayjs#1617]
I get the error message while I think my code is "correct" (e.g. it follows the dayjs documentation).

[This other issue](https://github.com/iamkun/dayjs/issues/297) could be related, but I'm not skilled enough to tell if it actually is.

Here is my code:

    import * as dayjs from 'dayjs';
    // ...
    export class MyComponent {
    // ...
      public doStuff() {

        const utc = require('dayjs/plugin/utc');
        const timezone = require('dayjs/plugin/timezone');
        dayjs.extend(utc);
        dayjs.extend(timezone);            
        const mytime = dayjs().tz("Asia/Dubai");  // Property 'tz' does not exist on type 'Dayjs'.ts(2339)
    

**Information**
 - Day.js Version 1.10.6
 - Typescript 4.3.4

**Comment by joealden** [comment]
@lucrus73 it may have something to do with the fact that you are using `require` to load the plugins. In your situation, can you not import the plugins as static imports (along with the existing `dayjs` import)?

**Comment by lucrus73** [comment]
I don't know, I just copied the sample code in the documentation. How do I use `import` instead of `require` in this case?
