### ISSUE TITLE
dayjs("2").format()  == '2001-02-01T00:00:00+09:00' ???

### ISSUE THREAD

**Issue by kihyunkimlee** [iamkun/dayjs#1634]
Hi guys.
First of all, Thank you for creating and managing this wonderful time library module.
I think you are really great people!!
I hope one day I can help you to manage this module.

**Describe the bug**
Now I'm trying to change my typescript codes's time library module from moment.js to dayjs.
But I got a strange result like below.

```typescript
console.log(dayjs("2").isValid())        // true
console.log(dayjs("2").format())        // "2001-02-01T00:00:00+09:00"
```

I expected it to be invalid and dayjs would throw error.
But It didn't at all.
I can't understand how these result came out.

Could anyone please explain me why these result came out?

**Information**
 - Day.js Version [1.10.7]
 - OS: [macOS Big Sur 11.4]
 - node: [12.22.3]
 - Time zone: [e.g. GMT-09:00 KST (Korea Standard Time)]

**Comment by imwh0im** [comment]
Hello. 

I checked this phenomenon.
string "2" returns the code as follows.

```javascript
dayjs('2')
// {
//  '$L': 'en',
//  '$d': 2001-01-31T15:00:00.000Z,
//  '$x': {},
//  '$y': 2001,
//  '$M': 1,
//  '$D': 1,
//  '$W': 4,
//  '$H': 0,
//  '$m': 0,
//  '$s': 0,
//  '$ms': 0
//  }
new Date('2')  // 2001-01-31T15:00:00.000Z
new Date('2').getFullYear()  // 2001
new Date('2').getMonth() // 1
new Date('2').getDate()  // 1
new Date('2').getDay() // 4
new Date('2').getHours() // 0
new Date('2').getMinutes() // 0
new Date('2').getSeconds() // 0
new Date('2').getMilliseconds() // 0
```
so 'isValid' is returned true
and dayjs object is also set as a result.

In the case of format, it seems that such a value comes out because it add +9 hours (In Your timezone).

**Comment by kihyunkimlee** [comment]
Thanks you for commenting!

So... why does dayjs parse the string "2" to "2001-02-01T00:00:00Z" ?

As far as I know,  string "2" does not satisfy with ISO 8601 format.

**Comment by imwh0im** [comment]
`new Date()` is Javascript objects.
It would be a good idea to check it out on the JavaScript community.

**Comment by kihyunkimlee** [comment]
Ahhhh~ I see!!

I thought Dayjs throw error if given string doesn't satisfy with ISO 8601 format and no extra format was given.

So... Dayjs doesn't throw any error if string doesn't satisfy with ISO 8601 format, right @imwh0im ?

**Comment by imwh0im** [comment]
@kihyunkimlee 
Yes. In addition, the wrong format gives the phrase 'invalid date'.

**Comment by kihyunkimlee** [comment]
@imwh0im 
Thanks!
