### ISSUE TITLE
Parsing '2020-12-20T15:00:00+08' is broken in 1.10+

### ISSUE THREAD

**Issue by Mirochiu** [iamkun/dayjs#1636]
**Describe the bug**
```
const day = require('dayjs');
console.log(`result:${dayjs('2020-12-20T15:00:00+08').format()}`);
```

In Day.js v1.9.8, we got `result:2020-12-20T15:00:00+08:00`.
In Day.js v1.10.7, we got `result:Invalid Date`.

Is this a new feature or breaking change?

**Expected behavior**
we expect the result is `result:2020-12-20T15:00:00+08:00`.

**Information**
- Day.js: 1.10.7
- OS: Ubuntu 20.04.1
- Node.js: v.16.9.1
- Time zone: Asia/Taipei (CST, +0800)

**Comment by imwh0im** [comment]
It is difficult to check because the difference between versions is too large. Can you narrow the gap?

1.10.7  => 2021-09-10
1.9.8 => 2020-12-27

**Comment by Mirochiu** [comment]
> It is difficult to check because the difference between versions is too large. Can you narrow the gap?
> 
> 1.10.7 => 2021-09-10
> 1.9.8 => 2020-12-27

I've test v1.10.0. The result:Invalid Date.

**Comment by rumax** [comment]
Same issue with dayjs 1.10.7 web or react native environment:

```
// 1)
console.log(dayjs('12/08/2021', 'DD/MM/YYYY').format('DD/MM/YYYY')) // "08/12/2021"

2)
console.log(dayjs('21/10/2021', 'DD/MM/YYYY').format('DD/MM/YYYY')) // "Invalid Date"

3)
console.log(dayjs('10/21/2021', 'DD/MM/YYYY').format('DD/MM/YYYY')) // "21/10/2021"
```

It seems like parser does not take into account format, which is valid according to documentation https://day.js.org/docs/en/parse/string-format, and expects first number to be month, even if it is specified as a day.

> It is difficult to check because the difference between versions is too large. Can you narrow the gap?

@imwh0im the latest version is definitely broken, why do you need a diff? or these reported cases work for you?

**Comment by BePo65** [comment]
Using an offset in a date/time string requires the customParseFormat' plugin to work.

I am on dayjs 1.11.2 and this test works for me (the timezone and utc plugins are only used to format the result as CST):
```
import dayjs from 'dayjs'
import customParseFormat from 'plugin/customParseFormat'
import timezone from 'plugin/timezone'
import utc from 'plugin/utc'

dayjs.extend(customParseFormat)
dayjs.extend(utc)
dayjs.extend(timezone)


it('Parsing is broken', () => {
  const input = '2020-12-20T15:00:00+08'
  const format = 'YYYY-MM-DD[T]HH:mm:ssZ'
  const resultDayjs = dayjs(input, format)
  expect(resultDayjs.isValid()).toBe(true)
  expect(resultDayjs.tz('Asia/Taipei').format()).toBe('2020-12-20T15:00:00+08:00')
})
```

**Comment by Mirochiu** [comment]
> Using an offset in a date/time string requires the customParseFormat' plugin to work.
> 
> I am on dayjs 1.11.2 and this test works for me (the timezone and utc plugins are only used to format the result as CST):
> 
> ```
> import dayjs from 'dayjs'
> import customParseFormat from 'plugin/customParseFormat'
> import timezone from 'plugin/timezone'
> import utc from 'plugin/utc'
> 
> dayjs.extend(customParseFormat)
> dayjs.extend(utc)
> dayjs.extend(timezone)
> 
> 
> it('Parsing is broken', () => {
>   const input = '2020-12-20T15:00:00+08'
>   const format = 'YYYY-MM-DD[T]HH:mm:ssZ'
>   const resultDayjs = dayjs(input, format)
>   expect(resultDayjs.isValid()).toBe(true)
>   expect(resultDayjs.tz('Asia/Taipei').format()).toBe('2020-12-20T15:00:00+08:00')
> })
> ```

Thanks for your suggestion. It work well when we applied the plugin with time format.

Show my snippet in node.js below for anyone finding a solution.
```nodejs
const dayjs = require('dayjs')
const customParseFormat = require('dayjs/plugin/customParseFormat')
dayjs.extend(customParseFormat)
const format = 'YYYY-MM-DD[T]HH:mm:ssZ'
console.log(`result:${dayjs('2020-12-20T15:00:00+0800', format).format()}`);
console.log(`result:${dayjs('2020-12-20T15:00:00+08', format).format()}`);
```
