### ISSUE TITLE
May I add Japanese translation?

### ISSUE THREAD

**Issue by ohbarye** [iamkun/dayjs#164]
Thanks for the great library.

I just want to make sure that there is a demand for having Japanese documents for dayjs. I believe that it's nice to have it in order to let more people use dayjs. In terms of that, I'm in favor of doing it.

On the other hand, I know some library authors don't like to have documents in several language because:

- they can't maintain documents written in languages that they are not familiar.
- it tends to get obsolete. Contributors basically update only English documents, and it's likely that none updates documents of other languages.

**Comment by iamkun** [comment]
@ohbarye Simple answer, thanks and yes! 

And I will open a issue detailing how to translate locals, documents as well as file structure.

**Comment by ohbarye** [comment]
@iamkun 
Thanks for your answer! Okay I'll try to translate in free time. 💪 

> And I will open a issue detailing how to translate locals, documents as well as file structure.

I'm looking forward to that.
