### ISSUE TITLE
There are spaces in the relative time in the Chinese language pack

### ISSUE THREAD

**Issue by 188007803** [iamkun/dayjs#1648]
**Describe the bug**
dayjs('2021-09-27 18:22:32').fromNow(); // output：3 小时前
There are spaces in a output sentence。

**Expected behavior**
dayjs('2021-09-27 18:22:32').fromNow(); // output：3小时前
Chinese characters are next to each other, no spaces are needed。

**Information**
 - Day.js Version v1.10.7
 - OS: MacOS
 - Browser：chrome latest

**Comment by iamkun** [comment]
Feel free to customize it yourself. https://day.js.org/docs/en/customization/relative-time
