### ISSUE TITLE
Arabic numbers aren't showing for Arabic locale

### ISSUE THREAD

**Issue by MirzaLeka** [iamkun/dayjs#1706]
Hi,
I've just stumbled upon an issue with the Arabic language. When I use Dayjs with Arabic locale, it displays English numbers instead of Arabic. Here is an example and comparison to Moment:

```
import * as dayjs from 'dayjs'
import 'dayjs/locale/ar';
import * as localizedFormat from 'dayjs/plugin/localizedFormat';
import * as customParseFormat from 'dayjs/plugin/customParseFormat';
import * as advancedFormat from 'dayjs/plugin/customParseFormat';
import * as moment from 'moment'

dayjs.extend(localizedFormat);
dayjs.extend(advancedFormat);
dayjs.extend(customParseFormat);

console.log('dayjs :>> ', dayjs().locale('ar').format('LLL'));
console.log('moment :>> ', moment().locale('ar').format('LLL'))
```
The output
![image](https://user-images.githubusercontent.com/23176181/142683522-79d844d0-bbe0-4c57-94a2-9055633950c3.png)

So I looked into the locales file for Arabic and if I understood correctly, on [line 57](https://github.com/iamkun/dayjs/blob/dev/src/locale/ar.js#L57), you are replacing Arabic numbers with English.
Is this expected or is there something that I'm missing here?

_Update_: 
I came across the [AdvancedFormat](https://day.js.org/docs/en/plugin/advanced-format) plugin, imported and extended, but doesn't help either.

Please correct me if I'm doing something wrong.
I just want my dates to be formatted like with the Moment.js 😃

I'm using  Dayjs: 1.10.7 with TypeScript

Regards

**Comment by cjz9032** [comment]
I found something new here: 
https://day.js.org/docs/en/plugin/preparse-postformat

**Comment by MirzaLeka** [comment]
> I found something new here: https://day.js.org/docs/en/plugin/preparse-postformat

Thank you so much! This is exactly what I was looking for.
The full solution for anyone else with the same problem:

```
import * as dayjs from 'dayjs';
import 'dayjs/locale/ar'
import * as localizedFormat from 'dayjs/plugin/localizedFormat';
import * as preParsePostFormat from 'dayjs/plugin/preParsePostFormat'

dayjs.extend(localizedFormat);
dayjs.extend(preParsePostFormat);

dayjs().locale('ar').format('LLL'); // ١٣ مايو ٢٠٢٢ ١١:٣٢
```

Closing the ticket.
