### ISSUE TITLE
timezone plugin is too slow - performance issues

### ISSUE THREAD

**Issue by JanKaifer** [iamkun/dayjs#1714]
**Describe the bug**
Using timezone plugin makes all operations on `dayjs` objects longer than `0.5ms` that is painfully slow. (Rendering table of 10x10 dates takes `100ms` just for dayjs - and even more when I do operations on those dates).

**Expected behavior**
Using timezone should be cheap enough, that I don't need to implement hacks and optimizations to avoid calls to `add`, `startOf`, or `isSame`.

**Reproduction**
If this is a supported use case (doing operations on 100+ dates synchronously with user actions), I can try to provide a reproducible benchmark.

**Information**
 - Day.js Version: 1.10.7
 - OS: OSX Montenerey
 - Browser: Chrome 96
 - Time zone: Europe/Prague

**Comment by janousek** [comment]
@JanKaifer this is because of "toLocaleString": https://github.com/iamkun/dayjs/issues/1236

**Comment by JanKaifer** [comment]
👍 i briefly checked source code before and there was some caching, but not for `toLocaleString`.

I'm closing as duplicate.
