### ISSUE TITLE
Weekday plugin doesn't work with negative numbers

### ISSUE THREAD

**Issue by EPolishchuk** [iamkun/dayjs#1721]
**Describe the bug**
According to https://day.js.org/docs/en/get-set/weekday,
if I'm put negative week day to weekday(), it should return
this day on previous week.

**Expected behavior**
const today = dayjs('2021-11-10');
today.weekday(-5);
today.weekday(5);

I'm expecting to get day for 5th of November, 2022
and 12th of November. It's last Friday and next Friday
relative to 10th of November.

But I'm getting "Wed Nov 10 2021 00:00:00 GMT+0200"
for (-5) and correct "Fri Nov 12 2021 00:00:00 GMT+0200"
for (5).

**Information**
 - Day.js Version 1.10.7
 - OS: MacOs
 - Browser Node.js 16
 - Time zone:  GMT+0200

**Comment by tomelliot** [comment]
@EPolishchuk I think you're misunderstanding the use case for weekday(). The documentation isn't super explanatory.

> if I'm put negative week day to weekday(), it should return
> this day on previous week.
This is not correct.

`today.weekday()` will return an integer representing which day of the week it is. Generally Sunday or Monday are set as day 0 (depending on locale). If Sunday is day 0, then Monday is day 1, Tuesday is 2, ... Saturday is 6. The following Sunday is day 0 again.

`today.weekday(0)` looks at `today`, works out which week `today` is in, and then returns a dayjs object that represents the start day of that week (generally either the Sunday or Monday at the start of the week).

`today.weekday(1)` returns the dayjs object of the first day of the week that `today` is in.

If you are simply looking to add or subtract dates from `today`, then look at `today.add()` and `today.subtract()`.

Here is an example of it at work:
![image](https://user-images.githubusercontent.com/3267684/144718732-5535fcde-03f4-4ba8-807a-8f3e4b110eeb.png)

**Comment by EPolishchuk** [comment]
@tomelliot you didn't mention the negative variable for the weekday plugin once in your reply =)
I'm looking to get last Friday relative to today. This plugin should've done this.

But instead, it gives some random date. Like that:

![image](https://user-images.githubusercontent.com/6026389/144720349-fd038e00-408f-4f70-8ba2-10479938c2dd.png)

![image](https://user-images.githubusercontent.com/6026389/144720364-a9f8b53b-49fc-488a-90a3-c94129dca9cc.png)

Why weekday(-7) returns Sunday, 21 of November? Why not 28th?

**Comment by tomelliot** [comment]
@EPolishchuk the dates it returns aren't random, they follow a very consistent logic. In the example screenshot you've given:

**`dayjs().weekday()`:**
`dayjs()` = 2021/12/04
`dayjs().weekday()` = The start of the week for the date 2021/12/04 = 202/12/28 (the Sunday of the week that 2021/12/04 is in).
`dayjs().weekday(-7)` = 7 days before the start of the week for the date 2021/12/04.

**Comment by EPolishchuk** [comment]
Oh. Now it's making sense.

@tomelliot thank you. Now I got it =)

**Comment by Slapbox** [comment]
> dayjs().weekday() = The start of the week for the date 2021/12/04 = 2021/12/28

This is incredibly confusing behavior which the docs fail to adequately explain: https://day.js.org/docs/en/plugin/weekday
