### ISSUE TITLE
Setting `week()` changes year

### ISSUE THREAD

**Issue by subwaymatch** [iamkun/dayjs#1751]
**Describe the bug**
Setting a week of the year using `week()` during the last week of a year (where the first day of next year is within the same week) sets a dayjs object's week to that of next year.

![image](https://user-images.githubusercontent.com/1064036/147410471-d099913e-1245-45ec-abf7-b4f43a34064f.png)

```javascript
dayjs("2021-12-26").week(35).format("YYYY-MM-DD")

# expected
'2021-08-28'

# returns
'2022-08-21'
```

Just for reference, 2021-12-26's year is 2021 and week is 1.
![image](https://user-images.githubusercontent.com/1064036/147410934-d5d384d9-973a-4f26-8d2b-0c0a76695290.png)

**Expected behavior**
Using `week()` should change the week of the year of the **current year**.

**Information**
 - Day.js Version: 1.10.7 (tested using the console in day.js.org)
 - OS: Windows 10
 - Browser: Chrome Version 96.0.4664.110
 - Time zone: GMT-06:00 CST (Central Standard Time) - America/Chicago

**Comment by claviering** [comment]
TypeError: dayjs(...).week is not a function ?

**Comment by subwaymatch** [comment]
Try extending dayjs with the `WeekOfYear` plugin.

https://day.js.org/docs/en/get-set/week

![image](https://user-images.githubusercontent.com/1064036/147502250-2798b7f9-5d43-4258-b8ae-c49d4dd54034.png)

**Comment by subwaymatch** [comment]
> TypeError: dayjs(...).week is not a function ?

Try extending dayjs with the `WeekOfYear` plugin.

https://day.js.org/docs/en/get-set/week

![image](https://user-images.githubusercontent.com/1064036/147502250-2798b7f9-5d43-4258-b8ae-c49d4dd54034.png)

**Comment by claviering** [comment]
Try `dayjs("2021-12-26").startOf('year').week(35).format("YYYY-MM-DD")`

**Comment by subwaymatch** [comment]
@claviering Thanks for the suggestion. 🙏 I've already worked around the issue using similar code but was hoping for clarifications on the expected behavior. In any case, I'll close the issue in a few days if there are no updates on this thread.
