### ISSUE TITLE
Replacing momentjs with dayjs results in frozen browser tab

### ISSUE THREAD

**Issue by ikulis-profico** [iamkun/dayjs#1762]
**Describe the bug**
We are moving our CRA React application from momentjs to dayjs. We use quite a few plugins so I have set up an adapter module that imports dayjs and used plugins, extends, and exports dayjs again. Our app is monorepo and replacement for the individual apps works fine, however, at shared modules at one point it breaks completely. The end result is a frozen browser tab. I have narrowed it down to 11 files (from 80) but since they depend on each other, it is kind of tricky to narrow it down further.  I have placed console.log()s in all of them to see at which point the freezing happens but none of them ever fire. On chrome result it is a non-responsive tab, console and network tabs are empty, on firefox I have to kill the process to close the browser.  It seems like the app freezes before it loads. I'm aware this is not much info to go on, but I honestly don't know how to debug this...
I'm hoping to at least get some insight...

What I've considered/tried:
- useEffect infinite loop (checked but it never runs in the first place)
- imported dayjs and plugins into every file one by one instead of using a common adapter
- instance passed as props to dom elements causing infinite rerender (google search came up with this)

Plugin list:

```
'dayjs/plugin/objectSupport'
'dayjs/plugin/updateLocale'
'dayjs/plugin/isSameOrBefore'
'dayjs/plugin/isSameOrAfter'
'dayjs/plugin/duration'
'dayjs/plugin/pluralGetSet'
'dayjs/plugin/isBetween'
'dayjs/plugin/localeData'
'dayjs/plugin/relativeTime'
```

**Expected behavior**
Expected app to work as before while using momentjs in best case scenario. We do expect some inconsistencies that can be ironed out.

**Information**
 - Day.js Version: 1.10.7 // We have tried other versions, including the one we successfully use on another project
 - OS: MacOS 11.6 Big Sur
 - Browser: Brave, Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64); Firefox 95.0.2 (64-bit); Regular Google Chrome

 - Time zone: GMT+1

**Comment by captrik** [comment]
We had the same problem after replacing momentjs with dayjs.  
In our case it was caused by a **const variable** not being modified by the "**add**" operator inside a loop (which worked with momentjs).

Before:  
```
const date = dayjs(new Date());
while(something) {
  ...
  date.add(1, 'd');
}
```

After:  
```
let date = dayjs(new Date());
while(something) {
  ...
  date = date.add(1, 'd');
}
```

**Comment by ikulis-profico** [comment]
Thanks, I'll check it out. Since it's not a widespread problem I was guessing it was something like that.
I'll update after checking 👍

**Comment by ikulis-profico** [comment]
Thank you very much @captrik, I have found a single two-line while loop we had in all of our code. 
I never knew it was there...
Thanks, man! 
I'm closing the issue
