### ISSUE TITLE
Getting invalid date while using 'DD/MM/YYYY' format 

### ISSUE THREAD

**Issue by DhansAL** [iamkun/dayjs#1786]
**Describe the bug**
I was trying to do this,
``` 
dayjs('31/01/2022')
```
and it gave me an `invalid date`.  However, by putting the date in `MM/DD/YYYY` format it seems to work fine.
I am not using any plugins such as `customParseFormat`.

simple replication for the issue;
``` typescript
import dayjs from "dayjs";

  console.log(
    "the current date in dd mm yyyy format is ",
    "31/01/2022",
    "the date for tommorrow is",
    {
      bug: dayjs("31/01/2022").add(1, "day"),
      working: dayjs("01/31/2022").add(1, "day"),
    }
  );
```
I am guessing `dayjs`  takes dates in only `mm/dd/yyyy` format by default.

**TECH STACK USED**

- typescript
- electron v16*
- react

**Information**
 - Day.js Version `1.10.7`
 - OS: windows10
 - Browser `chromium`
 - Time zone: `IST`

**Comment by alumni** [comment]
Same issue with `dayjs('15.10.2020', 'DD.MM.YYYY')`.

**Comment by alumni** [comment]
The `CustomParseFormat` plugin is required, see https://day.js.org/docs/en/plugin/custom-parse-format.

Not really optimal and quite confusing if you're migrating from momentjs, but one of the things that make this library minimal.

**Comment by SakuOtonashi** [comment]
> The `CustomParseFormat` plugin is required, see https://day.js.org/docs/en/plugin/custom-parse-format.
> 
> Not really optimal and quite confusing if you're migrating from momentjs, but one of the things that make this library minimal.

It works for me, thanks.
![屏幕截图 2022-03-18 160423](https://user-images.githubusercontent.com/69532233/158960915-281696cd-8065-4092-b03e-5f477142655c.png)

**Comment by Horlando-Leao** [comment]
<3 obrigado pela ajuda!

**Comment by arielmell0** [comment]
You helped a lot, thank you guys! ❤️
