### ISSUE TITLE
Parse String + Format is not working as expected. Day and month are mixed up

### ISSUE THREAD

**Issue by evilPaprika** [iamkun/dayjs#1787]
**Describe the bug**

```
import dayjs from "dayjs";

const date = dayjs("09.01.2022", "DD.MM.YYYY");

console.log("expected 9, actual: " + date.date()); // actual 1
console.log("expected 1, actual: " + (date.month() + 1)); // actual 9
```

**Playground:**
https://codesandbox.io/s/dayjs-playground-forked-r63fu?file=/src/index.js

**Expected behavior**
Day and month parsed correctly.

**Information**
 - Day.js Version 1.10.7
 - Browser chrome 97.0.4692.99
 
 
 Is there something I am missing?

**Comment by kaujaj** [comment]
You need to extend the CustomParseFormat plugin
```
import dayjs from "dayjs";
important customParseFormat from "days/plugin/customParseFormat"
//Extend
dayjs.extend(customParseFormat);

const date = dayjs("09.01.2022", "DD.MM.YYYY");

console.log("expected 9, actual: " + date.date()); // actual 9
console.log("expected 1, actual: " + (date.month() + 1)); // actual 1
```

**Comment by evilPaprika** [comment]
omg, you're right! 

![image](https://user-images.githubusercontent.com/27489220/151921012-a0b3f5c3-38f9-413b-9caa-4d3ecdf58aea.png)

I wish that there was a warning if string + format parsing was used incorrectly.
