### ISSUE TITLE
add week and  dayOfYear API?

### ISSUE THREAD

**Issue by huruji** [iamkun/dayjs#181]
for to gets the week of the year and to gets the day of year like `moment().week()` and `moment().dayOfYear()`

It's always used in projects，especially in a project which is involving statistical analysis of data.

I have written the code like this:
![image](https://user-images.githubusercontent.com/15937065/40285248-a2e4c1da-5ccc-11e8-97fc-9da1792c809a.png)

if it's ok, I will make a PR

**Comment by iamkun** [comment]
Also I tend to remove `isLeapYear`  from core to plugin.  Maybe we could group `dayOfYear `, `weekOfYear` all-together

How do you think?

**Comment by huruji** [comment]
Agreed. As a plugin is much better. How about named **advancedGet** or **getPlus**, we can add more GET APIS in this plugin.

**Comment by Imperat** [comment]
By my personal opinion it must be on core of the library. These functions are useful for some users, but if we will remove some of them for getting better library size, we have the risk to have a little piece of functional in library itself.
Also it's not good practice to remove some features which were been released without moving it into "deprecated" status. Probably we can investigate how to implement these methods as short as possible. It's needed to have a really good curiosity, but we can carefully discuss implementation and review PR's

**Comment by iamkun** [comment]
> Also it's not good practice to remove
agreed @Imperat , that's why I use 'tend to' not 'going to'.

> These functions are useful for some users

I don't agree with this.  Every function is useful for some user in some project. But we have to really decide what should be included into our core code.

**Comment by huruji** [comment]
> Probably we can investigate how to implement these methods as short as possible
> agreed @Imperat , we can do just like #185 
>
@iamkun Oh, may I ask a question? How many plugins will Dayjs have in the future? If the number is greater than 10，a plugin may be a good choice. But if the number is small, we should consider make it be in the core of Dayjs.

**Comment by iamkun** [comment]
No idea at the moment. 

What I am thinking is, we are a tiny, fast  date time lib. We can't take everything into our core code.

And if you could do a quick search on Github about moment user's public codes. You could find that the most common APIs they are using is nearly just covered in our core code.

That is to say, module && plugin should be a better solution.

**Comment by iamkun** [comment]
Then we need a vote system, laugh 😬 

> so I had to modify the source code

That's why we have a plugin design, users could extend Day.js to whatever they want.

**Comment by Imperat** [comment]
I take my previous words back after example with calendar plugins. It's really important to give developers of vue/react components, jquery plugins and other extremely light version of the library.
Finally agree with @iamkun.

**Comment by naulacambra** [comment]
@huruji you might be interested in #259 ;)

**Comment by huruji** [comment]
@naulacambra oh, yeah, nice code.

**Comment by iamkun** [comment]
:tada: This is included in version 1.8.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dayjs)
- [GitHub release](https://github.com/iamkun/dayjs/releases/tag/v1.8.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
