### ISSUE TITLE
Is dayjs alive?

### ISSUE THREAD

**Issue by codeability-ab** [iamkun/dayjs#1811]
Hello!
Is this project still maintained?

As I write this there are 367 open issues and 78 unmerged PRs. I have a PR that has been ready for merge for about 8 months.

I work for a large corporation and for us it's important that we only use actively maintained software. We're also trying to contribute if we can.

We're in the middle of migrating from moment to dayjs.  I start to feel it's not such a good idea anymore.

I hope I'm wrong because dayjs is a great library!

best regards Johan

**Comment by justingolden21** [comment]
I really hope it is alive but it really doesn't seem to be... issues and PRs keep opening and not a single one has any discussion or activity really.

**Comment by iamkun** [comment]
We are busy preparing the 2.x version. Sorry for the delay in the PR review. 

I will trigger a new minor version ASAP

**Comment by justingolden21** [comment]
Glad to hear! Thanks for the hard work 😄
