### ISSUE TITLE
dayjs in browser with Typescript does not work with esbuild when using 'import * as dayjs from "dayjs"'

### ISSUE THREAD

**Issue by francisu** [iamkun/dayjs#1814]
This is not really a bug, but a failure to follow the [documented instructions]( https://day.js.org/docs/en/installation/typescript). I'm opening (and closing) the issue in hopes that someone else with this problem can find the solution quickly.

**Describe the bug**
When, in Typescript, using 

`import * as dayjs from 'dayjs';`

And accessing dayjs in the browser, when build with esbuild, this error happens:

`TypeError: dayjs is not a function`

The solution is to change the import to be this:

`import dayjs from 'dayjs'`

**Information**
 - Day.js Version [v1.10.7]
 - OS: [MacOS]
 - Browser [Chrome 98]
 - Time zone: [GMT-07:00 DST (Pacific Daylight Time)]

**Comment by jingfee** [comment]
@francisu did you find a solution to this?
