### ISSUE TITLE
day() returns wrong value

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [iamkun/dayjs#1821]
**Describe the bug**
I'm calling day() on a date, and it returns 6 instead of 5

**Expected behavior**
Should return 5

**Information**
 - Day.js Version: 1.10.8 and 1.10.7
 - OS: Windows 
 - Browser Chrome 99.0.4844.51
 - Time zone: private
 
Line of code: `dayjs('2022-03-05T03:40:59+00:00').day()`
This one works: `parseInt(dayjs(this.date).format("DD"))`

**Comment by SunnyAureliusRichard** [comment]
This library is clearly dead, moved onto date-fns

**Comment by IgorKvasn** [comment]
I can also configrm this bug - it happens occasionaly and it is very very difficult to reproduce

**Comment by iamkun** [comment]
If you want to get the date of month, you should use dayjs().date() not dayjs().day()

<img width="743" alt="image" src="https://user-images.githubusercontent.com/17680888/163539947-5b6b6200-9878-4f8b-ba60-4adb5760242f.png">
https://day.js.org/docs/en/get-set/date
