### ISSUE TITLE
dayjs(unixTimeStamp).fromNow() is not working.

### ISSUE THREAD

**Issue by siddiquiaffan** [iamkun/dayjs#1838]
### ` fromNow ` function is not working in react.
I tried to use ` fromNow ` funciton in react but got error.

#### My Code:
```js
import dayjs from 'dayjs'

const timeGap = dayjs(unixTimeStamp).fromNow()
console.log(timeGap)
```

#### Error:
```
TypeError: dayjs__WEBPACK_IMPORTED_MODULE_3___default(...)(...).fromNow is not a function

```

**Expected behavior**
When use ` dayjs(uts).fromNow() ` it should return the time difference from the time passed till now.

**Information**
 - Day.js Version **1.11.0**
 - OS: **Windows 11**
 - Browser **99.0.4844.82**
 - Time zone: **(GMT+5:30)**

**Comment by iamkun** [comment]
fromNow requires an additional plugin `RelativeTime` to work 

https://day.js.org/docs/en/display/from-now

**Comment by siddiquiaffan** [comment]
I passed Unix time stamp. The same code worked in browser.

```js
import dayjs from 'dayjs'

const timeDiff = dayjs(1648030466723).fromNow()
console.log(timeDiff)
```
