### ISSUE TITLE
Sum two times

### ISSUE THREAD

**Issue by theprobugmaker** [iamkun/dayjs#1839]
Working with timestamps in JavaScript has been a pain in the 🍑 . I don't know if I'm doing something wrong or if it's really complicated.

I'm going to write in plain JS what I want to do and I need help making it easier on `dayjs` if possible.

JS doesn't have a `Time` format, only `Date`, so if I want to create a date with the time as `00:00:00` I would need something like this:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)
```

I can't just `new Date("00:00:00")` otherwise I get a `Invalid Date` message.

Now Imagine that I want to sum two times. `00:00:00` and `00:30:00`. If you try this:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)

const b = new Date()
b.setHours(0, 30, 0, 0)

const c = a + b
```

`c` is now a string 😞 

But let's try using an approach that seems to be the right one:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)

const b = new Date()
b.setHours(0, 30, 0, 0)

const c = new Date(a.getTime() + b.getTime())
```

The result is funny, the year is now `2074`, the hour is like `03:30:00` (it might differ for you), but not even close to what we wanted.

The only way I could make it work was doing something like this:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)

const b = new Date()
b.setHours(0, 30, 0, 0)

const c = new Date()
c.setHours(a.getHours() + b.getHours())
c.setMinutes(a.getMinutes() + b.getMinutes())
c.setSeconds(a.getSeconds() + b.getSeconds())
```

Now we have the right sum of times.

Is there a better way of doing that? Is there a way that `dayjs` can help me with that? Thank you very much.

**Comment by coclav** [comment]
> Is there a better way of doing that? Is there a way that `dayjs` can help me with that? Thank you very much.

Yes. Look at the duration plugin
