### ISSUE TITLE
 ideas about saving some bytes 

### ISSUE THREAD

**Issue by FoxDaxian** [iamkun/dayjs#185]
https://github.com/iamkun/dayjs/blob/97763f83fc84ea86ca8a3adb0ada467127a4eb0e/src/utils.js#L27

**Comment by iamkun** [comment]
Sounds interesting, any detailed information please?

**Comment by Imperat** [comment]
Good idea to write it in less amount of symbols:
```
-const isUndefined = s => s === undefined
+const isUndefined = s => s === void 0
```

**Comment by iamkun** [comment]
yes, it's shorter than undefined and save a little bytes 😁

**Comment by a13821190779** [comment]
I thought you probably got it, so. . .

**Comment by Imperat** [comment]
I had some ideas about saving some bytes.. example:
-return Utils.padStart(this.$H < 13 ? this.$H : this.$H - 12, match === 'hh' ? 2 : 1, '0')
+return Utils.padStart(this.$H < 13 ? this.$H : this.$H - 12, match.length, '0')
Let me investigate it when I will have free time ;)

**Comment by Imperat** [comment]
@a13821190779 but we need to merge it, of course. Can you open PR?)

**Comment by a13821190779** [comment]
ok @Imperat 
and I will continue to pay attention and make good suggestions. :)

**Comment by iamkun** [comment]
This is an interesting topic and I've change the title a little bit.

**Comment by huruji** [comment]
oh, a great idea. @a13821190779

**Comment by a13821190779** [comment]
@huruji 哈哈

**Comment by guisturdy** [comment]
rollup-plugin-uglify plugin will help us do this , an we already using this in `build/rollup.config.js` .

**Comment by iamkun** [comment]
@guisturdy Just noticed your comment after I merge that PR.

**Comment by waitingsong** [comment]
undefined is not save, and can be modified .
void 0 alwalys equal to the undifined  : `assert(typeof (void 0) === 'undeifned) `

**Comment by iamkun** [comment]
great discussion
