### ISSUE TITLE
locale bug

### ISSUE THREAD

**Issue by fantian007** [iamkun/dayjs#1854]
**Describe the bug**
dayjs.locale('zh-cn');
dayjs.locale(); // zh-cn
dayjs().startOf('week'); // 2022-04-10  is incorrect

**Expected behavior**
should be: 2022-04-11

**Information**
 - Day.js Version [1.11.0]
 - OS: [Mac Pro]
 - Browser [100.0.4896.75]
 - Time zone:  [China Beijing GMT+8]

**Comment by iamkun** [comment]
dayjs().startOf('week').format()

**Comment by fantian007** [comment]
> dayjs().startOf('week').format()

1. a  = dayjs().startOf('week').format();
2. a = dayjs().startOf('week'); a.format() 

为什么1,2 输出结果不一样呢？

**Comment by fantian007** [comment]
o, @arco-design/web-react 's bug, closed
