### ISSUE TITLE
🌟 Day.js 2.0 alpha preview is available

### ISSUE THREAD

**Issue by sxzz** [iamkun/dayjs#1879]
The v2 branch is here #2066 

If you have issues with v2, please comment on this issue. Please **do not comment** on irrelevant content.

## Changelog

- supports ESM

<details>

<summary>Outdated</summary>

The information is outdated, we're planning them released when v3.0.

### `2.0.0-alpha.0`

⚠️ At this very early stage, some plugins and locales have not been implemented. (PR welcomed)
⚠️ v2 has been rewritten. The compatibility of any private API is not guaranteed.

#### Breaking Change

- `dayjs.locale(preset, object, isLocal)` => `dayjs.locale(preset, isLocal, object)`
- drop support of node < 14.19.0
- importing plugins or locale (maybe will be changed in the future)
	~~`import 'dayjs/plugin/isToday'`~~ > `import 'dayjs/dist/plugin/isToday'`

#### Feature

- supports ESM
- rewrite using TypeScript

</details>

**Comment by benmccann** [comment]
I'm a maintainer of SvelteKit and contributor to Vite. We frequently see users having difficulty using Day.js with Vite. E.g. https://github.com/sveltejs/kit/issues/699. These issues seem to be caused by https://github.com/iamkun/dayjs/issues/1765.

Would you be open to a PR to convert the library to ESM for 2.0?

**Comment by sxzz** [comment]
@benmccann 2.0 supports ESM now, you can try it 
https://unpkg.com/browse/@sxzz/dayjs@2.0.0-alpha.2/dist/

**Comment by benmccann** [comment]
Thanks! Sorry for the noise. I didn't realize that as there wasn't any update on https://github.com/iamkun/dayjs/issues/1765

**Comment by vhscom** [comment]
I bumped to the v2 alpha (build 2) and it looks like some plugins are missing from the packaged bundles. Things I was looking for are `weekOfYear`, `isBetween` and `isSameOrAfter` though the `/dist/plugins` directory doesn't seem to include them. Is that a packaging error or are those being rewritten?

**Comment by sxzz** [comment]
@vhscom 

As mentioned in issue content.

> At this very early stage, some plugins and locales have not been implemented

**Comment by vhscom** [comment]
I should learn to read better. Thanks @sxzz. 😄

**Comment by nieaowei** [comment]
文档在哪里呢？

**Comment by sxzz** [comment]
> 文档在哪里呢？

旧文档也适用

**Comment by BePo65** [comment]
Perhaps it is a good idea to stay with English in this repository so that everybody can follow the discussions (but perhaps it is a good idea to use it to improve our knowledge of foreign languages - just kidding ;-)

**Comment by BePo65** [comment]
IMHO it is a good idea to redo the code base for dayjs because this way we have a chance to improve the usability for typescript and add esm support.
I build a minimal angular 13 project to get accustomed to the new version and here are my first findings:

* 'utility-types' is a 'dependencies' (not a 'devDependencies') used in 'units' (resulting in a "cannot find module 'utility-types'" when building my angular app)

* the dist folder does not contain a 'package.json' file after building dayjs.  
It is a good practice - or a requirement? -  to include a package.json to a project); even without a dependency, the generated code that will be published to npmjs, should contain a package.json to give information about the project.

* to build version 2, I fetched the next branch, deleted the package-lock.json and the node_modules folder and ran 'npm i'.  
Running 'lint' I got 745 warnings, lots of them stating "`Delete `␍`eslintprettier/prettier`".  
OK, this is an alpha version, so this is not a problem, but the character mentioned in the warning was not an ASCII character (;-), but always at the end of all lines in the referenced files (e.g. in dayjs.ts). Just as I am curious: is this an uncommon line endings character?  
Unluckily I did not find the sources of @sxzz/eslint-config-prettier and @sxzz/eslint-config-ts and their package.json did not contain a 'repository' tag (which is at least a good practice). @sxzz perhaps you could add this tag to your eslint packages?

As a next step, I will add more examples to my test project (e.g. using locales).

If you need a helping hand, I could contribute e.g. one of the plugins. As I am currently working on issue #1596, perhaps I could "migrate" the `customParseFormat` plugin.

Anyway, thanks for starting this "issue" 👍

**Comment by vhscom** [comment]
If reworking the code, a rethink on how plugins are included would be nice (especially since only two or three have been implemented). Currently my static analysis tools aren't able to determine when a particular plug-in is no longer used because each is immediately referenced by name within my codebase, e.g.:

```ts
import dayjs, { type Dayjs } from 'dayjs';
import weekOfYear from 'dayjs/plugin/weekOfYear.js';
import isBetween from 'dayjs/plugin/isBetween.js';
dayjs.extend(weekOfYear);
dayjs.extend(isBetween);
```

If I stop using `weekOfYear` or `isBetween` my static analysis tools won't tell me.

I realize the way the plug-ins are architected this goal is not easily achievable but perhaps someone knows a technique which might help address this.

**Comment by sxzz** [comment]
> IMHO it is a good idea to redo the code base for dayjs because this way we have a chance to improve the usability for typescript and add esm support. I build a minimal angular 13 project to get accustomed to the new version and here are my first findings:
> 
> * 'utility-types' is a 'dependencies' (not a 'devDependencies') used in 'units' (resulting in a "cannot find module 'utility-types'" when building my angular app)

Fixed, https://github.com/iamkun/dayjs/commit/f3088ea6143a62fdd11e23843c6d076caa4973da

> * the dist folder does not contain a 'package.json' file after building dayjs.
>   It is a good practice - or a requirement? -  to include a package.json to a project); even without a dependency, the generated code that will be published to npmjs, should contain a package.json to give information about the project.

It's a good practice, i think. The `dist` folder only contains bundle code, and other files will located in root folder. 

You can see the bundle files here. https://unpkg.com/browse/dayjs@2.0.0-alpha.2/

> * to build version 2, I fetched the next branch, deleted the package-lock.json and the node_modules folder and ran 'npm i'.
>   Running 'lint' I got 745 warnings, lots of them stating "`Delete `␍`eslintprettier/prettier`".
>   OK, this is an alpha version, so this is not a problem, but the character mentioned in the warning was not an ASCII character (;-), but always at the end of all lines in the referenced files (e.g. in dayjs.ts). Just as I am curious: is this an uncommon line endings character?

dayjs 2 uses [pnpm](https://pnpm.io/) now. Please remove `node_modules` and try `pnpm install`.

>   Unluckily I did not find the sources of @sxzz/eslint-config-prettier and @sxzz/eslint-config-ts and their package.json did not contain a 'repository' tag (which is at least a good practice). @sxzz perhaps you could add this tag to your eslint packages?

[Source code](https://github.com/sxzz/eslint-config).

OK, I will add it later.

> 
> As a next step, I will add more examples to my test project (e.g. using locales).
> 
> If you need a helping hand, I could contribute e.g. one of the plugins. As I am currently working on issue #1596, perhaps I could "migrate" the `customParseFormat` plugin.
> 
> Anyway, thanks for starting this "issue" 👍


That's great. But I don't have a lot of time to focus on open source at the moment, so your PR may not be reviewed in time, but I'll do it as soon as I can. ❤️

**Comment by sxzz** [comment]
@vhscom 
This issue is fixed in v2 branch.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/6481596/167375748-f412a863-7bef-41a3-855f-76aa6859651f.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/6481596/167375761-b7bb1690-f902-4378-b4c1-f20189da0e75.png">

**Comment by BePo65** [comment]
> That's great. But I don't have a lot of time to focus on open source at the moment, so your PR may not be reviewed in time, but I'll do it as soon as I can.

But anyway that is what I call a real fast answer 👍 

So I will create a pr for issue #1596 for dayjs v2.0 - will take a few days.

**Comment by BePo65** [comment]
Still struggling with the baseline: when building the project with `pnpm run build`, I get the following error:
```
error TS5069: Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration'
or option 'composite'.
```
although the compilerOptions in `tsconfig.src.json` and `tsconfig.node.json` contain `"declaration": true`.

Any idea why this happens or am I the only one with effect?

**Comment by sxzz** [comment]
@BePo65 Fixed.

**Comment by benmccann** [comment]
I'd love if https://github.com/iamkun/dayjs/issues/498 could be implemented on the `next` branch to get rid of the need for locale files in the same way that Luxon supports all languages simply using the built-in browser support.

**Comment by BePo65** [comment]
I am currently working on the utc and customParseFormat plugins as examples for more complex plugins.  
As IMHO the 'core' dayjs module should not contain code that is exclusively needed by a plugin, I was taking a more detailed look at the 'core' code.

During that investigation I noticed that the `manipulate.test.js` from dayjs 1.x was missing. So I added it.

But then I stumbled over the fact that in the definition of `add` and `subtract` the 'D' unit was removed from the allowed units.  
When I look at the `units.ts`, then in 'export const units' the definition `D: UNIT_DATE` is in the position for 'day of month and a few lines below we have `d: UNIT_DAY /** Day of week */`. In the [documentation](https://day.js.org/docs/en/manipulate/add) it looks like 'd' is 'day of month'.

Are the letters 'd' and 'D' just swapped in the definition of Units or do I simply not understand the unit definitions (they are quite complex and understanding the use of the different types requires some time :-).

So @iamkun can you help me understand the add / subtract signature or the definition of the units?

**Comment by Bykiev** [comment]
@BePo65, as `dayjs` is replacement for `moment` `D` should be day of month and `d` is day of week
https://momentjs.com/docs/#/displaying/format/

**Comment by ntnyq** [comment]
[Repro repo](https://github.com/ntnyq/dayjs-alpha-test)

Run `pnpm start`

```js
console.log(dayjs().format(`YYYY-MM-DD`))
console.log(dayjs().subtract(1, 'day').format(`YYYY-MM-DD`))
```
The outputs are as expected.

Run `pnpm test`

```js
console.log(dayjs().format(`YYYY-MM-DD`))
console.log(dayjs().subtract(1, 'day').format(`YYYY-MM-DD`))
```

Expression above got the same output which is weired.

Instead with dayjs@1.x everything works as expected.

**Comment by lchrennew** [comment]
I don't know where the duration plugin is...

**Comment by BePo65** [comment]
The plugin is not yet implemented. Feel free to create a pr for that 😃

**Comment by BePo65** [comment]
**Urgent question about the base branch for dayjs2.0**

@sxzz I am currently working on implementing the more complicated plugins for dayjs 2.0 ('utc', 'CustomParseFormat'); my base for this code is the branch 'next'.

Now I noticed that the name of branches changed; there is even a new branch '2.0' (using jest and not vitest).
Before I invest to much time: can you tell me,what branch contributions to dayjs 2.0 should be based on?

**Comment by sxzz** [comment]
@BePo65 Currently, we plan to release `next` branch as v3, because refactoring all code is a really heavy task. v2 will only fix supporting ESM.

**Comment by Bykiev** [comment]
> @BePo65 Currently, we plan to release `next` branch as v3, because refactoring all code is a really heavy task. v2 will only fix supporting ESM.

any news when v2 will be available?

**Comment by sxzz** [comment]
@Bykiev it has been released as `2.0.0-alpha.4`. When does it get stable? I don't know. /cc @iamkun

**Comment by sxzz** [comment]
dayjs 2 will be experimental in [Element Plus](https://github.com/element-plus/element-plus) v3 branch. When it gets stable, then we will consider making dayjs 2 into the stable branch.

**Comment by donysukardi** [comment]
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/410792/195496314-7fcddd4c-e2a6-46fe-93ec-0f5cf550507a.png">

the type for timezone plugin seems to be incorrect.. it's not registering setDefault function

**Comment by websitevirtuoso** [comment]
any changes> when will be new release?

**Comment by websitevirtuoso** [comment]
Last change in v2 has been made 8 month ago. I think no one is working on v2.

**Comment by nestle49** [comment]
Any news?

**Comment by nestle49** [comment]
R u alive?

**Comment by andorfermichael** [comment]
I hope this will continue ...

**Comment by nestle49** [comment]
@sxzz does it make sense to wait for version 2?

**Comment by damianobarbati** [comment]
any news on this? :(

**Comment by lordvcs** [comment]
bump

**Comment by g-mero** [comment]
> Is there somebody out there, who is willing to take over this project? I will gladly do my part to help improve dayjs, but only if there is a chance that prs will be reviewed and merged / rejected in a timely manner. What do you think?

I've started a project called [esday](https://github.com/g-mero/esday), which aims to reimplement all the functionality of dayjs in TypeScript. Although it's still in its early stages, I've already implemented some core features and am actively using it in my own project.

**Comment by BePo65** [comment]
@g-mero  I worked on a similar topic 2 years ago (see issue #2140 and others from me that have 'dayjs 2.0 -' in the topic.

My problem was how to implement the dayjs plugin structure in a strictly typed environment. Especially the utc plugin modifies core functionalities of dayjs and unluckily of other plugins too (especially those that implement formatting and parsing). I stopped working on this, as the owner of this project seemed not have too much time to keep on working on this new version.

So if I can help you in any way implementing this rework, give me a note. I still do like dayjs, even when it seems kind of abandoned by the owner at the moment.

**Comment by BePo65** [comment]
@g-mero this month another project keeps me quite busy, but I hope to find the time to start to add some tests for the core functionality as a minimum.

Perhaps it would be helpful to add some more information about the basis and targets of esday to the readme of esday.

Examples would be:
* which version of dayjs do you take as a basis?
* will you fix the errors based on the lots of prs in dayjs
* do you try to be 100% compatible with `moment` (what was the idea behind dayjs) or 100% compatible with dayjs (and all of its errors it still has)?
* ...

**Comment by g-mero** [comment]
@BePo65 Thanks! I'll update the README soon.

**Comment by tim436024-design** [comment]
Any news on this here, will it still be released?
