### ISSUE TITLE
like this line, why assign default params..

### ISSUE THREAD

**Issue by a13821190779** [iamkun/dayjs#188]
https://github.com/iamkun/dayjs/blob/97763f83fc84ea86ca8a3adb0ada467127a4eb0e/src/index.js#L168

**Comment by guisturdy** [comment]
```javascript
const instanceFactory = (d, m, y = this.$y) => {
  const ins = wrapper(new Date(y, m, d), this)
  return isStartOf ? ins : ins.endOf(C.D)
}
```

1. why we pass params here ?
  `instanceFactory` using `new Date(y, m, d)` create an date instance, we need this params for create an date what we need

2. why this params ?
  here we need return the last day of this year. ( in `Date` month is beginning at 0 ,so December is 11 )

**Comment by a13821190779** [comment]
I change this line https://github.com/iamkun/dayjs/blob/97763f83fc84ea86ca8a3adb0ada467127a4eb0e/src/index.js#L168,
and used dayjs().endOf can get same result.

**Comment by a13821190779** [comment]
instanceFactory(31, 11, this.$y)  => instanceFactory(31, 11)

**Comment by guisturdy** [comment]
```javascript
const instanceFactory = (d, m, y = this.$y) => {
//                             ^^^^^^^^^^^
}
```
if not passing y ,  y would be set to `this.$y`

**Comment by a13821190779** [comment]
Isn't this.$y(instanceFactory(31, 11, this.$y)  ) the same as this.$y of arguments?

**Comment by iamkun** [comment]
fixed thanks
