### ISSUE TITLE
.format() method outputs different result from its original DayJS object 

### ISSUE THREAD

**Issue by guicalmeida** [iamkun/dayjs#1880]
**Describe the bug**
Using .format() at a dayjs() date outputs a different value from its original dayjs() object:

`console.log(day.js(date))` outputs:
```
{
  M: {
    $D: 16
    $H: 20
    $L: 'pt-br'
    $M: 1
    $W: 3
    $d: 'Wed Feb 16 2022 20:00:00 GMT-0300 (Horário Padrão de Brasília)'
    $m: 0
    $ms: 0
    $s: 0
    $x: {
    }
    $y: 2022
  }
}
```
when formatted, `console.log(dayjs(date).format('DD/MM/YYYY HH:MM'))` outputs:
```
'16/02/2022 20:02'
```

**Expected behavior**
Even tough the date is correctly formatted under the dayjs() original object, it becomes wrong when formatted using the .format() method. The 20:02 output is expected to be equal to 20:00, as the $d property indicates.

**Information**
 - Day.js Version ^1.11.0
 - OS: Ubuntu 20.04.4
 - Browser: Brave 1.37.116 / Chromium: 100.0.4896.127
 - Time zone: UTC/GMT -3 hours

**Comment by iamkun** [comment]
.format('DD/MM/YYYY HH:mm')

not MM

**Comment by guicalmeida** [comment]
well... this is embarassing. Sorry!
