### ISSUE TITLE
Short timezone is `GMT+#` instead of the shortcut of the timezone name

### ISSUE THREAD

**Issue by tukusejssirs** [iamkun/dayjs#1881]
**Describe the bug & Expected behavior**

For `Europe/Bratislava` timezone, `z` should output `CEST` or `CET` (based on DST), but it outputs `GMT+2` or `GMT+1` (based on DST).

On the other hand `zzz` outputs the expected `Central European Summer Time` or `Central European Time`.

**MWE**

```js
const dayjs = require('dayjs')
const advancedFormat = require('dayjs/plugin/advancedFormat')
const utc = require('dayjs/plugin/utc')
const timezone = require('dayjs/plugin/timezone')

dayjs.extend(advancedFormat)
dayjs.extend(utc)
dayjs.extend(timezone)

dayjs.tz.setDefault('Europe/Bratislava')

const now = dayjs()

console.log(`zzz :`, now.format('zzz'))  // Central European Summer Time or Central European Time
console.log(`z :`, now.format('z'))  // GMT+2 or GMT+1; should be CEST or CET
```

**Information**
 - Day.js Version: 1.11.1
 - OS: [e.g. iOS]: Arch Linux
 - Browser: n/a
 - Time zone: GMT+02:00 CEST (Central European Summer Time)

**Comment by llibdude** [comment]
related issues https://github.com/iamkun/dayjs/issues/1154 https://github.com/iamkun/dayjs/issues/1383 I am also hoping this would work

**Comment by tukusejssirs** [comment]
Thanks, @llibdude, I couldn’t find those issues when I searched the issues.

However, I think this and #1383 are duplicates of #1154, therefore I close this issue.

Hopefully, it’ll be fixed soon. :wink:
