### ISSUE TITLE
Incorrect parsing of ISO 8601 format

### ISSUE THREAD

**Issue by dhyegocalota** [iamkun/dayjs#1885]
**Describe the bug**
I'm getting an incorrect parsing of an ISO 8601 date.

```ts
import dayjs from 'dayjs';
import dayjsPluginUTC from 'dayjs-plugin-utc';

dayjs.extend(dayjsPluginUTC);

console.log(dayjs('2015-12-24T00:00:00Z'));
```

It parses incorrectly regardless the `UTC` flag. It always parses to `22nd December 2015`.

![image](https://user-images.githubusercontent.com/5576007/167217998-366590a6-4919-4057-a14c-5de6985bfbda.png)

**Expected behavior**
I'd expect the library to parse the ISO 8601 `'2015-12-24T00:00:00Z'` correctly.

**Information**
 - Day.js Version: 1.8.11
 - `dayjs-plugin-utc` Version: 0.1.0
 - OS: Mac OSX Big Sur v11.6
 - Browser: Google Chrome Version 101.0.4951.54 (Official Build) (x86_64)
 - Time zone: [e.g. GMT-04:00 ET (Eastern Daylight Time)]

**Comment by iamkun** [comment]
'dayjs-plugin-utc' plugin is not maintained by us.

please raise an issue there, or use our built-in UTC solution.https://day.js.org/docs/en/parse/utc
