### ISSUE TITLE
Missing `ordinal` property in InstanceLocaleDataReturn & GlobalLocaleDataReturn types

### ISSUE THREAD

**Issue by R3tep** [iamkun/dayjs#1922]
There is missing `ordinal` property in `InstanceLocaleDataReturn` & `GlobalLocaleDataReturn` types

Plugin `localeData`

file [localeData.d.ts](https://github.com/iamkun/dayjs/blob/dev/types/plugin/localeData.d.ts) 

[Documentation reference](https://day.js.org/docs/en/plugin/locale-data)

**Comment by iamkun** [comment]
would you like to submit a pr to fix this?

**Comment by R3tep** [comment]
https://github.com/iamkun/dayjs/pull/1931
