### ISSUE TITLE
Locale: km key is incorrect for `Cambodia`

### ISSUE THREAD

**Issue by chantouchsek** [iamkun/dayjs#1924]
**Describe the bug**
The `km` is incorrect according to [ISO 3166-2:KH](https://en.wikipedia.org/wiki/ISO_3166-2:KH#:~:text=ISO%203166%2D2%3AKH%20is,coded%20in%20ISO%203166%2D1.)

**Expected behavior**
The `km` key, it should change to `kh`

**Information**
 - Day.js Version [1.10.4]
 - OS: [e.g. MacOS]
 - Browser [e.g. chrome 102.0.5005.61]
 - Time zone: [e.g. GMT+07:00 DST (Asia/Phnom_Penh)]

**Comment by Squls** [comment]
Pull request open at https://github.com/iamkun/dayjs/pull/1948

**Comment by chantouchsek** [comment]
It was as mistake, It should `km`
