### ISSUE TITLE
isBetween always returning false for hour comparison 

### ISSUE THREAD

**Issue by marksie1988** [iamkun/dayjs#1933]
**Describe the bug**

when using isBetween it is returning false, when should be true: 

```
	var startTime = dayjs('14:00', 'HH:mm').subtract(1, 'minute')
	var endTime = dayjs('21:00', 'HH:mm').add(1, 'minute')
	console.log(event.startDateTime)
	console.log(event.startDateTime.isBetween(startTime, endTime, 'hour', '[]'))
```

![image](https://user-images.githubusercontent.com/159166/172480112-34ab29a0-19aa-4d5e-9023-d99e21304f7f.png)

**Expected behavior**

when the time is between 14:00 and 21:00 return true 

**Information**
 - Day.js Version: 1.11.3
 - OS: Windows 11
 - Browser: Edge Version 102.0.1245.33 (Official build) (64-bit)
 - Time zone: GMT +0100 BST

**Comment by snowtreetree** [comment]
![image](https://user-images.githubusercontent.com/30932683/172971116-4a62c835-85a0-4add-a5c5-a5f42cc5079f.png)
not in same day？

**Comment by BePo65** [comment]
Sorry, but it is very hard to trace an issue, when all I got is a screenshot of what?  
What is the value of `event.startDateTime`?

I wrote a little test and all I got a what is expected:

```
const startTime = dayjs('14:00', 'HH:mm').subtract(1, 'minute')
const endTime = dayjs('21:00', 'HH:mm').add(1, 'minute')

const testTime1 = dayjs('12:00', 'HH:mm')
console.log(testTime1.isBetween(startTime, endTime, 'hour', '[]'))  // false

const testTime2 = dayjs('13:00', 'HH:mm')
console.log(testTime2.isBetween(startTime, endTime, 'hour', '[]'))  // true

const testTime3 = dayjs('15:00', 'HH:mm')
console.log(testTime3.isBetween(startTime, endTime, 'hour', '[]')) // true

const testTime4 = dayjs('21:00', 'HH:mm')
console.log(testTime4.isBetween(startTime, endTime, 'hour', '[]'))  // true

const testTime5 = dayjs('22:00', 'HH:mm')
console.log(testTime5.isBetween(startTime, endTime, 'hour', '[]'))  // false
```

**Comment by marksie1988** [comment]
The event.startDateTime is the screenshot record. 

I can't understand why it's not working, like you say, running tests by themselves works, however when using the `event.startDateTime` which is a dayjs record from a class object it fails.

**Comment by marksie1988** [comment]
> ![image](https://user-images.githubusercontent.com/30932683/172971116-4a62c835-85a0-4add-a5c5-a5f42cc5079f.png) not in same day？

I'm not comparing days, just the time

**Comment by BePo65** [comment]
Sorry, but a dayjs is always a date and time object; if you omit the date part, then the current date is used.

But when the event that creates the `event.startDateTime` is from the same day as startTime and endTime (what I suppose is he case), then I don't understand the effect.

Would you be so kind to just print the startTime and EndTime - in the best case using the format() function, so that the result could be copied in a comment (and from there to my test scenario)? Using something like this:

```
console.log(startTime.format())
console.log(endTime.format())
console.log(event.startDateTime.format())
```

**Comment by marksie1988** [comment]
```
console.log(startTime.format())
console.log(endTime.format())
console.log(event.startDateTime.format())
```

returns: 

```
2022-06-11T08:59:00+01:00
2022-06-11T10:01:00+01:00
2022-06-24T16:55:00+01:00
```

the dates will be different, although I would expect that if im setting `isBetween` to `hour` that it would only compare the hours and ignore everything else. but from what it sounds like the date is still taken into consideration?

IF that is the case then i guess i need to set the startTime and endTime with the same date as event.startDateTime to resolve this?

**Comment by BePo65** [comment]
>  that it would only compare the hours and ignore everything else

The documentation is a little bit 'compact' at this point.  
What happens is that dayjs (as moment) use all parts from `hour` up, meaning hour, day, month, year and thus ignoring minutes, seconds and milliseconds.  
If you just want to compare hours and nothing else, perhaps it would be easier to use the getter (`event.startEndTime.hour()`, if 'event.startEndTime' is a dayjs object).

What concerns your second topic
> there is no way to check the full time

You can simply compare dayjs objects `(event.startDateTime >= startTime) && (event.startDateTime <= endTime)`

**Comment by marksie1988** [comment]
Yes I think I will need to set the start time and endtime to the event.stsrtdatetime, then update the hours and minutes, then I can compare with this.

**Comment by BePo65** [comment]
Perhaps it helps to clone either startTime or endTime and set the hour and minute of this clone from event.startEndTime before using `isBetween`.

**Comment by marksie1988** [comment]
> Perhaps it helps to clone either startTime or endTime and set the hour and minute of this clone from event.startEndTime before using `isBetween`.

thanks, This is exactly what I ended up doing and it worked great :) thanks for the assistance guys
