### ISSUE TITLE
Question - how to open an issue or pull request for improving the documentation

### ISSUE THREAD

**Issue by BePo65** [iamkun/dayjs#1934]
I have several points to improve the documentation, but how should I open an issue for such a topic so that it can easily be integrated into the documentation when the idea is accepted?

Points are for example:
- list of incompatibilities with moment
- list of allowed separator characters for customParseFormat
- added information for parsing / converting to a time zone
- change the example in the documentation for setters as dayjs is immutable

**Comment by iamkun** [comment]
Feel free to open an issue in this repo.

Also, note we have a separate repo to store doc files.
https://github.com/dayjs/dayjs-website
