### ISSUE TITLE
Invalid date in the future considered valid

### ISSUE THREAD

**Issue by deraw** [iamkun/dayjs#1950]
**Describe the bug**
When validating an invalid date which is in the future, it is considered valid:

```js
dayjs('2022-13-12', 'YYYY-YY-DD').isValid() // true
dayjs('2022-13-12').isValid() // true
```

**Expected behavior**
It should return `false` since the date is invalid:

```js
new Date('2022/13/12') // Invalid Date
new Date('2022-13-12') // Invalid Date
```

**Information**
 - Day.js version: v1.11.3
 - OS: Windows 11
 - Browser: Chrome 102
 - Time zone: Europe/Paris UTC+2

**Comment by jelle-blaauw** [comment]
`dayjs('2022-13-12')` causes the 13th month to become the first one of the next year. A bit odd, perhaps. The alternative would be that the constructor fails. Anyway, the resulting date is then 2023-01-21, which is a valid date.

**Comment by BePo65** [comment]
Dayjs behaves same like moment except for a few situations, where (as an improvement) it behaves like a javascript Date object (see my [comment](https://day.js.org/docs/en/timezone/set-default-timezone) in the pull request 1914).  
This means that your 'invalid future date' is parsed with 'overflow' (like Date does). If you want the same behavior like moment, use the customParseFormat plugin with the `strict` option - this will deliver an `invalid date`.

**Comment by deraw** [comment]
> Dayjs behaves same like moment except for a few situations, where (as an improvement) it behaves like a javascript Date object (see my [comment](https://day.js.org/docs/en/timezone/set-default-timezone) in the pull request 1914). This means that your 'invalid future date' is parsed with 'overflow' (like Date does). If you want the same behavior like moment, use the customParseFormat plugin with the `strict` option - this will deliver an `invalid date`.

Thanks for your reply and your explanation, the `strict` option was exactly what I needed!

**Comment by danielrosasi** [comment]
tiver que fazer isso que resolveu o `problema.`

const convertDate = values.birthdate.split("/").reverse().join("-");

**Comment by danielrosasi** [comment]
tive que fazer essa situação que resolveu o problema.

const convertDate = values.birthdate.split("/").reverse().join("-");
