### ISSUE TITLE
ISO week off by 1 when formatting

### ISSUE THREAD

**Issue by andreasvirkus** [iamkun/dayjs#1952]
**Describe the bug**

`.format('w')` returns the wrong ISO week number (1 higher), for example

```
$ dayjs.utc('2022-06-17T00:00:00Z').format('w')
> '25'
```

However `dayjs.utc('2022-06-17T00:00:00Z').isoWeek()` correctly returns `24`

This is replicable in the console of the day.js.org docs

**Expected behavior**

`dayjs.utc('2022-06-17T00:00:00Z').format('w')` should return `24` instead of 25

**Information**
 - Day.js Version v1.11.3
 - OS: MacOS 12.4
 - Browser Brave (Version 1.39.120 Chromium: 102.0.5005.99)
 - Time zone: GMT+03:00 EEST (Eastern European Summer Time)

**Comment by jelle-blaauw** [comment]
You need to use `format('W')` (capital W) for ISO week. See [the advanced format docs](https://day.js.org/docs/en/plugin/advanced-format).

**Comment by andreasvirkus** [comment]
🤦 Thanks for noticing, that fixed it alright
