### ISSUE TITLE
[BUG] When the second parameter of diff method is year and the third parameter is true; it not days/the year duration

### ISSUE THREAD

**Issue by cn1001wang** [iamkun/dayjs#1971]
**Describe the bug**
a=dayjs('2021-04-30T10:30:30.000Z')
b=dayjs('2021-05-01T10:30:30.000Z')
b.diff(a,'y',true)==0.002777777777777777

**Expected behavior**
I hope that is 1/365=0.0027397260273972603
but you return 1/30/12=0.002777777777777777

**Information**
 - Day.js Version v1.11.3
 - OS: macOS
 - Browser chrome 100
 - Time zone: 2022-06-30T00:14:35+08:00

**Comment by Bykiev** [comment]
Hi, momentjs is calculating the diff in the same way as dayjs, here is a [demo](https://codesandbox.io/s/async-brook-0q5dhi?file=/src/index.js)
