### ISSUE TITLE
dayjs().format('Do') has an error

### ISSUE THREAD

**Issue by abner-forever** [iamkun/dayjs#1978]
TypeError: r.ordinal is not a function
<img width="516" alt="image" src="https://user-images.githubusercontent.com/40969630/177686835-a4f3df28-6ff1-4ea0-b610-beb31a34f1ba.png">

**Comment by Bykiev** [comment]
Hi, I did a sandbox and was unable to reproduce the issue, did you imported advancedFormat plugin?

```
var advancedFormat = require('dayjs/plugin/advancedFormat')
dayjs.extend(advancedFormat)
```
here is a [demo](https://codesandbox.io/s/dayjs-playground-forked-07weil?file=/src/index.js)

**Comment by abner-forever** [comment]
> Hi, I did a sandbox and was unable to reproduce the issue, did you imported advancedFormat plugin?
> 
> ```
> var advancedFormat = require('dayjs/plugin/advancedFormat')
> dayjs.extend(advancedFormat)
> ```
> 
> here is a [demo](https://codesandbox.io/s/dayjs-playground-forked-07weil?file=/src/index.js)

I import the plugin maybe my project has other error, thank you

**Comment by abner-forever** [comment]
In my peoject this.$locale has 3 properties 
<img width="448" alt="image" src="https://user-images.githubusercontent.com/40969630/177931482-6b804214-8080-4630-9e11-39757dc98c29.png">

**Comment by Bykiev** [comment]
> In my peoject this.$locale has 3 properties <img alt="image" width="448" src="https://user-images.githubusercontent.com/40969630/177931482-6b804214-8080-4630-9e11-39757dc98c29.png">

it's ok, https://github.com/iamkun/dayjs/blob/master/src/locale/en.js

**Comment by Bykiev** [comment]
It comes from [advancedFormat](https://github.com/iamkun/dayjs/blob/c0e8e6cddf671a30b0ad8130edfe607add3a4137/src/plugin/advancedFormat/index.js#L26) plugin

**Comment by Bykiev** [comment]
The same issue is described in #1891

**Comment by abner-forever** [comment]
hello 
 I got the reason I add the code

 `import localeEN from 'dayjs/locale/en'
dayjs.locale(localeEN)`

so cause the above error

**Comment by abner-forever** [comment]
@Bykiev please  look this demo   https://codesandbox.io/s/dayjs-playground-forked-9stl6w
