### ISSUE TITLE
Refresh on globally updating locale

### ISSUE THREAD

**Issue by PanArnaud** [iamkun/dayjs#1986]
Hi everyone,

I was wondering if there is a way to update all instance of dayjs around my react native app, when I change the locale using a button for e.g.

I read on [the documentation](https://day.js.org/docs/en/i18n/changing-locale), but it doesn't specify if it's possible.

Thank you

**Comment by Bykiev** [comment]
Hi, according to the docs, you should set the locale before creating instances of dayjs or recreate instances. You can achieve this by saving specified locale in browser's localStorage (or DB) and load it before creating instances of dayjs by calling `dayjs.locale('de') // use loaded locale globally`

**Comment by PanArnaud** [comment]
:( Okay, gonna see how I will manage this. Thank you !
