### ISSUE TITLE
Formatting a date from any format

### ISSUE THREAD

**Issue by subashdbc** [iamkun/dayjs#1991]
Hi,

I have a date `18_07_2022` like this, I try formatting this date to `Monday` for that when I use `momentjs` I will do like this,

`moment('18_07_2022', 'DD_MM_YYYY').format('dddd') // Monday`

but when I try with dayjs is not working, it returns with `Invalid date`

`dayjs('18_07_2022', 'DD_MM_YYYY').format('dddd') // Invalid date`

Is there any way to achieve this in dayjs?

**Comment by Bykiev** [comment]
Hi, you should use [CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format) plugin to specify the format. Here is a [demo](https://codesandbox.io/s/dayjs-playground-forked-k9j7g9?file=/src/index.js)

**Comment by subashdbc** [comment]
@Bykiev Thanks
