### ISSUE TITLE
dayjs.format() is not working properly

### ISSUE THREAD

**Issue by Prince891028** [iamkun/dayjs#2000]
**Describe the bug**
I want to add [st, nd, rd, th] to the formatted date
I used dayjs.format("MMM DD[st] YYYY");

**Expected behavior**
Jul 25th, 2022

**Current result**
Jul 25Th, 2022

[th] first letter is capitalized

**Comment by Bykiev** [comment]
Hi, `dayjs().format("MMM DD[st] YYYY");` will return `Jul 25st 2022`, not `Jul 25Th, 2022`. You can also use `Do` format. Here is a small [demo](https://codesandbox.io/s/dayjs-playground-forked-y40mdy?file=/src/index.js:214-243)

**Comment by Prince891028** [comment]
That works for me!

Thank you.
