### ISSUE TITLE
Can we use dayjs in antd datepicker?

### ISSUE THREAD

**Issue by logeshwaran1998** [iamkun/dayjs#2017]
Facing some issues with dayjs antd datepicker? is possible to use it? Thanks

If Yes. Please suggest the solution here

**Comment by Bykiev** [comment]
Hi, you can find docs here: https://ant.design/docs/react/replace-moment

**Comment by logeshwaran1998** [comment]
#[](url
![Uploading Screenshot 2022-08-08 at 11.58.52 AM.png…]()
)

**Comment by logeshwaran1998** [comment]
> Hi, you can find docs here: https://ant.design/docs/react/replace-moment
Thanks

<img width="1327" alt="Screenshot 2022-08-08 at 11 58 52 AM" src="https://user-images.githubusercontent.com/87631285/183353901-c90fca0c-97f7-44cf-a09f-d18a37aac6e2.png">
 Facing this issue while passing dayjs to datepicker.
 Is have any solution for this case? Thanks

**Comment by Bykiev** [comment]
Can you please create a small runnable demo (with codeSandbox or smth else)?

**Comment by logeshwaran1998** [comment]
@Bykiev Thanks, Issue has been fixed.

**Comment by iamkun** [comment]
please ref to Bykiev's reply

**Comment by logeshwaran1998** [comment]
@iamkun Is Dayjs have a range method? like moment().range()

**Comment by Bykiev** [comment]
> @iamkun Is Dayjs have a range method? like moment().range(). Please suggest a solution. Thanks

you can try [dayjs-range-extend](https://github.com/imwh0im/dayjs-range-extend) plugin

**Comment by logeshwaran1998** [comment]
> > @Bykiev Thanks, Issue has been fixed.
> 
> Hey, can I ask how you fixed this?

Just imported the below lines
 
import weekday from "dayjs/plugin/weekday"
dayjs.extend(weekday)
