### ISSUE TITLE
Unexpected parsing result

### ISSUE THREAD

**Issue by dimitarkolev** [iamkun/dayjs#2028]
` dayjs('94.88.74','DD.MM.YY').isValid() //true`

I don't think this is a valid date.

**Comment by Bykiev** [comment]
Hi, I was unable to reproduce tge issue. Here is a [demo](https://codesandbox.io/s/dayjs-playground-forked-bc3vo7?file=/src/index.js)

**Comment by dimitarkolev** [comment]
Never thought that **Strict parsing** is designed for that. I believe that's not only me. It will be great if it's more clear in the docs. 10x for the help.
