### ISSUE TITLE
31.12.2019 23:59 Invalid Date 

### ISSUE THREAD

**Issue by phoique** [iamkun/dayjs#2039]
**Describe the bug**
Even though I specify the format type of the incoming date in Dayjs, it gives an "Invalid Date" error. A sample date I sent is "31.12.2019 23:59" and I am sending the date format "DD.MM.YYYY HH:mm" as follows. 
Here is the full code: `dayjs('31.12.2019 23:59', 'DD.MM.YYYY HH:mm')`

**Expected behavior**
An object that does not return the Invalid Date error but returns the details of the date.

**Information**
  - Day.js Version 1.11.5
  - OS: Mac OS
  - Browser Color
  - Timezone:

**Comment by hakimio** [comment]
You need [CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format) plugin for this to work.

**Comment by phoique** [comment]
> You need [CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format) plugin for this to work. [More info](https://day.js.org/docs/en/parse/string-format)

Yes it was fixed when I added this plugin
