### ISSUE TITLE
The document description is strange.

### ISSUE THREAD

**Issue by ujuc** [iamkun/dayjs#204]
Hi,

I am currently translating in Korean.
I see strange discription.

This line, "### As JSON `.toJSON()`" section.

https://github.com/iamkun/dayjs/commit/cca50147fc9336299736ded458e05a82e6f68b69#diff-a8c2016c6f80f463e1a2006360e6abf8L364

This commit change.
```
-Serializing a `Dayjs` object to JSON, will return an ISO8601 string.
+Returns an ISO8601 string.
```

and 

https://github.com/iamkun/dayjs/commit/b1e7ec35e8f8ab7311d783bc6438a1af2b45f0eb#diff-a8c2016c6f80f463e1a2006360e6abf8L309

```
-Returns an ISO8601 string.
+Returns the `Dayjs` formatted in an ISO8601 `string`.
```

remove "Serializing a `Dayjs` objwct to JSON".
Did anything change during this period?

**Comment by iamkun** [comment]
Thanks  @ujuc for the translation. 

The final words in our Doc is just mean that you will get a formatted ISO8601 `string` from your current `Dayjs` Object.

Is this what you mean?

**Comment by ujuc** [comment]
Yes, Ok 🤣
