### ISSUE TITLE
Wrong result when using format endOf('month')

### ISSUE THREAD

**Issue by teq-vunguyen** [iamkun/dayjs#2046]
**Describe the bug**
I try to console 
`dayjs('1941/12/01').endOf('month').format('YYYY/MM/DD')` → result: `1941/12/31` (correct)
`dayjs('1943/12/01').endOf('month').format('YYYY/MM/DD')` → result: `1943/12/31` (correct)
but
`dayjs('1942/12/01').endOf('month').format('YYYY/MM/DD')` → result: `1943/01/01` (wrong)

![image](https://user-images.githubusercontent.com/67266729/187396110-d94e2f87-1a5a-4158-84aa-d85b0068d3d2.png)

**Expected behavior**
I think the result of this case will be `1942/12/31`

**Information**
 - Day.js Version [1.11.5]
 - OS: [Macbook]
 - Browser [Chrome]
 - Time zone: [GMT+07:00 (Indochina Time)]

**Comment by Bykiev** [comment]
Hi, the result is correct, because you're parsing the date in local timezone. It's seems UTC offset was different in 1943. Most likely you should parse the date with `utc` plugin

var utc = require('dayjs/plugin/utc')
dayjs.extend(utc)

dayjs.utc('1941/12/01').endOf('month');
