### ISSUE TITLE
.isValid() returns true for February 31

### ISSUE THREAD

**Issue by johnmarinelli** [iamkun/dayjs#2081]
**Describe the bug**
.isValid() returns true when using February 29/30/31, even when passing `true` as the third argument (see https://github.com/iamkun/dayjs/issues/1850#issuecomment-1101519818).  It seems like the date wraps around to March 1, 2, and 3.

**Expected behavior**
.isValid() should return false

**Information**
 - Day.js Version: dayjs@^1.11.5:
 - OS: macOS
 - Browser: Chrome Version 106.0.5249.91 (Official Build) (x86_64)
 - Time zone: CET Central EU Time

CSB: https://codesandbox.io/s/dayjs-forked-mbcrn8

**Comment by Bykiev** [comment]
It seems you're using a very old version and I can't reproduce the issue with latest version. Here is a forked [demo](https://codesandbox.io/s/dayjs-forked-7zwodg?file=/src/index.js)

**Comment by johnmarinelli** [comment]
@Bykiev you're right, sorry for reporting on an old version.  I'll close the ticket.
