### ISSUE TITLE
Invalid date when changing timezone

### ISSUE THREAD

**Issue by ablanco** [iamkun/dayjs#2137]
**Describe the bug**
I'm getting an _Invalid Date_ error when changing the timezone with dayjs.

It is related to the `src/plugin/timezone/index.js` file, line 98 and 99.

``` javascript
const target = date.toLocaleString('en-US', { timeZone: timezone })
const diff = Math.round((date - new Date(target)) / 1000 / 60)
```

`new Date` doesn't work with the output of `toLocaleString`, so that conversion doesn't work. For example:

``` javascript
const date = Date(2022, 3, 20);
date.toLocaleString("en-US", { timeZone: "Europe/Madrid" });
// This outputs: '4/20/2022, 12:00:00 AM'
new Date('4/20/2022, 12:00:00 AM');
// This returns an Invalid Date
```

This makes this code to return an _Invalid Date_:

``` javascript
dayjs(`${date} ${time}`).tz('Europe/Madrid').format('MMM D, YYYY - HH:mm');
```

**Expected behavior**
I expected the method `tz` to return a valid dayjs object in the requested timezone.

**Information**
 - Day.js Version 1.11.6
 - OS: ArchLinux
 - Browser Chrome 107 (also in Node 19.0.1)
 - Time zone: GMT+01:00 CEST

**Comment by MZPL** [comment]
The issue has already been reported here: https://github.com/iamkun/dayjs/issues/2102

**Comment by ablanco** [comment]
I looked for a similar bug, but I missed that one. Thanks!
