### ISSUE TITLE
 _dayjs.default.utc is not a function

### ISSUE THREAD

**Issue by niwococo** [iamkun/dayjs#2142]
`import dayjs from 'dayjs';

dayjs.utc()

I got : _dayjs.default.utc is not a function

dayjs version: 1.11.6

node : 12.10.0
browser: chrome
OS: MAC OS 13.0.1 

`

**Comment by BePo65** [comment]
It looks like you are using dayjs in a browser script. Did you include the utc plugin as described in the [documentation](https://day.js.org/docs/en/plugin/loading-into-browser)?

**Comment by niwococo** [comment]
Thx, I got it.
