### ISSUE TITLE
weekOfYear returns wrong result for the beginning of this year

### ISSUE THREAD

**Issue by UlrichHP** [iamkun/dayjs#2185]
**Describe the bug**
I want to get last year date which matches the same week year and day of a date with a **fr** locale.
I also noticed that these errors are no longer happening after the 30 january 2023

**Expected behavior**
Monday 02 january 2023 should be Monday 03 January 2022 but the result is : Monday 11 January 2021

You can see it here: [https://runkit.com/embed/u1xvs7v4jax7](https://runkit.com/embed/u1xvs7v4jax7)

**Information**
 - Day.js Version: v1.11.7
 - Browser: chrome 108

**Comment by UlrichHP** [comment]
Updating locale and modifying yearStart with value 3 seems to fix this issue.
But i don't understand why.

**Comment by UlrichHP** [comment]
Updating weekStart fixed it it seems...

**Comment by 1765659645** [comment]
@UlrichHP 
Is there a type error when you set yearStart?

**Comment by UlrichHP** [comment]
@1765659645 No, i didn't see any errors

**Comment by 1765659645** [comment]
> @1765659645 No, i didn't see any errors

Ok I solved it using updateLocale
