### ISSUE TITLE
the result of add and subtract is different to php

### ISSUE THREAD

**Issue by zeroone2005** [iamkun/dayjs#2186]
js code:
date = '2022-12-31'

$result = dayjs(date).add(6, 'month').subtract(1, 'day').format('YYYY-MM-DD')

$result is  2023-6-29

PHP code:
	$start = '2022-12-31';
	$end   = strtotime("{$start} +6 month -1 day");
       $result = date('Y-m-d', $end);
$result is 2023-6-30

**Comment by KronosDev-Pro** [comment]
Dayjs adds 6 months and gives the last day of the month, you don't need to subtract 1 day avec dayjs.

```js
var start = '2022-12-31';
var end = dayjs(start).add(6, 'M')
console.log(end.format('YYYY-MM-DD')); // 2023-06-30

// if subtract 1 day
var start = '2022-12-31';
var end = dayjs(start).add(6, 'M').subtract(1, 'd')
console.log(end.format('YYYY-MM-DD')); // 2023-06-29
```

**Comment by zeroone2005** [comment]
TKU
