### ISSUE TITLE
Incorrect .add() result with timezone plugin

### ISSUE THREAD

**Issue by YiJing233** [iamkun/dayjs#2195]
**Describe the bug**
Hi Team, there is a confusing problem I'm facing with:
There is a timestamp, and I transform it into a dayjs object with the timezone plugin. But when I use `.add(1, 'month')`, the result is wrong, which seems to be added too much😫.

``` javascript
dayjs.extend(utc);
dayjs.extend(timezone);

const originalDate = dayjs.tz(1669852800000, "Etc/GMT");
console.log("originalDate", originalDate);
console.log('formated OriginalDate', originalDate.toISOString());
const addedDate = originalDate.add(1, "month");
console.log("addedDate", addedDate);
console.log('formated addedDate', addedDate.toISOString());

```

And the result is:
```
originalDate M {$L: "en", $d: Thu Dec 01 2022 00:00:00 GMT+0800 (中国标准时间), $x: Object, $y: 2022, $M: 11…}

formated OriginalDate 2022-12-01T00:00:00.000Z 

addedDate  M {$L: "en", $u: true, $offset: 0, $d: Tue Jan 31 2023 00:00:00 GMT+0800 (中国标准时间), $x: Object…}

formated addedDate 2023-01-31T00:00:00.000Z 
```

Here is my codesandbox link: https://codesandbox.io/s/dank-lake-kc5w1i?file=/src/index.js

**Expected behavior**
It should be '2022-01-01T00:00:00.000Z'

**Information**
 - Day.js Version v1.11.7
 - OS: MacOS Monterey  12.5.1
 - Browser  Chrome 108.0.5359.124 (x86_64)
 - Time zone: [Asia/Shanghai / UTC +8]

**Comment by KronosDev-Pro** [comment]
I suppose this is a GMT topic is in issue #2037 and solved in pull request #2118.

## Test
```js
describe('test issue #2195', () => {
  dayjs.extend(utc)
  dayjs.extend(timezone)

  console.log(dayjs(1669852800000).tz(GMT).add(1, 'month'))
  expect(dayjs(1669852800000).tz(GMT).add(1, 'month').isSame(moment(1669852800000).tz(GMT).add(1, 'M'))).toBe(true)
})
// pass
```
result : 2023-01-01T00:00:00.000Z

**Comment by YiJing233** [comment]
Sorry that I can not get the same result as you did 😭. I cloned the repo and installed moment-timezone as Moment.js Doc said and then run this case, but the output of testing is failed.
```javascript
// timezone.test.js
import MockDate from 'mockdate'
// import moment from 'moment'
import dayjs from '../src'
import timezone from '../src/plugin/timezone'
import utc from '../src/plugin/utc'
import moment from 'moment-timezone';
// ...
it('test issue #2195', () => {
  console.log(dayjs(1669852800000).tz('GMT').add(1, 'month'))
  expect(dayjs(1669852800000).tz('GMT').add(1, 'month').isSame(moment(1669852800000).tz('GMT').add(1, 'M'))).toBe(true);
})
```

And the result is
```
    Expected value to be:
      true
    Received:
      false
 Dayjs  object '$d': 2023-01-30T11:00:00.000Z,
 Moment Moment<2023-01-01T00:00:00Z>
```
Moment is the correct result.

I have debugged the running progress of `.add()` function, and I noticed that It happened when somewhere (maybe `.clone()`?) setting the `$d` value with `.getUTCDate()` which seems got '30',

**Comment by KronosDev-Pro** [comment]
You cloned this repo https://github.com/BePo65/dayjs/tree/fix/issue2037 ?

**Comment by KronosDev-Pro** [comment]
I updated the test above

here is the feedback:
![image](https://user-images.githubusercontent.com/58274538/211577002-588cb8d2-3f36-4888-bda3-feddf88ff509.png)

**Comment by KronosDev-Pro** [comment]
Okay, have you tried with this repo [dayjs](https://github.com/BePo65/dayjs/tree/fix/issue2037) ? it fixes some timezone plugin errors

**Comment by KronosDev-Pro** [comment]
I have set the time zone on my machine to UTC+8.

With the dayjs [repo](https://github.com/iamkun/dayjs), I have the same error
while on the 'fix/issue2037' [repo](https://github.com/BePo65/dayjs/tree/fix/issue2037), I have no errors

**Comment by YiJing233** [comment]
Ok, I used the repo you said above and changed the branch to 'fix/issue2037' and the test case passed successfully.🎉

So, may I ask when will this branch be merged into main?

**Comment by KronosDev-Pro** [comment]
no worries, with pleasure.

unfortunately I don't have this information.

**Comment by KronosDev-Pro** [comment]
Hi 👋
@YiJing233 don't forget to close this issue, if is solve 😉

**Comment by zxd65885152** [comment]
Hi,
Same problem suffered.
I'd like to ask whether the pr is merged?
