### ISSUE TITLE
Cannot set properties of undefined (setting '$timezone')

### ISSUE THREAD

**Issue by TheFallenSpirit** [iamkun/dayjs#2200]
**Describe the bug**
When trying to set timezone of a dayjs object, I receive the following error:

```
/home/fallen/Desktop/Projects/Kiyo/Bot/node_modules/dayjs/plugin/timezone.js:1
TypeError: Cannot set properties of undefined (setting '$timezone')
    at M.f.tz (/home/fallen/Desktop/Projects/Kiyo/Bot/node_modules/dayjs/plugin/timezone.js:1:1275)
```

**Expected behavior**
Dayjs will set the timezone and return the time.

**Information**
 - Day.js Version: 1.11.7
 - OS: Linux (Ubuntu 20.04)
 - Browser N/A (NodeJS Backend App)
 - Time zone: From: PST (Canada/Pacific) to Etc/UTC

**Comment by KronosDev-Pro** [comment]
Hi 👋

`$timezone` is a private variable if you want.
You can use this function `dayjs().tz('America/New_York')`

don't forget to look at the [documentation](https://day.js.org/docs/en/plugin/timezone) that is made to help you in this case 😉

Hopefully this will solve your question, if so, don't forget to close this issue 😉

**Comment by TheFallenSpirit** [comment]
It appears I was not extending dayjs with the UTC plugin. Thanks for the link to the documentation that fixed my issue.
