### ISSUE TITLE
ss [plural for seconds]

### ISSUE THREAD

**Issue by diomed** [iamkun/dayjs#223]
I don't see string for plural of seconds anywhere in translations,
and I'm pretty sure if there's d, dd and m, mm, and h, hh, there 
should also be s, **ss**

**Comment by iamkun** [comment]
Yes, we have this.



s | 0-59 | The second
-- | -- | --
ss | 00-59 | The second, 2-digits
SSS | 000-999 | The millisecond, 3-digits

**Comment by diomed** [comment]
it isn't in any translate file however.
it should be, right?

**Comment by aalises** [comment]
@diomed @iamkun we don't need the 'ss' string as our RelativeTime plugin does not use it. As differentiating from 1 second to 9 seconds is quite specific, we just provide the 'few seconds' generalization for this case. See how the locales are written.

**Comment by iamkun** [comment]
@aalises I skipped the `ss` string in our RelativeTime plugin just because I want to keep the same behavior as moment.js.  However, if we think it necessary, we could add it back.

**Comment by aalises** [comment]
@iamkun I don't think it's necessary to be fair :+1:

**Comment by prantlf** [comment]
@aalises, using just `s` with "a couple of seconds" is fine. I agree, that there's no need to make it more complicated to "count the seconds".

But there is a problem with using your localization functionality in real-world applications, which are not in English. Assuming, that "*in* a couple of seconds" and "a couple of seconds *ago*" uses the same common text "a couple of seconds" is wrong. Other languages need to apply declension specific to preposition used. I opened #302 about it.

**Comment by iamkun** [comment]
discussion 302
