### ISSUE TITLE
How do you set the locale dynamically to the users locale

### ISSUE THREAD

**Issue by tgreen7** [iamkun/dayjs#2262]
I want to display the date and a placeholder that is relevant to the user's location.

```js
console.log(`dayjs.Ls[dayjs.locale()].formats.L:`, dayjs.Ls[dayjs.locale()].formats.L);
```

would work if I could set the locale to the correct locale but dayjs only loads the "en" locale by default. So how do I load in the user's locale dynamically so that the format is appropriate?

There is the function `dayjs.tz.guess()` which returns `Europe/Paris` but I would need `fr` to use in 

```js
const localeToUse = "fr"
require(`dayjs/locale/${localeToUse}`)
dayjs.locale(localeToUse);
```

also this all seems overly complicated but I don't see an easier way to do this.

**Comment by aashrafh** [comment]
You can use the `Intl.DateTimeFormat().resolvedOptions().locale` property to get the user's system locale.

```javascript
const dayjs = require('dayjs');
const utc = require('dayjs/plugin/utc');
const timezone = require('dayjs/plugin/timezone');
const advancedFormat = require('dayjs/plugin/advancedFormat');
dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.extend(advancedFormat);

async function setUserLocale() {
  const userLocale = Intl.DateTimeFormat().resolvedOptions().locale;
  try {
    await import(`dayjs/locale/${userLocale}`);
    dayjs.locale(userLocale);
    console.log(`Locale set to ${userLocale}`);
  } catch (error) {
    console.log(`Error loading locale ${userLocale}:`, error);
  }
}

setUserLocale().then(() => {
  console.log(`dayjs.Ls[dayjs.locale()].formats.L:`, dayjs.Ls[dayjs.locale()].formats.L);
});
```

The `setUserLocale` gets the user's system locale and tries to load the corresponding Day.js locale file using a dynamic import.

**Comment by tgreen7** [comment]
@aashrafh I am trying to test this locally on mac by changing my timezone.

and I am seeing this.

```js
const guess = dayjs.tz.guess()
console.log(`guess:`, guess)
const userLocale = Intl.DateTimeFormat().resolvedOptions().locale;
console.log(`userLocale:`, userLocale)
```

```
guess: Europe/Rome
userLocale: en-US
```

Why is the user locale not changing? Is there any way to test that this will work for people in internationally?
