### ISSUE TITLE
Calendar Callback Function

### ISSUE THREAD

**Issue by waveo-wangxiao** [iamkun/dayjs#2293]
**Describe the bug**
I want to use isoWeek to compare if the 2 dates are same / last / next week.
Here is my code: [jsfiddle](https://jsfiddle.net/wxlittle/sm6wt1nh/13/)
I get error "Uncaught TypeError: _this.isoWeek is not a function"

**Expected behavior**
The result of dayjs().startOf('isoWeek').calendar() should be this Monday;

**Information**
 - Day.js Version:  v1.11.7
 - OS: Mac OS
 - Browser: chrome 112
 - Time zone: GMT+08:00

**Comment by walkadaw** [comment]
Hi, @waveo-wangxiao in your case maybe you should use function declaration instead arrow function because you lost this
```
dayjs.updateLocale('en', {
	calendar: {
		lastDay: '[yesterday]',
		sameDay: '[today]',
		nextDay: '[tomorrow]',
		lastWeek (now: Dayjs) { 
			return now.isoWeek() === this.isoWeek() ? '[on] dddd' : '[last] dddd';
		 },
		nextWeek (now: Dayjs) { return now.isoWeek() === this.isoWeek() ? '[on] dddd' : '[next] dddd'; },
		sameElse (now: Dayjs) { return now.year() === this.year() ? 'l' : 'll'; },
	}
})

console.log(dayjs().startOf('isoWeek').calendar());
```
