### ISSUE TITLE
wrong locale id with relativeTime (past)

### ISSUE THREAD

**Issue by mkhuda** [iamkun/dayjs#234]
Hi, I tried dayjs using relativeTime plugin.
This is the code:

`dayjs(mytime).fromNow()`,

But the result is `yang lalu 3 jam` (for example), it should be ` 3 jam yang lalu` for Indonesian.

Looks like here:
https://github.com/iamkun/dayjs/blob/2814f2ffc15c398cdf1326dedaa43c363d2b2a5f/src/locale/id.js#L9

Thank you

**Comment by iamkun** [comment]
THX, will check this.
