### ISSUE TITLE
README has invalid HTML for badges

### ISSUE THREAD

**Issue by jamiehaywood** [iamkun/dayjs#2343]
**Describe the bug**
The readme files contains [html with no closing tags](https://github.com/iamkun/dayjs/blob/b3624de619d6e734cd0ffdbbd3502185041c1b60/README.md?plain=1#L21) which cannot be parsed by Docusaurus.

**Expected behavior**
READMEs contain valid HTML

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
fixed thanks
