### ISSUE TITLE
Cannot read property 'weekdays' of undefined

### ISSUE THREAD

**Issue by cobola** [iamkun/dayjs#235]
````
log.info(dayjs().format('YYYYMM'))

 TypeError: Cannot read property 'weekdays' of undefined
      at h.d.format (node_modules/dayjs/dayjs.min.js:1:4622)
      at Context.<anonymous> (test/tool_test.js:43:24)

````

**Comment by iamkun** [comment]
@cobola looks ok in my browser environment.

Any detailed information? node, browser version, locale setting?

Or maybe a online demo with jsfiddle.net

**Comment by iamkun** [comment]
I tried node v8.9.4, still fine.

Have you changed your Day.js global locale setting? like `dayjs.locale()` with a wrong locale?

**Comment by cobola** [comment]
i got it , the default locale is undefined 
i need set dayjs.locale('en')

then it works

i need require('dayjs/locale/zh-cn') , if use another locale 

many thanks

**Comment by iamkun** [comment]
@cobola glad to hear your problem solved. However, the default locale should be `en` English not `undefined`.

I think there might be still some problem with your usage?

**Comment by cobola** [comment]
i got ```undefined``` locale with
```
dayjs().format('YYYY')
```
first time 

but i cannot repeat it  now 
the default locale is ```en```

**Comment by iamkun** [comment]
@cobola 
All right, great. Let us know if this bug reproduced.

**Comment by joetidee** [comment]
Same issue here.I have v1.8.6 installed.

Usage:
```
import dayjs from "dayjs";
const getFormattedDateFromString = (dateStr, format) => dayjs(dateStr).format(format);
...
const dateId = getFormattedDateFromString("2019-01-31T15:00:00Z", "YYYYMMdd");
```

**Comment by iamkun** [comment]
@joetidee Tested ok. A reproduction link or GitHub repo, please?

**Comment by joetidee** [comment]
ok, my issue was because I was passing `en-gb` to `dayjs.locale` rather than `en`.
