### ISSUE TITLE
can provoide the commonjs require useage

### ISSUE THREAD

**Issue by iamwelk** [iamkun/dayjs#239]
I want to use dayjs in wechat mini-program, but it use commonJS grammar，and I can't find how to use it with require. 
Is there any way to use this in mini-program or provide a another commonJS module?

**Comment by iamkun** [comment]
@iamwelk CommonJS require is available out of the box. Just `var dayjs = require('dayjs')`.

However, as far as I know, wechat mini-program doesn't support npm module, so you might have to download `dayjs.min.js` to your project folder manually then do the require. (Or use some other mini-program framework that supports npm module)

**Comment by iamwelk** [comment]
I know~ thank you!
