### ISSUE TITLE
formatting on `dd` gives offset from UTC in stead of day name

### ISSUE THREAD

**Issue by jelmerdemaat** [iamkun/dayjs#240]
Given the code:

```js
dayjs('2018-08-25').format('dd')
```

The expected result is:

```
Sa
```

The given result is:

```
+0200
```

See a minimal reproduction of the issue here:
https://codepen.io/jelmerdemaat/pen/mKmxVR?editors=1010#

The same goes for formatting on 'ddd'. I can't find anything I'm doing wrong, so this seems like a bug.

**Comment by iamkun** [comment]
@jelmerdemaat Seems a bug with cdnjs. The package version froze at 1.5.24 vs 1.6.7 now.

Try the latest version of Day.js here `<script src="https://unpkg.com/dayjs"></script>`

Maybe we should submit a bug report to cdnjs as well.

**Comment by jelmerdemaat** [comment]
Thanks! It works in the newer version. 👍
