### ISSUE TITLE
Nth Day of the Month, eg, 2nd Saturday of the month

### ISSUE THREAD

**Issue by edjw** [iamkun/dayjs#241]
It would be great if it was possible to use this to get the nth day of the month. For example, for the second Saturday of the month something like this `.nthDayOfMonth(Saturday, 2)` would be really useful for community groups, churches, choirs etc

**Comment by iamkun** [comment]
Sounds interesting. 

Seems moment.js doesn't has some similar APIs like this `nthDayOfMonth `?

**Comment by edjw** [comment]
Not in the core of Moment. There's a plugin called moment-recur but it hasn't been  maintained in quite a while.

https://github.com/c-trimm/moment-recur

**Comment by iamkun** [comment]
We might could implement this as a plugin as well.

**Comment by naulacambra** [comment]
It would interesting to implement all moment-recur functionality? Or split it among several plugins?

**Comment by iamkun** [comment]
@naulacambra It would be great. But a large project.

**Comment by rdewolff** [comment]
Sounds interesting! Any news about that recurring function?

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by kubanac95** [comment]
Was looking for this when I found the following library. Maybe someone still needs it :)

https://github.com/FraserHamilton/dayjs-recur

**Comment by edjw** [comment]
From the readme of `dayjs-recur`...

```js
// A weekOfMonthByDay interval is available for combining with
// the daysOfWeek to achieve "nth weekday of month" recurrences.
// The following matches every 1st and 3rd Thursday of the month.
// (Note this cannot be combined at the dayjs with every(x).months() expression) 
const cal = dayjs.recur().every("Thursday").every([0, 2]).weeksOfMonthByDay();
```
