### ISSUE TITLE
the "L" date format for most locales should be "D/M/YYYY" rather than "DD/MM/YYYY"

### ISSUE THREAD

**Issue by francisu** [iamkun/dayjs#2446]
Currently a date with leading zeros cannot be parsed with many locales, for example, en-au does not recognize '1/7/2002', but would recognize '01/07/2002'.

I don't see why we don't use the single "D" or "M" in all of these cases to be more permissive.

If you agree, I would be happy to provide a PR.

**Comment by Pareder** [comment]
@francisu You can use `UpdateLocale` plugin (https://day.js.org/docs/en/plugin/update-locale) with such configuration:
```
dayjs.updateLocale('en', {
    formats: {
        L: 'M/D/YYYY'
    }
})
```
Instead of `en` pass the locale you are using.

**Comment by francisu** [comment]
> @francisu You can use `UpdateLocale` plugin (https://day.js.org/docs/en/plugin/update-locale) with such configuration:
> 
> ```
> dayjs.updateLocale('en', {
>     formats: {
>         L: 'M/D/YYYY',
>     },
> })
> ```
> 
> Instead of `en` pass the locale you are using.

Thanks so much; I know how I can work around this, my question is: would it be better to use 'M/D/YYYY' (or the reverse) as the default? I don't see a downside to doing this and think it would save others trouble.

**Comment by Pareder** [comment]
You can use `l` format, it is exactly `M/D/YYYY`, so there is no need to create two same formats.

**Comment by francisu** [comment]
> You can use `l` format (https://day.js.org/docs/en/display/format#list-of-localized-formats), it is exactly `M/D/YYYY`, so there is no need to create two same formats.

But the 'l' format does not exist in https://github.com/iamkun/dayjs/blob/dev/src/locale/en-au.js for example. Am I missing something?

**Comment by Pareder** [comment]
If it is not specified in locale config the default value (which is `D/M/YYYY`) will be used, for more details view this line of code https://github.com/iamkun/dayjs/blob/dev/src/plugin/localizedFormat/utils.js#L16.
