### ISSUE TITLE
timezone plugin guess function returns undefined in Chrome on mac Sonoma

### ISSUE THREAD

**Issue by montanaflynn** [iamkun/dayjs#2448]
When using the timezone plugin's `guess()` function it returns `undefined`, but only on my desktop mac using chrome. 

It works fine in Safari and iOS. 

```js
dayjs.extend(dayjsutc);
dayjs.extend(dayjstimezone);
console.log(dayjs.tz.guess());
// undefined
```

Here's a reproduction of the issue: https://jsbin.com/lequtegoda/1/edit?html,output

**Expected behavior**

I would expect the correct timezone string such as `Europe/London` as it does in other browsers.

**Information**
 - Day.js Version [e.g. v1.11.9]
 - OS: macOS 14.0 (23A339)
 - Browser: Google Chrome Version 116.0.5845.187 (Official Build) (arm64)
 - Time zone: London, UK (GMT+1)

**Comment by HaoWang201** [comment]
Having the same issue on Sonoma Chrome 117, but works on Safari.

**Comment by ricpan** [comment]
My timezone: America/Edmonton, getting America/Denver

Issues:
- Chrome version 117.0.5938.132
- Firefox developer 119.0b2 (64-bit)
- Microsoft edge 117.0.2045.40

Working
- Safari

**Comment by mse283** [comment]
This looks like it might be a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1487403

**Comment by ricpan** [comment]
I just tested on Android (Chrome), and it works as expected.
Chrome version: 117.0.5938.60, Android 11

**Comment by montanaflynn** [comment]
> My timezone: America/Edmonton, getting America/Denver
> 
> Issues:
> 
> * Chrome version 117.0.5938.132
> * Firefox developer 119.0b2 (64-bit)
> * Microsoft edge 117.0.2045.40
> 
> Working
> 
> * Safari

Seems like a completely unrelated issue, I suggest making your own issue.

**Comment by wahyubaskara** [comment]
Having the same issue

**Comment by buffet-player** [comment]
Can we deal the problem now? @montanaflynn

**Comment by brunocoelho** [comment]
[dayjs.tz.guess()](https://github.com/iamkun/dayjs/blob/dev/src/plugin/timezone/index.js#L143) is working properly in FF and Safari, chrome seems to be the problem. I only noticed it after upgrading to macOS Sonoma.

**Comment by phugodness** [comment]
> This looks like it might be a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1487403

same for me another bug to watch for
https://bugs.chromium.org/p/chromium/issues/detail?id=1487920

**Comment by brunocoelho** [comment]
It looks like it's working again.
`Chrome version 118.0.5993.88 (Official Build) (arm64)`
`MacOS Sonoma version 14.0`

![image](https://github.com/iamkun/dayjs/assets/827445/d909a8ec-3077-43b5-b049-771edc0560bd)

**Comment by buffet-player** [comment]
> It looks like it's working again. `Chrome version 118.0.5993.88 (Official Build) (arm64)` `MacOS Sonoma version 14.0`
> 
> ![image](https://user-images.githubusercontent.com/827445/277758806-d909a8ec-3077-43b5-b049-771edc0560bd.png)

how about edge in mac？is it fixed ？

**Comment by montanaflynn** [comment]
Seems like it's working fine for me now using latest chrome on the latest Sonoma versions so I'll close this issue.
