### ISSUE TITLE
cannot set day

### ISSUE THREAD

**Issue by bazo** [iamkun/dayjs#246]
have code like this

```js
    const selected = dayjs('2018-06');
    const days = [];
    for (let day = 1; day <= selected.daysInMonth(); day++) {
		const current = selected.set("day", day);
		console.log(current.format("DD")); //always 01
    }
````

the day part of current is always 1. if i set month or year, it works ok

**Comment by bazo** [comment]
ok, it needs to be "date"

**Comment by iamkun** [comment]
@bazo 
Yes. 
According to moment.js.
`date` => Date of Month
`day` => Day of Week 

We are doing the same.
