### ISSUE TITLE
hey,  have you consider add the startOf('season') feature

### ISSUE THREAD

**Issue by xuxiaoyuspallow** [iamkun/dayjs#248]

**Comment by huruji** [comment]
It's useful for some users. As a plugin may be a better choice.

**Comment by huruji** [comment]
In this plugin，we can add a new unit named `season`

**Comment by iamkun** [comment]
Agreed.

@xuxiaoyuspallow something like this?
Season | Start date | End date
-- | -- | --
Summer | 1 December | 28 February
Autumn | 1 March | 31 May
Winter | 1 June | 31 August
Spring | 1 September | 30 November

**Comment by raymondtm** [comment]
Is there any problem of the Southern Hemisphere? How about 'quarter'?

**Comment by iamkun** [comment]
Yes @raymondtm is right

**Comment by xuxiaoyuspallow** [comment]
@iamkun yep,  it may useful sometimes, like "season" and "quarter"

**Comment by iamkun** [comment]
a plugin adds `dayjs().startOf('quarter')` might be a good choice.

**Comment by xuxiaoyuspallow** [comment]
@iamkun I think I find a right way to process it. Thanks for your elegant package, it save me a lot of time.

**Comment by iamkun** [comment]
@xuxiaoyuspallow Great and it would be nice if you could share your code with us.

**Comment by xuxiaoyuspallow** [comment]
@iamkun well, it is just some hardcode thing, using the startOf('year') and add api.
