### ISSUE TITLE
Add is broken.

### ISSUE THREAD

**Issue by Aloento** [iamkun/dayjs#2485]
**Describe the bug**

```js
    const a = dayjs().add(0.5, "year").unix();
    const b = dayjs().unix();
    const c = a === b;
```

![image](https://github.com/iamkun/dayjs/assets/11802769/ea4bbfd3-a82c-4557-b46d-0738b4d4fd8d)

**Expected behavior**
const c is false

**Information**
 - Day.js Version 1.11.10
 - OS: Win11
 - Browser Edge Newest
 - Time zone: +1

**Comment by IITII** [comment]
> When decimal values are passed for days and weeks, they are rounded to the nearest integer before adding.

* It look like just using `Math.floor` for `year` unit. You can using [durations](https://day.js.org/docs/en/durations) for replace

<img width="588" alt="image" src="https://github.com/iamkun/dayjs/assets/33705067/0d79f049-e466-4841-aaa8-f35bfd2f3c1f">
