### ISSUE TITLE
dayjs.tz not working with nextjs / React Server Components

### ISSUE THREAD

**Issue by fmacherey** [iamkun/dayjs#2504]
**Describe the bug**
dayjs.tz does not work fully with nextjs app folder.
We have a custom react hook, which is doing some calculations with dayjs. It look like other functions from dayjs, e.g. `dayjs().weekday` work fine, but `dayjs().tz("Europe/Berlin")` throws a javascript error:
`hooks.ts:61 > Uncaught TypeError: dayjs__WEBPACK_IMPORTED_MODULE_0___default(...)(...).tz is not a function`

Even that I used "use client" directive in my custom hook, the error occurs. I suppose this happens, how nextjs bundles/imports the modules. I think the bug is originating from something inside dayjs, which is using browser-specific APIs. 

**Expected behavior**
dayjs.tz and all other dayjs methods should work in React Server Components (RSC) / nextjs.

**Information**
 - Day.js Version 1.11.10
 - OS: macos sonoma
 - Browser chrome 119
 - nextjs 14.0.0, react 18.2.0
 - Time zone: GMT+1

**Comment by fmacherey** [comment]
I had missed to setup the needed plugins. So everything works fine now.

**Comment by eungyeole** [comment]
@fmacherey  Can I ask how you solved it?

**Comment by fmacherey** [comment]
@eungyeole you need to add all plugins as you would in your application, when using dayjs. So for me, I am doing this in the setupTests file for jest, that I extend all needed plugins:
```
dayjs.locale(de);
dayjs.extend(utc);
dayjs.extend(tz);
dayjs.extend(isToday);
dayjs.extend(isTomorrow);
dayjs.extend(isBetween);
dayjs.extend(weekday);
```
