### ISSUE TITLE
Shortname format not working

### ISSUE THREAD

**Issue by eugenioclrc** [iamkun/dayjs#252]
Formatting date to shortnames its not working properly;

dayjs().format('ddd');
EXPECTED: "Mon", "Tue", etc
RETURNS: "-0300" (my timezone??)

**Comment by iamkun** [comment]
@eugenioclrc  try the latest version 😁

**Comment by eugenioclrc** [comment]
im using the 1.6.9 installed by npm

**Comment by iamkun** [comment]
@eugenioclrc 1.6.9 works ok and returns "Mon" in my browser. Can you please upload your code or supply  a online demo with jsfiddle etc. Thanks.

**Comment by eugenioclrc** [comment]
@iamkun  Fixed in version 1.6.10
