### ISSUE TITLE
Cannot read property 'mm' of undefined

### ISSUE THREAD

**Issue by lamartire** [iamkun/dayjs#255]
When using `ru` locale `dayjs().fromNow()` throws this error.

**Comment by iamkun** [comment]
@lamartire Yes. And it would be nice if you could add the Russian locale `fromNow` with a pull request. THX

**Comment by lamartire** [comment]
@iamkun here we go :smiley_cat:

**Comment by lamartire** [comment]
@iamkun so, when will be next release?

**Comment by iamkun** [comment]
@lamartire Cool, releasing.

**Comment by lamartire** [comment]
🙌
