### ISSUE TITLE
dayjs("2024-01-12 16:48:26 043", "YYYY-MM-DD HH:mm:ss SSS") doesn't work

### ISSUE THREAD

**Issue by DrMuda** [iamkun/dayjs#2554]
**Describe the bug**
dayjs("2024-01-12 16:48:26 043", "YYYY-MM-DD HH:mm:ss SSS") doesn't work
moment("2024-01-12 16:48:26 043", "YYYY-MM-DD HH:mm:ss SSS") works

**Expected behavior**
I hope to get a date with milliseconds， but get Invalid Date

**Information**
 - Day.js Version: Using the browser console on your website
 - Browser: edge 120.0.2210.133
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

<img width="623" alt="image" src="https://github.com/iamkun/dayjs/assets/73845204/622f75cf-09f1-4391-b6a8-d33bc6094ee1">

**Comment by Rolaka** [comment]
![image](https://github.com/iamkun/dayjs/assets/839943/dca50850-9317-4539-9153-e29004192f79)
no problem found, has Date protoype been modified?

**Comment by DrMuda** [comment]
> ![image](https://private-user-images.githubusercontent.com/839943/297241011-dca50850-9317-4539-9153-e29004192f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzU2MjMsIm5iZiI6MTcwNTk3NTMyMywicGF0aCI6Ii84Mzk5NDMvMjk3MjQxMDExLWRjYTUwODUwLTkzMTctNDUzOS05MTUzLWUyOTAwNDE5MmY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMjAyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzQwZjQ0M2NiNTVkMDQ3MmM0YzA4ZDZlY2JmNTEyYjdjZGJkMjcxNDgzMzNjY2IyMWMwYTEwOGU5YWM4NDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g9grniq1PC1IBaLXGem3Aebx1TG6ZUFgeAcYFeZ3pt4) no problem found, has Date protoype been modified?

I haven't modified the Date prototype, and I'm not sure why it has also returned to normal on my computer.
