### ISSUE TITLE
Incompatible parts with moment api

### ISSUE THREAD

**Issue by yoyo837** [iamkun/dayjs#2559]
**Describe the bug**
The following methods are available in `moment` but not defined in `dayjs`
```js
.years()
.months()
.days()
.hours()
.minutes()
.seconds()
.milliseconds()
```

**Expected behavior**
method is not a function 

**Information**
 - Day.js Version 1.11.10
 - OS macOS 14
 - Browser Chrome 120

**Comment by johannox** [comment]
They are supported if you use the PluralGetSet plugin: https://day.js.org/docs/en/plugin/plural-get-set

> PluralGetSet adds plural getter & setter APIs .milliseconds(), .seconds(), .minutes(), .hours(), .days(), .weeks(), .isoWeeks(), .months(), .quarters(), .years(), .dates().

**Comment by yoyo837** [comment]
> They are supported if you use the PluralGetSet plugin: https://day.js.org/docs/en/plugin/plural-get-set
> 
> > PluralGetSet adds plural getter & setter APIs .milliseconds(), .seconds(), .minutes(), .hours(), .days(), .weeks(), .isoWeeks(), .months(), .quarters(), .years(), .dates().

Okay, I found it, not just this, but many other things, all in the plugins.
