### ISSUE TITLE
.add(1, 'month) also changes the day, not just the month

### ISSUE THREAD

**Issue by henriqueleite42** [iamkun/dayjs#2564]
**Describe the bug**
Day is changed to the first day of the month
```js
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone';

dayjs.extend(utc);
dayjs.extend(timezone);

dayjs.tz.setDefault('UTC');

dayjs.tz('2024-01-15'),add(1, 'month').toISOString()

// Expected: '2024-02-15T00:00:00.000Z'
// Actual result: '2024-02-01T00:00:00.000Z'
```

**Information**
 - Day.js Version 1.11.10
 - OS: Ubuntu 22.04.3 LTS
 - Browser Node 20
 - Time zone: GMT-03:00, but should use UTC

**Comment by henriqueleite42** [comment]
Sorry, my mistake, I was seeing the wrong result

**Comment by buza-me** [comment]
You have a comma in your example. I wonder if you have ```add()``` defined somewhere. I just tested it out of curiosity in Node 20 on Windows and it works as expected.

**Comment by thadeucity** [comment]
The bug is real and it happens for `.add(1, 'year')` too
```js
const initial = dayjs.tz('2024-02-15').format('YYYY-MM-DD') // 2024-02-15
const expected= dayjs('2024-02-15').add(1, 'year').format('YYYY-MM-DD') // 2025-02-15
const result = dayjs.tz('2024-02-15').add(1, 'year').format('YYYY-MM-DD') // 2025-02-01
```

The bug only affects the day
