### ISSUE TITLE
Parse format DD-MM-YYYY is interpreted as MM-DD-YYYY

### ISSUE THREAD

**Issue by voliva** [iamkun/dayjs#2579]
**Describe the bug**
Calling `dayjs(dateStr, 'DD-MM-YYYY')` seems to behave the same way as `dayjs(dateStr, 'MM-DD-YYYY')`

**Expected behavior**
It should parse the date as day - month - year

**Information**
 - Day.js Version 1.11.0
 - OS: Windows 11
 - Browser Chrome 121
 - Time zone: CET

Reproduction sandbox: https://codesandbox.io/p/sandbox/dayjs-issue-6f34h2?file=%2Fsrc%2Findex.ts%3A13%2C44
```
dayjs("1990-11-20", "YYYY-MM-DD") 1990-11-20T00:00:00+01:00
dayjs("11-20-1990", "MM-DD-YYYY") 1990-11-20T00:00:00+01:00
dayjs("20-11-1990", "DD-MM-YYYY") Invalid Date
dayjs("20-01-1990", "DD-MM-YYYY") Invalid Date
dayjs("10-01-1990", "DD-MM-YYYY") 1990-10-01T00:00:00+01:00
```

**Comment by adlanarifzr** [comment]
@voliva You would need to use the `customParseFormat` plugin for this kind of parsing.

```typescript
import customParseFormat from 'dayjs/plugin/customParseFormat';
dayjs.extend(customParseFormat);
```

**Comment by voliva** [comment]
Thank you @adlanarifzr , I didn't see the big message on https://day.js.org/docs/en/parse/string-format

> This requires the `CustomParseFormat` plugin to work
