### ISSUE TITLE
startOf('week').format('YYYY-MM-DD') not work

### ISSUE THREAD

**Issue by artiely** [iamkun/dayjs#261]
it is not work `dayjs().startOf('week').format('YYYY-MM-DD')` or `dayjs().startOf('isoWeek').format('YYYY-MM-DD')`

**Comment by iamkun** [comment]
@artiely https://runkit.com/embed/7q6iei0v6p89   OK to me. And we don't have `startOf('isoWeek')` at the moment

**Comment by artiely** [comment]
My version is too old，I will update

**Comment by SublimeCT** [comment]
```javascript
import Day from 'dayjs'

const getWeekDay = ({d = Day()} = {}) => {
        let start
        let end
        if (d.day() === 0) {
            start = d.subtract(6, 'day')
            end = d
        } else {
            start = d.subtract(d.day() - 1, 'day')
            end = start.add(6, 'day')
        }
        return {start, end}
}
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
