### ISSUE TITLE
Adding a day to April 1st not working

### ISSUE THREAD

**Issue by alebenson** [iamkun/dayjs#262]
I'm trying to add 1 day from the first of April to get Monday, 02 Apr 18, and I get the same date.

```javascript
console.log( dayjs("2018-02-01").add(0,"day").format("dddd, DD MMM YY") ) // Thursday, 01 Feb 18
console.log( dayjs("2018-02-01").add(1,"day").format("dddd, DD MMM YY") ) // Friday, 02 Feb 18
console.log( dayjs("2018-03-01").add(0,"day").format("dddd, DD MMM YY") ) // Thursday, 01 Mar 18
console.log( dayjs("2018-03-01").add(1,"day").format("dddd, DD MMM YY") ) // Friday, 02 Mar 18

console.log( dayjs("2018-04-01").add(0,"day").format("dddd, DD MMM YY") ) // Sunday, 01 Apr 18
console.log( dayjs("2018-04-01").add(1,"day").format("dddd, DD MMM YY") ) // Sunday, 01 Apr 18 *
console.log( dayjs("2018-04-01").add(2,"day").format("dddd, DD MMM YY") ) // Monday, 02 Apr 18

console.log( dayjs("2018-05-01").add(0,"day").format("dddd, DD MMM YY") ) // Tuesday, 01 May 18
console.log( dayjs("2018-05-01").add(1,"day").format("dddd, DD MMM YY") ) // Wednesday, 02 May 18
console.log( dayjs("2018-06-01").add(0,"day").format("dddd, DD MMM YY") ) // Friday, 01 Jun 18
console.log( dayjs("2018-06-01").add(1,"day").format("dddd, DD MMM YY") ) // Saturday, 02 Jun 18
```

**Comment by iamkun** [comment]
@alebenson Seems ok to me. https://runkit.com/embed/szquqbtnx2rh

Any other information you could provide?

**Comment by alebenson** [comment]
@iamkun your sample is working for us but when we try to do the same on RunKit, we get the same output as the first message.

https://runkit.com/embed/r9j51zfzg7kr
node v8.11.3
dayjs 1.6.10

```javascript
var dayjs = require("dayjs")
console.log(dayjs("2018-04-01").add(1,"day").format("dddd, DD MMM YY")) // Sunday, 01 Apr 18
console.log(dayjs("2018-04-01").add(2,"day").format("dddd, DD MMM YY")) // Monday, 02 Apr 18
```

https://jsfiddle.net/pxw7gumo/
using: https://cdn.jsdelivr.net/npm/dayjs@1.6.10/dayjs.min.js

```javascript
console.log(dayjs("2018-04-01").add(1,"day").format("dddd, DD MMM YY")) // Sunday, 01 Apr 18
console.log(dayjs("2018-04-01").add(2,"day").format("dddd, DD MMM YY")) // Monday, 02 Apr 18
```

**Comment by iamkun** [comment]
@alebenson Interesting. Your timezone, DST please?

**Comment by alebenson** [comment]
@iamkun yes, here > https://www.timeanddate.com/time/change/new-zealand/auckland

**Comment by alebenson** [comment]
Hello @iamkun any update on this or a workaround?

**Comment by prantlf** [comment]
@alebenson, you could use the raw `Date` with `setUTCDate` as a workaround. If you want a workaround for `dayjs` instances, you could need to [check, if the day really changed and add 2 days, if it did not](https://github.com/iamkun/dayjs/issues/329#issuecomment-419741692). Clumsy, isn't it ;-) You can also try PRs #168 and #326 as a cleaner workaround.

Otherwise you case appears to be the same, as [I commented about](https://github.com/iamkun/dayjs/issues/329#issuecomment-420929964) at the issue #329 and similar to the others, who assume, that there's something like a "date-only mode" (#262, #249 and #74).

**Comment by iamkun** [comment]
@alebenson You may could try v1.7.7 and check if this issue is fixed. THX.
