### ISSUE TITLE
希望支持yyyy和dd

### ISSUE THREAD

**Issue by cweijan** [iamkun/dayjs#2622]
从element-ui转到element-plus, 原先的yyyy-MM-dd失效了, 必须写成YYYY-MM-DD, 但是年和日小写的yyyy和dd是标准通用规范, 希望能支持.

不仅仅是旧版本element-ui, 很多语言如Java的日期规范也是如此.

**Comment by alexlee002** [comment]
yyyy, YYYY的含义是不一样的
DD好像不是规范用法

**Comment by alexlee002** [comment]
dayjs对年份用的是YYYY， 这个是错误的， 正确的应该是yyyy

**Comment by yzw20110902** [comment]
希望支持下，能和element 保持一致吧，，现在两边不一致真是麻烦事

**Comment by alexlee002** [comment]
这个库感觉没人维护了，我现在是自己项目中使用自己定制的了~~~  反正我也不追求开源和跨平台
