### ISSUE TITLE
Can't input negative years

### ISSUE THREAD

**Issue by willismonroe** [iamkun/dayjs#2636]
**Describe the bug**
I'm trying to work with negative years in a mermaid-js gantt chart but tracing down their date parsing lead me to dayjs. Right now I can get a negative year to display by subtracting years from a positive year date, but there seems to be no way to parse a negative year from the outset.

**Expected behavior**
I would like to be able to enter `dayjs('-2600')` and get (NB I don't know if it's a friday) Fri, 01 Jan -2600 00:00:00 GMT.

**Information**
 - Day.js Version: 1.11.10
 - OS: Linux
 - Browser: Chrome 124

**Comment by willismonroe** [comment]
I know this is potentially not easy given the Julian/Gregorian change, but it would be very useful!

**Comment by klm-turing** [comment]
HI @willismonroe ,
I went through your issue and here's what I've come up with so far

`dayjs('-2006').toDate()` ==> `Wed Jan 01 -2600 00:00:00 GMT-0016 (Greenwich Mean Time)`.

Is this enough for you? Do you have any other use cases you'd like to test?

**Comment by willismonroe** [comment]
I just tried this on a REPL and got the same result as earlier:
![image](https://github.com/iamkun/dayjs/assets/715210/b3bb92f5-c411-47de-adb8-aec75bbd9ed0)

This is version 1.11.10 btw

**Comment by willismonroe** [comment]
Sorry @klm-turing were you showing the output of a proposed fix? If so, that's great. No other issues I'd like to test at the moment, as I mentioned earlier there are quite a few edge cases extra that would be worth looking into, but even just having negative years is a huge improvement.

**Comment by klm-turing** [comment]
@willismonroe I wanted to know if it was enough for you first. 

I linked a PR [2640](https://github.com/iamkun/dayjs/pull/2640). Test it and let me know

![Screenshot from 2024-04-26 16-49-29](https://github.com/iamkun/dayjs/assets/167549638/d99ed665-5ffc-4a81-992f-cd9754d23502)

**Comment by iamkun** [comment]
Maybe it will be better to be implemented via a plugin.
IMHO, this might be a project logic, not a common one in dayjs?

**Comment by klm-turing** [comment]
@iamkun nice touch, will do that

**Comment by klm-turing** [comment]
@iamkun The plugin is done, If you have time, Please have a look.
