### ISSUE TITLE
The mirror of gitee.io is no longer accessible and needs to be removed

### ISSUE THREAD

**Issue by linghengqian** [iamkun/dayjs#2657]
**Describe the bug**

- The mirror of gitee.io is no longer accessible and needs to be removed.
- Currently, a pop-up window pops up after opening https://day.js.org/en/ in a specific area, prompting me to visit https://dayjs.gitee.io/zh-CN .
- But https://dayjs.gitee.io/zh-CN is actually no longer available.Reference https://cn.v2ex.com/t/1038258 .
- ![image](https://github.com/iamkun/dayjs/assets/20187731/2f0a891d-a1c7-469c-96bb-f1116f1c8331)

**Expected behavior**

- The pop-up window of the gitee.io mirror station will no longer appear.

**Information**
 - Day.js Version [e.g. v1.0.0] v1.0.0
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome 62] chrome 62
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)] GMT-07:00 DST (Pacific Daylight Time)

**Comment by iamkun** [comment]
Fixed, thanks
