### ISSUE TITLE
Question: Is there any way to prevent `dayjs` from converting my date into local timezone before formatting?

### ISSUE THREAD

**Issue by aayushchugh** [iamkun/dayjs#2669]
Hey, I want to prevent dayjs to convert my date to local time zone is there any solution for this?

**Comment by dimarixsus** [comment]
Hey, could you provide an example of what you are getting and what would be your expected output?

If you want to ignore your server (usually your computer when developing) timezone, you could use the `utc` plugin and do dayjs.utc() directly

**Comment by aayushchugh** [comment]
Hey @dimarixsus,

So the backend is sending me the date in the `2024-04-15T09:00:03+05:30` format. The `+5:30` defines the timezone. This is India's timezone but if I open this website outside of India, the `DayJS` will automatically convert this date to their timezone and format it that way. But I don't want this to happen, I wish that this date should be formatted with the same time instead of their timezone

For eg: 

I have this date: `2024-04-15T09:00:03+02:00`, if I use `.format("DD/MM/YYYY HH:mm")` on this it is returning `15/04/2024 12:30` which is converted to my timezone i.e. `+5:30`. What I want is that, it should return `15/04/2024 09:00` only, without converting to the local timezone

**Comment by dimarixsus** [comment]
Hi @aayushchugh,

I that you have to build the dayjs date in the user local timezone and shift it to the offset you have with `.utcOffset()`. For eg:

Having this date `2024-04-15T09:00:00+02:00`:

You build it with `dayjs("2024-04-15T09:00:00+02:00")` and then do `.utcOffset("+02:00")` (which if your server already returns the offset that would be great, if not a regex expression could to the job)

So: `dayjs("2024-04-15T09:00:00+02:00").utcOffset("+02:00").format("DD/MM/YYYY HH:mm")` would give you the correct format!

**Comment by aayushchugh** [comment]
Guess I have to ask the backend dev to send utc offset
