### ISSUE TITLE
Parse format 'D/M/YYYY' and 'YYYY/D/M' acting unexpectedly

### ISSUE THREAD

**Issue by wangyinyuan** [iamkun/dayjs#2686]
**Describe the bug**
Is this a known bug?     
I'll look into the source code when I have time because it's so weird.
<img width="1070" alt="image" src="https://github.com/iamkun/dayjs/assets/110143758/2d8cc938-762c-44f9-aecf-f7705c846196">
<img width="1076" alt="image" src="https://github.com/iamkun/dayjs/assets/110143758/d8c7651a-fa4e-47ee-86dd-7caab4301089">

**Expected behavior**
for the first picture, the right output should be:
```
true
date1:  2023-08-07T00:00:00+08:00
date2:  2023-09-01T00:00:00+08:00
```
for the second one, the right output should be:
```
false
date1:  2023-07-08T00:00:00+08:00
date2:  2023-01-09T00:00:00+08:00
```
**Information**
 - Day.js Version [v1.11.11]
 - OS: [MacOS 14.5 (23F79)]
 - Node.js Version [v20.14.0]
 - Time zone: [GMT+08:00 CST (China Standard Time)]

**Comment by wlius-support3** [comment]
To include a format string (String + Format)

> This requires the [CustomParseFormat ](https://day.js.org/docs/en/plugin/custom-parse-format)plugin to work

[Source](https://day.js.org/docs/en/parse/string-format)

Once you've extended dayjs with the customParseFormat, you will no longer get unexpected results.

**Comment by wangyinyuan** [comment]
> To include a format string (String + Format)
> 
> > This requires the [CustomParseFormat ](https://day.js.org/docs/en/plugin/custom-parse-format)plugin to work
> 
> [Source](https://day.js.org/docs/en/parse/string-format)
> 
> Once you've extended dayjs with the customParseFormat, you will no longer get unexpected results.

Thank you so much, I saw the documentation as well, but I didn't see this place due to being in a hurry, it was an oversight on my part, after adding the plugin everything did work fine!
