### ISSUE TITLE
dayjs(value, 'YYYY-[Q]Q') 解析错误

### ISSUE THREAD

**Issue by guaijie** [iamkun/dayjs#2697]
**Describe the bug**
关于这个 issue 早在 2020 年就有提出，2023 年又被重新提出过，相关维护者也给出了将在不久后解决，但是到如今都没有得到解决，想咨询下最新进展情况，或是遇到了什么困难导致该 issue 一直得不到解决

**Expected behavior**

**Information**
 - Day.js 1.11.12
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by alexlee002** [comment]
你修复了提个PR也行啊

**Comment by iamkun** [comment]
fixed in https://github.com/iamkun/dayjs/pull/2705
