### ISSUE TITLE
not support ISO8601 like this '20180709T102210Z' ?

### ISSUE THREAD

**Issue by waitingsong** [iamkun/dayjs#273]
https://en.wikipedia.org/wiki/ISO_8601

support this `2018-07-09T10:22:10Z` , but  not '20180709T102210Z'

**Comment by iam10K** [comment]
Also could not get '2018-08-16T12:19:45.118+0000' to work in IE 11

**Comment by iamkun** [comment]
Try `CustomParseFormat` plugin in v1.8.2
