### ISSUE TITLE
bug(locale): Dutch months and weekdays should be lowercase

### ISSUE THREAD

**Issue by donroyco** [iamkun/dayjs#274]
## Type
Bug

## Where?
The Dutch locale 🇳🇱:
```dayjs/blob/master/src/locale/nl.js```

## What happened?
The Dutch language doesn't have capitalised months (`januari`, `februari`, `maart` etc.) and weekdays (`maandag`, `dinsdag`, `woensdag`, etc.), like the English language has (`January, February`, `March`, etcetera and `Monday`, `Tuesday`, `Wednesday`, etcetera).

Explanation from 'Our Language':

> But in the Green Book from 1954 the names of months and the days of the week got a lowercase letter, because they are not unique names, and that has remained the same since then.  _[Source](https://onzetaal.nl/taaladvies/oktober-october/)_

Reference to Moment `nl` locale: [moment/nl.js](https://github.com/moment/moment/blob/develop/locale/nl.js)

## And now?
I will open a PR soon to solve this bug. Cheers.

**Comment by iamkun** [comment]
Great fix, thanks @donroyco

**Comment by iamkun** [comment]
fix in 1.7.3
