### ISSUE TITLE
Typescript声明文件的最后是否可以导出整个namespace(能避免ts构建报错)

### ISSUE THREAD

**Issue by windylaugit** [iamkun/dayjs#2746]
**Describe the bug**
我在typescript中使用dayjs时，构建报错：'Can not find name 'Dayjs''
（作为对比，我也引入了moment，用于比对构建结果）
```typescript
import dayjs from 'dayjs'
import type { Dayjs } from 'dayjs'
import moment from 'moment'
import type { Moment } from 'moment'

export function isDayjs(value: any): value is Dayjs{
    return dayjs.isDayjs(value)
}
export function isMoment(value: any): value is Moment {
    return moment .isMoment(value)
}
```
项目构建后ts检查报错，且生成的 dist.d.ts 文件中：
```typescript
import { Moment } from 'moment';

export declare function isDayjs(value: any): value is Dayjs
export declare function isMoment(value: any): value is Moment
```

**Expected behavior**
期望能构建后不报错，且生成正常的 dist.d.ts文件。
我通过测试后发现，只需要在 dayjs的 index.d.ts文件末尾 添加一行： `export as namespace dayjs` 即可解决。

**Information**
 - Day.js 1.11.13
 - OS: win10
 - Browser chrome128
 - Time zone:GMT-08:00

**Comment by stouch** [comment]
Pourquoi vous écrivez en chinois ? Cela empêche de rechercher votre thread dans les issues avec la recherche par mots en anglais. Vous n'avez pas de traducteur vers l'anglais ?

**Comment by windylaugit** [comment]
> Pourquoi vous écrivez en chinois ? Cela empêche de rechercher votre thread dans les issues avec la recherche par mots en anglais. Vous n'avez pas de traducteur vers l'anglais ?

我是中国人，中文多美妙，我喜欢中文，且使用中文 和 我编写代码并无任何冲突， 不明白您为什么对此有疑问？

**Comment by stouch** [comment]
It makes harder for other users to find your thread using terms lookup in github search and/or google search with the terms of your issues.
