### ISSUE TITLE
Module has no has no default export with ts and rollup

### ISSUE THREAD

**Issue by waitingsong** [iamkun/dayjs#277]
```ts
import dayjs from 'dayjs'
```
compile with rollup , got error `Module 
> ".../source/node_modules/dayjs/index" has no default export.

**Comment by kaseyhinton** [comment]
any updates on this?

**Comment by Kikisek** [comment]
Try `import * as dayjs from 'dayjs'`, it helped me 😃

**Comment by aibrahim3546** [comment]
@Kikisek I did like what you mentioned...

like this:

`import * as dayjs from dayjs`

I am hitting this error now:

> Uncaught TypeError: dayjs is not a  function

**Comment by samtsai** [comment]
@aibrahim3546 to be sure, do you have quotes around the second `dayjs`?

`import * as dayjs from 'dayjs'`

**Comment by wangyiz4262** [comment]
@waitingsong @iamkun I re-did the Typescript definition in #466 which should fix the problem of default import. The current `index.d.ts` file does not make much sense to expose class to the user.

**Comment by iamkun** [comment]
Updates:
After v1.8.1 we could simply use `import dayjs from 'dayjs'` in a TypeScript project.

**Comment by Smirking** [comment]
Looks like this was reverted again here https://github.com/iamkun/dayjs/pull/476, so it's broken again as of 1.8.4 for rollup and things that use rollup, ng-packagr etc

**Comment by conradolk** [comment]
As @Smirking said, this is broken as of now and we have to use @Kikisek workaround.

**Comment by orige** [comment]
Even with @Kikisek workaround, I'm getting:
`TypeError: dayjs is not a function`

**version**:  1.8.28

**Comment by blestab** [comment]
Also getting this **version:** 1.8.35

**Comment by Lacroute** [comment]
For those who are experiencing the `Error: 'default' is not exported by node_modules/dayjs/dayjs.min.js` issue, add `@rollup/plugin-commonjs` as a dev dependency and configure your `jest.config.js` like below:

```
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import { terser } from "rollup-plugin-terser";

export default {
  input: 'src/index.js',
  output: {
    file: 'dist/index.min.js',
    format: 'cjs',
    plugins: [
      terser()
    ]
  },
  plugins: [
    nodeResolve(),
    commonjs()
  ]
};
```

**Comment by risalfajar** [comment]
1.10.7, error still happened

Have tried the workaround but still not working

`dayjs is not a function`

**Comment by sineraves** [comment]
Came across the `Error: 'default' is not exported by node_modules/dayjs/dayjs.min.js` error today with `1.10.7`.

Had success with:

```js
import dayjs from 'dayjs/esm';
```

**Comment by SeryiBaran** [comment]
It even worked for me with `import dayjs from 'dayjs'`, with this config:

```js
// rollup.config.js
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from 'rollup-plugin-typescript2';

export default {
  input: './src/main.ts',
  output: {
    file: './build/main.js',
    format: 'cjs',
  },
  plugins: [
    resolve({
      exportConditions: ['node'],
    }),
    commonjs(),
    typescript(),
  ],
};

```

**Comment by derwaldgeist** [comment]
Would be nice if this could be fixed by adding a default export.
