### ISSUE TITLE
`z` timezone formatting option does not transform date

### ISSUE THREAD

**Issue by SirSerje** [iamkun/dayjs#2770]
**Describe the bug**
When I want to use `z` as format value, it returns z without transformation
```
dayjs.extend(utc)
dayjs.extend(timezone)
// ...
export const formatDateTime = (
    datetime: string,
    timezoneStr: string,
    formatStr: string
  ): string => {
    const date = dayjs(datetime).tz(timezoneStr);
    return ${date.format(formatStr)} ${date.format('z')};
  };
```
test case:
```
beforeAll(() => {
  dayjs.extend(utc)
  dayjs.extend(timezone)
})
it('formats with the correct timezone abbreviation', () => {
    const datetime = '2024-11-18T12:00:00Z';
    const timezoneStr = 'Europe/London';
    const formatStr = 'YYYY-MM-DD HH:mm:ss';
    const formattedDate = formatDateTime(datetime, timezoneStr, formatStr);
    expect(formattedDate).toBe('2024-11-18 12:00:00 GMT'); // assuming GMT for the timezone
});
```
I've been looking into sources: https://github.com/iamkun/dayjs/blob/dev/src/index.js#L333 but unfortunaltelly lowercase `z` is not included

**Expected behavior**
`z` will be transformed correctly according to https://day.js.org/docs/en/plugin/advanced-format

**Information**
 - Day.js Version 1.11.13
 - OS: 14.6.1 (23G93)
 - Browser Version 130.0.6723.117 (Official Build) (arm64)
 - Time zone: Eastern Standard Time > Time zone in Ottawa, ON (GMT-5)

**Comment by ChaiyoKung** [comment]
Try to use `advancedFormat` plugin

```ts
import advancedFormat from "dayjs/plugin/advancedFormat";

dayjs.extend(advancedFormat);
```
