### ISSUE TITLE
dayjs.tz.guess() returns old name

### ISSUE THREAD

**Issue by mab98** [iamkun/dayjs#2784]
**Describe the bug**
dayjs.tz.guess() returns "Asia/Calcutta" instead of "Asia/Kolkata".

**Expected behavior**
dayjs.tz.guess() should return "Asia/Kolkata".

**Information**
 - Day.js Version [1.11.10]
 - Time zone: Asia/Kolkata (UTC+05:30)

**Comment by Siddhanta-Mallick** [comment]
`dayjs.tz.guess()` returns timezone provided by `Intl.DateTimeFormat().resolvedOptions().timeZone`, which of a part of the  javascript API `Intl.DateTimeFormat()` which in this case returns "Asia/Calcutta" for some reason.
Nothing wrong with dayjs source code.
