### ISSUE TITLE
could you replace 'c ? (anchor - anchor2) : (anchor2 - anchor)' with one month time?

### ISSUE THREAD

**Issue by FoxDaxian** [iamkun/dayjs#279]
https://github.com/iamkun/dayjs/blob/3c499f3a211f8bbdfe666095a6a4feef3d8ae12c/src/utils.js#L22

**Comment by iamkun** [comment]
Don't understand. What is a 'one month time'?

**Comment by iamkun** [comment]
But it's different in positive & negative

**Comment by a13821190779** [comment]
is's same in . a.clone().add(wholeMonthDiff...
so, different places just are (c ? -1 : 1)
if b < anchor In days， c is true. otherwise false.
when c is true wholeMonthDiff -1,  anchor - anchor2  = 1, c is false, anchor2 - anchor  = 1
so I think, you can remove Ternary expression

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
