### ISSUE TITLE
Not support isBetween() API

### ISSUE THREAD

**Issue by wangjianio** [iamkun/dayjs#287]

**Comment by lamartire** [comment]
@iamkun what about it? I think, I can implement that method.

**Comment by iamkun** [comment]
@lamartire  That would be nice. Just one question, a core API or a isBetween plugin?

**Comment by lamartire** [comment]
@iamkun , no matter, if it question about implementation. What will be better in your opinion?

**Comment by lamartire** [comment]
Got it. I will try to do it in few days.

**Comment by iamkun** [comment]
@wangjianio added isBetween plugin

**Comment by iamkun** [comment]
Update: Support isBetween() API  https://day.js.org/docs/en/query/is-between
