### ISSUE TITLE
 Property 'fromNow' does not exist on type 'Dayjs'

### ISSUE THREAD

**Issue by yashwp** [iamkun/dayjs#297]
I'm using the `relativeTime` plugin in my `.ts` file

Importing is done in below manner : -
`import * as dayjs from 'dayjs';`
`import relativeTime from 'dayjs/plugin/relativeTime';`
`dayjs.extend(relativeTime);`

I've also tried to change the import statement as:
`import dayjs from 'dayjs';` But started throwing new error as `no exported member`

Now when I'm using in the `fromNow` function as: -
`dayjs(this.created_at).fromNow();` the compiler is throwing an error 

**` Property 'fromNow' does not exist on type 'Dayjs'`**
 I'm using  `"dayjs": "^1.7.4",` version

What's the with usage? How can I fix this?

@iamkun Please address this issue

**Comment by dmk1111** [comment]
method `fromNow` is not present in `d.ts` file, that's why TS throws error.
You could add type `any` to `dayjs` or `relativeTime ` and check if it works after that or you could create `realativeTime.d.ts` file for that plugin and make PR

**Comment by iamkun** [comment]
@dmk1111 thanks for the reply. 

Just wondering if we should add plugin methods like `fromNow ` into our main `d.ts` file, or separated definition file.

**Comment by dmk1111** [comment]
@iamkun I suppose it better to keep them separate and than just import all of them to main file

**Comment by dmk1111** [comment]
@yashwp you could introduce PR with desired fixes, in case you want those changes to appear faster

**Comment by yashwp** [comment]
@dmk1111 Bro I don't know how to work with...`.d.ts` file. Otherwise, I would have done that...on the 2nd day itself... If you know can you help me with that?

**Comment by dmk1111** [comment]
@yashwp in case you want to know how to create `*.d.ts` files, you could refer to this SO thread:
https://stackoverflow.com/questions/18301898/generating-typescript-declaration-files-from-javascript

If you didn't manage to create it by yourself, I'll try to do this later, maybe in a week or so.

**Comment by yashwp** [comment]
@dmk1111 thanx :)

**Comment by iamkun** [comment]
This might help

```
declare module 'dayjs' {
    interface Dayjs {
        fromNow();
    }
}
```

**Comment by yashwp** [comment]
@dmk1111 I tried to create `.d.ts` file but didn't get it.  So can make it for me, that would be great help.

Thank u :)

**Comment by yashwp** [comment]
@dmk1111 @iamkun Can u fix this thing anytime soon? It's been 2 months....

**Comment by ypresto** [comment]
You need at least one import statement to use [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation).

```ts
import 'dayjs'
declare module 'dayjs' {
    interface Dayjs {
      ...
```

Also it seems you can nest module augmentation in `declare module`.

```ts
declare module 'dayjs/plugin/relativeTime' {
  module 'dayjs' {
    ...
```

**Comment by rdehuyss** [comment]
Also having issues with this... default installation of plugins does not work as described.

**Comment by timohofmeijer** [comment]
So a temporary fix, until plugin typings are merged, is adding the following to your typings:
(took me some fiddling, so perhaps it can save someone else the trouble)
```ts
// From: https://github.com/iamkun/dayjs/pull/418/files#diff-e5e546dd2eb0351f813d63d1b39dbc48

import { Dayjs, PluginFunc } from 'dayjs'
type DateType = string | number | Date | Dayjs

declare module 'dayjs' {
  interface Dayjs {
    fromNow(withoutSuffix?: boolean): string
    from(compared: DateType, withoutSuffix?: boolean): string
    toNow(withoutSuffix?: boolean): string
    to(compared: DateType, withoutSuffix?: boolean): string
  }
}
```

**Comment by wottpal** [comment]
Hey @iamkun  and @ypresto, thanks for your work!

On `1.8.7` I'm getting the following error (`ERROR in node_modules/dayjs/plugin/relativeTime.d.ts(1,22): error TS2305: Module '.../node_modules/dayjs/index"' has no exported member 'DateType'.`) when doing the following imports:

```
import * as dayjs from 'dayjs'
import * as relativeTime from 'dayjs/plugin/relativeTime'
import 'dayjs/locale/de'
```

I guess this could be related to this issue, right?

**Comment by iamkun** [comment]
@wottpal Thanks for the feedback, that's my mistake.

Fixed in v1.8.8. 😬

**Comment by stunaz** [comment]
fixed, merged, released... great? how to use it now? I am trying this :
```typescript
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

 dayjs.extend(relativeTime);
 console.log(dayjs.from(dayjs('1990')));
```

error :
`Property 'from' does not exist on type  ....`

**Comment by iamkun** [comment]
@stunaz dayjs version, please? And if in a TypeScript project, you could try `import * as dayjs from 'dayjs'`

**Comment by stunaz** [comment]
v 1.89 [see for yourself ](https://codesandbox.io/s/98v4x0jw9r)

**Comment by iamkun** [comment]
@stunaz I see.  You should use `dayjs().from` rather than `dayjs.from` according to our document.

**Comment by stunaz** [comment]
indeed @iamkun ... thanks!

**Comment by break7533** [comment]
```
import * as dayjs from 'dayjs';
import * as relativeTime from 'dayjs/plugin/relativeTime';
dayjs.extend(relativeTime);
```

This worked fine for me, in case anyone still needs it

**Comment by ko-devHong** [comment]
> ```
> import * as dayjs from 'dayjs';
> import * as relativeTime from 'dayjs/plugin/relativeTime';
> dayjs.extend(relativeTime);
> ```
> 
> This worked fine for me, in case anyone still needs it

The problem was solved using the above answer, but the type error still occurs, so the type was declared to eliminate it.
**/@types/dayjs/index.d.ts**
```
import { Dayjs, PluginFunc } from "dayjs";

declare module "dayjs" {
    interface Dayjs {
        fromNow(withoutSuffix?: boolean): string;
    }
}

```

**Comment by designbyadrian** [comment]
Still having this issue with version 1.11.0. This old post from 2019 solved it.

> So a temporary fix, until plugin typings are merged, is adding the following to your typings: (took me some fiddling, so perhaps it can save someone else the trouble)
> 
> ```ts
> // From: https://github.com/iamkun/dayjs/pull/418/files#diff-e5e546dd2eb0351f813d63d1b39dbc48
> 
> import { Dayjs, PluginFunc } from 'dayjs'
> type DateType = string | number | Date | Dayjs
> 
> declare module 'dayjs' {
>   interface Dayjs {
>     fromNow(withoutSuffix?: boolean): string
>     from(compared: DateType, withoutSuffix?: boolean): string
>     toNow(withoutSuffix?: boolean): string
>     to(compared: DateType, withoutSuffix?: boolean): string
>   }
> }
> ```

**Comment by iamkun** [comment]
@designbyadrian there should be a type file shipped with 1.11.0

**Comment by Kavignon** [comment]
What does that mean? I'm having a similar issue with this. I don't have much experience with frontend and simply explaining what I need to do would be great. I'm currently using the temporary fix and sitting on version 1.11.0

**Comment by huy-lv** [comment]
try this:
```
import dayjs from 'dayjs';
const relativeTime = require('dayjs/plugin/relativeTime');
dayjs.extend(relativeTime);
```

**Comment by omerg** [comment]
Changing the way relativeTime is imported should allow getting access to corresponding type definitions:

```typescript
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
dayjs.extend(relativeTime)
```

**Comment by nima** [comment]
Similarly, if not in a module (from @omerg's post), this worked for me:

```js
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
dayjs.extend(relativeTime)
```

**Comment by gajus** [comment]
We had a weird issue where the function was not available depending on how it was re-exported. This appears to be minification/tree-shaking related. We are using Rollup. This fixed it.

```diff
import originalDayjs from 'dayjs';
import advancedFormat from 'dayjs/plugin/advancedFormat.js';
import calendar from 'dayjs/plugin/calendar.js';
import duration from 'dayjs/plugin/duration.js';
import isBetween from 'dayjs/plugin/isBetween.js';
import isToday from 'dayjs/plugin/isToday.js';
import isYesterday from 'dayjs/plugin/isYesterday.js';
import relativeTime from 'dayjs/plugin/relativeTime.js';

originalDayjs.extend(advancedFormat);
originalDayjs.extend(relativeTime);
originalDayjs.extend(duration);
originalDayjs.extend(calendar);
originalDayjs.extend(isYesterday);
originalDayjs.extend(isToday);
originalDayjs.extend(isBetween);

- export { default as dayjs } from 'dayjs';
+ export { originalDayjs as dayjs };
```
