### ISSUE TITLE
benchmarks?

### ISSUE THREAD

**Issue by fundon** [iamkun/dayjs#32]
Any benchmarks?

**Comment by iamkun** [comment]
Nice point, thx.

I'm not sure what are you looking for at a benchmark test. Or what is your most concern? Size, Performance or something else?😋

**Comment by fundon** [comment]
About performance, compare with Moment.js

**Comment by kaermorchen** [comment]
And compare with date-fns

**Comment by prantlf** [comment]
I included `date-fns` in the PR #344.
