### ISSUE TITLE
Validation .isValid() doesn't work always

### ISSUE THREAD

**Issue by dakshshah96** [iamkun/dayjs#320]
The `.isValid()` validation doesn't function correctly under the following condition:

- When the the day part is 31 for a month which didn't have 31 days.

Some instances where `.isValid()` returns `true` for a date that is invalid:

- `dayjs().isValid('1995-02-31')`
- `dayjs().isValid('1995-03-31')`
- `dayjs().isValid('1995-04-31')`
- `dayjs().isValid('1995-06-31')`
- `dayjs().isValid('1995-09-31')`
- `dayjs().isValid('1995-11-31')`

**Comment by mixrich** [comment]
@dakshshah96 
`.isValid()` method has't attributes and passed value is discarded like if you call `dayjs().isValid()`. And you know, that `dayjs()` return current date which is always valid

**Comment by mixrich** [comment]
Moreover, `isValid` doesn't validate if passed date is `exists`, it's just validate that date was parsed correctly. So, if you pass `dayjs('2018-11-41').isValid()` the date will be parsed as `2018-12-10` and `isValid` will return `true` anyway

**Comment by prantlf** [comment]
You should not overestimate the quality of such validation. You will be able to catch nonsense like `MM=15`, `DD=42` or `DD=30` in February, if the user exchanges values of `DD` with `MM`, or types something totally wrong. However, you won't be able to ensure, that the whole date - particularly `DD` and `MM` - will be set, as the user intended from an input like `02/05/2018`. Was it May 2 or February 2? The user will still have to be aware of the actual format like `DD/MM/YYYY`. The date picker control usually helps better with ensuring that, than a robuster parser.

**Comment by majstorzelja** [comment]
Is this an option to validate if date exist?

```
function validate(date, format) {
  return dayjs(date, format).format(format) === date;
}

validate('2019/02/31', 'YYYY/MM/DD') // false
```

**Comment by YangAi** [comment]
> Is this an option to validate if date exist?
> 
> ```
> function validate(date, format) {
>   return dayjs(date, format).format(format) === date;
> }
> 
> validate('2019/02/31', 'YYYY/MM/DD') // false
> ```

Thanks! It's very helpful.

**Comment by ness-EE** [comment]
I'm just swapping over from Moment to DayJS. The unit tests I have in place to validate incorrect entries like 2000-02-31 pass with Moment and fail with DayJS

**Comment by bitnbytesio** [comment]
facing same issue, isValid() always returns true

```js
const dayjs = require("dayjs")
console.log(dayjs('2021-15-35').isValid())
```
```js
const dayjs = require("dayjs")

console.log(dayjs('2021-15-35', 'YYYY-MM-DD').isValid())
```

Expected: false
Received: true

Any suggestion?

**Comment by padas2** [comment]
Turns out
`dayjs('31/02/2021', 'DD/MM/YYYY', true).isValid()`
can be used to check if passed date exists or not.

But not sure how... could somebody explain ?

**Comment by mateuszpigula** [comment]
```javascript
console.log(dayjs("2021-15-35", "YYYY-MM-DD").isValid()); // true
console.log(dayjs("35/15/2021", "DD/MM/YYYY").isValid()); // false
```
So it is somehow related to the date format

**Comment by vamshi29292** [comment]
@mateuszpigula passing a third parameter `true` is checking if the date actually exists, unlike the native `Date` implementation.
`
dayjs("2021-15-35", "YYYY-MM-DD").isValid();          //true
dayjs("2021-15-35", "YYYY-MM-DD", true).isValid(); //false
`
I've tested a few cases including leap years, and this seems to work fine to check if the date actually exists.

**Comment by wmonecke** [comment]
Why is this still closed? This issue cost me at least 4 hours because it is still broken.

**Comment by fragsalat** [comment]
> Is this an option to validate if date exist?
> 
> ```
> function validate(date, format) {
>   return dayjs(date, format).format(format) === date;
> }
> 
> validate('2019/02/31', 'YYYY/MM/DD') // false
> ```

Such workaround only works for having DD and MM. Once you have non leading zero with D and M neither this approach nor the strict flag solves the issue. :(

**Comment by gamevnlc** [comment]
I get the same issue 
`dayjs('01/02, 20:00', 'MM/DD/YYYY, HH:mm', true).isValid()) // True`
if I extends with plugin customParseFormat. The result is False

**Comment by NikhilNanjappa** [comment]
Any update on this ?

I still get incorrect results (v1.11.3)

```
dayjs('2001-2-29', 'YYYY-M-D').isValid() // returns true; expected false
dayjs('2001-02-29', 'YYYY-MM-DD').isValid() // returns true; expected false

// date becomes Mar 01 2001 for some reason which is why its considered valid
```

FYI - Adding `customParseFormat` plugin doesnt fix this.

**Comment by RobAtRAC** [comment]
That's still validating as true for me too

**Comment by aderchox** [comment]
This is the very first thing I tried with Day.js and it's failed.
`console.log(dayjs("20-11-2022", "DD-MM-YYYY", true).isValid());` gives `false`.

**Comment by ethanfann** [comment]
Why does dayjs require a special plugin just to validate if a month has a 31st day?

**Comment by VladyslavYe** [comment]
Also, if you are having this problem check the parsing of your date:
```
dayjs('27.07.2023', 'DD.MM.YYYYY').format('DD.MM.YYYYY') // Invalid Date
```

If this occurs try adding an ext:
```
import customParseFormat from 'dayjs/plugin/customParseFormat';

dayjs.extend(customParseFormat);

dayjs('27.07.2023', 'DD.MM.YYYYY').format('DD.MM.YYYYY') // 27.07.2023
```


Hope this helped someone.

**Comment by Derrick-blocking** [comment]
> facing same issue, isValid() always returns true
> 
> const dayjs = require("dayjs")
> console.log(dayjs('2021-15-35').isValid())
> const dayjs = require("dayjs")
> 
> console.log(dayjs('2021-15-35', 'YYYY-MM-DD').isValid())
> Expected: false Received: true
> 
> Any suggestion?





https://javascripter.space/questions/issue-with-javascript-dateparse-function-not-functioning-as-expected
