### ISSUE TITLE
Consider adding bundlesize

### ISSUE THREAD

**Issue by limonte** [iamkun/dayjs#321]
First of all, thanks a lot for taking care of a package size and keeping it small.

Would you maybe consider adding the [bundlesize](https://github.com/siddharthkp/bundlesize) helper to this project to be able to easily track how many bytes each PR is adding to/redusing from the bundle?

![image](https://user-images.githubusercontent.com/6059356/44947144-63646100-ae11-11e8-806c-6d22923e5aca.png)

**Comment by iamkun** [comment]
Looks nice, maybe we could have a try.

**Comment by iamkun** [comment]
seems we are OK with `size-limit` at the moment, will consider bundlesize if needed
