### ISSUE TITLE
Dayjs is handling dates exceding month date limit in wrong way

### ISSUE THREAD

**Issue by rparashar-hrg** [iamkun/dayjs#341]
I was experimenting with this fantastic 2Kb library. But I saw strange behavior.
for example 
    `2018-08-56` 
this date should be passed as 2018-09-25 but it returns 2018-08-25.
Maybe I m wrong somewhere.
[https://runkit.com/rparashar-hrg/dayjs-test](https://runkit.com/rparashar-hrg/dayjs-test)

**Comment by xxyuk** [comment]
@rparashar-hrg try `dayjs('2018-08-56').format()`

**Comment by rparashar-hrg** [comment]
@xxyuk  thanks i understood the issue here actually it is  parsing month as index
