### ISSUE TITLE
Greetings depending on time of day?

### ISSUE THREAD

**Issue by wzup** [iamkun/dayjs#342]
Does this lib have this feature?

```
// Let's say it is 10am now
dateFns.greet(); // returns "Good morning"

// It is 2pm now
dateFns.greet(); // returns "Good afternoon"
```

Is it supported?

**Comment by Imperat** [comment]
Hello, @wzup! Surely not :)
But it's so simple to add this feature as plugin

**Comment by sbarbat** [comment]
Done it https://github.com/sbarbat/dayjs-greet-plugin 😉

**Comment by jidoggs** [comment]
> Done it https://github.com/sbarbat/dayjs-greet-plugin 😉

This is great. However It cannot work if I am localising the message.
If my user understands Swahili or Polish this plugin would not be great

**Comment by sbarbat** [comment]
@jidoggs feel free to make a PR 😎
