### ISSUE TITLE
Hot to set up the beginning date of the week?

### ISSUE THREAD

**Issue by Sunrise1970** [iamkun/dayjs#352]
Western countries generally believe that Sunday is the beginning of a week, while China believes that Monday is the beginning of a week. So there may be such a demand in China: DatePicker should be chosen from Monday to Sunday, and the components are Sunday to Monday. So I hope the official can provide a api that supports changing the order of weeks.

**Comment by adamlindqvist** [comment]
Just to add more information, not all Western countries has sunday as start of the week. Nordic countries uses Monday as start of the week too.

**Comment by mantcz** [comment]
Poland uses Monday as start of the week too.

**Comment by calmyournerves** [comment]
The whole of Europe and many other countries use Monday as the start of the week. Wikimedia Commons has a nice overview: https://commons.wikimedia.org/wiki/File:First_Day_of_Week_World_Map.svg

**Comment by ortonomy** [comment]
Just want to declare here that no, 'Western' countries do not consider Sunday to be the first day of the week. The _USA_ considers Sunday to be the first day of the week...
