### ISSUE TITLE
Inconsistent constructor behavior around `undefined` and `null`

### ISSUE THREAD

**Issue by jsumners** [iamkun/dayjs#361]
```
> assert.ok(dayjs(undefined).isValid())
undefined
> assert.ok(dayjs(null).isValid())
AssertionError [ERR_ASSERTION]: false == true
```

In other words, `dayjs(undefined)` results in an instance at the current date and time whereas `dayjs(null)` results in an invalid date. I think both should result in an invalid date.

**Comment by prantlf** [comment]
This is "as-designed". Day.js is meant to be a lightweight and immutable replacement of Moment.js. It means keeping the interface as compatible as possible.

```
> dayjs().toDate()
2018-10-14T18:13:40.428Z
> dayjs(undefined).toDate()
2018-10-14T18:13:44.140Z
> dayjs(null).toDate()
Invalid Date
```

```
> moment()
moment("2018-10-14T20:11:41.383")
> moment(undefined)
moment("2018-10-14T20:11:44.558")
> moment(null)
moment.invalid(/* NaN */)
```

Unfortunately, it makes the constructor incompatible with the native `Date` object. You cannot have both.

```
> new Date()
2018-10-14T18:10:28.471Z
> new Date(undefined)
Invalid Date
> new Date(null)
1970-01-01T00:00:00.000Z
```

By the way, the behaviour of the `Date` object is not intuitive either ;-)

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
