### ISSUE TITLE
ios下格式问题 变成NaN

### ISSUE THREAD

**Issue by xxvv** [iamkun/dayjs#376]
iphone se
dayjs('2018-11-02 11:22').fromat('YYYY-MM-DD HH:mm')

**Comment by zipeijun** [comment]
你好、我也遇到了同样的问题、请问解决了么？如何解决的？

**Comment by victoryli-yang** [comment]
我在 ie8 下也遇到了如上的问题，同样利用 '2018-10-01'.replace(/-/g, '/') 方法可以解决
