### ISSUE TITLE
weekdayShort localisation request

### ISSUE THREAD

**Issue by XXXVII** [iamkun/dayjs#377]
You need to implement weekdayShort field in localisation files instead of just trimming weekday values. Otherwise you'll have awkward results for different locales. Currently, Russian is unsupportive because of this issue. For instance, Friday (Пятница) trims to Пя instead of Пт that is used in the language.
```
const getShort = (arr, index, full, length) => (
  (arr && arr[index]) || full[index].substr(0, length)
)
```
is a wrong way handling in multy-localisation project.

**Comment by xxyuk** [comment]
there are `weekdaysShort` and `weekdaysMin` options in dayjs's locale config.

You could send a PR with the correct code in your language.
