### ISSUE TITLE
.add(1, 'month') Display is wrong

### ISSUE THREAD

**Issue by qzuser** [iamkun/dayjs#391]
dayjs('2018/2/28').add(1,'month').format('YYYY/MM/DD') => 2018/3/28
but i want 2018/3/31
dayjs('2018/4/30').add(1,'month').format('YYYY/MM/DD') => 2018/5/30
but i want 2018/5/31

Is that a bug ?

**Comment by prantlf** [comment]
The `add` method adds a calendar month. Not 30 or 31 days to move the date always to the end of the month. The method `add` cannot know, which one of the two options you want :-) If you want the end of the month, have a look at [`endOf`](https://github.com/iamkun/dayjs/blob/master/docs/en/API-reference.md#end-of-time-endofunit-string):

```js
dayjs('2018/2/28').add(1,'month').endOf('month')
dayjs('2018/4/30').add(1,'month').endOf('month')
```
