### ISSUE TITLE
how can i compare date like moment.duration

### ISSUE THREAD

**Issue by Evansy** [iamkun/dayjs#414]
How can i get a result like below by dayjs?

```js
const diff = moment.duration(moment("2018-01-01").diff(moment("2019-5-12 10:15:23")));
console.log(diff._date);
// {
    years: 1,
    months: 5,
    days: 12,
    hours: 10,
    ....
}
````

**Comment by naulacambra** [comment]
Check #122

**Comment by Evansy** [comment]
@naulacambra 
I've tried it, but it doesn't seem to fit my needs...

**Comment by iamkun** [comment]
have you tried RelativeTime plugin?

**Comment by Evansy** [comment]
> have you tried RelativeTime plugin?

yes, It' can't.

**Comment by naulacambra** [comment]
Can you show the code with RelativeTime plugin that you've tried?

**Comment by Newbie012** [comment]
Currently, I'm using RelativeTime to achieve that, but it's not perfect:

```
dayjs(milliseconds).locale('he').from(0, true)
```

The problem here is that it will show us only years or days or hours etc... It'll never show something like `2 Hours and 23 Minutes`. It would've been super if we could have a plugin that handles that, with an option of how "deep" do we want to be specific (e.g. be specific until minutes), Maybe something like:

```
dayjs().duration(milliseconds).until('minutes')
```

**Comment by iamkun** [comment]
@Newbie012 How does momentjs do this?

**Comment by Newbie012** [comment]
@iamkun I haven't used momentjs much in my projects since it's a one-hell-of-a-package :D, so I'm not sure exactly.

**Comment by iamkun** [comment]
@Newbie012 Yes, I don't know much about `moment.duration`, and not sure what kind of plugin / API should we provide.

**Comment by Newbie012** [comment]
Currently, I haven't found a lightweight maintained package that offers this kind of feature, so I guess it's up to you whether to implement this kind of plugin / API :)

**Comment by iamkun** [comment]
It's a nice to have feature, why not. 😁 Discussion welcome.

**Comment by iamkun** [comment]
#564 todo: Duration plugin

**Comment by tzsword** [comment]
@see https://github.com/huangjinlin/dayjs-precise-range
```typescript
   dayjs.extend(preciseDiff);

    const duration = dayjs.preciseDiff(dayjs(timeA), dayjs(timeB), true);
    const years = duration.years;
    const year = years ? `${years}年` : '';
    const months = duration.months;
    const month = months ? `${months}月` : '';
    const days = duration.days;
    const day = days ? `${days}天` : '';
    const hours = duration.hours;
    const hour = hours ? `${hours}小时` : '';
    const minutes = duration.minutes;
    const minute = minutes ? `${minutes}分` : '';

```

**Comment by qiwang97** [comment]
As it said `As with the other getters for durations, dayjs.duration().hours() gets the hours (0 - 23).`, it there anyway to show only hours without days like `30 hours 40 minutes` to show time down??
