### ISSUE TITLE
Problems with locations RU and UK 

### ISSUE THREAD

**Issue by docccdev** [iamkun/dayjs#415]
Problem with locations **ru/uk** when use **relativeTime** plugin: 

**Expectation:**
- 1 день
- 2 дня
- 3 дня
- 4 дня
- 5 дней

**Real:**
- 1 день
- 2 дней (must be a "дня")
- 3 дней (must be a "дня")
- 4 дней (must be a "дня")
- 5 дней

**Comment by Imperat** [comment]
Additionaly it's important to have a look at:

* 21 день
* 22 дня
* 23 дня
* 24 дня
* 25 дней

* 101 день
* 102 дня
* 103 дня
* 104 дня

but:
11, 12, 13,14 - дней

**Comment by TheBit** [comment]
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ru

**Comment by iamkun** [comment]
fixed in #767
