### ISSUE TITLE
Non-Arabic Numerals

### ISSUE THREAD

**Issue by bcmn** [iamkun/dayjs#416]
Our specific use case requires for conditionally displaying "[eastern arabic numerals](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals)" `۰۱۲۳۴۵۶۷۸۹` instead of "[arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals)" `0123456789`. Presumably any implementation would be intended to be easily extensible for any other commonly-used base 10 numeral systems.

This would result in DayJS strings like:
```
۲۸ آوریل ۲۰۱۸
پیش ساعت ۴
```
instead of (the current behaviour):
```
28 آوریل 2018
پیش ساعت 4
```

This issue is primarily to ascertain whether this is something that other people would feel is useful or necessary to have as a plugin for DayJS, though there are also some implementation issues that might be useful to discuss.

Obviously the alternative is that this could remain a bespoke implementation detail, & our project just treats this as a generic string formatting operation, completely unaware of DayJS.

--- 

### Implementation Thoughts

After a quick investigation, I'm not sure DayJS currently has a way of applying this sort of library-wide formatting operation to all strings returned? 

It is very easy to add the behaviour to any one function, e.g. `.format` or the overridden `.format` function of the `advancedFormat` plugin, but this would very noticeably miss applying the logic to other plugins, such as `relativeTime`. Is there a better solution than this?

I'm aware `advancedFormat` currently uses binding to achieve some conditional formatting. There _may_ be a way to do this for all plugins that might return a string containing a numeral, but it doesn't seem ideal. 🤔

**Comment by iamkun** [comment]
You may could extend `advancedFormat ` by adding your own tokens, like `DEMO`.

```
import advancedFormat from 'dayjs/plugin/advancedFormat' 
import youOwnFormat from 'dayjs/plugin/youOwnFormat' 
dayjs.extend(advancedFormat) 
dayjs.extend(youOwnFormat) 
dayjs().format('DEMO YYYY - MM') 
```

**Comment by kalyantm** [comment]
@iamkun  Can u please elaborate? I think I'm in need of a similar solution

**Comment by xxyuk** [comment]
@bcmn You might could simply do a global replace('1234', '۰۱۲۳۴۵۶۷۸۹') on the final `format` result .

This might be easy and without a dayjs plugin.

**Comment by VehpuS** [comment]
@bcmn - If still relevant, I believe #1255 solves this issue (at least that's how it's done in moment.js).

**Comment by iamkun** [comment]
@VehpuS great job, THX. I think we could mark this issue as fixed
