### ISSUE TITLE
Less than 1 day when tried to convert to ISOString function.

### ISSUE THREAD

**Issue by hiepndd** [iamkun/dayjs#423]
Hi there!
`dayjs('08/14/1996').toISOString();`
When i executed this line above. 
`Expected`
"1996-08-14T17:00:00.000Z"
`Actual`
"1996-08-13T17:00:00.000Z"

**Comment by hiepndd** [comment]
Hi @iamkun 
Yeah, i know that. So how can i  get exact which input into `dayjs` rather than get a time base on local time zone? 
Thanks!

**Comment by iamkun** [comment]
Not sure if `dayjs('08/14/1996').format()` is what you need.

**Comment by hiepndd** [comment]
Thanks so much @iamkun!
