### ISSUE TITLE
isBetween inclusivity solved

### ISSUE THREAD

**Issue by Noeldeveloper** [iamkun/dayjs#429]
I leave my two cents for isBetween functionality.

That's an approach of moment.js way to treat inclusivity, it can be added to isBetween plugin:

![image](https://user-images.githubusercontent.com/15780540/50001472-41948180-ff9d-11e8-9125-5e16d232501f.png)

code:

export type DayjsInclusivity = '()' | '[)' | '(]' | '[]';

isBetween(date: Dayjs, dateStart: Dayjs, dateEnd: Dayjs, precision?: UnitType, inclusivity?: DayjsInclusivity ) {
    let result = dayjs(date).isAfter(dateStart, precision) && dayjs(date).isBefore(dateEnd, precision);
    if (!result && (inclusivity || inclusivity !== '()')) {
      if (inclusivity === '[)') {
        result = dayjs(date).isSame(dateStart, precision);
      } else if (inclusivity === '(]') {
        result = dayjs(date).isSame(dateEnd, precision);
      } else {
        result = dayjs(date).isSame(dateStart, precision) && dayjs(date).isSame(dateEnd, precision);
      }
    }
    return result;
  }

**Comment by naulacambra** [comment]
Maybe you could create a PR with the changes?

**Comment by waseemahmad31** [comment]
Can I submit a pull request for this?

**Comment by naulacambra** [comment]
@waseemahmad31 sure 😀

**Comment by iamkun** [comment]
added in #464

**Comment by iamkun** [comment]
Update: Support isBetween() API  https://day.js.org/docs/en/query/is-between
