### ISSUE TITLE
date string parse not work on IE11 when timezone not contain colon

### ISSUE THREAD

**Issue by languanghao** [iamkun/dayjs#432]
From  [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) , it allows timezone with or without colon.

But dayjs can not work on ie11 when date string timezone without colon.  This is the example: https://jsbin.com/royewipupa/edit?html,js,console,output

**Comment by loveonelong** [comment]
The first, about your jsbin code:
`<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js' />` is invalid.
The correct way is `<script src=''></script>`.

I tested it on IE11.
`dayjs("2000-08-06T16:00:00.000+08:00").format('YYYY-MM-DD') -> 2000-08-06` is ok.
`dayjs("2000-08-06T16:00:00.000+0800").format('YYYY-MM-DD') -> NaN` failed.
IE11 does not support `+0100`.

You can view [http://dygraphs.com/date-formats.html](http://dygraphs.com/date-formats.html) or [https://segmentfault.com/a/1190000003710954?mType=Group](https://segmentfault.com/a/1190000003710954?mType=Group)

**Comment by iamkun** [comment]
try `CustomParseFormat`

**Comment by fabb** [comment]
I tried `'yyyy-MM-dd\'T\'HH:mm:ssZ'`, but it still does not parse.

**Comment by fabb** [comment]
I ended up inserting the colon with regex before passing it to dayjs...

```
isoDate.replace(/([+-]\d{2})(\d{2})$/g, '$1:$2')
```

**Comment by iamkun** [comment]
> I tried `'yyyy-MM-dd\'T\'HH:mm:ssZ'`, but it still does not parse.

@fabb a reproduction demo, please?

**Comment by fabb** [comment]
Same as the above demo, but with the parse format passed as 2nd parameter:
https://jsbin.com/jirosazeta/1/edit?html,js,console,output

**Comment by xxyuk** [comment]
@fabb 

You have to use `CustomParseFormat` plugin first.

```
dayjs.extend(customParseFormat)
```

after that you could pass format as 2nd parameter:
