### ISSUE TITLE
dayjs().isSame(dayjs(), 'year') not return expected result

### ISSUE THREAD

**Issue by lq920320** [iamkun/dayjs#433]
```
console.log(dayjs().isSame(dayjs(), 'year')); // true
console.log(dayjs('2018-12-19').isSame(dayjs(), 'year')); // false
console.log(dayjs().isSame(dayjs('2018-12-20'), 'year')); // false
console.log(dayjs('2018-12-20').isSame(dayjs('2018-12-22'), 'year')); // false
console.log(dayjs('2018-12-20').isSame(dayjs('2018-12-20'), 'year')); // true
```        
Was I use it in a wrong way?

**Comment by lq920320** [comment]
> Not problem with me. Got 5 'true' here https://runkit.com/embed/8ik32p25h1vv.

As I used dayjs.min.js file, and it return the wrong results. Copy the code form https://cdn.bootcss.com/dayjs/1.7.7/dayjs.min.js as a javascript file.

**Comment by lq920320** [comment]
> > Not problem with me. Got 5 'true' here https://runkit.com/embed/8ik32p25h1vv.
> 
> As I used dayjs.min.js file, and it return the wrong results. Copy the code form https://cdn.bootcss.com/dayjs/1.7.7/dayjs.min.js as a javascript file.

emm……     
I find the reason, the code on https://unpkg.com/dayjs@1.7.8/dayjs.min.js is right. Thanks a lot!

**Comment by lq920320** [comment]
https://unpkg.com/dayjs@1.7.7/dayjs.min.js  has this problem....

**Comment by LeiHanCN** [comment]
Apart from that, no other time unit can return the expected result.

```javascript
// The following four examples are expected to be true
// 1577164913000 => 2019-12-24 13:21:53,  1577164912000 => 2019-12-24 13:21:52
dayjs(1577164913000).isSame(dayjs(1577164912000), 'year') // false
dayjs(1577164913000).isSame(dayjs(1577164912000), 'month') // false
dayjs(1577164913000).isSame(dayjs(1577164912000), 'day')  // false
dayjs(1577164913000).isSame(dayjs(1577164912000), 'minute')  // false

// But the same time can be judged correctly in any time unit
dayjs(1577164913000).isSame(dayjs(1577164913000), 'year') // true
dayjs(1577164913000).isSame(dayjs(1577164913000), 'month') // true
```

**Comment by iamkun** [comment]
@LeiHanCN a demo, please?  Tested all `true` on my side.

https://runkit.com/embed/eaw4mvt2gk3l

**Comment by Shhuy** [comment]
In Firefox browser
dayjs('29991231').isSame('29991231', 'day') // true
dayjs('29991231').isSame('2999.12.31', 'day') // false
But in Chrome
dayjs('29991231').isSame('29991231', 'day') // true
dayjs('29991231').isSame('2999.12.31', 'day') // true
