### ISSUE TITLE
The conversion is incorrect. similar : 2018-12-26T20:12:36.000+0000

### ISSUE THREAD

**Issue by itning** [iamkun/dayjs#436]
```
dayjs("2018-12-26T20:12:36.000+0000").format("YYYY年MM月DD日 HH:mm:ss");
```
I got
```
2018年12月27日 04:12:32
```
What am I wrong?

**Comment by iamkun** [comment]
You forget your time zone.

This should be fine.
```
dayjs("2018-12-26T20:12:36.000+0800").format("YYYY年MM月DD日 HH:mm:ss");
```

**Comment by itning** [comment]
> You forget your time zone.
> 
> This should be fine.
> 
> ```
> dayjs("2018-12-26T20:12:36.000+0800").format("YYYY年MM月DD日 HH:mm:ss");
> ```

Is there a way to set the time zone? I can't change this string because it's a third-party api.

**Comment by DiamondYuan** [comment]
> > You forget your time zone.
> > This should be fine.
> > ```
> > dayjs("2018-12-26T20:12:36.000+0800").format("YYYY年MM月DD日 HH:mm:ss");
> > ```
> 
> Is there a way to set the time zone? I can't change this string because it's a third-party api.



you can 

```
dayjs("2018-12-26T20:12:36.000+0000").format("YYYY年MM月DD日 HH:mm:ss").add(-8,'hour')
```

**Comment by itning** [comment]
> > > You forget your time zone.
> > > This should be fine.
> > > ```
> > > dayjs("2018-12-26T20:12:36.000+0800").format("YYYY年MM月DD日 HH:mm:ss");
> > > ```
> > 
> > 
> > Is there a way to set the time zone? I can't change this string because it's a third-party api.
> 
> you can
> 
> ```
> dayjs("2018-12-26T20:12:36.000+0000").format("YYYY年MM月DD日 HH:mm:ss").add(-8,'hour')
> ```

Good idea,thanks.
