### ISSUE TITLE
dayjs(13timestamp) error

### ISSUE THREAD

**Issue by syymo** [iamkun/dayjs#437]
1.7.7  dayjs(13timestamp) error
`
$D: NaN
$H: NaN
$L: "en"
$M: NaN
$W: NaN
$d: Invalid Date {}
$m: NaN
$ms: NaN
$s: NaN
$y: NaN
`
![image](https://user-images.githubusercontent.com/26571594/50472220-ddd57400-09f2-11e9-85ff-2f87ae6df2b6.png)

1.7.8  dayjs(13timestamp) error  
![image](https://user-images.githubusercontent.com/26571594/50472253-f5acf800-09f2-11e9-9c84-ce7021b99302.png)

**Comment by syymo** [comment]
Your docs says it supports 13-bit timestamps
![image](https://user-images.githubusercontent.com/26571594/50472860-8be21d80-09f5-11e9-9c53-72ec02430c1b.png)
i use your docs 13timestamp still NaN-NaN-NaN

**Comment by xxyuk** [comment]
@syymo if you pass a timestamp in `Number` (10 bit or 13bit), it should work as you expected. 

check this
https://runkit.com/embed/7sqrjpnbelky

**Comment by syymo** [comment]
i find dayjs() can't accept a string, dayjs.unix() can accpet string but format time is wrong. thanks

**Comment by xxyuk** [comment]
cause you can't tell '20180101' is a 'yyyymmdd' time string or just a timestamp.

**Comment by syymo** [comment]
I don't think it's a timestamp problem. It's a type problem.I try same string and number but resolve is'not same.

**Comment by xxyuk** [comment]
@syymo any online code?

and dayjs.unix() can accept a 10-bit string and the formatting should be correct.

**Comment by syymo** [comment]
yes,but I don't understand why dayjs.unix() can accept string but dayjs() can't.

**Comment by xxyuk** [comment]
well then, according to your words,  how can we know `days('19700101')` means 1901-01-01 or 19700101 in Number as a timestamp?

**Comment by loveonelong** [comment]
About prase as an invalid date. #430
