### ISSUE TITLE
It is necessary to check parameters in comparative method

### ISSUE THREAD

**Issue by faremax1992** [iamkun/dayjs#442]
Here is a bug:
`dayjs().isSame(undefined, 'date');    //true`

I think it is necessary to check the first params in this method. like below plugin:

```
function (option, dayjsClass, dayjsFactory){
    dayjsClass.prototype.isSameDate = function (date) {
        if (!date) { .  // it is necessary
              return false;
        }
        const day = dayjsFactory(date);    // if date is undefined, here gets an object as current time
        return this.format(FORMAT) === day.format(FORMAT);
    };
}
```

**Comment by loveonelong** [comment]
I think the better way is `if(!isDayjs(date)) return false`.

**Comment by loveonelong** [comment]
Had `isSame(dayjs: Dayjs, unit?: UnitType): boolean`  in index.d.ts

**Comment by faremax1992** [comment]
@loveonelong 
`if(!isDayjs(date)) return false`
This way is not compatible the input of original Javascript `Date` object and UTC date string.

Now, There is already compatibility code like `const day = dayjsFactory(date);` in code.

**Comment by loveonelong** [comment]
Emmmm, I used Dayjs in my project with typescript. If you follow the `index.d.ts`, only Dayjs is allowed.
But does not rule out that some people used Javascript Date object or UTC date string.
Maybe you are right.

**Comment by iamkun** [comment]
@faremax1992 Day.js parse `dayjs(undefined)`  to `new Date()`, which is the same with `dayjs()`,
that's why `dayjs().isSame(undefined)` returns True.

**Comment by faremax1992** [comment]
> @faremax1992 Day.js parse `dayjs(undefined)` to `new Date()`, which is the same with `dayjs()`,
> that's why `dayjs().isSame(undefined)` returns True.

Yep, I see. But you got a `true` on `dayjs().isSame(date)` when the param `date` is `undefined` accidentally. It is very ambiguous.
I have an advice that checking the param of `isSame()` in method and providing another method named `isToday()`.Let it be unambiguous.

**Comment by xxyuk** [comment]
`moment().isSame(undefined, 'date')` returns `true` either

**Comment by faremax1992** [comment]
> `moment().isSame(undefined, 'date')` returns `true` either

OK. To keep them the same is more necessory. Thank you
