### ISSUE TITLE
Npm 安装的包里并没有 官方插件CustomParseFormat

### ISSUE THREAD

**Issue by gee1k** [iamkun/dayjs#449]
Npm 安装的包里并没有 官方插件CustomParseFormat
![image](https://user-images.githubusercontent.com/12059800/51087866-993c2d80-1793-11e9-83d5-a62984dd0bd0.png)

**Comment by iamkun** [comment]
CustomParseFormat代码刚刚合并到master 这一两天就会发布到 npm 请期待

**Comment by gee1k** [comment]
@iamkun 好的，麻烦有时间的话尽快哟。dayjs 挺好用的。我正需要使用这个功能 💯
