### ISSUE TITLE
customParseFormat format pattern validation

### ISSUE THREAD

**Issue by felixbecker** [iamkun/dayjs#459]
Hi, 

I had a hard time with the `customParseFormat` plugin since the date format pattern passed in to the constructer does not get validated for correct characters (or at least hints or warnings).

`dayjs('23.09.1950','DD.MM.yyyy');` parses as NaN
while `dayjs('23.09.1950','DD.MM.YYYY');` will parse ok.

While other programming languages support `Y` as well as `y` 

So this is not a big one and maybe only me that was not reading the docs thoroughly. ;-) 
I just wanted to report my finding in case someone cares ... a hint would have saved me time.

Anyway if this is not something you want to consider I am also ok with closing the issue

**Comment by iamkun** [comment]
Sorry, we have no plan to support this. Just use `Y` please.
