### ISSUE TITLE
dayjs('2018-12-31').week()

### ISSUE THREAD

**Issue by pandly** [iamkun/dayjs#460]
i think the result is 53 not 1

**Comment by naulacambra** [comment]
Which version are you using?

Check this [example](https://codepen.io/naulacambra/pen/zyVWRe?editors=1111) with version 1.8.0. Both `moment` and `dayjs` returns 1

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
