### ISSUE TITLE
How to convert to UTC?

### ISSUE THREAD

**Issue by aibrahim3546** [iamkun/dayjs#462]
I am struggling to convert my date to UTC.

Here is how I did it:

Normal conversion
```
console.log(dayjs('11-11-2018').format());
// output: 2018-11-11T00:00:00+08:00
```

UTC conversion
```
console.log(dayjs('11-11-2018', { utc: true, }).format());
// output: 2018-11-11T00:00:00+08:00
```

Both outputs are still showing in my timezone.

**Comment by xxyuk** [comment]
No support at present, however an UTC plugin is working in progress.

**Comment by aibrahim3546** [comment]
So at the moment are there any other tricky way for the conversion?

**Comment by aibrahim3546** [comment]
It looks like currently only momentjs able to perform this.

**Comment by karlmosenbacher** [comment]
@xxyuk whats the status with the UTC plugin?

**Comment by xxyuk** [comment]
@karlmosenbacher Will be avaliable in next version v1.8.9, maybe in two weeks I hope.

**Comment by iamkun** [comment]
Yes, please check.

https://day.js.org/docs/en/parse/utc

**Comment by vaynevayne** [comment]
```jsx
console.log(dayjs('11-11-2018', { utc: true, }).format());
```
this api design is better, Why not follow suit
