### ISSUE TITLE
ie11 (and other 'es5'-browsers) problem with transpile

### ISSUE THREAD

**Issue by yyynnn** [iamkun/dayjs#477]
Dayjs not transpiling down to es5 on version 1.8.4, leaving es6 code in bundle. (the babel/ts webpack config is fine)

1.7.4 is the last know working version

**Comment by xxyuk** [comment]
Just checked the final code in v1.8.4, everything looks fine in es5.

Any further information please?

**Comment by paulgv** [comment]
I've had the same issue after upgrading from 1.7.8 to 1.8.4, IE11 was logging a SyntaxError because of some arrow function in dayjs.
In dev mode, the error pointed to this line: https://github.com/iamkun/dayjs/blob/dev/src/index.js#L8

**Comment by gkkirsch** [comment]
This is also happening to us. We are using an ejected version of create react app's webpack build script with minimal changes. The build script isn't able to minify the js. It might not even get to the transpilers. 
![screen shot 2019-02-05 at 5 03 28 pm](https://user-images.githubusercontent.com/8840461/52312505-05abe600-2968-11e9-97b4-790fe89b78fc.jpg)

**Comment by Tvrqvoise** [comment]
@iamkun I think you have two options to fix this:

1. still transpile the "module" entrypoint, but don't transpile es6 modules.  This will let people who support the module entry (webpack et al) use es6 imports with tree shaking and whatnot, but will still run fat arrows, `const`s, and so on through webpack.
1. publish a new version which removes the `module` field entirely.  Then, publish a new major version with the module field back in and tell people to explicitly pass `dayjs` through babel themselves.  This would mean any webpack users would have to add an exception in their babel loader includes / excludes for `dayjs` specifically.  Not sure what the implication is for other module systems. This would make `dayjs` harder to use for people, but could have a small benefit in terms of module size.

For what it's worth, I prefer the first option.  I could open a PR for this too, if you're interested.

**Comment by iamkun** [comment]
option 1 pr welcome 😁

**Comment by iamkun** [comment]
Try hotfix v1.8.5, contains @Tvrqvoise's fix

**Comment by Tvrqvoise** [comment]
Confirmed that v1.8.5 works for me.  Thanks @iamkun for the quick updates and the great library!

**Comment by yyynnn** [comment]
yeah cool
