### ISSUE TITLE
add fromNow API ?

### ISSUE THREAD

**Issue by xcheese** [iamkun/dayjs#50]
Moment.fromNow

**Comment by bazjapan** [comment]
+1

**Comment by BSprite** [comment]
I think if fromNow is added, it needs to fit the objective of the project and remain a very lean function.  That's the reason I jumped on this in the first place is the kb weight vs moment.

If you look at moment, fromNow is a very robust function.

Definitely a really good part of it though.

**Comment by andylima** [comment]
There's a `Intl.RelativeTimeFormat` API for JS being developed within the TC39 — It's described as:
> Intl.RelativeTimeFormat is a low level API to facilitate libraries and frameworks to format relative time in a localized fashion by providing internationalized messages for date and time fields, using customary word or phrase when available.

Proposal page: https://github.com/tc39/proposal-intl-relative-time

As of 2018-04-29 it is at Stage 3 (Candidate Stage — Proposal is ready for implementations to gather more feedback) — for its up-to-date status, you can check here: 
[ECMAScript Internationalization API Specification proposals](https://github.com/tc39/proposals/blob/master/ecma402/README.md) page

It seems the final, full API is still being worked out.

Regarding a polyfill (or something close to it) these libraries may deserve a look:

- https://github.com/yahoo/intl-relativeformat
- https://github.com/catamphetamine/javascript-time-ago/blob/master/source/RelativeTimeFormat.js

...There will also be an official polyfill.

**Comment by aalises** [comment]
Just added a simple implementation based on timeago.js which can be seen at [#83](https://github.com/xx45/dayjs/pull/83) , WDYT?

**Comment by iamkun** [comment]
@aalises Nice code, thanks. We are adding locales support at the moment. And I think, APIs like fromNow should be shipped with locales out of box. Pr pending, but won't too long.

**Comment by aalises** [comment]
@iamkun Perfect! let me know if you need something, will be glad to help.

**Comment by iamkun** [comment]
@aalises Come join us here #92 #90.

**Comment by iamkun** [comment]
@xcheese @bazjapan @loo41 @BSprite @andylima  @aalises
added in release 1.6.4.🎊 🎉

check [RelativeTime Plugin](https://github.com/iamkun/dayjs/blob/master/docs/en/Plugin.md#relativetime)
