### ISSUE TITLE
Mocking the current date and time

### ISSUE THREAD

**Issue by kirakik** [iamkun/dayjs#500]
Hello,

I've been trying to write tests to check whether a person's age is higher or lower than some pre set thresholds. The issue is that I haven't been able to figure out how to mock the current date and time used by `dayjs`. Before switching, we were using `moment`, and it used the default `Date.now`, so mocking that was enough to get our tests to work, but here you seem to use something else... I've tried mocking manually as well as using some external libraries like `mockdate` and `jest-mock-date`, but no luck.

Is there something in particular that I need to do to mock the current date using `dayjs`?

Thank you!

**Comment by iamkun** [comment]
We use `mockdate` in our test, check here as a reference.

https://github.com/iamkun/dayjs/blob/dev/test/parse.test.js#L6

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
