### ISSUE TITLE
dayjs.toISOString() without seconds and/or milliseconds

### ISSUE THREAD

**Issue by waghcwb** [iamkun/dayjs#504]
How can I get a ISO string date format without the seconds and/or milliseconds on the output?

I know that I can do this
```js
import dayjs from "dayjs";

document.getElementById("app").innerHTML = dayjs("18/09/1995", "DD/MM/YYYY")
  .toISOString()
  .split(".")
  .slice(0, -1);
```

But, the plugin doesn't offer a way to get the output without the seconds and/or milliseconds like in luxon/moment?

```js
DateTime
  .fromFormat('18/09/1995', 'dd/LL/yyyy', { locale: 'pt-BR' })
  .toISO({ includeOffset: false, suppressMilliseconds: true })
```

**Comment by iamkun** [comment]
You could use `.format()` with the tokens you want.

**Comment by waghcwb** [comment]
@iamkun,

I don't want to show the date with a specific format, I want to set the date from a specific format. In Brazil the dates are in this format "DD/MM/YYYY" and not "MM/DD/YYYY", so when I get a date from user input, I will receive "18/09/1995" and not "09/18/1995".

**Comment by waghcwb** [comment]
@iamkun,

Thank you.

```js
dayjs(birthdayMasked, 'DD/MM/YYYY').format('YYYY-MM-DDTHH:mm:ss')
```
