### ISSUE TITLE
How to install plugins via npm?

### ISSUE THREAD

**Issue by waghcwb** [iamkun/dayjs#505]
Hi, 

I'm trying to install a "native" plugin (CustomParseFormat), but didn't handle how to do it.

This plugin doesn't come to the npm package

![image](https://user-images.githubusercontent.com/6169950/53135147-e95b9c00-3558-11e9-9f7c-728d4f030516.png)

And if I try to install like this, I get an error.

`npm i dayjs/plugin/customParseFormat -D`

I've found a workaround by getting the source code of the plugin and installing it manually.

By copying and pasting [this file](https://github.com/iamkun/dayjs/blob/dev/src/plugin/customParseFormat/index.js) and importing the plugin manually.

I miss a section at the docs on how to install plugins with npm.

**Comment by iamkun** [comment]
Please try our latest version. (Current v1.8.6)

**Comment by waghcwb** [comment]
@iamkun,

You're right I was using the wrong version for some reason

![image](https://user-images.githubusercontent.com/6169950/53173688-ee573480-35c6-11e9-80df-7f3f08be1a19.png)
