### ISSUE TITLE
Wrong info at documentation about customparseformat plugin

### ISSUE THREAD

**Issue by waghcwb** [iamkun/dayjs#506]
The [docs say](https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat) that we need to pass a string with the date format, like this

`dayjs('05/02/69 1:02:03 PM -05:00', 'MM/DD/YY H:mm:ss A Z')`

But, this give us an error, the correct way to use the plugin is with a object with `format` param

`dayjs('18/09/1995', { format: 'DD/MM/YYYY' })`

**Comment by iamkun** [comment]
Maybe relate to #505, please check your version first.
