### ISSUE TITLE
Trying to check card expiry

### ISSUE THREAD

**Issue by tcrands** [iamkun/dayjs#513]
Hi,

I'm currently migrating our project from moment to dayjs and we have a function to check card expiry: 

```
export function isExpired(date) {
  const currentDate = moment();
  const expiryDate = moment(date, 'MM-YY').endOf('month');
  return expiryDate.isBefore(currentDate, 'second');
}
```

However I'm getting different outputs from dayjs and moment when creating the data with the format `MM-YY` and the value `01/22`

```
moment('01/22', 'MM-YY') // 2022-01-01T00:00:00.000
dayjs('01/22', 'MM-YY') //2001-01-22T00:00:00.000
```

Could anyone give me a hand on how I can go about replicating the `isExpired` function with dayJs?

**Comment by xxyuk** [comment]
try CustomParseFormat plugin

**Comment by tcrands** [comment]
Worked perfectly thanks 👍
