### ISSUE TITLE
CustomParseFormat doesn't parse ordinals correctly when AdvancedFormat is enabled

### ISSUE THREAD

**Issue by injms** [iamkun/dayjs#522]
**Describe the bug**
When using `AdvancedFormat` plugin that allows ordinals, the `CustomParseFormat` plugin doesn't parse dates that have ordinals. So:

```javascript
dayjs('7th March 2019', 'Do MMMM YYYY')
```

returns 

```javascript
{ [Number: NaN]
  '$L': 'en',
  '$u': undefined,
  '$d': Invalid Date,
  '$y': NaN,
  '$M': NaN,
  '$D': NaN,
  '$W': NaN,
  '$H': NaN,
  '$m': NaN,
  '$s': NaN,
  '$ms': NaN }
```

**Expected behavior**
When both `AdvancedFormat` and `CustomParseFormat` plugins are enabled

```javascript
dayjs('7th March 2019', 'Do MMMM YYYY')
```

should return a dayjs object, either with or without the ordinal defined in it:

```javascript
{ [Number: 1551916800000]
  '$L': 'en',
  '$u': undefined,
  '$d': '2019-03-07T00:00:00.000Z',
  '$y': 2019,
  '$M': 2,
  '$D': 7,
  '$o': 'th', // maybe?
  '$W': 4,
  '$H': 0,
  '$m': 0,
  '$s': 0,
  '$ms': 0 }
```

**Information**
 - Day.js version 1.8.9
 - OS: Windows Subsystem Linux using Node v9.11.2

**Comment by iamkun** [comment]
It's not a bug related to `AdvancedFormat`,  just because `CustomParseFormat ` does not have the ability to parse token like `Do` at this version.

**Comment by injms** [comment]
I was just thinking that because `AdvancedFormat` can output `Do`, should `CustomParseFormat` be able to parse `Do`?

**Comment by iamkun** [comment]
>  should CustomParseFormat be able to parse Do?

This will be a feature request. I think it's good to have.

**Comment by injms** [comment]
Thank you 😄
