### ISSUE TITLE
Feature Request - Control the accuracy of RelativeTime

### ISSUE THREAD

**Issue by Newbie012** [iamkun/dayjs#523]
The `RelativeTime` plugin is pretty useful. But it has its cons.

The current output of `RelativeTime` would be as specific as the amount of the current time units (e.g 44 seconds, 14 minutes, 3 hours) but not such as "1 hour and 2 minutes".

My suggestion is to control the accuracy of the relative time. For example:

### Time from now `.fromNow(RelativeTimeOpts)`

```
type TimeUnit = 'seconds' | 'minutes' | 'hours' | 'days' | 'months' | 'years';

interface RelativeTimeOpts {
  withoutSuffix?: boolean;
  untilUntil?: TimeUnit;
}
```

This way, when we type `.fromNow({untilUntil: 'seconds'})` it will print:

---

 **2 hours, 25 minutes and 3 seconds ago**.

---

I guess that there's a better name than `untilUnit` out there, but you got the point :)

PS - I was sort-of already suggested it here - https://github.com/iamkun/dayjs/issues/414 but in a different way.

**Comment by iamkun** [comment]
Thanks. Maybe we should add a `dayjs.duration` plugin to better fits this situation.

**Comment by waseemahmad31** [comment]
I can try to implement this feature.

**Comment by iamkun** [comment]
@waseemahmad31 Maybe adding a `duration` plugin is better?

**Comment by iamkun** [comment]
#564 todo: Duration plugin
