### ISSUE TITLE
Typescript definition allows `quarter` as unit of time

### ISSUE THREAD

**Issue by choffmeister** [iamkun/dayjs#531]
**Describe the bug**

According to the typescript definition, this is valid:

```ts
val now = dayjs()
val nextQuarter = now.add(1, 'quarter')

now.valueOf() == nextQuarter.valueOf() // true
```

**Expected behavior**
Either the quarter calculation should work or the typescript definition should not allow passing `'quarter'` as unit of time.

**Information**
 - Day.js Version: 1.8.10

**Comment by iamkun** [comment]
Thanks, will fix soon

**Comment by iamkun** [comment]
Please use our `QuarterOfYear` plugin to get full `quarter` support after version 1.8.11.
```
import quarterOfYear from 'dayjs/plugin/quarterOfYear'

dayjs.extend(quarterOfYear)

dayjs().startOf('quarter') 
dayjs().add(1, 'quarter')
```

https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#quarterofyear
