### ISSUE TITLE
DayJS swap date with format

### ISSUE THREAD

**Issue by yTakkar** [iamkun/dayjs#532]
I have a date `09091998` and want to convert it to `YYYYMMDD` format which will result in `19980909`.

Below is my implementation,
```javascript
const date = '09091998'
const formattedDate = dayjs(date).format('YYYYMMDD')
console.log(formattedDate) // returns 9101006 instead of 19980909
```

Is there something wrong in my implementation?
Thnx in advance :)

**Comment by iamkun** [comment]
use `customParseFormat` plugin, please.

**Comment by yTakkar** [comment]
Thnx it worked like charm
