### ISSUE TITLE
Need help understanding how to use dayjs to stop safari from adjusting to GMT

### ISSUE THREAD

**Issue by NJM8** [iamkun/dayjs#534]
Hello, 
Thank you for the great library!

I am having problems with Safari adjusting for GMT and producing different dates. Can anyone advise how to properly use dayjs to format these dates? My two use cases are to compare a date to now (GMT is adding 5 hours to the comparison), and to format a date for display.

Here is the comparison:

```js
      import dayjs from "dayjs";
      import utc from "dayjs/plugin/utc";
      dayjs.extend(utc);
      // example date from backend: 2018-12-28 14:52:48.000000
      const lastUpdate = dayjs.utc(lastChanged.date.split(" ").join("T")); // need T or I get an undefined date.
      const now = dayjs.utc();
      const diff = now.diff(lastUpdate, "hours");
      console.log("day js dates and diff using utc");
      console.log(lastUpdate);
      console.log(now);
      console.log(diff);
```

In FF this is returning the correct UTC date:
https://ibb.co/vDgwZFh
But in Safari this still returns a GMT date:
https://ibb.co/GcKWS9c

My other case is just to format the date, sometimes Safari returns the incorrect date as I believe it is adjusting the time again.

```js
      dateToFormat = dateToFormat.split(" ").join("T");
      if (!dayjs(dateToFormat).isValid()) {
        throw `Expected a valid date in formatDate, received: ${dateToFormat}`;
      }
      return new dayjs(dateToFormat).format("YYYY-MM-DD");
```

I know there is a lot of information about this issue out there but I'm just not quite understanding how to correctly format and compare these dates with dayjs. Any help is much appreciated.

**Comment by iamkun** [comment]
try to use `dayjs().format()` to get the correct UTC format. There's no need to print the dayjs object instance.

**Comment by NJM8** [comment]
I'm not sure I follow you? I'm not printing the instance for use I'm comparing the dates:
This code: 
```js
      const l = dayjs.utc(lastChanged.date.split(" ").join("T"));
      const n = dayjs.utc();
      const t = n.diff(l, "hours");
      console.log(l.isUTC());
      console.log("day js dates and diff using utc");
      console.log(l);
      console.log(l.format());
      console.log(n.format());
      console.log(t);
```

Produces this is FireFox:
```
true 

day js dates and diff using utc 

Object { "$L": "en", "$u": true, "$d": Date 2019-01-25T03:32:33.000Z, "$y": 2019, "$M": 0, "$D": 25, "$W": 5, "$H": 3, "$m": 32, "$s": 33, … }

2019-01-25T03:32:33Z 

2019-03-15T17:55:00Z 

1190 
```

And this in Safari: 
```js
[Log] true
[Log] day js dates and diff using utc
[Log] f {$L: "en", $u: true, $d: Thu Jan 24 2019 17:32:33 GMT-0500 (EST), $y: 2019, $M: 0, …}
[Log] 2019-01-24T22:32:33Z
[Log] 2019-03-15T17:55:10Z
[Log} 1195
```
As you can see the dayjs object in Safari has $u: true indicating it is a UTC date but the date $d still shows the GMT -500 (EST), which on the last line messes up the hour difference (1190 versus 1195). So the question is how do I prevent the Safari dayjs object from using GMT.

**Comment by NJM8** [comment]
Got it figured out. Without Z Safari treats the incoming date as a local date not a UTC date so it is adjusting the time from local to UTC on a UTC date. 

Final code the produces the same result across browsers: 
```js
      const diff = dayjs
        .utc()
        .diff(dayjs(`${lastChanged.date.split(" ").join("T")}Z`), "hours");
```

**Comment by xxyuk** [comment]
How about using `customParseFormat` plugin to deal with such un-ISO date format?

**Comment by NJM8** [comment]
@xxyuk I tried to do that but couldn't get it to work with Safari, I forget exactly how I tried it but ended up with an invalid date in safari. Do you have an example of how to do it?

**Comment by xxyuk** [comment]
You should install `utc` and `customParseFormat` plugins according to the document.

Then just 
```
dayjs.utc('2018-01-01', 'YYYY-MM-DD') // with CustomParseFormat plugin
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
