### ISSUE TITLE
Talk to us on Gitter  联系作者微信 🤡😬😈

### ISSUE THREAD

**Issue by iamkun** [iamkun/dayjs#540]
Talk to us on Gitter: 
<a href="https://gitter.im/iamkun/dayjs"> 
<img width="200" src="https://user-images.githubusercontent.com/17680888/54799936-5b2f1e80-4c9a-11e9-84f9-d40124e9f937.png" alt="dayjs gitter">
</a>

https://gitter.im/iamkun/dayjs

----------------------------
For Chinese User

<img width="200" src="https://user-images.githubusercontent.com/17680888/54799735-67ff4280-4c99-11e9-995a-4372e7538d1f.png" alt="iamkun wechat">

**Comment by stunaz** [comment]
maybe spectum.chat?

**Comment by xiaomizhou66** [comment]
dayjs 怎么在微信小程序使用呀
