### ISSUE TITLE
How to use localeData ?

### ISSUE THREAD

**Issue by y0c** [iamkun/dayjs#542]
Hi 
i want to change moment.js to day.js in my library.

I wonder how to use localaleData in day.js.
In case of moment.js 
```javascript
moment.localeData(locale).monthsShort()
```

**Comment by iamkun** [comment]
@y0c 

We have an experimental plugin `localeData` from v1.8.10

```javascript
import dayjs from 'dayjs'
import localeData from 'dayjs/plugin/localeData'
import 'dayjs/locale/ko'

dayjs.extend(localeData) // use plugin
dayjs.locale('ko') // use locale

dayjs().localeData().monthsShort(dayjs())
```
demo: https://runkit.com/embed/488qfv8m02rz

feedback is welcomed.

**Comment by y0c** [comment]
Great, Thanks ! :)

**Comment by gpbl** [comment]
Isn't there a way to get the locale object from a dayjs date? 

Also I find the syntax for `dayjs().localeData().monthsShort(dayjs())` a bit confusing. Which one of the two `dayjs()` instances should be the localized ones? Why do i have to pass to `dayjs()` instances and not just `dayjs().localeData()`?

Thanks.

**Comment by iamkun** [comment]
updates #645

**Comment by transtone** [comment]
weeksMin, weeksSort ?

**Comment by iamkun** [comment]
@transtone  do you mean `weekdaysMin` `weekdaysShort`  ?
