### ISSUE TITLE
dayjs({seconds: 0}).format('mm:ss') return Invalid Date,but moment is work

### ISSUE THREAD

**Issue by Lihyrs** [iamkun/dayjs#547]
It's similar to the issue [#96](https://github.com/iamkun/dayjs/issues/96)

The package.js is:
```json
"dependencies": {
    ...
    "dayjs": "^1.8.11",
    "moment": "^2.24.0",
     ...
  },
```

**Comment by xxyuk** [comment]
@Lihyrs

As for as I know, dayjs does not support parsing object like `{seconds: 0}`

**Comment by iamkun** [comment]
We just released the ObjectSupport plugin to support this. https://day.js.org/docs/en/plugin/object-support
