### ISSUE TITLE
localizedFormat plugin is interpolating content inside square brackets

### ISSUE THREAD

**Issue by mariomc** [iamkun/dayjs#550]
**Describe the bug**
localizedFormat plugin is changing/interpolating content inside square brackets

```javascript
const dayJSformat = dayjs.format('[L]') // outputs: 29/03/2019
const momentFormat = moment.format('[L]') // outputs [L]
expect(dayJSformat).toEqual(momentFormat) // throws
```

**Expected behavior**
localizedFormat plugin should uphold behavior of the original format method and not change/interpolate content inside square brackets

**Information**
 - Day.js Version: all
 - OS: all
 - Browser: all

**Comment by mariomc** [comment]
If you want, i'll include this fix inside https://github.com/iamkun/dayjs/pull/546

**Comment by xxyuk** [comment]
Sounds good

**Comment by iamkun** [comment]
#546
