### ISSUE TITLE
Performance on browsers other than Chrome

### ISSUE THREAD

**Issue by kakadiadarpan** [iamkun/dayjs#553]
**Describe the bug**
Dayjs is considerably slower on Safari and Firefox when compared with Chrome

**Expected behavior**
A comparable performance with the native date operations

**Information**
 - Day.js Version: 1.8.11
 - OS: MacOS
 - Browsers: Chrome, Safari, Firefox

Test code:
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>title</title>
</head>

<body>
</body>
<!-- Latest compiled and minified JavaScript -->
<script src="https://unpkg.com/dayjs@1.8.11/dayjs.min.js"></script>
<script>
    const iterations = 50;
    const performanceTest = ( type, testFunction ) => {
        console.time( type );
        for ( let i = 0; i < iterations; i++ ) {
            testFunction();
        }
        console.timeEnd( type );
    };
    function dayjsDate() {
        const day = dayjs( )
    }
    function nativeDate() {
        const day = new Date( )
    }
    function dayjsDiff() {
        const day = dayjs( '2007-01-27' ).diff( dayjs( '2007-01-29' ), 'milliseconds' );
    }
    function nativeDiff() {
        const n = new Date( 2007, 0, 27 ) - new Date( 2007, 0, 29 );
    }
    performanceTest('Dayjs date', dayjsDate)
    performanceTest('Native date', nativeDate)
    performanceTest('Dayjs diff', dayjsDiff)
    performanceTest('Native diff', nativeDiff)
</script>

</html>
```

Results:
Safari:
![Screenshot 2019-04-02 at 09 20 39](https://user-images.githubusercontent.com/10805593/55384129-289ee480-552a-11e9-9b05-438a81ea9bc5.png)

Firefox:
![Screenshot 2019-04-02 at 09 21 22](https://user-images.githubusercontent.com/10805593/55384125-250b5d80-552a-11e9-8b0a-82dd51936184.png)

Chrome:
<img width="1263" alt="Screenshot 2019-04-02 at 09 28 52" src="https://user-images.githubusercontent.com/10805593/55384118-1e7ce600-552a-11e9-9816-32db7bcfd523.png">

**Comment by xxyuk** [comment]
Day.js `.diff` has quite a lot of logic of comparing between day, year and so on.

So the appropriate compare test should be 

```
function dayjsDiff() {
    const day = dayjs( '2007-01-27' ) - dayjs( '2007-01-29' );
}
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
