### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by ryanoshea** [iamkun/dayjs#56]
Could we include a typing declaration for use with TypeScript?

**Comment by iamkun** [comment]
Coming soon. Check out our road map here #39

**Comment by iamkun** [comment]
Seems we already have a pr #37 here. I'm new to TS, anyone could give it a review? THX

**Comment by iamkun** [comment]
Plus, @varHarrie what's this file `index.d.test.ts` used for?

**Comment by iamkun** [comment]
@ryanoshea @varHarrie Type definitions comes in release 1.5.23 thanks.😁

**Comment by iamkun** [comment]
released , close
