### ISSUE TITLE
startOf('week') doesn't start at midnight

### ISSUE THREAD

**Issue by kstadler** [iamkun/dayjs#562]
**Describe the bug**
startOf('week') doesn't start at midnight of the beginning of the week

**Expected behavior**
everything starting from the hour part of the date should  be zero

**Information**
- Day.js 1.8.2.
- TZ Europe/Berlin
- Reproduce by calling dayjs('2019-03-03T23:00:00.000Z').startOf('week')
- Same problem occurs with endOf

**Comment by xxyuk** [comment]
> everything starting from the hour part of the date should be zero

https://runkit.com/embed/i3dney0xh5ww

works fine here.

**Comment by kstadler** [comment]
strange... maybe that server is on UTC timezone so that there are no differences?

**Comment by iamkun** [comment]
Any reproduction link or repo, please?

**Comment by kstadler** [comment]
I don't know any online js tools that have a different timezone from utc, so I can't pursue this further.
Should we close the issue?

**Comment by iamkun** [comment]
Maybe. Feel free to reopen if you have updates on this
