### ISSUE TITLE
Add Request day().add(object)

### ISSUE THREAD

**Issue by hijazikaram** [iamkun/dayjs#575]
**Describe the bug**
Hi,

I kind of like this project, I'd like to use it to add an object instead of just using add(value: number, unit: string). I was using moment before but im moving into using dayjs because its way smaller. 

**Expected behavior**
`const maxTimestamp = moment(this.endDate.value.valueOf())
            .utc()
            .startOf('day');
 maxTimestamp.add({
                    hours: minTime.slice(0, 2),
                    minutes: minTime.slice(3, 5)
                });`
Trying to switch that into:
`const maxTimestamp = day(this.endDate.value.valueOf())
            .utc()
            .startOf('day');
 maxTimestamp.add({
                    hours: minTime.slice(0, 2),
                    minutes: minTime.slice(3, 5)
                });`
**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]

**Comment by xxyuk** [comment]
> Trying to switch that into: 

Exact the same with above line?

**Comment by hijazikaram** [comment]
the first one im using moment, trying to use dayjs instead

**Comment by hijazikaram** [comment]
@xxyuk

**Comment by iamkun** [comment]
Yes, we could support this as a plugin to add a time object.

**Comment by hijazikaram** [comment]
Having the same issue with this 
`startDateTime = startDateTime.set({
                hour: startTime.get('hours'),
                minutes: startTime.get('minutes'),
                seconds: startTime.get('seconds')
            });
            endDateTime = endDateTime.set({
                hour: endTime.get('hours'),
                minutes: endTime.get('minutes'),
                seconds: startTime.get('seconds')
            });`

**Comment by hijazikaram** [comment]
dayjs doesnt let you set an object

**Comment by iamkun** [comment]
What's the best name for these two plugins?

`AdvancedGet` `SetObject` `AdvancedAddSubtract`?

**Comment by hijazikaram** [comment]
AdvancedGet AdvancedSet

**Comment by hijazikaram** [comment]
etc...

**Comment by iamkun** [comment]
But add && subtract is actually the same function, so there's no need adding two separate `AdvancedAdd` & `AdvancedSubtract`, but if there's only one AdvancedAdd,  it may get some user confusing that why no AdvancedSubtract.

**Comment by hijazikaram** [comment]
You can do AdvancedAddSubtract

**Comment by hijazikaram** [comment]
Can you hit me up when you add them please so i can close this issue
Thanks!

**Comment by iamkun** [comment]
Sure. You could do `dayjs.add().add().add()` at this moment.

**Comment by hijazikaram** [comment]
wow i didnt know that you can do that lol

**Comment by hijazikaram** [comment]
can i do the same with .set

**Comment by hijazikaram** [comment]
I did something like this for the .add
`const minutes =
                    +(minTime.slice(0, 2) * 60) + +minTime.slice(3, 5);
                newMinTimestamp = minTimestamp.add(minutes, 'minute');
                minTimestamp = newMinTimestamp;`

**Comment by hijazikaram** [comment]
@iamkun is it possible i can do this  endTime = day(df.endTime, 'HH:mm:ss'); instead of  endTime = moment(df.endTime, 'HH:mm:ss'). Doing it right now will return NAN

**Comment by iamkun** [comment]
yes, `customParseFormat` plugin, please.

**Comment by hijazikaram** [comment]
i have it added but its not doing anything

**Comment by hijazikaram** [comment]
do i have to do something like day.customParseFormat()

**Comment by iamkun** [comment]
online demo, please.

**Comment by hijazikaram** [comment]
`import * as moment from 'moment';
import * as day from 'dayjs';
import * as utc from 'dayjs/plugin/utc';
import * as customParseFormat from 'dayjs/plugin/customParseFormat';
day.extend(customParseFormat);
day.extend(utc);
public updatetime() {
        const df = this.dateFilter;
        let startDateTime = moment(df.startDate);
        let endDateTime = day(df.endDate);
        let startTime = day()
            .utc()
            .startOf('day');
        let endTime = day()
            .utc()
            .endOf('day');
            console.log(endTime)
        if (df.startTime) {
            startTime = day(df.startTime, 'HH:mm:ss');
        }
        if (df.endTime) {
            console.log(df.endTime)
            console.log(day(df.endTime).format('HH:mm:ss'))
            endTime = day(df.endTime, 'HH:mm:ss');
        }
        startDateTime = startDateTime.set({
            hour: startTime.get('hour'),
            minutes: startTime.get('minute'),
            seconds: startTime.get('second')
        });
        // endDateTime = endDateTime.set({
        //     hour: endTime.get('hours'),
        //     minutes: endTime.get('minutes'),
        //     seconds: startTime.get('seconds')
        // });
        df.startDate = startDateTime.toDate();
        df.endDate = endDateTime.toDate();
    }`

**Comment by hijazikaram** [comment]
@iamkun hope this helps

**Comment by hijazikaram** [comment]
drf.endtime should always equal something like 12:04

**Comment by hijazikaram** [comment]
I think i got it, im sending in a a time that doesnt have seconds, its breaking it. In moment, if the time doesnt have seconds, it automatically add the seconds to the time :00

**Comment by iamkun** [comment]
We just released the ObjectSupport plugin to support this. https://day.js.org/docs/en/plugin/object-support
