### ISSUE TITLE
Issue parsing a date string with time

### ISSUE THREAD

**Issue by ashleydavis** [iamkun/dayjs#579]
This is a great library and I've been porting my code from moment to dayjs.

I just found a problem parsing a date that has a time.

See end for example code.

**Describe the bug**

Date string with time isn't being parsed correctly.

Actual output: 2017/05/01 17:05:00

**Expected behavior**

Expected output: 2017/12/31 17:00:00

**Information**
 - Day.js Version: 1.8.12
 - OS: Windows 10
 - Browser: N/A 
- Node.js: v10

**Example code that demonstrates the problem**:

const dayjs = require('dayjs');
const customParseFormat = require('dayjs/plugin/customParseFormat');
dayjs.extend(customParseFormat);

console.log(
    dayjs("2017/01/31 17:00:00", "YYYY/MM/DD HH:MM:ss").format("YYYY/MM/DD HH:MM:ss")
);

**Comment by iamkun** [comment]
should be 'YYYY/MM/DD HH:mm:ss'

**Comment by ashleydavis** [comment]
Thanks for the quick response! That works great.

I should have seen that! I've been staring at the code and your docs for an hour and it still didn't occur to me :(

Thanks for your effort with this library.
