### ISSUE TITLE
Differences to moment?

### ISSUE THREAD

**Issue by flosse** [iamkun/dayjs#58]
Could you add a section to the README.md that explains the differences to moment? Why is it faster/smaller? What features are missing? Are the parts of the API that are different? What was your motivation to "reinvent" the wheel?

**Comment by nathfreder** [comment]
+1

**Comment by iamkun** [comment]
Will do

**Comment by acrazing** [comment]
Is dayjs fully compatible with moment? I hope to use alias in webpack to replace moment with dayjs, but I cannot ensure if it is ok to do it. Is there any guidelines?

**Comment by naulacambra** [comment]
There are some functions that are not yet implemented, and others are available through plugins. Try to change the alias, and see if everything works fine

**Comment by acrazing** [comment]
Well, I found the second argument of `Dayjs#diff` is different, it accepts singular but `Moment#diff` accepts plural.

**Comment by xxyuk** [comment]
@acrazing Dayjs accepts both I think

**Comment by acrazing** [comment]
@xxyuk um.. I use typescript to check it, its singular only and is required in `index.d.ts`: https://github.com/iamkun/dayjs/blob/master/index.d.ts#L57

**Comment by xxyuk** [comment]
Oh I see.

We might could update it like this ? I'm not sure

```

export type UnitType = 'millisecond' | 'milliseconds' | 'second' | 'seconds' | 'minute' | 'minutes' | 'hour' | 'day' | 'week' | 'month' | 'quarter' | 'year' | 'date'

```

But I'm not good with TS, anyone could send a PR to fix this?

**Comment by zediah** [comment]
One thing I've just come across that's different is Moment accepts an array on constructor - e.g. `moment([2018, 1, 1])` but dayjs doesn't seem to know how to parse this.

**Comment by xxyuk** [comment]
@zediah Yes, Day.js can't parse array or object at this time.

**Comment by xxyuk** [comment]
https://github.com/you-dont-need/You-Dont-Need-Momentjs

Here is a simple comparison between Day.js, Moment.js, Luxon, Native Date and Date-fns.

**Comment by sandstrom** [comment]
Would also be good if the readme mentioned [Luxon](https://github.com/moment/luxon), which is an immutable moment-js descendent.

**Comment by niftylettuce** [comment]
It looks like all of these Get + Set functions are missing from dayjs, even with all plugins enabled https://momentjs.com/docs/#/get-set/

**Comment by xxyuk** [comment]
@niftylettuce  may be you are wrong.

**Comment by niftylettuce** [comment]
@xxyuk 	correct, I am wrong in the sense that the plural versions are not available, https://github.com/iamkun/dayjs/blob/dev/docs/en/API-reference.md#get-and-set, e.g. `hour()` exists but not its alias `hours()`.  just discovered this.

**Comment by iamkun** [comment]
Please see https://github.com/iamkun/dayjs/issues/58#issuecomment-481955828
