### ISSUE TITLE
"Mixed" relative time support?

### ISSUE THREAD

**Issue by danqing** [iamkun/dayjs#583]
I think a useful feature is like how GitHub displays date:

* If it's recent enough: just now, a minute ago, a day ago, etc.
* If it's more ancient: 2018/01/02

So essentially it's a mix of relative and absolute dates. It's not a big deal to implement just that, but maybe it's something dayjs can support out of the box?

Thanks!

**Comment by danqing** [comment]
Actually - Github doesn't do that (sorry :p) - I probably saw it somewhere else. Still I think it's a valid feature to consider.

**Comment by iamkun** [comment]
try our relativeTime plugin

**Comment by danqing** [comment]
This is a feature request for the relative time plugin (which I'm fully aware of and using)

**Comment by iamkun** [comment]
Sorry, we have no plan to support this. You could extend it by yourself easily.

**Comment by danqing** [comment]
Got it.

**Comment by mmilano** [comment]
interested in this behavior as well, but not clear on what the process would be. 
would someone be able to provide advice on how to extend it "easily"?

**Comment by baloodevil** [comment]
A minor enhancement to enable this would be to pass the *date* to [additional token processing](https://day.js.org/docs/en/customization/relative-time#additional-token-processing) methods.  So in addition to parameters `(number, withoutSuffix, key, isFuture)`, we also get *`date`*.  Then we could choose to customize the `MM`, `y`, and `yy` properties to display a full date for just those cases, for example.
