### ISSUE TITLE
Custom parsing doesn't work well

### ISSUE THREAD

**Issue by ashinzekene** [iamkun/dayjs#599]
**Describe the bug**

```js
import dayjs from "dayjs";
import customParseFormat from 'dayjs/plugin/customParseFormat';
import AdvancedFormat from 'dayjs/plugin/advancedFormat';

dayjs.extend(AdvancedFormat);
dayjs.extend(customParseFormat);

dayjs("2019 May 15 10:31:18 WAT +01:00", "YYYY MMM DD HH:mm:ss Z")
```
returns `Invalid Date`

**Expected behavior**
```js
import customParseFormat from 'dayjs/plugin/customParseFormat'

dayjs.extend(customParseFormat)
dayjs("2019 May 15 10:31:18 WAT +01:00", "YYYY MMM DD HH:mm:ss Z")
```
should return `May 15, 10:31 AM` like moment js

**Information**
 - Day.js v1.8.16
 - OS: MacOS Mojave 10.14.5
 - Browser: Chrome 74.0.3729.157
 - Time zone: GMT+01:00 WAT(West African Time)

**Comment by iamkun** [comment]
https://runkit.com/embed/pys8spt19xh5

Looks good

**Comment by ashinzekene** [comment]
Can you try. Runkit shows loading infinitely for me
```js
var dayjs = require("dayjs")
dayjs("2019 May 15 10:31:18 WAT +01:00").format("YYYY/MM/DD H:mm")
```

**Comment by iamkun** [comment]
please use customParseFormat plugin to escape `WAT` string, check the code in my upper comment.

**Comment by laxmi1990** [comment]
how to define customparseformat in our application.
We are defining in package.json     "dayjs": "1.9.6", to get it in our applcation.
How do i refer  customparseformat.
efine(['baja!', //LITOK
        
        'dayjs', //LITOK
        ],

**Comment by iamkun** [comment]
@laxmi1990 https://day.js.org/docs/en/plugin/loading-into-nodejs

**Comment by Wintereise** [comment]
> please use customParseFormat plugin to escape `WAT` string, check the code in my upper comment.

I'm sorry to have to ask this, but what is the escape sequence for the custom parse format plugin? For example, how would one deal with the `WAT` string as it's present on the initial comment of this issue without doing manual string manipulation?

The docs do not seem to mention this [0][1], neither does your runkit repo in this issue.

0: https://day.js.org/docs/en/plugin/custom-parse-format
1: https://day.js.org/docs/en/parse/string-format#list-of-all-available-parsing-tokens
