### ISSUE TITLE
Incorrect translation of 'July' to Thai language

### ISSUE THREAD

**Issue by pakaponk** [iamkun/dayjs#606]
**Describe the bug**
In Thai locale file `src/locale/th.js`, July was translated incorrectly

**Expected behavior**
July should be translated to `กรกฎาคม`. NOT `กรกฏาคม`
**NOTE:** There is a subtle difference between `ฎ` and `ฏ`

**Information**
 - Day.js Version: 1.8.14
 - OS: OS X Mojave
 - Browser: Chrome 74
 - Time zone: GMT+07:00

**Comment by iamkun** [comment]
pr welcomed
