### ISSUE TITLE
Some documentation/guidance to Typescript  and using dayjs as a Vue.js plugin

### ISSUE THREAD

**Issue by cyril-gambis** [iamkun/dayjs#611]
Hello!

I have a Vue.js project using Typescript, and try to use dayjs.
It's a bit difficult to understand how to set it up... can someone help me?
It's mainly a problem with Visual Code Studio and type checking. The application works fine, except for the Typescript error.

What I have done:
- npm install for dayjs
- create a file "dayjs.plugin.ts" (in a "src/plugins" directory):

```javascript
import Vue from 'vue';
import dayjs from 'dayjs';
import 'dayjs/locale/en';

import relativeTime from 'dayjs/plugin/relativeTime';
import LocalizedFormat from 'dayjs/plugin/localizedFormat';
import utc from 'dayjs/plugin/utc';

dayjs.locale(process.env.VUE_APP_I18N_LOCALE);
dayjs.extend(relativeTime);
dayjs.extend(LocalizedFormat);
dayjs.extend(utc);
Vue.prototype.$dayjs = dayjs;
```

- in my "main.ts" file, I add the import:

```javascript
import '@/plugins/dayjs.plugin';
```

- (here is the tricky part) create a file "dayjs-declaration.d.ts"

**In fact, I absolutely don't know what to put for the type $dayjs :(
I put "Dayjs" type, but I have serious doubts about it.**

```typescript
// 1. Make sure to import 'vue' before declaring augmented types
import Vue from 'vue'

import { Dayjs } from 'dayjs';

// 2. Specify a file with the types you want to augment
//    Vue has the constructor type in types/vue.d.ts
declare module 'vue/types/vue' {
  // 3. Declare augmentation for Vue
  interface Vue {
    $dayjs: Dayjs;
  }
}
```

- in a method of a Vue component, I try to call dayjs:

```javascript
  formatDateDayJs(date: Date): string {
    return this.$dayjs(date).fromNow();
  }
```

The good thing: my application works
The bad thing: I have a Typescript error:

169:12 Cannot invoke an expression whose type lacks a call signature. Type 'Dayjs' has no compatible call signatures.

I understand that "this.$dayjs" is of type "Dayjs", and this type is declared as (I use relativeTime plugin):

```javascript
declare module 'dayjs' {
  interface Dayjs {
    fromNow(withoutSuffix?: boolean): string
    from(compared: ConfigType, withoutSuffix?: boolean): string
    toNow(withoutSuffix?: boolean): string
    to(compared: ConfigType, withoutSuffix?: boolean): string
  }
}
```

so, I shouldn't be able to do a "$dayjs(argument)".

Have you any idea of what I should do?

Thank you!
Cyril

**Comment by cyril-gambis** [comment]
Ok, I finally managed to fix it:

In the dayjs-declaration.d.ts, I took the type of "dayjs" from index.d.ts of dayjs:

```typescript
declare module 'vue/types/vue' {
  // 3. Declare augmentation for Vue
  interface Vue {
    $dayjs(date?: dayjs.ConfigType, option?: dayjs.OptionType, locale?: string): dayjs.Dayjs;
  }
}
```

Everything works fine, with code completion and no more typescript error.

**Comment by iamkun** [comment]
https://day.js.org/docs/en/installation/typescript this might help

**Comment by Mrbngle** [comment]
This worked for me: 

`import dayjs, { Dayjs } from 'dayjs';`

**Comment by acidjazz** [comment]
@cyril-gambis 's solution here is perfect, this works great in vue3:

```ts
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $dayjs(date?: dayjs.ConfigType, option?: dayjs.OptionType, locale?: string): dayjs.Dayjs;
  }
```

when i do 
```ts
app.config.globalProperties.$dayjs = dayjs
```

this issue should re-open until this gets into the docs @iamkun :)
