### ISSUE TITLE
Strange i18n format issue

### ISSUE THREAD

**Issue by mgcrea** [iamkun/dayjs#619]
**Describe the bug**

Not sure how this bug can exist as there is unit tests covering this but `format('L')` won't work and output `"L"`. Even if the locale is properly loaded. 

```
dayjs().locale('fr').format('L'); // "L"
```

**Information**

https://runkit.com/mgcrea/5d10e452ea5ab1001d9675a3

**Comment by overdub60** [comment]
I have the same issue! @mgcrea  Have you been able to fix it?

**Comment by mgcrea** [comment]
no, had to manually set the format for now.

**Comment by iamkun** [comment]
what's your expected behavior? @mgcrea @overdub60

**Comment by overdub60** [comment]
@iamkun With the example provided by @mgcrea , the result of format() should be `03/07/2019` in this case. But we get `L`.

**Comment by iamkun** [comment]
I think `LocalizedFormat` plugin is what you are looking for.

https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#localizedformat

**Comment by mgcrea** [comment]
@iamkun Ouch, indeed! Sorry for the noise.

Might be worth adding a line regarding this in the [i18n README](https://github.com/iamkun/dayjs/blob/dev/docs/en/I18n.md), as `// abbreviated format options allowing localization` does make it look like it should work out of the box.

Maybe `// abbreviated format options allowing localization (requires the LocalizedFormat plugin)`

**Comment by overdub60** [comment]
Thanks for pointing us to the plugin! I also had the expectation that it would work out of the box. I agree that adding a note to the i18n README would be very helpful.
