### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by Likunone** [iamkun/dayjs#624]
![1191562578827_ pic_hd](https://user-images.githubusercontent.com/15193414/60800490-debc3f00-a1a7-11e9-9023-310084358427.jpg)
![1201562578864_ pic_hd](https://user-images.githubusercontent.com/15193414/60800499-e1b72f80-a1a7-11e9-92e1-26b0ca32d8ab.jpg)
One is the method I wrote myself, and one is dayjs. There's a big difference in performance

**Comment by xxyuk** [comment]
@Likunone Vanilla js is of course and always the best in performance. However, a lib dose more than just a single date compare. 

That is to say, there's no need for this comparison. Besides, Day.js is still fast enough even in your 300000 times tests.

**Comment by kirillgroshkov** [comment]
Fair comparison is with other Date libs (moment, luxon, date-fns, etc), not with vanilla js
