### ISSUE TITLE
Alternate constructor support?

### ISSUE THREAD

**Issue by planttheidea** [iamkun/dayjs#63]
I've been traipsing through the documentation and the code, and didn't see anything, so if it's there and I missed it I apologize.

Is there a plan to support other constructors for different use cases, the way `moment.utc` and `moment.unix` operate? Everything currently appears to be local timezones only.

**Comment by gpsimmo** [comment]
+1

**Comment by zgayjjf** [comment]
Need this too.

**Comment by iamkun** [comment]
dayjs.unix is available now
