### ISSUE TITLE
Invalid Date, with timezone offset (Firefox, Safari)

### ISSUE THREAD

**Issue by workgena** [iamkun/dayjs#631]
**Describe the bug**
When calling `dayjs("2019-07-15 06:46:25 +0100")` the Firefox/Safari returns "NaN".

```javascript
dayjs("2019-07-15 06:46:25 +0100") => NaN
```

In this example ` +0100` contains leading space. This space is the core of the problem. If the space is removed, then dayjs works as expected.

**Expected behavior**
`dayjs("2019-07-15 06:46:25 +0100")` => "1563169585000"
`dayjs("2019-07-15 06:46:25 +0100").format("YYYY-MM-DD")` => "2019-07-15"

### Demo: https://jsfiddle.net/fr4c5mwd/3/

**Information**
 - Day.js Version 1.8.15
 - OS: Ubuntu, OS X
 - Browser Firefox 68, Safari
 - Time zone *on my computer*: GMT+0300 (Eastern European Summer Time)

*Notice: Chrome/Edge works correctly.*

**Comment by iamkun** [comment]
Will do. Thanks.

**Comment by Duan112358** [comment]
got the same strange behaviour  ~

**Comment by tadaniya** [comment]
for my case, chrome is work but safari is not working

```
const d = new Date(dayjs(`${year}-${month}-${date}`).format(("YYYY-MM-DD")));
const isoDate = d.toISOString();
```

I just do like this to get iso date.

**Comment by iamkun** [comment]
date string other than ISO format please use customParseFormat plugin
