### ISSUE TITLE
toJSON throw exception instead of returns null

### ISSUE THREAD

**Issue by guillaumebriday** [iamkun/dayjs#632]
**Describe the bug**
There is a different behaviour between moment and dayjs when date is invalid and toJSON is called.

```js
dayjs('wtf').toJSON()
> Uncaught RangeError: Invalid time value
```

```js
moment('wtf').toJSON()
> null
```

**Expected behavior**
It's annoying when you when to call an api with a nullable field, for example :

```js
this.$store.dispatch('tasks/addTask', {
    title: this.form.title,
    due_at: dayjs(this.form.due_at).second(0)
})
```

This code does not work if `this.form.due_at` is `""` or `null` 

But this one works :

```js
this.$store.dispatch('tasks/addTask', {
    title: this.form.title,
    due_at: moment(this.form.due_at).second(0)
})
```

Thank you in advance 

**Information**
 - Day.js Version 1.8.15
 - OS: macOS 10.14.5
 - Browser chrome 75 and firefox 68
 - Time zone: Paris

**Comment by xxyuk** [comment]
https://runkit.com/embed/tay2fpsxv5bz

moment('').second(0)  moment(null).second(0) also return  Invalid Date

**Comment by g1eny0ung** [comment]
@xxyuk I think guillaumebriday means that the `toJSON()` method would stop the program.

I view the moment.js' source code. It will check the date is valid then choose call `toISOString()` or return `null`.

```
function toJSON () {
  // new Date(NaN).toJSON() === null
  return this.isValid() ? this.toISOString() : null;
}
```

Should we also check if it is valid by calling `isValid()`?

**Comment by guillaumebriday** [comment]
yep exactly @g1eny0ung !

I ended doing this in my own application :

```js
{ due_at: dayjs(this.form.due_at).isValid() ? dayjs(this.form.due_at).second(0) : null }
```

I will open a PR

**Comment by g1eny0ung** [comment]
@guillaumebriday 👍
