### ISSUE TITLE
Failed to parse date with format (Invalid date)

### ISSUE THREAD

**Issue by rapkin** [iamkun/dayjs#635]
**Describe the bug**
This works not as expected:
```js
dayjs('13.06.2019', 'DD.MM.YYYY').toString()
// >> "Invalid Date"

dayjs('12.06.2019', 'DD.MM.YYYY').format('DD.MM.YYYY')
// >> "06.12.2019"
```
As you can see lib detects first number as month.

**Expected behavior**
```js
dayjs('13.06.2019', 'DD.MM.YYYY').format('DD.MM.YYYY')
// >> "13.06.2019"

dayjs('12.06.2019', 'DD.MM.YYYY').format('DD.MM.YYYY')
// >> "12.06.2019"
```

**Information**
 - Day.js Version 1.8.15
 - OS: MacOS 10.14.5
 - Browser Chrome 75
 - Time zone: GMT+02:00

**Comment by iamkun** [comment]
try CustomParseFormat plugin https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat

**Comment by Lukaaaa** [comment]
this bug is still here!

**Comment by theTestingApproach** [comment]
This is still a bug

**Comment by iceney** [comment]
If the time component has AM/PM, it'll show Invalid date; otherwise it seems to work for me.
