### ISSUE TITLE
[Question] Whole day?

### ISSUE THREAD

**Issue by strarsis** [iamkun/dayjs#637]
Is it possible to define a whole day? When a specific time (hours, minutes, seconds, milliseconds) is also set to zero for that day, it causes issues with DST (Daylight Saving Time) and when switching between timezones (UTC and others) because then the `00:00` time can be crossed, which causes the day object to skip a day.

**Comment by iamkun** [comment]
Don't really understand. Please add more description or demo code, please.

**Comment by strarsis** [comment]
@iamkun: So let's say there is some kind of timetable for multiple months, each day is assigned a state.
```js
let day1 = moment("2019-12-20");
let day2 = moment("2019-12-21");
// and so on
````
The issue is that these `moment` dates also contain a specific time, directly before the next day.
This causes issues, especially when calculating a `moment-range` between days with DST transition,
one day will be missing then in the overall day count.

**Comment by iamkun** [comment]
a online demo please?

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
