### ISSUE TITLE
Ability to transform seconds to time

### ISSUE THREAD

**Issue by Wyzix33** [iamkun/dayjs#641]
Hi,
is it possible to transform seconds to time: for example 3602 seconds to 01:00:02, like a utility or something :)
just like moment has:
```js
var seconds = 3820;
var duration = moment.duration(seconds, 'seconds');
var formatted = duration.format("hh:mm:ss");
console.log(formatted);
```
Thanks

**Comment by iamkun** [comment]
#564

**Comment by brett-east** [comment]
Is this coming? The `duration` plugin has been released, but it doesn't have a `format` method, and I can't see anything in the documentation that explains how to format a duration as time.

**Comment by iamkun** [comment]
the `duration` plugin does not have a `format` method. Nor does `moment#duration`

**Comment by guanzo** [comment]
@brett-east unless i'm missing something, dayjs can already format a duration as time. Try plugging this into runkit: https://npm.runkit.com/dayjs

```js
var dayjs = require("dayjs")
var utc = require('dayjs/plugin/utc')

dayjs.extend(utc)

const oneMinute = 60000
dayjs.utc(oneMinute).format('HH:mm:ss')
```

**Comment by guanzo** [comment]
@brett-east unless i'm missing something, dayjs can already format a duration as time. Try plugging this into runkit: https://npm.runkit.com/dayjs

```js
var dayjs = require("dayjs")
var duration = require('dayjs/plugin/duration')
var utc = require('dayjs/plugin/utc')

dayjs.extend(duration)
dayjs.extend(utc)

const oneMinuteAgo = dayjs().subtract(1, 'minute')
const dur = dayjs.duration(dayjs().diff(oneMinuteAgo))

dayjs.utc(dur.asMilliseconds()).format('HH:mm:ss'))
```

For w/e reason, I have to use `dayjs.utc()` instead of `dayjs()` when formatting, otherwise the "hours" segment is off by 8 hours. Prolly some timezone crap.

**Comment by peterpoe** [comment]
Here is my solution, using [i18next pluralization](https://www.i18next.com/translation-function/plurals) to format the parts:

```ts 
const start = dayjs(startDate)
const end = dayjs(endDate)
const days = end.diff(start, 'days')
const totalHours = end.diff(start, 'hours')
const totalMinutes = end.diff(start, 'minutes')
const totalSeconds = end.diff(start, 'seconds')
const hours = totalHours - days * 24
const minutes = totalMinutes - totalHours * 60
const seconds = totalSeconds - totalMinutes * 60
const parts: string[] = []
if (days > 0) {
  parts.push(t('dateTimeParts.days', { count: days }))
}
if (hours > 0) {
  parts.push(t('dateTimeParts.hours', { count: hours }))
}
if (minutes > 0) {
  parts.push(t('dateTimeParts.minutes', { count: minutes }))
}
if (seconds > 0) {
  parts.push(t('dateTimeParts.seconds', { count: seconds }))
}
console.log(parts.join(', '))
```
