### ISSUE TITLE
fromNow() gives inconsistent results between UTC & local mode

### ISSUE THREAD

**Issue by denchen** [iamkun/dayjs#646]
**Describe the bug**
I've found a situation where `fromNow()` gives different results from MomentJS, and it gives different results depending on if you're in UTC mode or not.

Given the following:

```javascript
let dutc = dayjs.utc(currentTimestamp37hrsAgo); // UNIX time for 37 hours before now
let mutc = moment.utc(currentTimestamp37hrsAgo);

console.log(`37 hours ago - DayJS (utc):     ${dutc.toISOString()}, fromNow(): ${dutc.fromNow()}`);
console.log(`37 hours ago - MomentJS (utc):  ${mutc.toISOString()}, fromNow(): ${mutc.fromNow()}`);
```

Output of the above:

```
37 hours ago - DayJS (utc):     2019-07-28T09:28:35.873Z, fromNow(): a day ago
37 hours ago - MomentJS (utc):  2019-07-28T09:28:35.873Z, fromNow(): 2 days ago
```

Here's a [more extensive reproduction on Runkit](https://runkit.com/accelerate/fromnow)

If it helps, my local timezone is PST (-07:00)

**Expected behavior**
It is my understanding that `fromNow()` should not "care" about timezones, and it's based strictly off of the difference in absolute time. `fromNow()` should give the same results, regardless of if we're using `.utc()` or not. I didn't check to see if `toNow()` also has the same problem, but I'd assume so.

**Information**
 - Day.js Version: `1.8.15`
 - OS: `MacOS 10.14.6`
 - Browser: `Chrome 75.0.3770.142`
 - Time zone: `-07:00 DST (Pacific Daylight Time)`

**Comment by g1eny0ung** [comment]
[Runkit Clone](https://runkit.com/g1eny0ung/5d3fdd63874318001395eaa9)

Here is my result and seems that it works as normal. I'm in UTC+8 (Beijing).

By viewing documents and code, I found `moment.js` will compare the local time in the `fromNow()` method. [The code](https://github.com/moment/moment/blob/develop/src/lib/duration/create.js#L64)

But `day.js` won't do some special handling. The `fromNow()` method in day.js will call the `diff()` Internally. The diff method will use different comparison methods for different units.

So, I think maybe In some special cases, the `fromNow()` will have inconsistent results.

I can't completely guarantee that I am right. Maybe need some discussion?
@denchen @iamkun @xxyuk

**Comment by denchen** [comment]
@g1eny0ung 

The difference is that your timezone is _ahead_ of UTC (+8), and my timezone is _behind_ UTC (-7). If I manually change my laptop's timezone to +8, `fromNow()` gives correct results, but if I change my timezone to any timezone after UTC, even -1, then I'll get different results.

However, there's another way to replicate the difference without changing your timezone. Instead of subtracting 37 hours, **add** 37 hours. In other words:

```javascript
let currentTimestamp37hrsAgo = currentTimestamp + (37 * 60 * 60 * 1000);
```

Then you'll get the different results in your Beijing timezone.

```
37 hours ago - DayJS:           2019-08-01T07:04:28.958Z,  fromNow(): in 2 days
37 hours ago - MomentJS:        2019-08-01T07:04:28.958Z,  fromNow(): in 2 days
37 hours ago - DayJS (utc):     2019-08-01T07:04:28.958Z,  fromNow(): in a day
37 hours ago - MomentJS (utc):  2019-08-01T07:04:28.958Z,  fromNow(): in 2 days
```
```

**Comment by g1eny0ung** [comment]
@denchen Got it. I will check the source code and try to find out where the problem lies.

**Comment by g1eny0ung** [comment]
@denchen #649 

The problem is `fromNow()` method's internal `diff` method will calculate timezone offset when use `dayjs.utc`.

In order to maintain consistency, I use a boolean argument to avoid timezone comparison in **relativeTime** plugin.

**Comment by aemc** [comment]
has this been fixed?
