### ISSUE TITLE
Property 'week' does not exist on type 'Dayjs'

### ISSUE THREAD

**Issue by kingller** [iamkun/dayjs#652]
Hi,
When I use it with `TypeScript`, an error happens,
```
TS2339: Property 'week' does not exist on type 'Dayjs'.
```
Can you add the defined type to your `index.d.ts`?
```
week(): number
```
Thanks.

**Comment by harryhan24** [comment]
same problems.

**Comment by iamkun** [comment]
https://day.js.org/docs/en/get-set/week

This dependent on WeekOfYear plugin to work

**Comment by OlineVEZA** [comment]
still get the same error

**Comment by rajkeshwar** [comment]
I am having the same error `TS2339: Property 'week' does not exist on type 'Dayjs'.`. Even I have the weekOfYear configured like `dayjs.extend(weekOfYear);`

**Comment by AndreasHassing** [comment]
Did you perhaps use it like this:
```typescript
dayjs.week(); // yields an error
```

Instead of like this?:
```typescript
dayjs().week(); // works as expected
```

`week()` is an instance method declared on the `Dayjs` interface- unlike a plugin like `duration` which also adds static members, like: `dayjs.duration({ minutes: 30 })`.

**Comment by master117** [comment]
Why is this closed? This problem still exists

**Comment by aasutossh** [comment]
Use it like
```
import weekOfYear from "dayjs/plugin/weekOfYear";
// instead of 
// var weekOfYear = require("dayjs/plugin/weekOfYear");
dayjs.extend(weekOfYear);
```

If you use the way shown in docs, you'll get type error.

**Comment by skstuder** [comment]
This is still a problem.

**Comment by skstuder** [comment]
Here is what was confusing to me. You have to import and extend the plugin, but not use the same naming. 

import weekOfYear from 'dayjs/plugin/weekOfYear'

dayjs.extend(weekOfYear)

in your code: `dayjs().**week**()` not `dayjs().weekOfYear()`
