### ISSUE TITLE
the weekStart option in locale file seens not work.

### ISSUE THREAD

**Issue by julywind** [iamkun/dayjs#662]
**Describe the bug**
```
const dayjs = require('dayjs')
const weekday = require('dayjs/plugin/weekday')
const locale = {
  weekStart: 1
}
dayjs.locale(locale, null ,true)
dayjs.extend(weekday)

const d1 = dayjs().startOf('week')

const date = d1.toDate()
console.log(date, d1.weekday())
```
result is '2019-08-17T16:00:00.000Z 0' 
**Expected behavior**
2019-08-18T16:00:00.000Z 1

**Information**
 - Day.js Version [e.g. v1.0.0] 1.8.15
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome 62] node test.js
 - Time zone: GMT+8 Asia/Shanghai

**Comment by julywind** [comment]
am i changing weekday option in a right way?

**Comment by iamkun** [comment]
You are changing locale in the wrong way. Please check our docs and choose a build-in locale that week start on Monday.

**Comment by julywind** [comment]
all the doc, I can find only this, "dayjs().startOf('week'); // 取决于 locale 文件里 `weekStart` 的值", but i don't know how to change it. could you help me to find it? thanks!

**Comment by iamkun** [comment]
https://github.com/iamkun/dayjs/blob/dev/docs/en/I18n.md#customize

**Comment by xxyuk** [comment]
```
import enLocale from 'dayjs/locale/en-gb' // weekStart 1
 
dayjs.locale('en-gb').startOf('week').format()
```

**Comment by julywind** [comment]
I wanna change the weekStart option only, not all the locale properties   because it's one of my calendar options. It seems imposibble to do like that.
thank you very much!

**Comment by iamkun** [comment]
just `import enLocale from 'dayjs/locale/en'` and modify it to the config you want, and `dayjs.locale(enLocale)`.

**Comment by robertwt7** [comment]
> just `import enLocale from 'dayjs/locale/en'` and modify it to the config you want, and `dayjs.locale(enLocale)`.

You're amazing! Fixed my issue. Thanks

**Comment by iamkun** [comment]
here's another solution https://github.com/iamkun/dayjs/issues/215#issuecomment-471280396

**Comment by bilal42011** [comment]
This en-gb locale startWeek property is 1 but it is not working ..Any solution
