### ISSUE TITLE
customParseFormat + validate does not give expected result

### ISSUE THREAD

**Issue by eye1985** [iamkun/dayjs#663]
Hi,

It looks like validate does not work correctly when paired with the customParseFormat. 
It always return true if the input is a number.

E.g:
https://codesandbox.io/embed/ecstatic-leftpad-y595p

Expected behavior:
dayjs.extend(customParseFormat);
const res = dayjs("99.99.9999","MM.DD.YYYY").isValid(); <-- This should return false.

Or perhaps this not the right way to validate user input of the format?

**Information**
 - Day.js Version 1.8.15
 - OS: OSX
 - Browser Chrome 76.0.3809.100
 - Time zone: GMT+2

**Comment by iamkun** [comment]
customParseFormat just do a rough validation check, if a given string could be parsed into a valid js Date, we will consider it as 'Valid'

**Comment by eye1985** [comment]
Thanks for the reply, but is there any way validating on a custom format without using customParseFormat? 

Or do I have to just write my own validator for "MM.DD.YYYY"?

**Comment by iamkun** [comment]
No at this moment. But we will.

**Comment by eye1985** [comment]
Great, thank you for your time.
