### ISSUE TITLE
Feature request: calendar time in locales

### ISSUE THREAD

**Issue by tomhuze** [iamkun/dayjs#669]
Would it be possible to add a "calendar" key to the dayjs locale format template to support calendarTime in the same way as relative time is supported?

If this would be possible I could submit a PR updating all the locales with the calendar formatting data that exists in moment.js locales (or help with any other alternate approach that makes more sense.)

Thank you for this wonderful project.

**Comment by iamkun** [comment]
Please check #570 and join the discussion.
