### ISSUE TITLE
Why doesn't en.js locale contains all translations?

### ISSUE THREAD

**Issue by nicooprat** [iamkun/dayjs#675]
**Describe the bug**
The https://github.com/iamkun/dayjs/blob/dev/src/locale/en.js file doesn't contain all translation which causes errors.

**Expected behavior**
`en.js` should have the same keys as any other locale such as https://github.com/iamkun/dayjs/blob/dev/src/locale/fr.js to avoid confusion and errors.

**Information**
 - Day.js Version 1.8.16
 - OS: Mac High Sierra
 - Browser Brave latest
 - Time zone: Paris

I might have missed something but I couldn't translate some keys, mainly using the RelativeTime plugin. Is there any good reason the default locale is missing them? My current workaround is to load 'en-gb'.

Thanks.

**Comment by iamkun** [comment]
https://github.com/iamkun/dayjs/blob/dev/src/plugin/relativeTime/index.js

The en plugin locale is separated into each plugin self.

And you can get all the file like this.
```
var dayjs = require("dayjs")
var relativeTime = require('dayjs/plugin/relativeTime')
dayjs.extend(relativeTime)

console.log(dayjs.Ls['en']) 

```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
