### ISSUE TITLE
dayjs().set() support Object param?

### ISSUE THREAD

**Issue by sam019** [iamkun/dayjs#677]
```
dayjs().set({
  hour: 12,
  minute: 30,
  second: 30
})
```
not working...

**Comment by iamkun** [comment]
please use `.set(hour).set(minute).set(second)` instead

**Comment by sam019** [comment]
> please use `.set(hour).set(minute).set(second)` instead

thanks.
but it is more convenient if support object param, because momentjs support it, when move from momentjs, it doesn't need to change the code.

**Comment by iamkun** [comment]
ok we will

**Comment by vitordino** [comment]
is a PR welcome to this issue? @iamkun 

i can probably start the implementation, to have a more concrete discussion on it

**Comment by ChuckJonas** [comment]
plus one on this feature.  It's common for Calendar Dates to be represented in Objects via:

```
{
  year: 2019,
  month: 10, //0-11
  day: 30
}
```

**Comment by Epistol** [comment]
Especially since .toObject() method exist, would be nice to have the way back of it

**Comment by xiaohuoni** [comment]
这么做感觉挺奇怪的。
```
const toDayjs = (obj: any) => {
  const { year, month, date, hour, minute, second } = obj;
  return dayjs().set('year', year).set('month', month).set('date', date).set('hour', hour).set('minute', minute).set('second', second)
}
```
```
moment(moment().toObject())
```

**Comment by iamkun** [comment]
We just released the `ObjectSupport` plugin to support this. https://day.js.org/docs/en/plugin/object-support

**Comment by xiaohuoni** [comment]
cool！

**Comment by xSorc** [comment]
@iamkun Hello,
Is it correct behaviour that ObjectSupport plugin get month started from 1, but dayjs return month started with 0?

```js
dayjs().get('month') // 8
dayjs({ month: dayjs().get('month') }).get('month') // 7
```

It's very uncomfortable. I always need to remember that this parts of one lib works in different way.
The expected behaviour something like this:
```js
dayjs().get('month') === dayjs({ month: dayjs().get('month') }).get('month') // true
```

**Comment by iamkun** [comment]
@xSorc this is absolutely a bug that I did not review it deeply.

```
dayjs({month: 1}) 
```

should return `2020-02-01` instead if `1970-01-01`

**Comment by iamkun** [comment]
@xSorc a fixed pr here https://github.com/iamkun/dayjs/pull/1089

**Comment by iamkun** [comment]
fix: fix objectSupport plugin to get the correct result (zero-based month) is released in 1.9.1

**Comment by BigBird15** [comment]
hi!

i used objectSupport plugin, but for some reason it still doesn'w work :c 

```
dayjs.extend(objectSupport);
dayjs({}); 
```

it doesn't compile: 

> TS2769: No overload matches this call.   Overload 1 of 3, '(date?: string | number | Dayjs | Date): Dayjs', gave the following error.     Argument of type '{}' is not assignable to parameter of type 'string | number | Dayjs | Date'.       Type '{}' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more.   Overload 2 of 3, '(date?: string | number | Dayjs | Date, format?: OptionType, strict?: boolean): Dayjs', gave the following error.     Argument of type '{}' is not assignable to parameter of type 'string | number | Dayjs | Date'.       Type '{}' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more.   Overload 3 of 3, '(date?: string | number | Dayjs | Date, format?: OptionType, locale?: string, strict?: boolean): Dayjs', gave the following error.     Argument of type '{}' is not assignable to parameter of type 'string | number | Dayjs | Date'.       Type '{}' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more.

I used other plugins and didn't have any problems with them
what should I do to fix this?

**Comment by braydoncoyer** [comment]
I seem to be getting the same issue as @BigBird15, but when passing the object with `year`, `month`, and `day`.
