### ISSUE TITLE
Add aliases

### ISSUE THREAD

**Issue by muuvmuuv** [iamkun/dayjs#682]
**Describe the feature**

I want to set dayjs locale with `window.navigator.language`. The problem is, that in my case, `window.navigator.language` returns `de-DE` which is not a valid format. It would be great if you could add aliases.

Here is a SO question with a list of valid locales, but I guess there must be something on the internet that browsers use as reference: https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes

**Comment by iamkun** [comment]
maybe you can add your own helper function to fix this at the moment. like
```
localeHelper = () => {}  //de-DE returns de 
```

**Comment by muuvmuuv** [comment]
This works for the moment, thanks.

For anyone looking for something like that.:

```js
const dayjs = require('dayjs')
const UTC = require('dayjs/plugin/utc')
const LocalizedFormat = require('dayjs/plugin/localizedFormat')
const { isDev } = require('../environment.js')

const availableLanguages = ['en', 'de']

// include locale for each available language
require('dayjs/locale/de')

const localeHelper = lang => {
  const locale = availableLanguages.find(locale => {
    if (locale === lang) {
      return true
    }
    const regex = new RegExp(`${locale}-.*`)
    return regex.test(lang)
  })
  return locale ? locale : availableLanguages[0]
}

module.exports = () => {
  const lang = window.navigator.language
  const locale = localeHelper(lang)

  dayjs.extend(LocalizedFormat)
  dayjs.extend(UTC)
  dayjs.locale(locale)

  if (isDev) {
    console.log('Preferred language:', lang, locale)
  }
}
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
