### ISSUE TITLE
CustomParseFormat for weekdays

### ISSUE THREAD

**Issue by machsix** [iamkun/dayjs#686]
According to the table https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#list-of-all-available-format-tokens, `CustomParseFormat` doesn't support weekdays.

Is it possible to add the feature?

Like `星期一 19 八月 2019 16:08:18` => `2019-08-19 16:08:18 Monday`

**Comment by iamkun** [comment]
we've supported this already.
