### ISSUE TITLE
Provide playground for dayjs

### ISSUE THREAD

**Issue by Xuhao** [iamkun/dayjs#687]
It's good for new user like me or someone interest dayjs to have a place to try dayjs handily.

Like lodash or moment which can try it directly on its website console. 

Maybe build a website is a big deal but it's worth to try build one on third-party service like [jsfiddle](https://jsfiddle.net), and then put the link in README.md.

**Comment by JohnnyFun** [comment]
You could add it from dev tools to any page like:
```
var s = document.createElement('script')
s.src = 'https://unpkg.com/dayjs'
document.head.appendChild(s)
```

Then have at 'er:
![image](https://user-images.githubusercontent.com/8106379/70380905-9a240380-18ff-11ea-9dbb-a0a512c50f98.png)

**Comment by mattgreenfield** [comment]
I was after this too so have made a simple codepen with dayjs loaded in https://codepen.io/gmattgreenfield/pen/vYELJgj?editors=0011

**Comment by iamkun** [comment]
You can try it on out website now!

https://day.js.org/

**Comment by WLyKan** [comment]
> You can try it on our website now!
> 
> https://day.js.org/

should load all plugins, now the plugins is undefined
