### ISSUE TITLE
Wrong utcOffset when Node.js host has different timezone

### ISSUE THREAD

**Issue by H-s-O** [iamkun/dayjs#689]
**Describe the bug**
The `utcOffset()` value is affected by the host's timezone.

```
process.env.TZ = 'America/Toronto'
console.log(dayjs('2019-10-09T09:36:32.357-04:00').utcOffset())
// -240
```

```
process.env.TZ = 'Asia/Tokyo'
console.log(dayjs('2019-10-09T09:36:32.357-04:00').utcOffset())
// 540
```

**Expected behavior**
The `utcOffset()` value should match the parsed ISO8601 date string, regardless of the host's timezone.

**Information**
 - Day.js Version: 1.8.16
 - Node.js Version: 10.16.0

**Comment by xxyuk** [comment]
I think this is a designed feature.

Tested with moment.js got the same result. Always the host timezone offset.

https://runkit.com/embed/ia3s86zk7tow

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by dpkirchner** [comment]
I can't re-open @iamkun this but it's indeed still an issue in 1.10.7 (and node v17.0.1):

foo.js:

```javascript
const dayjs = require('dayjs');
const offset = dayjs('2021-11-17T01:57:45.403+02:00').utcOffset();

console.log(offset);
```

should print '120', prints '0' instead.

**Comment by H-s-O** [comment]
To add to my initial issue:

When I call `dayjs('2019-10-09T09:36:32.357-04:00').utcOffset()`, I know that it will create an immutable dayjs object with values parsed from an explicitly defined date (which includes a timezone offset) and I thus expect `utcOffset()` to return the offset parsed from that date, not the host's timezone offset.

If `utcOffset()` is used to return the host's timezone offset, I think it should rather be on the global dayjs object, perhaps like `dayjs.utcOffset()`. Or better document the current behavior.
