### ISSUE TITLE
Wrong locale for belgium

### ISSUE THREAD

**Issue by blaadje** [iamkun/dayjs#690]
ATM [BE](https://github.com/iamkun/dayjs/blob/dev/src/locale/be.js) locale (which should be belgium) seems to correspond to [belarus](https://en.wikipedia.org/wiki/Belarus) where the country code is `BY`. It is problematic for us as we needs to make exception for this locale and use the FR one instead.

**Expected behavior**
I guess we should have `by` for belarus instead and having correct locale for `be`

**Information**
 - Dayjs v1.8.16
 - OS: MAC OS 
 - Browser chrome 62
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
Hi, according to ISO_639-2 code mentioned in  https://github.com/iamkun/dayjs/issues/171 https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

be is for Belarusian 

while Dutch (Belgium) [nl-be]  is for Belgium

**Comment by blaadje** [comment]
Alright thanks for clarifying 👌
