### ISSUE TITLE
Timezone list and guess time zone feature

### ISSUE THREAD

**Issue by Hassan-Moin** [iamkun/dayjs#695]
Is there a feature or a plugin through we can get the list of time zones e.g.
in moment-timezone we can get the list of time zones from 
`momentTz.tz.names()`

Also can we guess the timezone using dayjs ? 
`momentTz.tz.guess()`

Are these features available currently in dayjs or are there workarounds to get them without using momentTz.

**Comment by SarathSantoshDamaraju** [comment]
@iamkun , Any update on this?

**Comment by Adam23** [comment]
@iamkun , Any update on this?

**Comment by garymathews** [comment]
@iamkun , Any update on this?

**Comment by alegalviz** [comment]
momentTz.tz.guess() uses `Intl.DateTimeFormat().resolvedOptions().timeZone` so you can use something like

`dayjs(new Date().toLocaleString("en-US", {timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone})).format('h:mA')`

https://caniuse.com/#feat=internationalization

**Comment by SarathSantoshDamaraju** [comment]
`Intl.DateTimeFormat().resolvedOptions().timeZone` is not an apt solution. It returns `undefined` on IE 11.

And even moment.tz.guess has a [fallback](https://github.com/moment/moment-timezone/blob/92417fb266545c564b3522e29f7ebd5188d56179/builds/moment-timezone-with-data-10-year-range.js#L351) for it.

**Comment by ianldgs** [comment]
> Intl.DateTimeFormat().resolvedOptions().timeZone is not an apt solution.
For people who only use dayjs on the back-end or that don't support IE11 it's a perfectly apt solution. My suggestion would be to use it, and allow a plugin for the fallback.

**Comment by PaulPCIO** [comment]
@ianldgs if it's a perfectly apt solution then use `Intl.DateTimeFormat().resolvedOptions().timeZone`?

I would rather like to see the equivalent to `momentTz.tz.guess()` which works on IE11 allowing for much better support.

**Comment by ianldgs** [comment]
@PaulPCIO how is including the same logic of `momentTz.tz.guess()` by default, which might be large and deviates from the main objective of this lib (to be lightweight) better than using a version that works 90~99% of the time, and allowing a plugin for anyone who needs to support the other 1~10% of users (read IE11 or lower)?

**Comment by PaulPCIO** [comment]
@ianldgs yea sorry never meant to give the impression that this should be included in the core lib...
This would, of course, be plugin based as the OP suggested, I see to have misread your comment before posting 😉 

_PS: as for your 1~10% of users on IE11, that's why we love enterprises that run in 3rd world countries 🤣

**Comment by iamkun** [comment]
Update: Day.js Time Zone Plugin https://day.js.org/docs/en/timezone/timezone

------

Guessing user zone. dayjs.tz.guess()

**Comment by raoufswe** [comment]
The timezone plugin looks great so far and wondering if there a way to list all timezones? 

I'm thinking of something like dayjs.tz.names()

**Comment by iamkun** [comment]
@raoufswe seems the js `Intl` API does not offer this list function. Correct me if I am wrong.

**Comment by raoufswe** [comment]
@iamkun I don't think they expose this functionality. here is a snipper from the doc that might be useful. 

<img width="1090" alt="Screenshot 2020-09-04 at 6 26 58 PM" src="https://user-images.githubusercontent.com/28605803/92229657-643a9c80-eedc-11ea-984a-a2d9ed293c6e.png">

I looked up some libraries that provide the functionality and it seems they compile their own data in .json file and iterate over it.

**Comment by iamkun** [comment]
@raoufswe 

> I looked up some libraries that provide the functionality and it seems they compile their own data in .json file and iterate over it.

Correct, but we will not do this to keep fit. 😬

**Comment by raoufswe** [comment]
@iamkun 
I just knew about this proposal https://github.com/tc39/proposal-intl-enumeration
It's in Stage 2 right now and will be very helpful once it's shipped :D

**Comment by antonin87** [comment]
Timezone plugin works well, but i can't set up timezone in the jest tests.

On jest.setup.js i did : 

```
jest.doMock('dayjs', () => {
  dayjs.tz.setDefault('Europe/Paris');
  return dayjs;
});
```

And when i log dayjs.tz.guess() on tests, i have following error : 

`TypeError: Intl.DateTimeFormat(...).resolvedOptions is not a function`

Is there any way to mock timezone in jest ?

**Comment by justingolden21** [comment]
Is there a way to list all timezones?

**Comment by kdgyimah** [comment]
> Is there a way to list all timezones?

I did not find a way in dayjs, even after combing through their files. I resorted to a package. Find below:
JSON file: [timezones-list-json](https://github.com/omsrivastava/timezones-list/blob/master/dist/timezones.json)
Package: https://github.com/omsrivastava/timezones-list

**Comment by nelsonmestevao** [comment]
As @raoufswe mention, you can now use `Intl.supportedValuesOf("timeZone")` in major browsers 🎉

**Comment by AkioSarkiz** [comment]
> As @raoufswe mention, you can now use `Intl.supportedValuesOf("timeZone")` in major browsers 🎉

This isn't the right way to get the list, because it depends on Node.js version
