### ISSUE TITLE
Mock timezone for snapshot testing

### ISSUE THREAD

**Issue by alandrei** [iamkun/dayjs#702]
**Describe the bug**
I am currently migrating from Moment.js to Day.js and in our current test suite we're mocking moment and setting the default timezone to UTC (for snapshot tests)

While in moment-timezone.js you can set the default timezone like:

`
jest.doMock('moment', () => {
    moment.tz.setDefault('UTC')
    return moment	
}) `

Is there a way to do the same with Day.js? (maybe using the [UTC plugin](https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#list-of-official-plugins))

**Expected behavior**
I would like to be able to easily set/mock the timezone for all the tests to UTC with Day.js, regardless of the syntax.

**Information**
 - Day.js 1.8.16
 - OS: macOS 10.14.6
 - Browser: Chrome 77.0.3865.120
 - Time zone: GMT+0200 (Central European Summer Time)

**Comment by iamkun** [comment]
There's no default UTC setting at present.

But we will support set UTC offset in the next version.

**Comment by iamkun** [comment]
release

**Comment by hisuwh** [comment]
How do you actually do this now then?
