### ISSUE TITLE
Web-based Documentation

### ISSUE THREAD

**Issue by denisinvader** [iamkun/dayjs#707]
It's quite uncomfortable to access docs through GitHub files. It would be nice to have a web version of docs with search and sections. 

I suggest using [Vuepress](https://vuepress.vuejs.org) and Github pages or an external server and domain name.

As far as I can see, the migration of current docs to Vuepress will be rather simple because of its structure.

I could integrate Vuepress in this

**Comment by denisinvader** [comment]
#709

**Comment by iamkun** [comment]
Yes we have one ! https://day.js.org/
