### ISSUE TITLE
line break while using inside svg

### ISSUE THREAD

**Issue by sudoStatus200** [iamkun/dayjs#708]
**Describe the bug**
I want resultant date in this form:

5:30 AM
Sunday

I tried using this h:m A[\n]dddd but it didn't work
I am using this inside text svg
**Expected behavior**
there should be a line break feature in dayjs().format() 

**Information**
 - Day.js Version 1.8.14
 - OS: linux
 - Browser chrome
 - Time zone: GMT 5:30

**Comment by iamkun** [comment]
dayjs().format([TOKEN]).replace('your line break code', 'TOKEN')

**Comment by bviala** [comment]
In my case the problem was that I was using a h1 which doesn't allow line breaks
