### ISSUE TITLE
immutable require clone API? 

### ISSUE THREAD

**Issue by mx1700** [iamkun/dayjs#71]
我认为 immutable 不需要 clone。
各位有告知一下 clone 的使用场景吗？

**Comment by iamkun** [comment]
All public APIs are all immutable.

Still, if you want to get a copy of current `Dayjs` instance, use `clone`.

**Comment by mx1700** [comment]
@iamkun Since immutable, why do you need to obtain a copy? There is no need for two identical objects.

**Comment by mx1700** [comment]
@iamkun 出于兼容 moment 考虑可以理解。
如果不考虑兼容，我觉得可以私有 clone，没必要暴露出来给用户。
