### ISSUE TITLE
Cannot convert YYYY-MM format to correct dayjs when use customParseFormat

### ISSUE THREAD

**Issue by kingller** [iamkun/dayjs#712]
Hi,
When I convert `YYYY-MM` format to `dayjs` when use `customParseFormat` as bellow
```
import dayjs, { Dayjs } from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';

dayjs.extend(customParseFormat);

dayjs('2020-02', 'YYYY-MM').format('YYYY-MM')
```
I got the value is `2020-03`
Expect: `2020-02`

**Comment by iamkun** [comment]
https://runkit.com/embed/ydhiaf56iwjl

<img width="570" alt="Screen Shot 2019-11-01 at 12 58 09 AM" src="https://user-images.githubusercontent.com/17680888/67968767-ee71fe80-fc42-11e9-8bb7-8e656945f502.png">

please provide a valid reproduction link

**Comment by kingller** [comment]
Sorry, This is an error in my code.
