### ISSUE TITLE
Not Format correctly for dayjs('0010-12', 'YYYY-MM') 

### ISSUE THREAD

**Issue by kingller** [iamkun/dayjs#720]
**Describe the bug**
```
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';
dayjs.extend(customParseFormat);

dayjs('0010-12','YYYY-MM').format('YYYY-MM-DD');
dayjs('0110-12','YYYY-MM').format('YYYY-MM-DD');
dayjs().year(1).startOf('year').format('YYYY-MM-DD');
```

**The above returns:**
```
1910-12-06
110-12-06
1901-01-01
```

**Expected behavior**
```
0010-12-01
0110-12-01
0001-01-01
```
1. I want to get to correct year, and get the day as `01`, not current day.
2. And if possible, how to make the year to keep four digits? if not, I cannot convert it back to dayjs
```
dayjs("10-12", "YYYY-MM").format("YYYY-MM-DD")  => Invalid Date
```

[Click Here you can see the issue](https://codesandbox.io/embed/mutable-river-gucl6?fontsize=14)

**Comment by iamkun** [comment]
> get the day as 01, not current day.

This is a bug and will be fixed soon


Plus, what's this strange data '0010-12' '0110-12' used for?

**Comment by kingller** [comment]
It's for the date picker component, when I change the input value, it will give me not correct value, maybe nobody will use this date, but it will be a bug for my company's tester.

**Comment by iamkun** [comment]
As for native date object 
```
new Date(0010)
Thu Jan 01 1970 00:00:00 
```

And we will keep the same with it.

**Comment by kingller** [comment]
For `moment` as bellow,
```
moment('0010', 'YYYY').format('YYYY-MM-DD')
```
it will be `0010-01-01`,
I don't know why native date object do this.
Can dayjs('0110-12','YYYY-MM').format('YYYY-MM-DD') parse to `0110-12-01`?

**Comment by xxyuk** [comment]
I don't think 0010-01-01 is a useful date to most users.

**Comment by sveta4acova** [comment]
dayjs 1.8.17

dayjs('10.12.2019', 'DD.MM.YYYY').format('DD-MM-YY')
expected 10-12-19
return 12-10-19

Help!

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
