### ISSUE TITLE
Invalid date with i18n date format

### ISSUE THREAD

**Issue by anupai** [iamkun/dayjs#729]
**Describe the bug**
```
<script src="https://unpkg.com/dayjs"></script>
<script src="https://unpkg.com/dayjs/locale/pt-br"></script>
```
`dayjs('Ter, 23 Fev 2021',{locale: 'pt-br'})`
// invalid date

`dayjs('Dom, 12 Jan 2020',{locale: 'pt-br'})`
// Sat, 11 Jan 2020 13:00:00 GMT

This happens for most of the month in `pt-br` locale. `Fev, Abr, Mai, Ago, Set, Out, Dez`

**Expected behavior**
`dayjs('Ter, 23 Fev 2021',{locale: 'pt-br'})`
// Tue, 23 Feb 2021 13:00:00 GMT

**Information**
 - Day.js Version 1.8.12
 - OS: windows
 - Browser - chrome
 - Time zone: GMT-11:00 DST (Australian Eastern Standard Time ( AEST ))]

**Comment by iamkun** [comment]
check here as a reference.
https://day.js.org/docs/en/parse/string-format
