### ISSUE TITLE
Invalid parse 2019年11月11日 YYYY年MM月DD日

### ISSUE THREAD

**Issue by linningmii** [iamkun/dayjs#730]
**Describe the bug**

```javascript
dayjs('2019年11月11日', 'YYYY年MM月DD日').format('YYYY-MM-DD')) // Invalid Date
moment('2019年11月11日', 'YYYY年MM月DD日').format('YYYY-MM-DD'))  // 2019-11-11
```

**Expected behavior**

2019-11-11

**Information**

 - Day.js Version v1.8.17
 - OS: macOS 10.14.6
 - Browser: [Alipay MiniProgram IDE Simulator](https://render.alipay.com/p/f/fd-jwq8nu2a/pages/home/index.html)
 - Time zone: GMT+8

I also try the same version of dayjs in node 12.12 runtime, it doesn't work either

**Comment by iamkun** [comment]
https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat

CustomParseFormat plugin

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
