### ISSUE TITLE
[feature request] Add helper to set last day of month

### ISSUE THREAD

**Issue by everdimension** [iamkun/dayjs#731]
Hello! Thanks a lot for this library.

I stumbled upon a case where I need to be able to set a "maximum" date for the current month. E.g.

```js
dayjs().set('date', 'max'); // is it 30 or 31 or 28? I wish I could just tell the lib to pick the right one
```

What do you think? If you agree that it is a good idea I'd be glad to make a PR.
But I think the exact API should be discussed first.

Thanks!

**Comment by everdimension** [comment]
Oh, well, I just realized I can do this:

```js
dayjs().set('date', 1).add(1, 'month').subtract(1, 'day');
```

:)

**Comment by iamkun** [comment]
You can use 
```
dayjs().endOf('month')
```

**Comment by everdimension** [comment]
Oh, thanks!! Did not find that. I guess the issue is solved, then
