### ISSUE TITLE
Will dayjs('1211', 'HH:mm') support convert to expect value

### ISSUE THREAD

**Issue by kingller** [iamkun/dayjs#740]
```
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';
dayjs.extend(customParseFormat);

dayjs('1211', 'HH:mm').format('HH:mm')
```
result: `12:01`
expect: `12:11`

When I input the value `1211`, and convert it with `moment`, it's value is `12:11`. Will dayjs support this?

**Comment by distantnative** [comment]
Shouldn't it be `dayjs('1211', 'HHmm').format('HH:mm')`?

**Comment by iamkun** [comment]
agreed with @distantnative

**Comment by kingller** [comment]
When user enters a number in the input, he hopes that it can be converted into a standard format instead of must enter a colon. As the result of `dayjs('2019-12-11 1235').format('YYYY-MM-DD HH:mm')` is `2019-12-11 12:35`, but the result of `dayjs('2019-12-11 1235', 'YYYY-MM-DD HH:mm').format('YYYY-MM-DD HH:mm')`when I specify the format is `2019-12-11 12:05`.  
Now I've dealt with the logic by myself.

**Comment by distantnative** [comment]
@kingller I think it's hard for dayjs to make assumptions about how user input differs, especially when you exactly define a custom parse format and then the data you pass is not in the format you specify yourself.

**Comment by kingller** [comment]
OK. Thanks.
