### ISSUE TITLE
Typescript type definition for locale

### ISSUE THREAD

**Issue by Mushr0000m** [iamkun/dayjs#742]
V1.8.17

I try to list all weekdays that are stored in the locale file under `weekdaysShort` key, but when doing : `import dayjsFr from 'dayjs/locale/fr';` I get the classic `Could not find a declaration file for module`error. I'm I doing something wrong or there is not type definition for locales ? If so can you add them ?

Thanks

**Comment by iamkun** [comment]
fixed in #716 and will be available in next release.
