### ISSUE TITLE
Parse date ignoring timezone

### ISSUE THREAD

**Issue by distantnative** [iamkun/dayjs#747]
We want to parse and format dates no matter of the current timezone of the browser.
I thought the UTC plugin will be for that, but somehow I cannot get it to work:

```js
let value = "2018-11-25";
let obj = dayjs.utc(this.value, "YYYY-MM-DD");
let date = obj.date();
```

Setting my browser to the timezone of Vancouver, I always get `24` for `date`- instead of `25`.
What am I doing wrong?

**Comment by iamkun** [comment]
a reproduction link or demo please, utc plugin should always give you 25 in result

**Comment by distantnative** [comment]
Reproduction: https://codepen.io/distantnative/pen/ExaKRoE

With timezone of Berlin:
<img width="566" alt="Screen Shot 2019-12-11 at 18 57 42" src="https://user-images.githubusercontent.com/3788865/70646977-49d2db80-1c48-11ea-8dfc-c35bff419541.png">

With timezone of Vancouver (switched to via https://mybrowseraddon.com/change-timezone.html):
<img width="506" alt="Screen Shot 2019-12-11 at 18 57 54" src="https://user-images.githubusercontent.com/3788865/70647007-5c4d1500-1c48-11ea-81d9-4832ba4196d6.png">

**Comment by iamkun** [comment]
https://codepen.io/iamkun/pen/wvBWMpY

looks fine after changing the timezone using the extension you mentioned above.

<img width="1235" alt="Screen Shot 2019-12-11 at 7 40 22 PM" src="https://user-images.githubusercontent.com/17680888/70680803-3f5e2380-1cd4-11ea-8122-f77e42737f21.png">

**Comment by iamkun** [comment]
I see, maybe it a bug from that extension. Try to change your timezone using the operating system setting and try again.

**Comment by distantnative** [comment]
OK I see, it does work when changing the operating system. Weird ß bug of the plugin then. Thanks for your efforts!
