### ISSUE TITLE
format("lll") with locale doesn't show AM/PM

### ISSUE THREAD

**Issue by whtFlower** [iamkun/dayjs#749]
https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#localizedformat

1)  dayjs().format("lll") return [2019年12月11日 16:42] instead of [**2019年12月11日 午後 4時42分32秒**]. If you look at the documentation it says english locale will return [Aug 16, 2018 8:02 PM] which I expected to do the same thing for japanese with locale

2) dayjs().format("LT") returns [16:42] instead of [**午後 4時42分**]. Doc shows english locale will return [8:02 PM]

3) we need this format with japanese locale. does dayjs locale support this? **"MMM D, YYYY h:mm:ss A"**

**Information**
 - Day.js Version [1.8.16]

**Comment by iamkun** [comment]
Locale format for Japanese is defined here https://github.com/iamkun/dayjs/blob/dev/src/locale/ja.js#L11

If you want to use your custom format, please extend or modify the locale file.

**Comment by whtFlower** [comment]
@iamkun  Could you give me sample code of how to extend it? 

I this is what I have currently.  
dayjs().locale("ja")
dayjs().format("LT") which prints out [16:42] instead of [午後 4時42分]. How can I use to modify this to show correct way in japanese?

```
{
...
LT: 'h:mm A',
}
```
do you mind providing sample code of how to use this with dayjs().format("LT")?

**Comment by whtFlower** [comment]
those time format is very different per locale. it's confusing. Is there any way to have 2PM in Chinese and Japanese for time display? it works correctly for Korean.


This is the format expected: 

![Screen Shot 2019-12-13 at 2 23 50 PM](https://user-images.githubusercontent.com/36006709/70836170-3fcdeb80-1db4-11ea-85f6-45576f2c3424.png)

however for Japanese & Chinese time comes out with military time. see the Chinese
![Screen Shot 2019-12-13 at 2 23 25 PM](https://user-images.githubusercontent.com/36006709/70836235-7146b700-1db4-11ea-9409-1109d5fd8ee1.png)

however Korean comes out correctly
![Screen Shot 2019-12-13 at 2 25 05 PM](https://user-images.githubusercontent.com/36006709/70836269-8c192b80-1db4-11ea-994a-bcbb10ca3b4a.png)

**Comment by iamkun** [comment]
https://runkit.com/embed/s0f9f1d8ayxz
If our locale file does not suit your need, just update it with yours.
```
var dayjs = require("dayjs")
var jaLocale = require('dayjs/locale/ja')
var localizedFormat = require('dayjs/plugin/localizedFormat')
dayjs.extend(localizedFormat)

jaLocale.formats.LTS = 'h:mm:ss A' // update locale format string

dayjs.locale(jaLocale, null, true)
dayjs().locale('ja').format('LTS')
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
