### ISSUE TITLE
Format Parsing Inconsistent.

### ISSUE THREAD

**Issue by michaelpelletier** [iamkun/dayjs#750]
**Describe the bug**
Currently there seems to be a discrepancy in how browsers interpret dates, resulting in things working correctly on one browser but not the other. This particular use case involves the format being written as "Wed, 11 Dec 2019 16:39:00 +00:00". 

This parses correctly on:
- The latest Chrome for Mac & Windows
- The latest Firefox for Mac & Windows
- The latest Safari for Mac

But it throws an "Invalid Date" message in the latest version of MS Edge on Windows. 

Here is a simple Codepen: https://codepen.io/michaelpelletier/pen/MWYevGg

**Expected behavior**
It... should parse evenly across browsers. 

**Information**
 - Day.js Version: v1.8.17 (Latest)
 - OS: Windows 10
 - Browser: Edge v18 (Latest)
 - Time zone: GMT-05:00 EST

**Comment by iamkun** [comment]
for date string other than ISO format, please use our customParseFormat plugin to make it the same in all browsers

https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat

**Comment by michaelpelletier** [comment]
@iamkun That'll work in the interim but it is strange to me that I have to use a plugin for something that works out of the box 98% of the time.

**Comment by xxyuk** [comment]
What's your expected solution then, please? 

To add some compatible logic from official plugin to dayjs main bundle to make it work on some less popular browser for some un-standard time format string? 

That will cause bundle size increased to all dayjs users.
