### ISSUE TITLE
weekOfYear shows wrong calender week at the turn of the year

### ISSUE THREAD

**Issue by Khazl** [iamkun/dayjs#760]
**Describe the bug**
I probably found a bug in the weekOfYear plugin.
The 2019-12-30 should be calender week 1 but it shows as calender week 53.

Here my example at codepen:
https://codepen.io/khazl/pen/NWPvoYb?editors=0012

Calender weeks:
http://www.whatweekisit.org/

**Information**
 - Day.js Version 1.8.17
 - Browser Chrome latest

**Comment by iamkun** [comment]
Thanks. Will fix in next release
