### ISSUE TITLE
the result of dayjs("2019-02", "YYYY-MM") is wrong

### ISSUE THREAD

**Issue by kingller** [iamkun/dayjs#761]
**Describe the bug**
```
import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";
dayjs.extend(customParseFormat);

2019-02 dayjs format: {dayjs("2019-02", "YYYY-MM").format("YYYY-MM")}
```
result: `2019-03`
expected: `2019-02`

**Information**
 - Day.js Version 1.1.18
 - OS: mac
 - Browser: chrome 79.0.3945.88
 - Time: 2019-12-30T15:30:00+08:00

Reproduce address: https://codesandbox.io/s/gifted-feynman-bshbk?fontsize=14&hidenavigation=1&theme=dark

**Comment by iamkun** [comment]
Thanks. Will fix in next release

**Comment by kingller** [comment]
When will it be released?
