### ISSUE TITLE
Constructor not working with custom format

### ISSUE THREAD

**Issue by pedrofurtado** [iamkun/dayjs#763]
@iamkun 

```javascript
dayjs('12/05/2009', 'DD/MM/YYYY') -> gives me day 5 of December, instead of day 12 of May
```

but this not:
```javascript
dayjs('13/12/2009', 'DD/MM/YYYY') -> getting me 'Invalid date', instead of day 13 of December
```

**Comment by iamkun** [comment]
please use our customParsePlugin

**Comment by pedrofurtado** [comment]
@iamkun How do I use this plugin? Is there some doc example code? 👍 🤝

**Comment by iamkun** [comment]
> @iamkun How do I use this plugin? Is there some doc example code? 👍 🤝

@pedrofurtado https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat
