### ISSUE TITLE
Possible bug regarding dayjs.locale() usage

### ISSUE THREAD

**Issue by denchen** [iamkun/dayjs#765]
I want to have `weekStart` be 1 (start on Monday instead of Sunday), so my understanding is that we're supposed to use `dayjs.locale()` to override. So something like:

```javascript
import dayjs from 'dayjs';
import en from 'dayjs/locale/en';

dayjs.locale({
  ...en,
  weekStart: 1
});
```

However, if I do this, then some functions break, such as `dayjs().format('ll')`, which gives me `TypeError: Cannot read property 'replace' of undefined`.  Although `dayjs().format('LL')` _does_ work.

I got around the problem by including `formats` in the locale info:

```javascript
import dayjs from 'dayjs';
import en from 'dayjs/locale/en';

dayjs.locale({
  ...en,
  weekStart: 1,
  formats: {
    LT: 'h:mm A',
    LTS: 'h:mm:ss A',
    L: 'MM/DD/YYYY',
    LL: 'MMMM D, YYYY',
    LLL: 'MMMM D, YYYY h:mm A',
    LLLL: 'dddd, MMMM D, YYYY h:mm A'
  }
});
```

So my question is, am I supposed to include `formats` when overriding locale? Should I have to include other keys as well? Or is this a bug?

**Information**
 - Day.js Version: **1.8.18**
 - OS: **macOS Catalina 0.15.2**
 - Browser: **Chrome 79.0.3945.88**
 - Time zone: **GMT-07:00 PST (Pacific Daylight Time)**

**Comment by iamkun** [comment]
You can try #766 UpdateLocale plugin in our latest release.
```
dayjs.updateLocale('en', {
  weekStart: 6
})
```
