### ISSUE TITLE
"Do" does not format day to "1st, 2nd..."

### ISSUE THREAD

**Issue by NikkiMeganMoore** [iamkun/dayjs#775]
**Describe the bug**
Not sure if this is a bug or if it is not supported, but when I use the format "MMMM Do, YYYY"
I get the result "January 2o, 2020" instead of the expected "January 2nd, 2020"

**Expected behavior**
Using "Do" should format as "1st", "2nd", etc. like momentjs

**Information**
 - Day.js Version 1.8.16
 - OS: macOS 10.14.6
 - Browser: Chrome 79.0.3945.117

**Comment by iamkun** [comment]
https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#advancedformat
