### ISSUE TITLE
startOf manipulation not working

### ISSUE THREAD

**Issue by malangaveuday** [iamkun/dayjs#778]
**Describe the bug**
 startOf function not working.

**Expected behavior**
I compared this with moment in follow example in code sandbox
https://codesandbox.io/s/moment-dayjs-zozqm

**Information**
 - Day.js Version [e.g. v1.8.19]
 - Codesandbox
 - Firefox
 - GMT+0530

**Comment by iamkun** [comment]
Any detail, please?

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
