### ISSUE TITLE
Can't get the Days of the Week

### ISSUE THREAD

**Issue by faropoulos** [iamkun/dayjs#779]
**Describe the bug**
I should be able to get all the days of the week with `dayjs().weekdays()`. Sadly, that function doesn't exist. I even tried the weekday plugin, and still get nothing. Am i missing something;

Below you will find the code

```
import dayjs from 'dayjs';
import el from 'dayjs/locale/el';

dayjs.locale('el');
dayjs().weekdays();
```

**Expected behavior**
I should be able to get an array with the names of the Days of the Week.

**Information**
 - Day.js Version **1.8.19**
 - OS: **Mac OS**
 - Browser **Chrome 79**
 - Time zone: **Eastern European Time Zone, GMT +3**

**Comment by iamkun** [comment]
Thanks.
I've update localeData plugin to support this in our coming release.
```
import localeData from 'dayjs/plugin/localeData'
dayjs.extend(localeData)

//dayjs.locale('en')
dayjs.localeData().weekdays()
```
