### ISSUE TITLE
relativeTime plugin produces non grammatically valid output for POLISH language

### ISSUE THREAD

**Issue by it-xtech-dev** [iamkun/dayjs#782]
**Describe the bug**
Relative time output makes no sens in polish language for function .fromNow (and possibly other function in this plugin).

**Expected behavior**
Expected output has been documented here:
https://codepen.io/xtech-dev/pen/OJPapqa?editors=0010
(output matters, implementation may of course vary)

**Information**
 - Day.js Version [v.1.8.19]
 - OS: [Windows 10]
 - Browser [e.g. chrome 79.0.3945.88 ]
 - Time zone: [ UTC/GMT +1 hour]

**Additional notes**
Resonable solution has been already proposed https://github.com/iamkun/dayjs/pull/659 but seems to be rejected.

**Comment by iamkun** [comment]
fixed in d3724758bb27d5b17587b995ba14e7e80dcd1151 and will release soon

**Comment by it-xtech-dev** [comment]
thx
