### ISSUE TITLE
Locale Serbia SR wrong (RS would be correct)

### ISSUE THREAD

**Issue by stefanbinder** [iamkun/dayjs#785]
**Describe the bug**
Currently the file is named /locale/sr.js 
But the real country code is RS.
https://countrycode.org/serbia

**Expected behavior**
The file sr.js and sr-cyrl.js should be renamed to rs.js and rs-cyrl.js

**Information**
 - Day.js Version 1.8.18,

**Comment by iamkun** [comment]
we use ISO 639 short code https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
