### ISSUE TITLE
Using DayJS with Typescript

### ISSUE THREAD

**Issue by samywang92** [iamkun/dayjs#788]
Hello!  I am currently trying to use DayJS with typescript and I do not see an @types in DefinitelyTyped but I do see the following folder: 
https://github.com/iamkun/dayjs/tree/dev/types

How would I use this folder or what should I do to properly import dayjs into my Typescript project?
My project currently runs fine, it just has a Typescript error.

I also saw this issue opened and what he wrote looks similar to the folder listed above:
https://github.com/iamkun/dayjs/issues/611

Any help is greatly appreciated and many thanks!

**Comment by iamkun** [comment]
Day.js comes with Typescript support already. 

```
import * as dayjs from 'dayjs'
```

**Comment by samywang92** [comment]
I got the following error:

`23:18 This expression is not callable.
  Type 'typeof dayjs' has no call signatures.
    21 |   },
    22 |   mounted() {
  > 23 |     const test = dayjs('2020-01-28 11:59:36.902596072-08:00').format(
       |                  ^
    24 |       'MM.D.YYYY'
    25 |     )
    26 |     console.log(test)
`

When using import * as dayjs from 'dayjs' and I did some research and turns out with dayjs we can just do "import dayjs from 'dayjs'"

Thank you! :)

**Comment by iamkun** [comment]
https://day.js.org/docs/en/installation/typescript this might help

**Comment by chenEdgar** [comment]
I got the same error "Cannot find module 'dayjs'.ts(2307)"  . Event though I tryed these two using ways. [have-trouble-importing-dayjs](https://day.js.org/docs/en/installation/typescript#have-trouble-importing-dayjs)

dayjs version:  1.8.28

**Comment by iamkun** [comment]
@chenEdgar  a reproduction repo, please?

**Comment by chenEdgar** [comment]
@iamkun here it is [reproduction respo](https://github.com/chenEdgar/dayjs-ts-demo)

**Comment by iamkun** [comment]
@chenEdgar try to add  `"moduleResolution": "node"`  in your `tsconfig.json`

**Comment by chenEdgar** [comment]
@iamkun it works. thanks

**Comment by dviramontes** [comment]
if anyone else is still having this issue after trying the above - this worked for me 
`import { default as dayjs } from 'dayjs';`

**Comment by GeorgePasquali** [comment]
> if anyone else is still having this issue after trying the above - this worked for me
> `import { default as dayjs } from 'dayjs';`

Hi, just wanted to add that it would be the same doing something like this:
```
import dayjs from 'dayjs';
```

**Comment by tsirolnik** [comment]
Docs should be changed to @GeorgePasquali 's way... 

The default which noted in the docs
```ts
import * as dayjs from 'dayjs'

// e.g
dayjs().format()
```

returns

```
This expression is not callable.
  Type 'typeof dayjs' has no call signatures.
```

**Comment by anburocky3** [comment]
> `import { default as dayjs } from 'dayjs';`

Same problem have you fixed it? Without solution, the issue has been closed. 👎

**Comment by nawlbergs** [comment]
so i had two apps in same repo... client(angular) and server (node).. and npm modules installed in root.   
- Server had issues with `import dayjs from 'dayjs'`
- Client had issues with `import * as dayjs from 'dayjs'`

so.. daysjs uses this junk `export = dayjs` which is fine in commonjs (the export itself is essentially a function or class... ).

Other module systems export an "object" .. eg `export { method1, method2, .... }`

Either way... I had to turn on `"allowSyntheticDefaultImports": true` in the angular project.. and now I just use `import dayjs from 'dayjs'` in both projects.

**Comment by anil1kuppa** [comment]
> import { default as dayjs } from 'dayjs'

I'm getting the error "`Module '"dayjs"' has no exported member 'default'"` when I try the above

**Comment by KevinZyz** [comment]
> Docs should be changed to @GeorgePasquali 's way...
> 
> The default which noted in the docs
> 
> ```ts
> import * as dayjs from 'dayjs'
> 
> // e.g
> dayjs().format()
> ```
> 
> returns
> 
> ```
> This expression is not callable.
>   Type 'typeof dayjs' has no call signatures.
> ```

set "esModuleInterop": false or remove the field in your tsconfig.json

**Comment by robertwt7** [comment]
gosh, the docs should say `import dayjs from "dayjs"`

**Comment by vhscom** [comment]
Usage tip for those looking for type completion:

```typescript
import dayjs, { type Dayjs } from 'dayjs';

const startOfMonth = (date: Dayjs) => {
  return date.startOf('month'); // identifier with type completions
}
```

**Comment by lin09** [comment]
> https://day.js.org/docs/en/installation/typescript this might help

+ unplugin-auto-import: 'dayjs': [['default', 'dayjs']]
error: Property 'default' does not exist on type 'typeof dayjs'. 
const dayjs: typeof import('dayjs')['default']

+ unplugin-auto-import: 'dayjs': [['*', 'dayjs']]
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Cannot call a namespace ('dayjs')

**Comment by rommyarb** [comment]
Using regular import with @ts-ignore works for me:
```ts
// @ts-ignore
import dayjs from 'dayjs'
```

- Vue 3 with Vite
- Built & hosted on Vercel

**Comment by franckDev21** [comment]
> if anyone else is still having this issue after trying the above - this worked for me `import { default as dayjs } from 'dayjs';`

Thanks

**Comment by ivanbportugal** [comment]
```
import dayjs from 'dayjs'
```

- NextJS v13

**Comment by szaboattilaprog** [comment]
Under Nuxt 3
Make a plugin ts file like name `useDayJs.client.ts` with this code.
```Ts
import dayjs from 'dayjs'
import duration from 'dayjs/plugin/duration.js'
import relativeTime from 'dayjs/plugin/relativeTime.js'
export default defineNuxtPlugin((nuxtApp) => {
  dayjs.extend(duration)
  dayjs.extend(relativeTime)
  nuxtApp.provide('dayjs', dayjs)
})
declare module '#app' {
  interface NuxtApp {
    $dayjs: dayjs.Dayjs
  }
}
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $dayjs(date?: dayjs.ConfigType): dayjs.Dayjs
  }
}
```

and when use do this in a vue file:
```Ts
import dayjs, { type Dayjs } from 'dayjs'
const { until } = defineProps<{
    until: string
  }>()
const now = useNow() //vueuse tool
const untilDayjs = ref<Dayjs>()
const untilDuration = computed(() => {
    if (untilDayjs.value) {
      if (untilDayjs.value.isBefore(now.value)) {
        return dayjs.duration(0)
      }
      return dayjs.duration(untilDayjs.value.diff(now.value))
    }
  })

onBeforeMount(() => {
    untilDayjs.value = dayjs(until)
  })
```

**Comment by sedatbasar** [comment]
> > import { default as dayjs } from 'dayjs'
> 
> I'm getting the error "`Module '"dayjs"' has no exported member 'default'"` when I try the above

You can use `import * as dayjs from "dayjs"` for that issue
Or alternatively you may use CommonJS way `const dayjs = require("dayjs")`

**Comment by luisjuniorj** [comment]
> > if anyone else is still having this issue after trying the above - this worked for me
> > `import { default as dayjs } from 'dayjs';`
> 
> Hi, just wanted to add that it would be the same doing something like this:
> 
> ```
> import dayjs from 'dayjs';
> ```

Docs, should be updated to this.

**Comment by chalkiasS** [comment]
If you're using ESModules and **need to import a plugin**, here's how:

Let's say I wanted to import the utc plugin.

import utc from 'dayjs/plugin/utc.js';

Works like a charm. Unfortunately, the documentation only seems to have CommonJS examples, leaving us who are trying to avoid it scrambling for answers.

**Comment by anburocky3** [comment]
> If you're using ESModules and **need to import a plugin**, here's how:
> 
> Let's say I wanted to import the utc plugin.
> 
> import utc from 'dayjs/plugin/utc.js';
> 
> Works like a charm. Unfortunately, the documentation only seems to have CommonJS examples, leaving us who are trying to avoid it scrambling for answers.

You are right, documentation can be improved to make this DX friendly.
