### ISSUE TITLE
Lazy loading translation files

### ISSUE THREAD

**Issue by Epistol** [iamkun/dayjs#789]
**Describe the bug**
Impossible to lazy-load any translation file in the case where the lang is dynamicaly set

**Expected behavior**
Something like https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

**Comment by iamkun** [comment]
ref: #739



Load this via `script` element `https://unpkg.com/dayjs/locale/uk`, then you can use `dayjs.locale('uk')`

```
var script = document.createElement('script');
script.onload = function() {
  dayjs.locale('uk')
};
script.src = "https://unpkg.com/dayjs/locale/uk";
document.head.appendChild(script);
```

**Comment by ryan-mcginty-alation** [comment]
@iamkun I realize that is the documented way to initialize a locale, but that isn't lazy loading it. It requires the locale be imported statically up front. Is it possible to dynamically import? Thanks

**Comment by NateRadebaugh** [comment]
For future people, here's what I was able to do in JS to create separate bundles and lazy-load based on the current locale to avoid pulling in too many in the initial build:

```ts
export async function initializeDayjsLocale() {
  const locale = window.__locale;
  if (locale) {
    const localeParts = locale.split("-");
    const language = localeParts[0];
    try {
      switch (language) {
        case "en":
        case undefined:
          // English is default
          break;

        case "es":
          await import("dayjs/locale/es");
          break;

        case "de":
          await import("dayjs/locale/de");
          break;

        case "fr":
          await import("dayjs/locale/fr");
          break;

        case "it":
          await import("dayjs/locale/it");
          break;
      }

      dayjs.locale(language);
    } catch (error) {
      console.error(error);
    }
  }
}
```
