### ISSUE TITLE
Adding addWeekDays functionality

### ISSUE THREAD

**Issue by minasm** [iamkun/dayjs#791]
Hello there,
I am trying to migrate to DayJS and so far all went pretty easy. I was wondering if you plan to implement a weekDay to the add method? 
Something like `dayjs().add(7,'weekday')` to skip weekend days?  Or just `addWeekDays` method?

Thank you!

**Comment by iamkun** [comment]
Day.js will keep the same API as moment.js. So, probably no in the short term. But you can add it yourself easily through a plugin. https://day.js.org/docs/en/plugin/plugin
