### ISSUE TITLE
Date Parsing fails for millisecond pieces that are longer than 3 characters

### ISSUE THREAD

**Issue by johnmarinelli** [iamkun/dayjs#796]
**Describe the bug**
On Safari, given this input:
`'2020-02-14T17:00:00.000000'`
dayjs' `REGEX_PARSE` will fail, because the milliseconds piece is 6 characters long:
https://github.com/iamkun/dayjs/blob/dev/src/index.js#L59

On Chrome, this is fine.  The output of `dayjs(date).format()` will be the same, whether the given dates' milliseconds piece is 3 or 6 characters long.
On Safari, the output will be different, depending on the length of the milliseconds piece.

code sandbox (open in safari): https://codesandbox.io/s/dayjs-vs-moment-eubxe?fontsize=14&hidenavigation=1&theme=dark

I suspect an easy fix would be to change the last capture group of `REGEX_PARSE` to allow more than 3 characters for milliseconds pieces.  

**Expected behavior**
In Safari, the formatted date should be the same, whether the milliseconds piece is 3 characters or 6.

**Information**
 - Day.js Version 1.8.19
 - OS: Mac
 - Browser: Safari
 - Time zone: Australian Eastern

**Comment by ygj6** [comment]
@johnmarinelli It seems that the issue was resolved in this commit: https://github.com/iamkun/dayjs/commit/d1bdd36a56e3d1786523a180e3fc18068f609135#diff-deacbb7ba720e1d8d121b6fe08bad977

**Comment by johnmarinelli** [comment]
@ygj6 looks like it, thank you for the update
