### ISSUE TITLE
DayJS set date incorrect

### ISSUE THREAD

**Issue by ValkyrieQ** [iamkun/dayjs#798]
**Describe the bug**
I passed specific day month year then format it. But it output incorrect. For example
`dayjs().date(30).month(2).year(2020).format('DD/MM/YYYY')` <<< output is 01/03/2020
`dayjs().date(31).month(2).year(2020).format('DD/MM/YYYY')` <<< output is 02/03/2020
`dayjs().date(30).month(3).year(2020).format('DD/MM/YYYY')` <<< output is 01/04/2020
`dayjs().date(31).month(3).year(2020).format('DD/MM/YYYY')` <<< output is 02/04/2020

**Expected behavior**
Expect output
30/03/2020 and 31/03/2020
30/04/2020 and 31/04/2020

**Information**
 - Day.js Version 1.8.20
 - OS: Windows 10
 - Browser: Chrome and Terminal
 - Time zone: GMT +7

**Comment by ttsirkia** [comment]
If you start with `date`, it will use the curren month (February) which does not have 30 days.

```
dayjs().date(30).format('DD/MM/YYYY')
"01/03/2020"
```

Start with the year, then month and then day.

**Comment by ttsirkia** [comment]
Even that may cause problems. If you want to use integers to initialize the object, I suggest this: https://day.js.org/docs/en/parse/date

**Comment by ValkyrieQ** [comment]
> If you start with `date`, it will use the current month (February) which does not have 30 days.
> 
> ```
> dayjs().date(30).format('DD/MM/YYYY')
> "01/03/2020"
> ```
> 
> Start with the year, then month and then day.

Hi @ttsirkia Thank you very much for information. Both solutions are solve my issues.

**Comment by gourvankit** [comment]
This is still an open Bug.

**Comment by ttsirkia** [comment]
It is not a bug, working as intended and documented. Calling `dayjs()` initializes it with the current timestamp. If you then change the date number and it exceeds the number of days in the current month, the overflowing days will be pushed to the next month. Either use the order years, months and days or use the proper constructor.
