### ISSUE TITLE
Does dayjs work server side

### ISSUE THREAD

**Issue by bschwartz757** [iamkun/dayjs#800]
**Describe the bug**

This isn't so much a bug report as a question (although it would be nice if the README was updated to explicitly say whether it works in a Node web server.)

**Expected behavior**

The dayjs README lets me know that it is meant for server side use as well as client side/browser.

**Information**
 - Day.js Version [e.g. v1.0.0]
 - Browser [e.g. chrome 62]
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
Of course.

You can check here as a reference. https://day.js.org/docs/en/installation/installation
