### ISSUE TITLE
Default calendar formats

### ISSUE THREAD

**Issue by scorsi** [iamkun/dayjs#805]
Hello,

I'm looking to change the default formats of the `Calendar` plugins.
Actually, I'm forced to override the `calendar` method like this:
```javascript
const oldCalendar = dayjs.prototype.calendar;
dayjs.prototype.calendar = function newCalendar(referenceTime = null, formats = {}) {
  return oldCalendar.bind(this)(referenceTime, {
    // TODO: add i18n here
    sameDay: '[Aujourd\'hui à] LT', 
    lastDay: '[Hier à] LT',
    lastWeek: 'dddd [dernier à] LT',
    sameElse: 'LLLL',
    ...formats,
  });
};
```

Which does not respect our code standards.

Is there any other options ?

Thanks,

**Comment by iamkun** [comment]
You can also pass specifying calendar output formats as the second parameter.

https://day.js.org/docs/en/display/calendar-time

**Comment by scorsi** [comment]
Well, actually I have to pass the exact same calendar format to a lot a different place in my code. To avoid code duplication I would like to setup a default formats to dayjs for calendar plugin so, I just have to call `mydate.calendar()` which is what I do with __momentjs__.

**Comment by iamkun** [comment]
Oh, I see. Maybe there's a better way. You can update the locale config like this.
```js
var dayjs = require("dayjs")
var calendar = require('dayjs/plugin/calendar')
var updateLocale = require('dayjs/plugin/updateLocale')
dayjs.extend(updateLocale)
dayjs.extend(calendar)
dayjs.updateLocale('en', {
  calendar: {
  sameDay: '[Today at] h:mm A[ your format]',
  nextDay: '[Tomorrow][ your format]', 
  nextWeek: 'dddd[ your format]', 
  lastDay: '[Yesterday][ your format]',
  lastWeek: '[Last] dddd[ your format]', 
  sameElse: 'DD/MM/YYYY[ your format]'
}
})

dayjs().calendar(dayjs('2008-01-01'))
```
https://runkit.com/embed/w2atmrrgv3kb
<img width="568" alt="Screen Shot 2020-02-29 at 5 25 31 PM" src="https://user-images.githubusercontent.com/17680888/75604904-8829b980-5b18-11ea-89af-cd43b790c345.png">

**Comment by scorsi** [comment]
Awesome, I’ll try that but it’s appear to be what I would like to achieve and in addition with i18n spec ! Thanks !

**Comment by iamkun** [comment]
fixed
