### ISSUE TITLE
Does Calendar can use function in format as possible value

### ISSUE THREAD

**Issue by scorsi** [iamkun/dayjs#806]
Hello,

It could be a good idea to add callbacks as possible values to Calendar format.
Like __momentjs__ does since `2.14.0` : [look here](https://momentjs.com/docs/#/displaying/calendar-time/).

Exemple:
With arrow function:
```javascript
dayjs("2020-02-26").calendar(null, {
  sameElse: (now, self) => {
    const d = self.diff(now);
    if (d > 0) return "After";
    else return "Before";
  }
});
```
With classic function:
```js
dayjs("2020-02-26").calendar(null, {
  sameElse: function (now) {
    const d = this.diff(now);
    if (d > 0) return "After";
    else return "Before";
  }
});
```

We can pass a function which take as parameter the date given to calendar call (here `null` so `now`) and to be fully compatible with __momentjs__ we can use `this` instead of the second parameter to access the base instance (here `dayjs("2020-02-26")`).

Thanks ;)

**Comment by iamkun** [comment]
will do

**Comment by KarthikSiddarth** [comment]
I am interested in working on this.

**Comment by iamkun** [comment]
@KarthikSiddarth   that would be nicem thx

**Comment by iamkun** [comment]
added now 😬
