### ISSUE TITLE
How to include a plugin using unpkg or cdnjs

### ISSUE THREAD

**Issue by MartijnHarmenzon** [iamkun/dayjs#812]
How can you include a plugin using cdnjs or unpg?
I want to include the utc plugin within a Vanilla JS website.

I found the following code:
```
<script src="path/to/dayjs/plugin/advancedFormat"></script>
<!-- Load plugin as window.dayjs_plugin_NAME -->
<script>
  dayjs.extend(window.dayjs_plugin_advancedFormat)
</script>
```

But instead of storing the plugin file locally, I would like to include it from unpgk or cdnjs.

**Comment by iamkun** [comment]
You can check here is a reference.
https://day.js.org/docs/en/plugin/loading-into-browser

**Comment by iamkun** [comment]
```
 <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
  <script src="https://unpkg.com/dayjs@1.8.21/plugin/utc.js"></script>

  <script>
    dayjs.extend(window.utc);
  </script>
```

**Comment by MartijnHarmenzon** [comment]
Thanks @iamkun for the quick response. 
I included the above code.
Unfortunately this results in an error:
**TypeError: t is not a function**

Any suggestion?
