### ISSUE TITLE
Invalid Thai translation on "fromNow" function when 1 day passed

### ISSUE THREAD

**Issue by ReiiYuki** [iamkun/dayjs#816]
**Describe the bug**

Invalid result when i apply with one day passed

Current result is `วัน ที่ผ่านมา`

**Expected behavior**

It should be `1 วัน ที่ผ่านมา`

**Information**
 - Day.js Version 1.8.21
 - OS: OSX
 - Browser Chrome  80.0.3987.122 
 - Time zone: GMT+07:00 (Indochina Time)

**Comment by iamkun** [comment]
Thanks. 

Could you please send us a pull request to correct this in "Thai" (cause we don't know this language.)

This's easy, just to keep sync between 
https://github.com/iamkun/dayjs/blob/dev/src/locale/th.js#L19
and 
https://github.com/moment/moment/blob/develop/locale/th.js#L46
`relativeTime` section, and ignore the `ss` one.

Thanks
