### ISSUE TITLE
[Bug] Parsed utc time string does not format in locale timezone

### ISSUE THREAD

**Issue by lucianholt97** [iamkun/dayjs#832]
**Describe the bug**
`dayjs('09:00:00', {format: 'HH:mm:ss', utc: true}).format('HH:mm:ss')` returns `'09:00:00'` and does not consider the browser timezone offset

**Expected behavior**
My browser has a timezone offset of `'+01:00'` and `'10:00:00'` is excepted as return value.
Also I notices in the console, that the underlying Date instance is correct, so I did the following workaround, which works fine but should not be needed:
```
let date = dayjs('09:00:00', {format: 'HH:mm:ss', utc: true}).toDate()
return dayjs(date).format('HH:mm:ss') -> '10:00:00'
```
**Information**
 - Day.js Version: ^1.8.16
 - Browser [e.g. chrome 62]
 - Time zone: UTC+01:00

**Comment by iamkun** [comment]
passing config to the constructor is not a recommended way.

please use https://day.js.org/docs/en/parse/utc

**Comment by iamkun** [comment]
var dayjs = require("dayjs")
var customParseFormat = require('dayjs/plugin/customParseFormat')
var utc = require('dayjs/plugin/utc')

dayjs.extend(utc)
dayjs.extend(customParseFormat)
dayjs.utc('09:00:00', 'HH:mm:ss').local().format('HH:mm:ss')
