### ISSUE TITLE
Yesterday shows as tomorrow

### ISSUE THREAD

**Issue by canpoyrazoglu** [iamkun/dayjs#834]
**Describe the bug**
Day.js displays my date (yesterday) as tomorrow.

**Expected behavior**
It should display it as yesterday

**Information**
 - Day.js Version 1.8.22
 - OS: macOS 10.15 Catalina
 - Browser: Chrome 80.0.3987.132
 - Time zone: GMT+3

---

I have a Unix timestamp `1584030726` which is a stamp of `Thursday, March 12, 2020 4:32:06 PM`. (yesterday afternoon as I'm writing this).

I have day.js in my React app:

```

import dayjs from 'dayjs'
import calendar from 'dayjs/plugin/calendar'
dayjs.extend(calendar);
[...]
<span>dayjs().calendar(dayjs.unix(1584030726))</span>

```

For some reason it displays as `Tomorrow at 1:32 PM` (the time is correct, the date is wrong). If I try a date from today (e.g. now), it displays correctly as today.

**Comment by xxyuk** [comment]
I think this is an expected result and the same as moment.js.

**Comment by canpoyrazoglu** [comment]
@xxyuk weird. I haven't tried moment.js but I don't understand how this is the excepted result. I (obviously) want to display a date in yesterday as `yesterday`, not `tomorrow`.

**Comment by iamkun** [comment]
You can check the doc here https://day.js.org/docs/en/display/calendar-time

**Comment by iamkun** [comment]
Calendar time displays time relative to a given reference time (defaults to now) but does so slightly differently than dayjs#fromNow.

```
moment('2020-03-12').calendar() // Yesterday at 12:00 AM
moment('2020-03-12').fromNow() // 2 days ago  
```

**Comment by iamkun** [comment]
Calendar time displays time relative to a given reference time (defaults to now) but does so slightly differently than dayjs#fromNow.
```
dayjs('2020-03-12').calendar() // Yesterday at 12:00 AM
dayjs('2020-03-12').fromNow() // 2 days ago  
```

**Comment by canpoyrazoglu** [comment]
Okay, it was a confusion about which-time-relates-to-which.
