### ISSUE TITLE
PouchDB compatibility

### ISSUE THREAD

**Issue by eduardodallmann** [iamkun/dayjs#835]
I have an object assembled from backend data, the date values are typed as `dayjs.Dayjs`, then I write directly to PouchDB, and the properties of type dayjs are written like this:
![image](https://user-images.githubusercontent.com/7562936/76688465-c7bdce80-660b-11ea-89ee-8062be2813d2.png)

When I load information from memory, I can't use it just like this: `dayjs(fields.data)`.

How do I restore a dayjs object from my localstorege data?

**Comment by iamkun** [comment]
It's not recommended to save Day.js object directly.  You can do
https://day.js.org/docs/en/display/unix-timestamp-milliseconds

https://day.js.org/docs/en/parse/unix-timestamp-milliseconds

```
dayjs().valueOf() // save unix time stamp

// load from data base time stamp
var time = 'data-base-time-stamp'
dayjs(time) // and use it
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
