### ISSUE TITLE
add(1, 'month') returns inconsistent results

### ISSUE THREAD

**Issue by borisovg** [iamkun/dayjs#837]
**Describe the bug**
This returns a date in the next month:
```
dayjs('2020-01-01').add(1, 'month').toISOString();
"2020-02-01T00:00:00.000Z"
```
This returns date in the same month:
```
dayjs('2020-03-01').add(1, 'month').toISOString();
"2020-03-31T23:00:00.000Z"
```

**Expected behavior**
Return date in the next month.

**Information**
 - Day.js Version: 1.8.22
 - OS: Debian GNU/Linux
 - Browser: Firefox 74
 - Time zone: GMT (London)

**Comment by iamkun** [comment]
Hi, this is the expected `ISO string` result.

You can call `.format` to get the display date string in the next month.

**Comment by borisovg** [comment]
Understood, thanks!

**Comment by cshouts-tasc** [comment]
> Hi, this is the expected `ISO string` result.
> 
> You can call `.format` to get the display date string in the next month.

This seems pretty unexpected. I would expect the ISO date for the example code
`dayjs('2020-03-01').add(1, 'month').toISOString();`
to be
`"2020-04-01T00:00:00.000Z"`
