### ISSUE TITLE
Custom range?

### ISSUE THREAD

**Issue by mackelito** [iamkun/dayjs#840]
I have been looking in the docs, googling and searched git issues but have not been able to find anything about setting a custom range?

I need to do something like this...
- if more that 47h show x days 
- if more than 24h but less than 47h show x days and x hours
- if less than 24h show x hours
- if less than 3h show x hours and x mins
- if less that 1h show x mins

Is that doable?

**Comment by iamkun** [comment]
This is a REALLY custom feature, I think. Better implement it in your own project or a custom plugin.

**Comment by mackelito** [comment]
Yeah it sure is super custom :)
I was kind of hoping that we could tap in to the range config :)

**Comment by mackelito** [comment]
we currently working on doing it like 
```
dayjs.updateLocale('sv', {
      relativeTime: {
        ...dayjs.en.relativeTime,
hh: (number, withoutSuffix, key, isFuture) => {
          console.log(number, withoutSuffix, key, isFuture)
          if (isFuture) {
            return `${number} timmar`
          }
        },
```
etc...

but then we need it for each locale.. just ends up in non dry code :)

**Comment by iamkun** [comment]
Or maybe https://github.com/iamkun/dayjs/issues/830#issuecomment-598023425 is a better way?

**Comment by iamkun** [comment]
Update: https://github.com/iamkun/dayjs/pull/851

We can set custom range thresholds now. 😬
