### ISSUE TITLE
Possible to use custom time as base time?

### ISSUE THREAD

**Issue by Wyzix33** [iamkun/dayjs#843]
Hi, 
I was searching for a way to use server time in my calculations, and found this lib:
https://github.com/NodeGuy/ServerDate
Is is possible to make dayjs base time the same way so it won't depend on system time (maybe a plugin) ? 
That is to initialize dayjs with a timestamp we get from our server so it is synchronized with the server's clock when it is first loaded and then it can re-synchronize itself from time to time to keep the two clocks from drifting apart.
Thanks

**Comment by iamkun** [comment]
We don't have plan to do this in the short term.
