### ISSUE TITLE
subtract() can't change current Day.js object

### ISSUE THREAD

**Issue by OwenShi** [iamkun/dayjs#844]
**Describe the bug**
the api subtract() can't change current Day.js object.
utcOffset() too

**Expected behavior**
those api can change current dayjs object like docs, also like moment.js

**Information**
 - Day.js Version V1.8.23
 - OS: OS X
 - Browser chrome 80
 - Time zone: GMT + 08:00

https://runkit.com/shiwj/5e74626583a1ec001a82bf9c
<img width="642" alt="subtract problem" src="https://user-images.githubusercontent.com/22406464/77141506-1c53c480-6ab8-11ea-9663-85101254d0b1.png">

**Comment by iamkun** [comment]
https://day.js.org/docs/en/parse/parse

The Day.js object is immutable, that is, all API operations that change the Day.js object in some way will return a new instance of it.

**Comment by OwenShi** [comment]
> https://day.js.org/docs/en/parse/parse
> 
> The Day.js object is immutable, that is, all API operations that change the Day.js object in some way will return a new instance of it.

ok，but the docs said 'Mutates the current Day.js object by xxxx' , this may be misunderstood.

**Comment by iamkun** [comment]
I'll update it, thanks.

**Comment by iamkun** [comment]
@OwenShi  Docs updated. Is it better now? 😬

**Comment by OwenShi** [comment]
> @OwenShi Docs updated. Is it better now? 😬

hhh，good job 😬～

**Comment by iamkun** [comment]
close now 😀
