### ISSUE TITLE
String + Format wrong

### ISSUE THREAD

**Issue by nguyenduclong-ict** [iamkun/dayjs#853]
**Describe the bug**
dayjs.extend(customParseFormat)
dayjs("05/08/2019", "DD/MM/YYYY").format('DD/MM/YYYY')

// => 08/05/2019

**Comment by iamkun** [comment]
<img width="560" alt="Screen Shot 2020-04-01 at 11 00 00 AM" src="https://user-images.githubusercontent.com/17680888/78094783-f7d8e000-7407-11ea-868c-9ceac05109bb.png">
https://runkit.com/embed/hv3n1ajm7ldv
