### ISSUE TITLE
[docs] Customize Plugin needs to be updated

### ISSUE THREAD

**Issue by mayeths** [iamkun/dayjs#859]
**Describe the bug**
I want to extend `format()` like [the docs said](https://day.js.org/docs/en/plugin/plugin), but it seems like someone just add `this.invalid()` after [this commit](https://github.com/iamkun/dayjs/commit/cbc10684d3b542f699060f1318946680114ec42a?diff=unified#diff-1fdf421c05c1140f6d71444ea2b27638R258).

The current docs is outdated:
```javascript
  // overriding existing API
  // e.g. extend dayjs().format()
  const oldFormat = dayjsClass.prototype.format
  dayjsClass.prototype.format = function(arguments) {
    // original format result
    const result = oldFormat(arguments)
    // return modified result
  }
```

`this.invalid` called in `oldformat` won't find what `this` is.

**Expected behavior**

Update the docs with calling `const result = oldFormat.bind(this)(arguments)` instead of `const result = oldFormat(arguments)`

**Information**
 - Day.js Version [v1.8.23]
 - OS: [Windows10]
 - Browser [chrome 80]
 - Time zone: [CST (China Standard Time) UTC/GMT +8 hours]

**Comment by iamkun** [comment]
Doc updated, thanks.
