### ISSUE TITLE
[bugs] "advancedFormat" plugin rely on "weekOfYear" plugin

### ISSUE THREAD

**Issue by mayeths** [iamkun/dayjs#860]
**Describe the bug**
[advancedFormat.js](https://github.com/iamkun/dayjs/blob/d568273223/src/plugin/advancedFormat/index.js#L25) handle `wo, w, ww` format, but `week()` is provided by [weekOfYear.js](https://github.com/iamkun/dayjs/blob/d568273223/src/plugin/weekOfYear/index.js#L5). [The docs](https://day.js.org/docs/en/plugin/advanced-format) didn't identify that we have to extend `weekOfYear` plugin first.

Two possible solutions:
1. `import weekOfYear from './weekOfYear'` and extend it in advancedFormat.js
2. Update the doc of `advancedFormat` likes this:
```javascript
var advancedFormat = require('dayjs/plugin/advancedFormat')
var weekOfYear = require('dayjs/plugin/weekOfYear')
dayjs.extend(weekOfYear)  // wo, w and ww format relies on it
dayjs.extend(advancedFormat)

dayjs().format('Q Do k kk X x')
```

**Comment by iamkun** [comment]
<img width="714" alt="Screen Shot 2020-04-08 at 3 34 41 PM" src="https://user-images.githubusercontent.com/17680888/78757085-7c9a9f80-79ae-11ea-9e00-d541ae48018c.png">
It is listed here.

**Comment by mayeths** [comment]
My bad, closing issue😆
