### ISSUE TITLE
Difference between locale fr monthsShort abbreviation and moment.js abbreviation

### ISSUE THREAD

**Issue by PierrickGT** [iamkun/dayjs#861]
**Describe the bug**
Fr locale abbreviations for monthsShort differ from Moment.js ones since a dot is missing at the end of months with more than 4 letters.

Here is the code line concerned:
https://github.com/moment/moment/blob/13a61b285c095bda7ea8e33156090ea5ccfeaef1/locale/fr.js#L13
https://github.com/iamkun/dayjs/blob/fc08ab68f8a28269802deeab9d6b0473b92cdc51/src/locale/fr.js#L10

**Expected behavior**
I expect to have the same abbreviations than Moment.js

**Information**
 - Day.js Version: 1.8.23
 - OS: Mac OS 10.15.4
 - Browser: Chrome 80.0.3987.163
 - Time zone: GMT+01:00

**Comment by iamkun** [comment]
Can you send us a PR with the correct one, please?

**Comment by PierrickGT** [comment]
> Can you send us a PR with the correct one, please?

Here you go: https://github.com/iamkun/dayjs/pull/862

**Comment by iamkun** [comment]
Cool thanks
