### ISSUE TITLE
[Request for Improvement] Non-necessary Output String when NULL is given

### ISSUE THREAD

**Issue by mcdmaster** [iamkun/dayjs#874]
**Describe the bug**
- The NULL input produces non-necessary output in string i.e. 'Invalid Date'

**Expected behavior**
- Null values go to output straightforward (AS-IS)

**Information**
 - Day.js Version: current
 - OS: Linux, Windows (both x64)
 - Browser: Chrome, Safari, Edge et al.
 - Time zone: GMT+9:00 (Osaka/Tokyo/Sapporo)

**Comment by iamkun** [comment]
Day.js treats dayjs(null) as an invalid input.
https://day.js.org/docs/en/parse/now

**Comment by mcdmaster** [comment]
Sorry but I disagree. I do not think that Day.js has to get back with non-Date value i.e. string when an invalid data comes in. Anyway, I will try to issue a PR. Thanks in advance

**Comment by iamkun** [comment]
Day.js focus on date-time input only and treats all non-date value as an invalid date.

**Comment by mcdmaster** [comment]
Your implication is that the caller has to expect Day.js output as not only date-time but also string, right? Although I do understand that invalid data needs to be addressed as "invalid", my colleague and I are anxious that it gets back with a data type other than date-time or null indeed

**Comment by iamkun** [comment]
You will always get a `Day.js` object whatever you pass into the dayjs contractor. 

The only difference is some of the them are valid `Day.js` objects and others not.

You can tell by calling `dayjs.isValid` to get a boolean if it's valid or not.

Thus, a valid object `format` to a date string, and an invalid object to 'Invalid Date'.
