### ISSUE TITLE
QuarterOfYear plugin methods not compiling in TypeScript

### ISSUE THREAD

**Issue by david-crouch** [iamkun/dayjs#875]
When attempting to use the QuarterOfYear plugin in TypeScript, I get the following compilation error when attempting to use any of the following methods:
   .startOf('quarter')
   .endOf('quarter')
   .add(n, 'quarter')
(Note: I have not tried any other methods - it may be failing on more than just these)

_Error: Argument of type '"quarter"' is not assignable to parameter of type 'OpUnitType'._

The plugin is being referenced via:
  var quarterOfYear = require('dayjs/plugin/quarterOfYear')
  dayjs.extend(quarterOfYear)

**Comment by iamkun** [comment]
Tested ok on the latest version of Day.js. What's yours, please.

**Comment by david-crouch** [comment]
Hi, 

I am using version 1.8.24

**Comment by iamkun** [comment]
a re-production repo, please?

**Comment by david-crouch** [comment]
Thanks for your assistance. I have created a repro here: 
https://github.com/david-crouch/Issue_DayJs_QuarterPlugin

Line 10 of App.tsx compiles fine (now.startOf('month')), but Line 10 where I attempt the same for 'quarter' is failing to compile.

![image](https://user-images.githubusercontent.com/41879680/79725618-a5188700-8328-11ea-8e9a-2fe8a910d36e.png)

Same error when attempting to run:
![image](https://user-images.githubusercontent.com/41879680/79725715-c7120980-8328-11ea-86d6-91fba41ea1e1.png)

**Comment by iamkun** [comment]
<img width="688" alt="Screen Shot 2020-04-20 at 3 50 27 PM" src="https://user-images.githubusercontent.com/17680888/79727269-b9f01d00-831e-11ea-92b5-e4627972be72.png">

Please check https://day.js.org/docs/en/installation/typescript

**Comment by david-crouch** [comment]
Thank you. Yes, that has done the trick. :-)

Please note, I was following the documentation from this page previously:
https://day.js.org/docs/en/plugin/quarter-of-year

**Comment by iamkun** [comment]
Better check our doc related to the Typescript part.
