### ISSUE TITLE
Can I set multiple values as second parameter into onSame method?

### ISSUE THREAD

**Issue by CreativeRusBear** [iamkun/dayjs#879]
I wanna compare two `dayjs` objects using `onSame` method. But I wanna checking date without time.

Can I set multiple values as second parameter like this: `dayjs().isSame(dayjs(), 'date month year')`?

**Comment by iamkun** [comment]
I don't think this should be the right way.

you can simply compare `dayjs1.format('YYYY-MM-DD') === dayjs2.format('YYYY-MM-DD')`

**Comment by CreativeRusBear** [comment]
@iamkun Ok, thanks
