### ISSUE TITLE
Add motivation to README 

### ISSUE THREAD

**Issue by Olian04** [iamkun/dayjs#88]
In my opinion there should probably be a section of the README dedicated to explaining the "why?" and the "what?" of dayjs. 

* Why should you pick dayjs over an established library such as momentjs?
* What makes dayjs unique? 
* Why was it created?
* What problems does it solve, what holes in the market does it fill? 

Etc. You get it.

**Comment by adamfaliq42** [comment]
Quite similar to OP, but I think there should be a section describing how dayjs work, that makes it better than other libraries.

**Comment by iamkun** [comment]
#58
