### ISSUE TITLE
CustomParseFormat + strict parsing issue

### ISSUE THREAD

**Issue by peetboy** [iamkun/dayjs#905]
**Describe the bug**
I tested strict parsing from documentation and it doesn't work as expected.
`dayjs('1970-00-00', 'YYYY-MM-DD', true).isValid() // returns true`

Similarly
`dayjs('13/05/2020abcdefg', 'DD/MM/YYYY', true).isValid() // returns true`

**Expected behavior**
Strict parsing should return false according the docs.
> You may specify a boolean for the last argument to use strict parsing. Strict parsing requires that the format and input match exactly, including delimeters.

`dayjs('1970-00-00', 'YYYY-MM-DD', true).isValid() // false`

**Information**
dayjs - latest version
browser - Chrome, Edge, Firefox

**Comment by iamkun** [comment]
Please check and try our latest version.

**Comment by peetboy** [comment]
> 
> 
> Please check and try our latest version.

Which version? I'm using the latest (installed yesterday from npm).
This is not working for me even on day.js.org site when trying in dev tools, although not sure which version is installed there.

**Comment by iamkun** [comment]
Have you extended the plugin  CustomParseFormat first?

ref: https://day.js.org/docs/en/parse/string-format

**Comment by peetboy** [comment]
> 
> 
> Have you extended the plugin CustomParseFormat first?

Yes. I did some code changes and reinstall the package and it seems to work now.
