### ISSUE TITLE
查找--isSame不支持时间戳格式数据

### ISSUE THREAD

**Issue by keepAwayFrom404** [iamkun/dayjs#907]
**Describe the bug**
isSame不支持时间戳格式数据
**Expected behavior**
**Information**
 - Day.js Version [e.g. v1.7.5]
 - OS: 1014.4
 - Browser  chrome 81

dayjs(1589357282710).isSame(1589357262710, 'day') // 同一天时间戳但比较为false，moment是ok的

**Comment by iamkun** [comment]
Please use the latest version, v1.7.5 does not support the second argument. 请升级 Day.js 版本， 1.7.5 是不支持第二个参数的。
