### ISSUE TITLE
Incorrect year formatting

### ISSUE THREAD

**Issue by upendra-web** [iamkun/dayjs#910]
**Describe the bug**
`yyyy` is not formatted properly as year. For eg: `dayjs().format('DD MMM, yyyy')` is giving output `20 May, yyyy`

**Expected behavior**
For `dayjs().format('DD MMM, yyyy')` => `20 May, 2020`

**Screenshot**
![Screenshot 2020-05-20 at 2 00 20 PM](https://user-images.githubusercontent.com/43108965/82424590-073ce700-9aa3-11ea-9c1c-26c5350231ae.png)

**Information**
 - Day.js Version: 1.8.27
 - OS: Mac OSX
 - Browser: Chrome 81.0.4044.138
 - Time zone: Indian Standard UTC +5:30

**Comment by iamkun** [comment]
`yyyy` is not listed on our docs, neither does moment.js doc. Please use `YYYY` instead.

**Comment by upendra-web** [comment]
Yeah, but still some of the popular libraries like React DatePicker uses `yyyy` format and as it also mentioned in this [link](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md) that `yyyy` is correct way of using year. Can you please comment on this?

**Comment by upendra-web** [comment]
And have another case, please check the below screenshot
![Screenshot 2020-05-20 at 2 42 17 PM](https://user-images.githubusercontent.com/43108965/82428481-32760500-9aa8-11ea-84de-fbff80602d48.png)

In the above screenshot, for `ddd`, `moment.js` give day of the year and `dayjs` is giving year. Is this intentional?

**Comment by iamkun** [comment]
Please check List of all available formats https://day.js.org/docs/en/display/format#list-of-all-available-formats
