### ISSUE TITLE
Cannot read property 'unix' of undefined (Jest)

### ISSUE THREAD

**Issue by BYODKM** [iamkun/dayjs#912]
When I run a simple test with Jest, a `TypeError` occurred.

```ts
import dayjs from 'dayjs'

export function foo(epoch: number){
  return dayjs.unix(epoch).format('YYYY/MM/DD HH:mm')
}

// TypeError: Cannot read property 'unix' of undefined
```

Then I tried this, it eliminated the error.

```ts
// import dayjs from 'dayjs'
const dayjs = require('dayjs')
```

But I prefer using an `import` statement. Any idea?

**Information**

```
  "dependencies": {
    "@types/jest": "^25.2.3",
    "dayjs": "^1.8.27",
    "jest": "^26.0.1",
    "ts-jest": "^26.0.0",
    "typescript": "^3.9.3"
  }
```

**Comment by iamkun** [comment]
Please check here as a reference. https://day.js.org/docs/en/installation/typescript

**Comment by BYODKM** [comment]
@iamkun Oh sorry, my bad.

Without `"esModuleInterop": true`, my rollup said good to go. But Jest doesn't. I should have read further documentations.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
