### ISSUE TITLE
Month Abbreviations improvement

### ISSUE THREAD

**Issue by eslepova** [iamkun/dayjs#914]
Hi,

We moved from moment to dayjs a few months ago.  And everything is perfect except for one thing: declension of months.

In moment we have:
`moment.updateLocale('en', {
     monthsShort : {
          format: 'янв_фев_мар_апр_мая_июня_июля_авг_сен_окт_ноя_дек'.split('_'),
         standalone: 'янв_фев_март_апр_май_июнь_июль_авг_сен_окт_ноя_дек'.split('_')
     }
});` (https://momentjs.com/docs/#/customization/month-abbreviations/)

Do you have plans to add it?

**Comment by iamkun** [comment]
Of course.

Just check `UpdateLocale` plugin here  https://day.js.org/docs/en/customization/customization

**Comment by eslepova** [comment]
Do you mean you will add it sometime?

**Comment by iamkun** [comment]
@eslepova we have this already. Just check our website for more detail.

**Comment by eslepova** [comment]
Yes, but it allows us to add only one monthsShort setting, but the moment has 2 settings for monthsShort - format and standalone.
Some languages like Russian have different ways of spelling short months depends of declension. Like "май" and "мая". Both of them are monthsShort.

**Comment by iamkun** [comment]
You can check here as a reference. https://github.com/iamkun/dayjs/blob/dev/src/locale/ru.js#L39 

`monthsShort` also accept a function

**Comment by iamkun** [comment]
Besides, tested dayjs gives the correct result as you mentioned above.
<img width="574" alt="Screen Shot 2020-05-25 at 6 01 16 PM" src="https://user-images.githubusercontent.com/17680888/82802663-d816e300-9eb1-11ea-8af5-fb980cc58aba.png">
https://runkit.com/embed/ai6s8h4zfcbr

**Comment by eslepova** [comment]
So ru.js already has everything inside it, and I don't have to add 'monthsShort' manually, which it is used to be in the project. Now I understand, thanks a lot!
The reason for the problem was that monthsShort was overwritten in the project.

It would be nice if you put in doc https://day.js.org/docs/en/customization/customization example that monthsShort can be a function.

Thanks a lot again!

**Comment by iamkun** [comment]
doc updated thanks.
