### ISSUE TITLE
japanese locale missing words 

### ISSUE THREAD

**Issue by Wzqqqqqqqq** [iamkun/dayjs#922]
**Describe the bug**
Hi, I am trying to use locale function to format a date to Japanese format, and I found always missing the Japanese word 'day'(日) after format.

dayjs('2018-05-05').locale('ja').format('MMMM DD')
 it will dispaly '5月05' and missing '日' in Japanses, and I checked the documents 'MMMM' equals month number with '月' but it is not work for 'DDDD'.

Is it my own personal mistake or a bug ?

**Expected behavior**
dayjs('2018-05-05').locale('ja').format('MMMM DD')

result should be :  5月5日

**Information**
 - Day.js Version [v1.8.20]
 - OS: [ iOS]
 - Browser [ipad]
 - Time zone: [GMT-07:00 DST (Pacific Daylight Time)]

**Comment by iamkun** [comment]
May be you should try 
`dayjs('2018-05-05').locale('ja').format('MM月 DD日')` instead
