### ISSUE TITLE
Wrong parsing date by format 'DD.MM.YYYY'

### ISSUE THREAD

**Issue by RUVATA** [iamkun/dayjs#923]
**Describe the bug**
Wrong parsing date by format 'DD.MM.YYYY'
to reproduce, place code in browser (DevTools) console:
```javascript
fetch("https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.8.28/dayjs.min.js", {
  "method": "GET",
}).then((resp) => resp.text().then(function (text) {
  eval(text)
}));
var test = dayjs('12.04.2012', 'DD.MM.YYYY')
console.log(test.format('DD.MM.YYYY')) // 04.12.2012 ! WTF
```

**Expected behavior**
correct parsing from custom format declared with correct usage of macro-insert literals

**Information**
 - Day.js Version [1.8.28]
 - OS: [MacOS|Windows]
 - Browser [chrome 83.0.4103.61]
 - Time zone: [GMT+3 (Moscow) Russian Federation]

**Comment by Narquadah** [comment]
Did you make sure to use extend dayjs by the plugin `CustomParseFormat`?

```js
dayjs.extend(CustomParseFormat);
```

Also I'd recommend using the strict mode:
```js
dayjs('12.04.2012', 'DD.MM.YYYY', true)
```

**Comment by RUVATA** [comment]
ОК, sorry, [docs](https://day.js.org/docs/en/parse/string-format) tell's me about it in special warrning block. Sad for your distracting

but signature of call 'dayjs' with strict mode is not correctly typed for TypeScript 
```typescript
declare function dayjs (date?: dayjs.ConfigType, option?: dayjs.OptionType, locale?: string): dayjs.Dayjs
```
the third argument may be **locale**, not boolean flag
![image](https://user-images.githubusercontent.com/2040022/83883042-a8869700-a74b-11ea-8125-24a05b4d2133.png)

But that's another story
