### ISSUE TITLE
Type definition for dayjs incomplete

### ISSUE THREAD

**Issue by LarsKumbier** [iamkun/dayjs#924]
The type for `daysjs()` does not honor the functionality described in the [string + format](https://day.js.org/docs/en/parse/string-format) document, after loading the `CustomParseFormat` plugin.

The following ways of calling the `daysjs()` constructor are valid:

```
dayjs.extend(customParseFormat)
dayjs('1970-01-01', 'YYYY-MM-DD')  // (1) string format
dayjs('1970-01-01', 'YYYY-MM-DD', true) // (2) strict parsing
dayjs('1970-01-01', 'YYYY-MM-DD', 'de', true) // (3) strict parsing with locale
dayjs('1970-01-01', 'YYYY-MM-DD', 'de') // (4) permissive parsing with locale
```

However, the typescript type file only cover cases (1) and (4), but fail to consider cases (2) and (3):

```
// src: https://github.com/iamkun/dayjs/blob/dev/types/index.d.ts#L4
declare function dayjs (date?: dayjs.ConfigType, option?: dayjs.OptionType, locale?: string): dayjs.Dayjs
```

**Workarounds**

A workaround for case (2) is to cast the (supposed) `locale`-option to any:
```
dayjs('1970-01-01', 'YYYY-MM-DD', true as any)
```

Case (3) does not have a workaround, beside overwriting the types in a project-wide index.d.ts file.

**Comment by iamkun** [comment]
Thanks. Fixed.
