### ISSUE TITLE
TypeError: this.week is not a function

### ISSUE THREAD

**Issue by CreativeRusBear** [iamkun/dayjs#925]
**Describe the bug**
Following [the documentation page](https://day.js.org/docs/en/get-set/week-year) that describes WeekYear function, I'm trying to repeat that code on the Node.js project. But I'm get an error like: **"TypeError: this.week is not a function"**.

**Expected behavior**
Getting the week-year value.

**Information**
 - Day.js Version: 1.8.28
 - OS: Windows 10 Pro
 - Browser:  none
 - Time zone: GMT+0300 (Moscow)
- Code: 
```js
const dayjs = require('dayjs');
const weekYear = require('dayjs/plugin/weekYear')
dayjs.extend(weekYear)

const wY = dayjs().weekYear();
console.log(wY);
```

**Comment by iamkun** [comment]
```
const dayjs = require('dayjs');
const weekYear = require('dayjs/plugin/weekYear')
const weekOfYear = require('dayjs/plugin/weekOfYear')
dayjs.extend(weekYear)
dayjs.extend(weekOfYear)

const wY = dayjs().weekYear();
console.log(wY);
```

My bad, doc updated.

**Comment by CreativeRusBear** [comment]
@iamkun Thanks
