### ISSUE TITLE
Documentation improve "Z" & "ZZ" format descriptions

### ISSUE THREAD

**Issue by sheffieldnick** [iamkun/dayjs#930]
**Describe the bug**
Very minor issue with the [List of all available formats](https://day.js.org/docs/en/display/format#list-of-all-available-formats), `ZZ` description is "The offset from UTC, 2-digits" when it is 4 not 2-digits, nor does that help distinguish it from `Z` which is also 4-digits.

**Expected behavior**
Perhaps update both to something like?
```
Z    The offset from UTC, ±HH:mm
ZZ   The offset from UTC, ±HHmm
```

**Comment by iamkun** [comment]
Cool, updated.
