### ISSUE TITLE
Dayjs not working in safari with dayjs

### ISSUE THREAD

**Issue by Bluefitdev** [iamkun/dayjs#931]
**Describe the bug**

as mentioned in #73 and #254 , my dayjs is not working in safari. Not sure how did you guys fixed it. It shows as invalid date on `dayjs(2020-06-16T16:21:00+1000).format('HH:mm')`

This is in the iso8601 format, goes like this: `2020-06-16T16:21:00+1000`

It is perfect in chrome though.. 

**Information**
 - Day.js version: 1.8.28
 - Browser safari 13.1

**Comment by xxyuk** [comment]
Try https://day.js.org/docs/en/parse/string-format CustomParseFormat plugin

**Comment by Bluefitdev** [comment]
Yeah that one actually worked.. does this mean that as of current in safari we have to use that despite the iso format? 

Sometimes its feels unnatural (becasue i'm using react) to initiate `dayjs.extend` in component `useEffect` when I just need to display formatted value at the body

**Comment by xxyuk** [comment]
You only need to `extend` once in your index.js file. And use it everywhere.

**Comment by Bluefitdev** [comment]
Ah i see... I didn't know that.

Alright then thanks

**Comment by ashishsurya** [comment]
Even though I am extending the "CustomParseFormat plugin" , I am getting the same issue
