### ISSUE TITLE
Feature request: empty duration check

### ISSUE THREAD

**Issue by eldhenn** [iamkun/dayjs#939]
Way to check if duration is empty. Something like `dayjs.duration({hour: 2}).subtract({minute: 120}).isEmpty()`

**Comment by eldhenn** [comment]
Or - duration comparsion. greaterThen, lesserThen, equalTo. And would be wonderful to have cmp() function, returning {-1; 0; 1}

**Comment by iamkun** [comment]
const compare = duration1.asSeconds() - duration2.asSeconds()
