### ISSUE TITLE
'MM-YYYY' format is returning different values in different timezones

### ISSUE THREAD

**Issue by sarah-vanderlaan** [iamkun/dayjs#941]
**Describe the bug**
`dayjs(value, 'MM-YYYY')` is returning different values depending on timezone.  

This issue was discovered when a client using our application in California was viewing a date one month earlier than our development team was seeing here in Europe.  I investigated the issue and can reproduce it on `day.js.org` and a timezone changer extension.  For my local timezone (GMT +2), the result of `dayjs("10-2010", "MM-YYYY")` is October 1 but if I change the timezone to California time (GMT -7) then I receive September 30.  

In our application we only show MM/YYYY in the view so this is resulting in an off-by-one value for the month.

Local:
![Screen Shot 2020-06-26 at 12 18 12 PM](https://user-images.githubusercontent.com/32620284/85847079-b4b6b080-b75b-11ea-8031-b57e7e0cad2a.png)

California:
![Screen Shot 2020-06-26 at 12 12 18 PM](https://user-images.githubusercontent.com/32620284/85846914-73be9c00-b75b-11ea-8c97-2bbcf49e3ead.png)

**Expected behavior**
I would like the result to be consistent regardless of timezone when I use the format "MM-YYYY".   Thanks in advance :)

**Information**
 - Day.js Version console version on day.js.org
 - OS: osX 10.15.4
 - Browser 83.0.4103.116
 - Time zone: GMT+2

**Comment by iamkun** [comment]
I can't re-product this on my side.
Any other detailed info you can provide? Thanks.
<img width="915" alt="Screen Shot 2020-06-28 at 6 59 22 PM" src="https://user-images.githubusercontent.com/17680888/85968398-9c62c200-b9f7-11ea-8329-e5cc74670e72.png">

**Comment by sarah-vanderlaan** [comment]
hi @iamkun, thanks for your reply!  Which extension did you try this with?

In order to reproduce this, I have installed the chrome extension [Change Timezone (Time Shift)](https://chrome.google.com/webstore/detail/change-timezone-time-shif/nbofeaabhknfdcpoddmfckpokmncimpj?hl=en).

If I have it disabled, and call `dayjs("10-2010", 'MM-YYYY')` on https://day.js.org/, then I receive October 2010, as expected. My browser is using my local timezone (GMT +2).

However, when I enable the extension to California time (GMT -7):
![Screen Shot 2020-07-03 at 11 23 48 AM](https://user-images.githubusercontent.com/32620284/86454556-b2d28b80-bd1f-11ea-9382-f63a4c3720aa.png)

then this is when I receive September 2010:
![Screen Shot 2020-07-03 at 11 24 23 AM](https://user-images.githubusercontent.com/32620284/86454601-c251d480-bd1f-11ea-912a-5e0312173587.png)

which is the same issue that is happening to my colleague in the US.

Can you try with the extension and see if that helps you to reproduce the issue?

**Comment by iamkun** [comment]
I updated the system timezone in the control panel.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
