### ISSUE TITLE
typescript环境下使用dayjs代替moment, DatePicker 的value会报ts类型检查错误

### ISSUE THREAD

**Issue by snoopy1412** [iamkun/dayjs#942]
**Describe the bug**
typescript环境下使用dayjs代替moment, 并按照官方指导安装antd-dayjs-webpack-plugin，但是在使用DatePicker组件的时候， 如果设置dayjs赋值value，会报ts类型检查错误
Type 'Dayjs' is missing the following properties from type 'Moment': calendar, local, isLocal, utc, and 46 more.  TS2740

**Information**
"dayjs": "^1.8.16",
"antd": "^4.3.5",
"antd-dayjs-webpack-plugin": "^1.0.0",
 - OS: [OSX]
 - Browser [chrome 83.0.4103.106]
 - Time zone: [e.g. 北京时间2020年6月27日下午6点]

**Comment by iamkun** [comment]
这个要不就等 antd fix，要不可以考虑 as any 先忽略这个错误

**Comment by snoopy1412** [comment]
> 这个要不就等 antd fix，要不可以考虑 as any 先忽略这个错误

thank you

**Comment by pgrekovich** [comment]
For those who are still looking for a solution to this problem:
```
import { Dayjs } from 'dayjs'
import {
  PickerProps,
  PickerDateProps,
  RangePickerProps as BaseRangePickerProps,
} from 'antd/lib/date-picker/generatePicker'

export type DatePickerProps = PickerProps<Dayjs>
export type RangePickerProps = BaseRangePickerProps<Dayjs>
export type WeekPickerProps = Omit<PickerDateProps<Dayjs>, 'picker'>
export type MonthPickerProps = Omit<PickerDateProps<Dayjs>, 'picker'>

```

**Comment by ZippoLee12138** [comment]
真坑啊，还没解决，mui时间组件只能any了
