### ISSUE TITLE
Array format support is not reflected in the type definition for typescript

### ISSUE THREAD

**Issue by crhg** [iamkun/dayjs#944]
**Describe the bug**
Array format is supported by #906, but typescript gives the following type error.

```typescript
dayjs('2020-02-02', ['YYYY', 'YYYY-DD-MM'])
```

```
 error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string | { locale?: string | undefined; format?: string | undefined; utc?: boolean | undefined; } | undefined'.
      Type 'string[]' is not assignable to type 'string'.
```

I think we need to update the function signature for typescript.

**Expected behavior**
It works just as well as javascript

**Information**
 - Day.js Version : 1.8.28
 - OS: macOS

**Comment by iamkun** [comment]
Updated, thanks.

**Comment by sziraqui** [comment]
Same issue on dayjs.utc()

**Comment by RaymondMwaura** [comment]
Still unresolved:

> dayjs(dataItem[dateField], "DD-MM-YYYY");
