### ISSUE TITLE
I think many people want to have the function to detect the official holiday in each country, so would you please to develop such kind of function?

### ISSUE THREAD

**Issue by tangjunjunsvw** [iamkun/dayjs#946]
I think many people want to have the function to detect the official holiday in each country, so would you please to develop such kind of function?

**Comment by iamkun** [comment]
It will be better to implement this on your own through plugins. https://day.js.org/docs/en/plugin/plugin

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
