### ISSUE TITLE
Locale does not get set

### ISSUE THREAD

**Issue by malua** [iamkun/dayjs#954]
**Describe the bug**
I am trying to set the locale like this:
```

import dayjs from 'dayjs';
import 'dayjs/locale/de';
import LocalizedFormat from 'dayjs/plugin/localizedFormat';
import updateLocale from 'dayjs/plugin/updateLocale';
import CustomParseFormat from 'dayjs/plugin/customParseFormat';

dayjs.extend(LocalizedFormat);
dayjs.extend(updateLocale);
dayjs.extend(CustomParseFormat);

const browserLanguage =
  (navigator.languages && navigator.languages[0]) ||
  navigator.language ||
  navigator['userLanguage'] ||
  'en';

if (browserLanguage.indexOf('de') > -1) {
  console.log(browserLanguage);  // logs 'de'
  dayjs.locale('de');
  dayjs.updateLocale('de', {
    formats: {
      llll: 'dddd, D. MMM YYYY, HH:mm [Uhr]'
    }
  });
} else {
  dayjs.locale('en');
}

console.log('DAYJS: ' + dayjs.locale());   // logs 'en'
```
And the first console log always outputs 'de', then I set the locale to 'de', but if I call dayjs.locale() its always 'en'. 

What am I doing wrong? Any help would be greatly appreciated, thanks!

**Information**
 - Day.js 1.8.29
 - Every OS
 - Every browser

**Comment by iamkun** [comment]
Hi, you can check here as a reference. https://runkit.com/embed/x2lt6097vrgo

**Comment by malua** [comment]
Thanks for the fast answer and I see how it should work, but unfortunatly i can't figure it out in my project. I am using Stencil, maybe it has something to do with its build system. Thanks anyways!
