### ISSUE TITLE
weekOfYear `week` method doesn't seems to handle week number 53 for 'fr' locale

### ISSUE THREAD

**Issue by 4rno** [iamkun/dayjs#956]
**Describe the bug**
I have an issue with the _dayjs_ `week()` method compared with the _moment.js_ one.
My issue is probably linked to this one [#772 ](https://github.com/iamkun/dayjs/issues/772)

**Expected behavior**
I tried with that date: `2020-12-31`, which is supposed to be a day in the week number 53. (if i refer to this http://www.whatweekisit.org/ or any french calendar).

Here is an example of what _moment.js_ `week()` method return for 'fr' and 'en-gb' locales: https://runkit.com/4rno/5f05ee0eef35c50013368d1b
`moment.js` returns week 53. Which is correct

But, I have different results with _dayjs_: https://runkit.com/4rno/5f05ebfc841930001389a53e
In 'fr' locale, it returns week number 1. But in 'en-gb' locale, it returns correctly week 53.

It seems to be linked with the parameter `yearStart` in locale config files. But i don't know exactly how it is supposed to work.
Or maybe i'm wrong somewhere.

**Information**
 - Day.js Version v1.8.29
 - OS: [Mac OS]
 - Browser [Chrome 83]
 - Time zone: [CET]

**Comment by iamkun** [comment]
Thanks, Update French (fr) locale to set correct yearStart config.

**Comment by flomoto** [comment]
Same problem in german locale.

**Comment by niklasHagner** [comment]
Just wanted to let you know I was having this issue too while using dayjs version 1.10.4 but after upgrading to 10.10.7 it's resolved. ✅ 

The code I was using
```
var dayjs = require('dayjs')
var isToday = require('dayjs/plugin/isToday')
var weekOfYear = require('dayjs/plugin/weekOfYear')
var utc = require('dayjs/plugin/utc') // dependent on utc plugin
var timezone = require('dayjs/plugin/timezone');
const { months } = require('dayjs/locale/sv');
dayjs.extend(isToday)
dayjs.extend(weekOfYear)
dayjs.extend(utc)
dayjs.extend(timezone)
dayjs.tz.setDefault("Sweden/Stockholm")
require('dayjs/locale/sv')
dayjs.locale('sv')

//Test scenario
var firstDayOf2021 = dayjs("2021-01-01");
console.log("weekNumber:", firstDayOf2021.week()); //With version version 1.10.4 it'll incorrectly output week1, with 1.10.7 it'll correctly output week53
```
