### ISSUE TITLE
Duration plugin adds unnecessary days to result

### ISSUE THREAD

**Issue by sunsetninja** [iamkun/dayjs#960]
Hi! Thanks for this project!
I found a strange behaviour with duration plugin.
I guess, that it adds extra days to result (see examples below).
I think the problem appears because days count differ in different months and years.

**Example 1 (years):  wrong behaviour (i guess)**
The difference between these 2 dates is exactly 1 year (a leap year).
```js
const startDate = "2020-07-17T10:58:11.000Z";
const endDate = "2019-07-17T10:58:11.000Z";

const diff = dayjs(startDate).diff(endDate);
const diffInYears = dayjs(startDate).diff(endDate, "year", true);

const duration = dayjs.duration(diff);
```
`diffInYears` gives `1`, but duration gives `$d` which contains
```
days: 1
hours: 0
milliseconds: 0
minutes: 0
months: 0
seconds: 0
years: 1
```

**Example 2 (years): correct behaviour**
The difference between these 2 dates is exactly 1 year (not a leap year).
```js
const startDate = "2011-07-17T10:58:11.000Z";
const endDate = "2010-07-17T10:58:11.000Z";

const diff = dayjs(startDate).diff(endDate);
const diffInYears = dayjs(startDate).diff(endDate, "year", true);

const duration = dayjs.duration(diff);
```
`diffInYears` gives `1`, and duration gives `$d` which contains
```
days: 0
hours: 0
milliseconds: 0
minutes: 0
months: 0
seconds: 0
years: 1
```

**Example 2 (months):  wrong behaviour (i guess)**
The difference between these 2 dates is exactly 2 months.
```js
const startDate = "2020-07-17T10:58:11.000Z";
const endDate = "2020-05-17T10:58:11.000Z";

const diff = dayjs(startDate).diff(endDate);
const diffInMonths = dayjs(startDate).diff(endDate, "month", true);

const duration = dayjs.duration(diff);
```
`diffInMonths` gives `2`, but duration gives `$d` which contains
```
days: 1
hours: 0
milliseconds: 0
minutes: 0
months: 2
seconds: 0
years: 0
```

**Information**
 - Day.js Version [v11.8.29]
 - Time zone: [GMT+0300]

**Comment by sunsetninja** [comment]
I think the problem starts here: https://github.com/iamkun/dayjs/blob/b2642e2d1f87734a34808c66e5176cb18bc0414d/src/plugin/duration/index.js#L3

**Comment by iamkun** [comment]
The main reason is `dayjs(startDate).diff(endDate, "day", true) === 366` I think. That's why an extra day added.

**Comment by sunsetninja** [comment]
This result is correct, but for days values only. In years it should be `1`(and `diff` does it correctly).
But `Duration` plugin does not use diff but assumes that in year is always 365 days and in month - 30.
And this is the problem.

**Comment by iamkun** [comment]
Yes, but if we pass a diff number in milliseconds to `Duration` plugin, the only thing the plugin could do is to treat it as a day not a year.

**Comment by sunsetninja** [comment]
Oh, i see, durations cannot be accurate outside of a context. So, i should use some `diff` workaround here instead. Thank you. :)
