### ISSUE TITLE
"Do" Not working in format function

### ISSUE THREAD

**Issue by Sandeep0695** [iamkun/dayjs#976]
I am using code snippet : 
 dayjs('2020-07-31T20:25:07.657').format("Do MMM YYYY hh:mm A")
 
which returning value like "31**o** Jul 2020 12:00 AM" and i am expecting to return "31**st** Jul 2020 12:00 AM" ,

**Comment by iamkun** [comment]
https://day.js.org/docs/en/plugin/advanced-format
