### ISSUE TITLE
parseDate error from recent release.

### ISSUE THREAD

**Issue by Junyan** [iamkun/dayjs#979]
**Describe the bug**
from https://github.com/iamkun/dayjs/pull/969
```
// v1.8.30
export var REGEX_PARSE = /^(\d{4})-?(\d{1,2})-?(\d{0,2})[^0-9]*(\d{1,2})?:?(\d{1,2})?:?(\d{1,2})?.?(\d{1,3})?$/;


// v1.8.31
export var REGEX_PARSE = /^(\d{4})-?(\d{1,2})?-?(\d{0,2})[^0-9]*(\d{1,2})?:?(\d{1,2})?:?(\d{1,2})?.?(\d{1,3})?$/;
```
result：
![image](https://user-images.githubusercontent.com/17005098/89159563-3ba04980-d5a2-11ea-9ce8-ca809da1c0c8.png)

```
// v1.8.31
dayjs('2020/9/30').format(); // result: 2020-01-01T09:00:00+08:00
```

**Expected behavior**
```
// v1.8.30
dayjs('2020/9/30').format(); // result: 2020-09-30T00:00:00+08:00
```

**Information**
 - Day.js Version [e.g. v1.8.31]

**Comment by iamkun** [comment]
Thanks, fixed in https://github.com/iamkun/dayjs/pull/980#issuecomment-667884647

**Comment by dyoshikawa** [comment]
I'm sorry the new bug.
Thank you for reporting and fixing.

**Comment by yyfearth** [comment]
Still has issue with invalid date string, like `dayjs('2020/222')` will results `2021-10-02T07:00:00.000Z`
Which I expecting it return `Invalid Date`

**Comment by iamkun** [comment]
@yyfearth  https://github.com/iamkun/dayjs/pull/980#issuecomment-689961221
