### ISSUE TITLE
Parsing dayjs(date, format) - returns incorrect date  - since version 1.8.31

### ISSUE THREAD

**Issue by tyagiarpit** [iamkun/dayjs#983]
**Describe the bug**

var dayjs = require("dayjs@1.8.31")
console.log(dayjs('2020 Aug 04', 'YYYY MMM DD').toString())

>>> _"Wed, 01 Jan 2020 10:00:00 GMT"_

**Expected behavior**
var dayjs = require("dayjs@1.8.30")
console.log(dayjs('2020 Aug 04', 'YYYY MMM DD').toString())

>>> _"Tue, 04 Aug 2020 05:00:00 GMT"_

**Information**
 - Day.js Version >= v1.8.31
 - OS: MacOS
 - Browser: Chrome
 - Time zone: CST

**Comment by iamkun** [comment]
Please use String + Format parsing https://day.js.org/docs/en/parse/string-format

**Comment by tyagiarpit** [comment]
Appreciate the quick response.
Was this feature deprecated intentionally? Or is it a side effect of some other change? I am trying to figure out if it is worth fixing and creating a PR or else I'll have to modify our application.

**Comment by iamkun** [comment]
Day.js will not use the second argument 'YYYY MMM DD'' unless CustomParseFormat plugin is used.

There is a regex update in 1.8.31 to strict date parsing.

**Comment by tyagiarpit** [comment]
That explains it. Thanks.
