### ISSUE TITLE
Wrong time zone offset in  'Asia/Tokyo' when using 'timezone' plugin

### ISSUE THREAD

**Issue by makitow** [iamkun/dayjs#986]
**Describe the bug**
Wrong time zone offset in  'Asia/Tokyo' when using 'timezone' plugin

**Expected behavior**
```
dayjs.extend(utc);
dayjs.extend(timezone);

console.log(dayjs().tz('Asia/Tokyo').format('Z'));
// => +08:59.995649999999955
```

**Information**
 - Day.js Version 1.8.32
 - OS: mac
 - Browser Google Chrome 84
 - Time zone: GMT+09:00 JST

**Comment by iamkun** [comment]
Thanks, will fix it in the next release.
