### ISSUE TITLE
TypeScript error when using Timezone plugin: `timezone.d.ts(7,7): error TS2304: Cannot find name 'Dayjs'`

### ISSUE THREAD

**Issue by micalevisk** [iamkun/dayjs#989]
I got this error: `timezone.d.ts(7,7): error TS2304: Cannot find name 'Dayjs'` when I use `dayjs.extend(timezone);`

I think that `DayjsTimezone` interface should be declared inside the module declaration
https://github.com/iamkun/dayjs/blob/e69caba1b0957241a855aa0ae38db899fa2c3795/types/plugin/timezone.d.ts#L6-L17

or `Dayjs` import is missing here
https://github.com/iamkun/dayjs/blob/e69caba1b0957241a855aa0ae38db899fa2c3795/types/plugin/timezone.d.ts#L1

**Comment by iamkun** [comment]
Yes, it's definitely a bug.

**Comment by iamkun** [comment]
fixed thanks
