### ISSUE TITLE
CustomParseFormat for Buddhist era

### ISSUE THREAD

**Issue by gie3d** [iamkun/dayjs#990]
**Describe the bug**
CustomParseFormat plugin doesn't understand the format of BuddhistEra plugin. For example,
```js
import dayjs from 'dayjs';
import buddhistEra from 'dayjs/plugin/buddhistEra';
import customParseFormat from 'dayjs/plugin/customParseFormat';
dayjs.extend(customParseFormat).extend(buddhistEra);

const date = '120565'; // = 12 May 2022
const format = 'DDMMBB';
const result = dayjs(date, format).format('DD MMM YYYY'); // 12 May 2020
```

**Expected behavior**
I think the `result` should be **12 May 2022**

**Information**
 - Day.js Version v1.8.24
 - OS: macOS 10.15.6
 - Browser: running on nodejs v12.16.0
 - Time zone: GMT+07:00 Bangkok

**Comment by iamkun** [comment]
CustomParseFormat plugin does not support parsing BuddhistEra date at present.

**Comment by gie3d** [comment]
Thanks for the clarification. I'll try to figure it out if I could make it to support and the possibility to submit the PR.

**Comment by iamkun** [comment]
It will be better to support this via BuddhistEra plugin.

But I'm not sure if it can share some of the function in CustomParseFormat plugin or not.
